version: "1.3.0-beta01"
dependency_list {
}
release_checklist {
}
build_id: "13318856"
group_id: "androidx.wear.protolayout"
artifact_id: "protolayout-external-protobuf"
path: "/wear/protolayout/protolayout-external-protobuf"
sha: "52ffd6b72fa725a568d36bf139aa94156bd03fa3"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.wear.protolayout-protolayout-external-protobuf-all-13318856-1.3.0-beta01.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-expression"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-expression-pipeline"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-material"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-material-core"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-material3"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-proto"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-renderer"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-testing"
    version: "1.3.0-beta01"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
target: "androidx"
test_module_names: ":wear:protolayout:protolayout-external-protobuf:test"
