{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13470622"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-beta01-sources.jar",
          "url": "compose-foundation-1.5.0-beta01-sources.jar",
          "size": 214290,
          "sha512": "f2dd92e48aa2adab9d127a49bd5470fd947171728c1551a44ee838b1bdef86d5ceed54323ec15f9edaa2e73759fa35200670386bacfd1773057c32e0da9d4278",
          "sha256": "a51dd1049ecad03a56dae8bca85654e1184aa3eb831f19f4b742ea97162aa44b",
          "sha1": "60aef2920b7ee355cad46585b1ab62124cc78eec",
          "md5": "0e7cf5195cdabde81fbd92955df18d5e"
        },
        {
          "name": "compose-foundation-1.5.0-beta01-samples-sources.jar",
          "url": "compose-foundation-1.5.0-beta01-samples-sources.jar",
          "size": 21823,
          "sha512": "5eee98bbcbbd662be303e69eef8a7f174e9b4051d4fdddabf0ca0c6fe924564ec217b475cbd5f40aa8519c1906363f968c4ef1de8f1b1fcb8f89e9099cb689ff",
          "sha256": "e81991827b98e5cdd5b239aaf3d5fc95b42c7ae296815660771457928e083ae4",
          "sha1": "ab77893adab47a0cdceedcc76b009d457cb8b1bd",
          "md5": "78aecf42094bc99c4232df8ab1edab6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-beta01.aar",
          "url": "compose-foundation-1.5.0-beta01.aar",
          "size": 981049,
          "sha512": "49392575a0e9bbe62f37929c787933343dd9949a3bac7128d75d74cc3ad67a2bb809057be9e6881facdb49f42ea2eaa56ba3138b33102c27defafb1c8b0a77a0",
          "sha256": "49f3c9080e94d752c6801c83307edbc73b45499962f482ac09648618318ee244",
          "sha1": "ed68219b2dceed1d4d968adc856fa9b541565eb3",
          "md5": "73400a44eb515eaaf1403bda169def6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-beta01.aar",
          "url": "compose-foundation-1.5.0-beta01.aar",
          "size": 981049,
          "sha512": "49392575a0e9bbe62f37929c787933343dd9949a3bac7128d75d74cc3ad67a2bb809057be9e6881facdb49f42ea2eaa56ba3138b33102c27defafb1c8b0a77a0",
          "sha256": "49f3c9080e94d752c6801c83307edbc73b45499962f482ac09648618318ee244",
          "sha1": "ed68219b2dceed1d4d968adc856fa9b541565eb3",
          "md5": "73400a44eb515eaaf1403bda169def6b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.5.0-beta01-versionMetadata.json",
          "url": "compose-foundation-1.5.0-beta01-versionMetadata.json",
          "size": 47788,
          "sha512": "00382ef3f9af68cc7be4ea3ae39bf609cff18dea3bc8f0f1f2a4a89b41a029e9dc056c52fe21e4df6ce67d1b8f0ec5f2818ffc057ebfcd717dcd36f103d7de46",
          "sha256": "5145df527542360194da61ece451c0c154765a21c042c0d9ce9b7bd2e852811f",
          "sha1": "7e8cbf196b0a8fab433533a3722c8feb8406ed9a",
          "md5": "ffcd524195655cf3e4b4a3b06542334b"
        }
      ]
    }
  ]
}