version: "1.2.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.emoji"
    artifact_id: "emoji"
    version: "1.2.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.emoji"
group_id: "androidx.emoji"
artifact_id: "emoji-bundled"
path: "/emoji/emoji-bundled"
sha: "4aec854c427c10ef13687b93facb9e571cef4682"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-emoji-11423473.zip"
project_zip_path: "per-project-zips/androidx.emoji-emoji-bundled-all-11423473-1.2.0-alpha03.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
