version: "1.2.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.emoji"
    artifact_id: "emoji"
    version: "1.2.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.emoji"
group_id: "androidx.emoji"
artifact_id: "emoji-bundled"
path: "/emoji/emoji-bundled"
sha: "3e875a80adcdc0ae1415e676053e41d197781611"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.emoji-emoji-bundled-all-12324909-1.2.0-alpha03.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
