version: "1.2.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.emoji"
    artifact_id: "emoji"
    version: "1.2.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13318856"
group_id: "androidx.emoji"
artifact_id: "emoji-bundled"
path: "/emoji/emoji-bundled"
sha: "52ffd6b72fa725a568d36bf139aa94156bd03fa3"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.emoji-emoji-bundled-all-13318856-1.2.0-alpha03.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "emoji-emoji-bundledreleaseAndroidTest.xml"
test_module_names: ":emoji:emoji-bundled:testReleaseUnitTest"
