{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window-java",
    "version": "1.5.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13808536"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.5.0-beta02-sources.jar",
          "url": "window-java-1.5.0-beta02-sources.jar",
          "size": 13586,
          "sha512": "2740cab0281b3076a1f0f33d26b2351992d6692cc20dabad1e92e106c51ab46df2b00d601a3b98449ebabc028ea414c77e06662cad802a38dc74cfe71d60ee04",
          "sha256": "6a7420257024e4af2258bd53e3b4feb1a6b402089c19d390445bb37f7c33699c",
          "sha1": "ce05a96c2ef4d174ed394aaf38bb3a4c601f267d",
          "md5": "d880ba8a35c83cd7dad06323db13ea08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.5.0-beta02.aar",
          "url": "window-java-1.5.0-beta02.aar",
          "size": 18193,
          "sha512": "ce2dd9a061eb1ea19b48a0089d4266b16de890af1faa25695dbd6628dcfb68273d067e5e371ab3f8fafc0896f9875f5346fd44bf0dbf1e9659c011411295033f",
          "sha256": "3aab49a7fae0720fc3e2eb7971c8b96a2883e60f5e87477be2d4fd932d7a3486",
          "sha1": "38db7d19aa760f4294b7bc4d7332c9bfc1f8de83",
          "md5": "780887dedf20481e0b21c3d4b9b55efd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-java-1.5.0-beta02.aar",
          "url": "window-java-1.5.0-beta02.aar",
          "size": 18193,
          "sha512": "ce2dd9a061eb1ea19b48a0089d4266b16de890af1faa25695dbd6628dcfb68273d067e5e371ab3f8fafc0896f9875f5346fd44bf0dbf1e9659c011411295033f",
          "sha256": "3aab49a7fae0720fc3e2eb7971c8b96a2883e60f5e87477be2d4fd932d7a3486",
          "sha1": "38db7d19aa760f4294b7bc4d7332c9bfc1f8de83",
          "md5": "780887dedf20481e0b21c3d4b9b55efd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "window-java is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-java-1.5.0-beta02-versionMetadata.json",
          "url": "window-java-1.5.0-beta02-versionMetadata.json",
          "size": 3426,
          "sha512": "37c0548361fcc54ffcae075c0ba780a7ecc6838dab79310600f92866524699f1d4bf0d5b8b06b705a2ed0a728f2e5d9c54c0630bc7d08f257f625923aa86623a",
          "sha256": "13e300e67a12e5aa8acbd8b3ed9de0ca51094a4d57decc1024550098c09d4d6a",
          "sha1": "b5c12167588bdfbe2a26bdab589c5416a70bc51c",
          "md5": "245832b833c00546615472cfdb5df15e"
        }
      ]
    }
  ]
}