{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.animation",
    "module": "animation-core",
    "version": "1.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.4.0-alpha05.aar",
          "url": "animation-core-1.4.0-alpha05.aar",
          "size": 1369819,
          "sha512": "734e6534bbb12d1bbf8381d42f269180133a91521dc3b66f17421788bf5ef44d50603ea6c6e5c7f5797d3026654664fb0b8f880334c76ac591398afbe07be056",
          "sha256": "63de2ee6840e867862bcb74d90854a8da9a8f55b7ac85cf2555c3466b962865c",
          "sha1": "579c7f48ea19de507828e0f0f3f231eb24c677fd",
          "md5": "cae120dd05a0a1a986fc36c4e866a917"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "animation-core-1.4.0-alpha05.aar",
          "url": "animation-core-1.4.0-alpha05.aar",
          "size": 1369819,
          "sha512": "734e6534bbb12d1bbf8381d42f269180133a91521dc3b66f17421788bf5ef44d50603ea6c6e5c7f5797d3026654664fb0b8f880334c76ac591398afbe07be056",
          "sha256": "63de2ee6840e867862bcb74d90854a8da9a8f55b7ac85cf2555c3466b962865c",
          "sha1": "579c7f48ea19de507828e0f0f3f231eb24c677fd",
          "md5": "cae120dd05a0a1a986fc36c4e866a917"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "animation-core-1.4.0-alpha05-sources.jar",
          "url": "animation-core-1.4.0-alpha05-sources.jar",
          "size": 76758,
          "sha512": "b7230eee13102007572238982afcdc4c4347fd769e4107144d6752440ee3f92382d018f90924eac57e50e2f342b38b5ab8203caeee21b13847ca06186f15d295",
          "sha256": "f1c70ee5bb0e98daf704c4c3273cbde56e89591ced3a9bc8ac81a312729e7c81",
          "sha1": "3957e6971f325ed39642690069e47954e0fa88a3",
          "md5": "efe397b93b8e07dc004b0361c7c9f933"
        }
      ]
    }
  ]
}