version: "1.0.0-alpha09"
dependency_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha09"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.tools"
group_id: "androidx.privacysandbox.tools"
artifact_id: "tools-core"
path: "/privacysandbox/tools/tools-core"
sha: "4237f41666396b1ff39ffba3563807151fed2313"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.tools-tools-core-all-12004588-1.0.0-alpha09.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apicompiler"
    version: "1.0.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apigenerator"
    version: "1.0.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apipackager"
    version: "1.0.0-alpha09"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
