{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.7.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0-alpha04"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.0-alpha04.aar",
          "url": "appcompat-resources-1.7.0-alpha04.aar",
          "size": 66811,
          "sha512": "95534b847b53d4a15c3c74965dfe56611a28f9a729d10f60693569e0ecfab3b20529df732528adc84cc602d317245b3673fee4d82090100ff9bd80d2135ea018",
          "sha256": "19d9af3350a93136475350794346f009846b88ae08c3efba69aa53eb8b659116",
          "sha1": "7c8e8805fa8f335078bd979fe4d08f1373af1179",
          "md5": "4384ac54cbc45281d7b70cf4a84c8f6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0-alpha04"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.0-alpha04.aar",
          "url": "appcompat-resources-1.7.0-alpha04.aar",
          "size": 66811,
          "sha512": "95534b847b53d4a15c3c74965dfe56611a28f9a729d10f60693569e0ecfab3b20529df732528adc84cc602d317245b3673fee4d82090100ff9bd80d2135ea018",
          "sha256": "19d9af3350a93136475350794346f009846b88ae08c3efba69aa53eb8b659116",
          "sha1": "7c8e8805fa8f335078bd979fe4d08f1373af1179",
          "md5": "4384ac54cbc45281d7b70cf4a84c8f6a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0-alpha04"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.0-alpha04-sources.jar",
          "url": "appcompat-resources-1.7.0-alpha04-sources.jar",
          "size": 40928,
          "sha512": "bba674f3c5a2a64fd5053e900e68f4ba686f89c243fe1e78f428dc1b8bb931d311d7fd50962c86954499fc0efe5f7ee1eb38664eb66d5b63fd13999c13cf1bba",
          "sha256": "70d0afccaece5dcb39880072635fcb542f184a6bd1b110e21daa2362a81478f9",
          "sha1": "568c8ff719ba196d3eadbf16d577c3c25e15b85f",
          "md5": "9aca10b1fada507ccba8f255e0ff3377"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0-alpha04"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.7.0-alpha04-versionMetadata.json",
          "url": "appcompat-resources-1.7.0-alpha04-versionMetadata.json",
          "size": 8031,
          "sha512": "806786e5ae8b0ce26f8421ae002a031ef187d72678a325a4b384ba03f760da079879ff926dc13059fcbe53283b1598e31b5c56c6883ffdf91ca1333582833313",
          "sha256": "e92a3b59f460936fd345766d00b97af6a3cd6539d6fda0aa92c4abfe68d30b9a",
          "sha1": "3e2e83c02fcacf07c0312610aa4962732e553676",
          "md5": "388cb41eebb35332b914cddeee9eda19"
        }
      ]
    }
  ]
}