{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/1.3.0-alpha03/material3-window-size-class-1.3.0-alpha03.module",
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-release.aar",
          "url": "material3-window-size-class-android-1.3.0-alpha03.aar",
          "size": 17259,
          "sha512": "37e8a22ef59a2e763bd018c73dbfe26fe00021bf050c930e4713ccb400f869f387494870b5a81531bfa95a52fe08dd937fe00efd5f334524d54a54dcecc428c5",
          "sha256": "163d7817fe5069ecadd01b934708d312f6465b3deabd60f103498bd1afd892d3",
          "sha1": "98d9d083bf1280fb510c0e2ffbba33b7c8469c43",
          "md5": "6767f2f7324d211306c985213a0bd0db"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-release.aar",
          "url": "material3-window-size-class-android-1.3.0-alpha03.aar",
          "size": 17259,
          "sha512": "37e8a22ef59a2e763bd018c73dbfe26fe00021bf050c930e4713ccb400f869f387494870b5a81531bfa95a52fe08dd937fe00efd5f334524d54a54dcecc428c5",
          "sha256": "163d7817fe5069ecadd01b934708d312f6465b3deabd60f103498bd1afd892d3",
          "sha1": "98d9d083bf1280fb510c0e2ffbba33b7c8469c43",
          "md5": "6767f2f7324d211306c985213a0bd0db"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-android-1.3.0-alpha03-sources.jar",
          "url": "material3-window-size-class-android-1.3.0-alpha03-sources.jar",
          "size": 8474,
          "sha512": "8107ce4ae67ac4b5bad1f800cad205e71fa76e6acc8f7d15da7dee16cb8cf6279d4f8d7d540bb658d0a045e30d5222b1473f649d19380010e7bd1b41dd76b081",
          "sha256": "36df8e7f29455673a9e206b536c00d8d7d969dda682976a5b63a9f102236b955",
          "sha1": "cc44f4e95247fd47c9b0cc6e9c13e5ce689d3526",
          "md5": "213f6cbc23c5250c459fc0fa886e1966"
        }
      ]
    }
  ]
}