{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-complications-data-source",
    "version": "1.3.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13042766"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha05-sources.jar",
          "url": "watchface-complications-data-source-1.3.0-alpha05-sources.jar",
          "size": 19303,
          "sha512": "74fa936ef989f955c0dbd2a5dc69e1624a5fc17e97c7ea932cfcaca5b5a075b39dce1442a20a188edb83a036ba47db051245aeb21ecc510ce656fa21eaf70f24",
          "sha256": "a77356662e2184db9ca76457b612f1b84e329a265c4b573efa8131c342eeb09d",
          "sha1": "5bb0b7b3082e9e7bdfc229c964a3b922dec1f2ec",
          "md5": "6b1b2cdba182cb82e8b4e5c3a9b71adb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha05.aar",
          "url": "watchface-complications-data-source-1.3.0-alpha05.aar",
          "size": 36885,
          "sha512": "2fff32f142a9a68734ddf0e4823baf38df484bd831f498aa7c34987b946de2ff6bf5bd9cd8f01c8778dc8298c07d040eb28553cc15810d98d4251b38a3828df5",
          "sha256": "db599be43b9412ac541970a513c1d9d51fcdfc8d5b7223ba8804e5eb3d4bbad2",
          "sha1": "d5d60ee0134cec73478185a1387a75f06867afe7",
          "md5": "7730d04778e23811f4f2cad23fff2c01"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha05"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha05.aar",
          "url": "watchface-complications-data-source-1.3.0-alpha05.aar",
          "size": 36885,
          "sha512": "2fff32f142a9a68734ddf0e4823baf38df484bd831f498aa7c34987b946de2ff6bf5bd9cd8f01c8778dc8298c07d040eb28553cc15810d98d4251b38a3828df5",
          "sha256": "db599be43b9412ac541970a513c1d9d51fcdfc8d5b7223ba8804e5eb3d4bbad2",
          "sha1": "d5d60ee0134cec73478185a1387a75f06867afe7",
          "md5": "7730d04778e23811f4f2cad23fff2c01"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha05"
          },
          "reason": "watchface-complications-data-source is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-data-source-1.3.0-alpha05-versionMetadata.json",
          "url": "watchface-complications-data-source-1.3.0-alpha05-versionMetadata.json",
          "size": 5585,
          "sha512": "f926d6a3b169e23feb149e5bca98801965ba34676e253a195bc5e5b9471992b4c931b87861841012fce22bec2243b269585050f51856851dc78e3a3e96dd57cc",
          "sha256": "09d168b08074725bf726dd564e9bd00dce3fe2c80230aef42f6e6c027a8236e5",
          "sha1": "192a98e4685e08da1559295c213a65e483d0aa4a",
          "md5": "3c58fbcc3fb74b4c95ab94530a7807a0"
        }
      ]
    }
  ]
}