{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6732122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "url": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "size": 32493,
          "sha512": "b6dcee2b28cbaf979aeb60341b69bbccc2a5bb3b75c14d5d622575764c0314d593832da452c2949a91207059fd69770c931547e1f9c134ec94148998a0d2ded9",
          "sha256": "71a7212059f9d7c547189985243a5d802834890df7277fe7b75aa049f43d195e",
          "sha1": "84424d4332f8b20825951590861902cd65847905",
          "md5": "46f25d9046706f704f180d61502641d8"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "url": "navigation-ui-ktx-2.4.0-alpha01.aar",
          "size": 32493,
          "sha512": "b6dcee2b28cbaf979aeb60341b69bbccc2a5bb3b75c14d5d622575764c0314d593832da452c2949a91207059fd69770c931547e1f9c134ec94148998a0d2ded9",
          "sha256": "71a7212059f9d7c547189985243a5d802834890df7277fe7b75aa049f43d195e",
          "sha1": "84424d4332f8b20825951590861902cd65847905",
          "md5": "46f25d9046706f704f180d61502641d8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-ktx-2.4.0-alpha01-sources.jar",
          "url": "navigation-ui-ktx-2.4.0-alpha01-sources.jar",
          "size": 8751,
          "sha512": "0d56d35c76ca24964807607764080077f0d8ce960dc61e14629a2a1d50bd424ab455be041d64dc17edc52511c0db4d25c3e7b359a5bb44c9c37f2e0934ea1685",
          "sha256": "dc293a071dc2f04f69d456de6734531fa52ae69fecc83a4e1812006a3e5e3eae",
          "sha1": "407dd936012d5b65b0af3e897ea62e436a811419",
          "md5": "e5ff0652316f70fa6f7263ce5094a7ba"
        }
      ]
    }
  ]
}
