{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6761364"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.3.0-alpha07.aar",
          "url": "lifecycle-viewmodel-ktx-2.3.0-alpha07.aar",
          "size": 6434,
          "sha512": "9ae10e2f79a2c31dcc27033eef6f7bf12d0bc70883de071d40af760d730f75589b550cd760b55b3468d75759676e5775560dccf1c160f4907d2f2fa31b44e86e",
          "sha256": "687db1a0928d1a51e9c88e0a0f1b1a2f1c163a9c919179b0b9618457d19cfda9",
          "sha1": "e413969d12e2f7c5a459524ad7f0e21280914b5c",
          "md5": "27cb32f3233e472b4c3d70876f47f214"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.3.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.3.0-alpha07.aar",
          "url": "lifecycle-viewmodel-ktx-2.3.0-alpha07.aar",
          "size": 6434,
          "sha512": "9ae10e2f79a2c31dcc27033eef6f7bf12d0bc70883de071d40af760d730f75589b550cd760b55b3468d75759676e5775560dccf1c160f4907d2f2fa31b44e86e",
          "sha256": "687db1a0928d1a51e9c88e0a0f1b1a2f1c163a9c919179b0b9618457d19cfda9",
          "sha1": "e413969d12e2f7c5a459524ad7f0e21280914b5c",
          "md5": "27cb32f3233e472b4c3d70876f47f214"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.3.0-alpha07-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.3.0-alpha07-sources.jar",
          "size": 3202,
          "sha512": "bcd3217f2c0d20e3c815c0d2ad9bc5004bbe484e34d63c36ddafe016081dc52fcecc03212dd8c4b9b6bc2b9a6e257f86f4db8cb93224d3c4c7bc72674e05e196",
          "sha256": "b940019ff34b3645a2cc9299e34db4572bc4af83678f4ccc1a1f0d9e66a65a36",
          "sha1": "a716b53dcf7015ac5a51941d13959ba3f8b7d0ee",
          "md5": "8fe8a85ca7e03f9572a7b98fe9f0ab7c"
        }
      ]
    }
  ]
}
