version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-testing"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.glance"
group_id: "androidx.glance"
artifact_id: "glance-appwidget-testing"
path: "/glance/glance-appwidget-testing"
sha: "18f6e60651f9bc5e7096ce4dc0a2fbccc94f0f98"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.glance-glance-appwidget-testing-all-12529871-1.2.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-external-protobuf"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-multiprocess"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-preview"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-appwidget-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-material"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-material3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-preview"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.glance"
    artifact_id: "glance-testing"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
