{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-testing",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13115689"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.2.0-alpha01-sources.jar",
          "url": "glance-appwidget-testing-1.2.0-alpha01-sources.jar",
          "size": 15296,
          "sha512": "70cdf99216e3551459d801881cae020617a7a62831a34c79658e7052a66cfa0c554f362036a1aa236dd3bdbb24d4783ef4dee4af284ac2e623b2e885aa18b71c",
          "sha256": "b0efbc3e48341e3ae2d89388fbbcc7169fd49a8f92724dc90494735c8a029d63",
          "sha1": "a34ce91e58f3a121c3e0cf4227543713710ee138",
          "md5": "ac111ad5e1061e183aa7442cf8a6c014"
        },
        {
          "name": "glance-appwidget-testing-1.2.0-alpha01-samples-sources.jar",
          "url": "glance-appwidget-testing-1.2.0-alpha01-samples-sources.jar",
          "size": 6421,
          "sha512": "c3235e9fcb260df202eb558a823fd0ba71e25ee3ff8ce84ec49bfd5bd65e20796c62dffc3f27cfbdbd53292587e26f5cd18618c6c54edebc39366a9a35773e77",
          "sha256": "48417c76fd133f2aa99705974add62b5698397e8ebf84ea8d30c8c0684c4d1fb",
          "sha1": "93b4ed81dcf51a9c7dcdbc2b59479f7fc626e632",
          "md5": "a37d6d59c524bcc4a4028a215b826413"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.2.0-alpha01.aar",
          "url": "glance-appwidget-testing-1.2.0-alpha01.aar",
          "size": 65523,
          "sha512": "dc993c7e1b0a78bdd5e249cbb970ff97b73aafb1428b2905029a79aac198414d2982ced002f8e05886b3f3298b8d18d510bbe0139ca8ea95f3243112e32e5fb8",
          "sha256": "952d42858be18c93f9295836b98cb444047d0a35ec1b2334b9abaa5173cfed8b",
          "sha1": "23bb5e49fbb0df59fb706efacdc9d961aa24c255",
          "md5": "4e0a8d0d72f43272d437d433cc7864d2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.2.0-alpha01.aar",
          "url": "glance-appwidget-testing-1.2.0-alpha01.aar",
          "size": 65523,
          "sha512": "dc993c7e1b0a78bdd5e249cbb970ff97b73aafb1428b2905029a79aac198414d2982ced002f8e05886b3f3298b8d18d510bbe0139ca8ea95f3243112e32e5fb8",
          "sha256": "952d42858be18c93f9295836b98cb444047d0a35ec1b2334b9abaa5173cfed8b",
          "sha1": "23bb5e49fbb0df59fb706efacdc9d961aa24c255",
          "md5": "4e0a8d0d72f43272d437d433cc7864d2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-testing is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-testing-1.2.0-alpha01-versionMetadata.json",
          "url": "glance-appwidget-testing-1.2.0-alpha01-versionMetadata.json",
          "size": 4994,
          "sha512": "1b4451a695739a7b00e4466e2e9fa310733d10d3787bf1aa2125186b339bce5637445b70e5cd53d6a5f334611190b700982491387405f21134164c842cb250e6",
          "sha256": "e470b89f561e24f1a5924e744035805ca3324796664c7490ae2080a88b2eef72",
          "sha1": "7ef6cb7c0292709b85534d32f0bd8a69eb0b9cf8",
          "md5": "14290af378ac7a830169f8b335a99749"
        }
      ]
    }
  ]
}