version: "1.9.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-core-android"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-core-jvmstubs"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-core-linuxx64stubs"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "12976215"
group_id: "androidx.compose.animation"
artifact_id: "animation-core"
path: "/compose/animation/animation-core"
sha: "d1ec2613849f517c712bfd0c3d355dde0fdc631f"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.animation-animation-core-all-12976215-1.9.0-alpha01.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-core-lint"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-graphics"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-lint"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.animation"
    artifact_id: "animation-tooling-internal"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
kmp_children: "jvmStubs"
kmp_children: "linuxx64Stubs"
test_module_names: ":compose:animation:animation-core:jvmStubsTest"
test_module_names: ":compose:animation:animation-core:linuxx64StubsTest"
test_module_names: "compose-animation-animation-corereleaseAndroidTest.xml"
test_module_names: ":compose:animation:animation-core:testReleaseUnitTest"
