version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.wear.tiles"
group_id: "androidx.wear.tiles"
artifact_id: "tiles-proto"
path: "/wear/tiles/tiles-proto"
sha: "123fa973ef15f8dbddd2442a83e22388f2d4e83a"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.wear.tiles-tiles-proto-all-11628048-1.4.0-alpha01.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
  dependency {
    group_id: "androidx.wear.protolayout"
    artifact_id: "protolayout-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.tiles"
    artifact_id: "tiles"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.tiles"
    artifact_id: "tiles-material"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.tiles"
    artifact_id: "tiles-renderer"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.tiles"
    artifact_id: "tiles-testing"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.tiles"
    artifact_id: "tiles-tooling"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.wear.tiles"
    artifact_id: "tiles-tooling-preview"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
