{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression",
    "version": "1.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13259688"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.3.0-beta01-sources.jar",
          "url": "protolayout-expression-1.3.0-beta01-sources.jar",
          "size": 79582,
          "sha512": "55b7b05ab48f7a6a9d807648fa9cb160599decd433797bbf9c914e42a3b3a11638d68ada0114b351806f906f0ebf3937b6f499da4eec2662ecde381ccf41005f",
          "sha256": "18c0316238f1b87d3027741cf2fd33c09f5097547550b06aed1703bda484dc53",
          "sha1": "ccfa046bba5bb5361d5687cdabec40d909adb6be",
          "md5": "210be9417b9569bbec26d302d1ee180b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.3.0-beta01.aar",
          "url": "protolayout-expression-1.3.0-beta01.aar",
          "size": 316836,
          "sha512": "d27dfdad4407f9b42ac884ee221edc4125f76aba37dd6216f46590f4fed49602399a6bdfe67d12cac575ab016a735014f22dcf66702710554b2154a8a56bcdac",
          "sha256": "930e9c782338f700ded1d199895a5c6a407871f0f018ec43ac27a1735d3ec747",
          "sha1": "13d33eb4fb379450868fd2e2ee6496e412a497ec",
          "md5": "c0143fc6a9b90073f6d48a3595a76c17"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.3.0-beta01.aar",
          "url": "protolayout-expression-1.3.0-beta01.aar",
          "size": 316836,
          "sha512": "d27dfdad4407f9b42ac884ee221edc4125f76aba37dd6216f46590f4fed49602399a6bdfe67d12cac575ab016a735014f22dcf66702710554b2154a8a56bcdac",
          "sha256": "930e9c782338f700ded1d199895a5c6a407871f0f018ec43ac27a1735d3ec747",
          "sha1": "13d33eb4fb379450868fd2e2ee6496e412a497ec",
          "md5": "c0143fc6a9b90073f6d48a3595a76c17"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta01"
          },
          "reason": "protolayout-expression is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-1.3.0-beta01-versionMetadata.json",
          "url": "protolayout-expression-1.3.0-beta01-versionMetadata.json",
          "size": 32843,
          "sha512": "70dad5bcd4a05a77c703c336157028831cd1e309bb4a6e63f7ad7ce1365c31fff56c71aca7de6c4a4a3ee459611df5b389a2c73659490912ed5f59851f4227ed",
          "sha256": "1277c8627ba39c0f34a7e58c1c9bad551472db28219f8ac78eb466fbb98af6b1",
          "sha1": "5955648d5feacfcdd08c4c3ccd8182b0f23e06af",
          "md5": "f7209d44e7c3fb8af3494c3eaa83d367"
        }
      ]
    }
  ]
}