version: "1.8.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativearm32"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativearm64"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativex64"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativex86"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-jvm"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-linuxx64"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation"
path: "/annotation/annotation"
sha: "ad6bfd28037d5d5295d6de24cd2754dceb712b74"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-all-11623079-1.8.0-beta01.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
}
should_publish_docs: true
