version: "1.1.0-alpha05"
dependency_list {
}
release_checklist {
}
build_id: "androidx.health"
group_id: "androidx.health"
artifact_id: "health-services-client-external-protobuf"
path: "/health/health-services-client-external-protobuf"
sha: "93a6b8c80545df72a3e53b21ba238295436aaee6"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.health-health-services-client-external-protobuf-all-12912110-1.1.0-alpha05.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
}
should_publish_docs: false
is_kmp: false
target: "androidx"
