version: "1.1.0-alpha05"
dependency_list {
}
release_checklist {
}
build_id: "12944746"
group_id: "androidx.health"
artifact_id: "health-services-client-external-protobuf"
path: "/health/health-services-client-external-protobuf"
sha: "ddc1fb7522a112c60225c3e4eb1d0f077375fa1c"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.health-health-services-client-external-protobuf-all-12944746-1.1.0-alpha05.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
}
should_publish_docs: false
is_kmp: false
target: "androidx"
test_module_names: ":health:health-services-client-external-protobuf:test"
