version: "1.1.0-alpha05"
dependency_list {
}
release_checklist {
}
build_id: "13076784"
group_id: "androidx.health"
artifact_id: "health-services-client-external-protobuf"
path: "/health/health-services-client-external-protobuf"
sha: "b59dd011af04591679cf78abe1ed912e145662e7"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.health-health-services-client-external-protobuf-all-13076784-1.1.0-alpha05.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
}
should_publish_docs: false
is_kmp: false
target: "androidx"
test_module_names: ":health:health-services-client-external-protobuf:test"
