{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression-pipeline",
    "version": "1.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13420395"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-beta02-sources.jar",
          "url": "protolayout-expression-pipeline-1.3.0-beta02-sources.jar",
          "size": 75545,
          "sha512": "40f513c08a11b5f9c44dc58b8a3727ec06ee91ba09f8a4cf25981da1c387b6a24f77420ea394f2b787667e8cbd946ae48f551d81a41d9d59f1c03a127f26f53f",
          "sha256": "ce3639c192c55d1f821ccfbe096b5d54ac5fd39cf0bf577242697f01f5e4b024",
          "sha1": "f8bdd0ac6b803e1301f1e61cd34c1f755bd7168b",
          "md5": "54d1dcad8834cc03a333727d65efbfac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-beta02.aar",
          "url": "protolayout-expression-pipeline-1.3.0-beta02.aar",
          "size": 154267,
          "sha512": "d32412c00a85742d346cddb6ffc3dfd983e0278206e71107b9c58bc9bb26561979b9e554589d4be751fbd516c04408281d4b90055d1e3c2b112647625cd1c545",
          "sha256": "2e57a7fd369a6f0c18660133d95482c1bd4482e835536d2bdcfd6036a540c840",
          "sha1": "a0975fcc457b504a2fdbf0b499d10bdb5e2f4e1a",
          "md5": "e76a05594a545a8576b83cf172bf3b08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta02"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-beta02.aar",
          "url": "protolayout-expression-pipeline-1.3.0-beta02.aar",
          "size": 154267,
          "sha512": "d32412c00a85742d346cddb6ffc3dfd983e0278206e71107b9c58bc9bb26561979b9e554589d4be751fbd516c04408281d4b90055d1e3c2b112647625cd1c545",
          "sha256": "2e57a7fd369a6f0c18660133d95482c1bd4482e835536d2bdcfd6036a540c840",
          "sha1": "a0975fcc457b504a2fdbf0b499d10bdb5e2f4e1a",
          "md5": "e76a05594a545a8576b83cf172bf3b08"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-beta02"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-beta02-versionMetadata.json",
          "url": "protolayout-expression-pipeline-1.3.0-beta02-versionMetadata.json",
          "size": 5880,
          "sha512": "5c314fc79955d75182e03264f73d124441367518855c85d5024d023a88b4f113b9bc768c151019f8a18de381a90f2bf35c80c94ddf0522322280d970aaa785aa",
          "sha256": "9294742514bc19fc999a0d66b8d3b8809c0e8dca5ac33375ea7a920f0e6f3547",
          "sha1": "8dd9f2a4f8d59b0c1cf3bd7e62b58db9ccdac665",
          "md5": "13eff603f180c1ecadfe3671024ad65e"
        }
      ]
    }
  ]
}