version: "1.8.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.concurrent"
    artifact_id: "concurrent-futures"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.interpolator"
    artifact_id: "interpolator"
    version: "1.0.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.browser"
group_id: "androidx.browser"
artifact_id: "browser"
path: "/browser/browser"
sha: "27dafd9d844de4751285f29dadaa4d58d8796f64"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-browser-11024469.zip"
project_zip_path: "per-project-zips/androidx.browser-browser-all-11024469-1.8.0-alpha01.zip"
kotlin_version: "1.9.10"
dependency_constraint_list {
}
