{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-testing",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14028488"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01-sources.jar",
          "size": 42526,
          "sha512": "fb6d7058efdd3786688100ba647dafc8654993b4dcac167f0ca335cd2932578ed214d5999fc97ead8fe9e49c2ec9110724e294a151b1e2e2dac152326eaa3493",
          "sha256": "76424be984482c3601cbd4e502e0062c87c30c13d25db23fae3476c46ea84c0f",
          "sha1": "12b37fe01e75114b2d69d3a2f85cf6cd89e45fd9",
          "md5": "0318b466308f2d048c66472d83944f11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "size": 155609,
          "sha512": "a60ae30431dab7c74e3da5a1aa001924456e4d9f82e2a7d7992551970042fa5b7b0a0ca0e13f8d810fbd71d345992068403599543511c70eb3538bf37b8895a3",
          "sha256": "2e901068cdb25b59802170d2bc38456c4abc7b379007ff30f72b80de6d97710a",
          "sha1": "6dd6e27800f7178f78023d7e76fb2c1a2c3b72bd",
          "md5": "0cbcf8c823f83b865a49921df42229d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.camera.featurecombinationquery",
          "module": "featurecombinationquery",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-test",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01.aar",
          "size": 155609,
          "sha512": "a60ae30431dab7c74e3da5a1aa001924456e4d9f82e2a7d7992551970042fa5b7b0a0ca0e13f8d810fbd71d345992068403599543511c70eb3538bf37b8895a3",
          "sha256": "2e901068cdb25b59802170d2bc38456c4abc7b379007ff30f72b80de6d97710a",
          "sha1": "6dd6e27800f7178f78023d7e76fb2c1a2c3b72bd",
          "md5": "0cbcf8c823f83b865a49921df42229d6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "camera-camera2-pipe-testing-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-testing-1.0.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}