{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-complications",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-1.3.0-alpha03-sources.jar",
          "url": "watchface-complications-1.3.0-alpha03-sources.jar",
          "size": 20586,
          "sha512": "4219d221a0cef58c32b9826c2701f6c3617b68dcd371066086deade38004c623eccd2183fe0c71c3574da2b4cf298baf5dc757d8a212e7f9737c066aad9fe0f3",
          "sha256": "45e5466f0fd0a54ee3ad7d2ae3a678dd33203f0b5d8698e2379e6ca0f8c7a932",
          "sha1": "17b7abe74dcd1e04496ed297faba2fb562319dcd",
          "md5": "eb600ffff52f56f4ea18491ed8b67d5b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-1.3.0-alpha03.aar",
          "url": "watchface-complications-1.3.0-alpha03.aar",
          "size": 56513,
          "sha512": "fa7eb48be9377c3855a7bf7b00e90f4df381e0e993d53dd920ec3622f9e2145b8c1107f29343111341c542d36ea923e437b0ae774791ebd5515953bc8adabbca",
          "sha256": "5c81c2953123965ea94653e04528a2db845ea0a0befe352c6a31c9a0bb713e33",
          "sha1": "f7787601de2520069176d1ee30dd5b3a8e4f28bb",
          "md5": "084d95112788c362d27539012f44123f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-1.3.0-alpha03.aar",
          "url": "watchface-complications-1.3.0-alpha03.aar",
          "size": 56513,
          "sha512": "fa7eb48be9377c3855a7bf7b00e90f4df381e0e993d53dd920ec3622f9e2145b8c1107f29343111341c542d36ea923e437b0ae774791ebd5515953bc8adabbca",
          "sha256": "5c81c2953123965ea94653e04528a2db845ea0a0befe352c6a31c9a0bb713e33",
          "sha1": "f7787601de2520069176d1ee30dd5b3a8e4f28bb",
          "md5": "084d95112788c362d27539012f44123f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "watchface-complications is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-complications-1.3.0-alpha03-versionMetadata.json",
          "url": "watchface-complications-1.3.0-alpha03-versionMetadata.json",
          "size": 5832,
          "sha512": "c2d26ba0ac5bcba0ff23f0ffc15d940d064f40c63e27ca743bdf0e1ebcacc9381bf68eada3259e6817019669873a0a86454e98f70810feb9ebd9cb54b52951bd",
          "sha256": "84730a6f03051add39ad45313a03af2c07a4f13ee79275ed126030fd1e5b76a5",
          "sha1": "5eb15c84d6886e3e70f927c87665cdafff464617",
          "md5": "80167d1dde2e56e3758586cb2f2c480c"
        }
      ]
    }
  ]
}