version: "2.5.0-alpha12"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-android"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-iosarm64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-iossimulatorarm64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-iosx64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-jvm"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-linuxarm64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-linuxx64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-macosarm64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-macosx64"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.sqlite"
group_id: "androidx.sqlite"
artifact_id: "sqlite"
path: "/sqlite/sqlite"
sha: "1d85a4c4bfb2573264fd25efd031e9366f8a33d8"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.sqlite-sqlite-all-12640564-2.5.0-alpha12.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-bundled"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-ktx"
    version: "2.5.0-alpha12"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "android"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "jvm"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "macosx64"
kmp_children: "macosarm64"
