{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.3.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7139798"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta02.jar",
          "url": "room-compiler-processing-2.3.0-beta02.jar",
          "size": 582807,
          "sha512": "8bd68d6816c76682ddc5b2f6841600228c88761f5814f59519948ca2dac5d8853b9a7e4db410a74da2bf6e75ec4d9e55e4f471f8465d5b0742e5bb58b0c95245",
          "sha256": "8e2f4552786e6569cb86c540d3fd83700225dcb4c58c4a08a55153eb7f4d289b",
          "sha1": "fcc6c33c58b0720e9fe622c3e8de51f66f92b3cc",
          "md5": "ef336e1ecf75da33c2424d89f70a595f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.4.30-1.0.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta02.jar",
          "url": "room-compiler-processing-2.3.0-beta02.jar",
          "size": 582807,
          "sha512": "8bd68d6816c76682ddc5b2f6841600228c88761f5814f59519948ca2dac5d8853b9a7e4db410a74da2bf6e75ec4d9e55e4f471f8465d5b0742e5bb58b0c95245",
          "sha256": "8e2f4552786e6569cb86c540d3fd83700225dcb4c58c4a08a55153eb7f4d289b",
          "sha1": "fcc6c33c58b0720e9fe622c3e8de51f66f92b3cc",
          "md5": "ef336e1ecf75da33c2424d89f70a595f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta02-sources.jar",
          "url": "room-compiler-processing-2.3.0-beta02-sources.jar",
          "size": 123522,
          "sha512": "1199896ad770f455c5ce71eb3163729152677f4e743189bc4547fd05576d2a5fe23d752403e992f1ec2b2d58604aeb9b80979d3a0c61ee2f34b8b1e5a5dc855d",
          "sha256": "59bdadcf6ac883579d9d802d95ae2b59d9f88abc41e0b0f4ad892752f5eef46a",
          "sha1": "55832b69445adf5175a0889e6fae0a309111a372",
          "md5": "9c016bc0f5c8be7f5c584bf6070eb3e7"
        }
      ]
    }
  ]
}
