{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.print",
    "module": "print",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6947385"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "print-1.1.0-beta01.aar",
          "url": "print-1.1.0-beta01.aar",
          "size": 16064,
          "sha512": "9214c5924ab4c42021a21bd2f1f9d84a104da9bad5dad8a2fb8d4a323e92ab8ba69bbdc9a4edb9a7fa92317498d93e47f59e42da4446430e2b9da1f547ae3a5b",
          "sha256": "0d771d7f0389ae9e20ffbdd5b9ff20f62429782b661491ed1dd6bbdef2386094",
          "sha1": "cf9a775c1c58df5dea1ce9f7e2698e116902d816",
          "md5": "a594a3ff4551d73fd72bae48a1879677"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "print-1.1.0-beta01.aar",
          "url": "print-1.1.0-beta01.aar",
          "size": 16064,
          "sha512": "9214c5924ab4c42021a21bd2f1f9d84a104da9bad5dad8a2fb8d4a323e92ab8ba69bbdc9a4edb9a7fa92317498d93e47f59e42da4446430e2b9da1f547ae3a5b",
          "sha256": "0d771d7f0389ae9e20ffbdd5b9ff20f62429782b661491ed1dd6bbdef2386094",
          "sha1": "cf9a775c1c58df5dea1ce9f7e2698e116902d816",
          "md5": "a594a3ff4551d73fd72bae48a1879677"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "print-1.1.0-beta01-sources.jar",
          "url": "print-1.1.0-beta01-sources.jar",
          "size": 7147,
          "sha512": "f0d5ec60cae194ce29bf798dcf07169d85251bf1dedc73dc7eaf1b53c182c6e4b609e2799f457272baa1b7712f6527d574d234068d7208129725738f808d1cb7",
          "sha256": "b6189b61e826af0d64350f384378615ce84f43aafefe56b6e1af5af848b9abfe",
          "sha1": "f92413583ab7a95882a61b98bc7512878103b6a7",
          "md5": "c1c0e41c6a4059e2146d82ffe85f14cf"
        }
      ]
    }
  ]
}
