version: "1.5.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.collection"
group_id: "androidx.collection"
artifact_id: "collection-ktx"
path: "/collection/collection-ktx"
sha: "5aee86cca13a10a97d93540560cef9cb5ffa21ff"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.collection-collection-ktx-all-12431612-1.5.0-alpha03.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0-alpha03"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
