{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression-pipeline",
    "version": "1.3.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13192810"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha10-sources.jar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha10-sources.jar",
          "size": 75519,
          "sha512": "fcea173b4029705b934f419a04f76f8f3e00d75b60399afad4d2822e4812125108fb3dda8ed7aad12e77ab7a57be3feba8946cb3407dee244b5244d0616538c2",
          "sha256": "47eeceeb269fcf6a411de30052882ac53a7a83872420729922b85befd3dc6ece",
          "sha1": "edb59a864c1bc14a85c2dfe0729ebd8a0c3b7094",
          "md5": "e39e0e424de3781137d004297e687522"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha10.aar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha10.aar",
          "size": 154098,
          "sha512": "a5676f2c55534973bae5fe6dc1362f3bb67b9dc3280b0bdccbff19eb858cf03af24d9be3cd7518ee1fdab0fcd1996c8bc8c74efc8b6e09bbe6cb0890af386ba7",
          "sha256": "c410fcc68ade1e63e2b04bcea08aea0ac954ca7eab60fae7f3196213b162f225",
          "sha1": "a47a4a4f8f724e4aca9d9d4b3e9c35a30bfc999f",
          "md5": "a844a836febaa4e10586523c0f33844d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha10.aar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha10.aar",
          "size": 154098,
          "sha512": "a5676f2c55534973bae5fe6dc1362f3bb67b9dc3280b0bdccbff19eb858cf03af24d9be3cd7518ee1fdab0fcd1996c8bc8c74efc8b6e09bbe6cb0890af386ba7",
          "sha256": "c410fcc68ade1e63e2b04bcea08aea0ac954ca7eab60fae7f3196213b162f225",
          "sha1": "a47a4a4f8f724e4aca9d9d4b3e9c35a30bfc999f",
          "md5": "a844a836febaa4e10586523c0f33844d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha10"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha10-versionMetadata.json",
          "url": "protolayout-expression-pipeline-1.3.0-alpha10-versionMetadata.json",
          "size": 5880,
          "sha512": "5c314fc79955d75182e03264f73d124441367518855c85d5024d023a88b4f113b9bc768c151019f8a18de381a90f2bf35c80c94ddf0522322280d970aaa785aa",
          "sha256": "9294742514bc19fc999a0d66b8d3b8809c0e8dca5ac33375ea7a920f0e6f3547",
          "sha1": "8dd9f2a4f8d59b0c1cf3bd7e62b58db9ccdac665",
          "md5": "13eff603f180c1ecadfe3671024ad65e"
        }
      ]
    }
  ]
}