version: "1.0.0-alpha11"
dependency_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.12.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.12.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.sdkruntime"
    artifact_id: "sdkruntime-core"
    version: "1.0.0-alpha11"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.sdkruntime"
group_id: "androidx.privacysandbox.sdkruntime"
artifact_id: "sdkruntime-client"
path: "/privacysandbox/sdkruntime/sdkruntime-client"
sha: "0989b2705ed8f4d64c7830e7647c16b583668c21"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-privacysandbox-sdkruntime-11300958.zip"
project_zip_path: "per-project-zips/androidx.privacysandbox.sdkruntime-sdkruntime-client-all-11300958-1.0.0-alpha11.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.sdkruntime"
    artifact_id: "sdkruntime-core"
    version: "1.0.0-alpha11"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.sdkruntime"
    artifact_id: "sdkruntime-provider"
    version: "1.0.0-alpha11"
    is_tip_of_tree: true
  }
}
