{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-ktx",
    "version": "1.6.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.6.0-alpha04.aar",
          "url": "fragment-ktx-1.6.0-alpha04.aar",
          "size": 29589,
          "sha512": "932b6a7136ebd2ca1b83af201cd0e8ff41cf132d074e3b043e3dacbfee1359c6ee594fdd2d53c3735c7019c17b38070a10986acc9ba4cf88f12b12f2b0511002",
          "sha256": "84dbda812dae57cc01c15e79d996be384f820b2fa4d93f984f7df5ee776232ee",
          "sha1": "90e225bfa936d30594ed388525cd1475c8715a2f",
          "md5": "b1b390a87b9f32311dd61218da4b586f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.5.1"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.0"
          },
          "reason": "Mirror fragment dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-ktx-1.6.0-alpha04.aar",
          "url": "fragment-ktx-1.6.0-alpha04.aar",
          "size": 29589,
          "sha512": "932b6a7136ebd2ca1b83af201cd0e8ff41cf132d074e3b043e3dacbfee1359c6ee594fdd2d53c3735c7019c17b38070a10986acc9ba4cf88f12b12f2b0511002",
          "sha256": "84dbda812dae57cc01c15e79d996be384f820b2fa4d93f984f7df5ee776232ee",
          "sha1": "90e225bfa936d30594ed388525cd1475c8715a2f",
          "md5": "b1b390a87b9f32311dd61218da4b586f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fragment-ktx-1.6.0-alpha04-sources.jar",
          "url": "fragment-ktx-1.6.0-alpha04-sources.jar",
          "size": 6437,
          "sha512": "57ba3c7a5be2637bab276975f55d8c27190a3dd2f3f68a2e11997bbeded6e70c4322df7480771716c03b51f67de6f9b650b0334e2626e235c61070576143f1ec",
          "sha256": "fdc50d74e3b70712f8e4ed39c60fc1a3b613bb49e9a8a89fc53ac35926a3e823",
          "sha1": "656ee3b3618f377f8671e3a678a0fce0c8f56b1e",
          "md5": "582c3688a9fe6dd15b2b099ebe0d3b55"
        }
      ]
    }
  ]
}