version: "1.5.0-alpha06"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.biometric"
    artifact_id: "biometric"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.15.0-beta01"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.credentials"
group_id: "androidx.credentials"
artifact_id: "credentials"
path: "/credentials/credentials"
sha: "cba68203cb55fa2075a70d105a899b9b83a37a42"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.credentials-credentials-all-12469507-1.5.0-alpha06.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.credentials"
    artifact_id: "credentials-play-services-auth"
    version: "1.5.0-alpha06"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
