{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views-helper",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01.aar",
          "url": "emoji2-views-helper-1.5.0-alpha01.aar",
          "size": 22598,
          "sha512": "03da82fd5b7aa6af1a896ddd45ee7c137be9c40acfb18ac042749426d62fe383a8d954d6281d12e2ee317b537cb057ea638d541426187b5cf12ff23fff3c0e55",
          "sha256": "7b49460b4b989d242df8ca67f852cc8f212dde9fa4176d012f782c684a97f2ee",
          "sha1": "9c8fbc67642ca8b71c6dedd4a3576ae1629485ca",
          "md5": "2cbe295fa1b60c56c13524bcdb698a77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01.aar",
          "url": "emoji2-views-helper-1.5.0-alpha01.aar",
          "size": 22598,
          "sha512": "03da82fd5b7aa6af1a896ddd45ee7c137be9c40acfb18ac042749426d62fe383a8d954d6281d12e2ee317b537cb057ea638d541426187b5cf12ff23fff3c0e55",
          "sha256": "7b49460b4b989d242df8ca67f852cc8f212dde9fa4176d012f782c684a97f2ee",
          "sha1": "9c8fbc67642ca8b71c6dedd4a3576ae1629485ca",
          "md5": "2cbe295fa1b60c56c13524bcdb698a77"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01-sources.jar",
          "url": "emoji2-views-helper-1.5.0-alpha01-sources.jar",
          "size": 17591,
          "sha512": "04a0bde8df29903f572d57aee20fa0c9f2828f3cfa86baa1cc6c6c2cf5884572a3043d5ec6b21de4241a8779a5187c57b3bf0da885cb9529be21b89d98dd4108",
          "sha256": "7c813c4fc93038ef7d262fd894c48f960f6d914f79d83407106ede1ab55b92a0",
          "sha1": "53c89cc5c38159d675323a0031ea998130ac8bc0",
          "md5": "ac8cdad256777abad0666bfd54e77bc4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.5.0-alpha01"
          },
          "reason": "emoji2-views-helper is in atomic group androidx.emoji2"
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.5.0-alpha01-versionMetadata.json",
          "url": "emoji2-views-helper-1.5.0-alpha01-versionMetadata.json",
          "size": 1317,
          "sha512": "373f7f35002fa483145bcff32c864e10c06b59335a323c3c92fbe06b6d07aeed673103b89a500a4be6e5a931c2bdee756e49cde4d02bd2776212188ae8688adf",
          "sha256": "1f92fa04d9b57998b04776788753148c92eff2c012570e80754280edeba340df",
          "sha1": "a34522e3fe38ef005ebba2d790a230d697238073",
          "md5": "5d097511c796eb7bcf0e1fac28aaabef"
        }
      ]
    }
  ]
}