version: "1.5.0-beta02"
dependency_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0-beta02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "12958663"
group_id: "androidx.collection"
artifact_id: "collection-ktx"
path: "/collection/collection-ktx"
sha: "7b9c01964c34698a8fdf83210a5ffd2765512f1a"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.collection-collection-ktx-all-12958663-1.5.0-beta02.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0-beta02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":collection:collection-ktx:test"
