version: "1.6.0-alpha08"
dependency_list {
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-core"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-extended-android"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-extended-desktop"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.material"
group_id: "androidx.compose.material"
artifact_id: "material-icons-extended"
path: "/compose/material/material-icons-extended"
sha: "e459e4ff93f3d038a8eb839f53bd27c44d7435c5"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-material-10998100.zip"
project_zip_path: "per-project-zips/androidx.compose.material-material-icons-extended-all-10998100-1.6.0-alpha08.zip"
kotlin_version: "1.9.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-core"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-ripple"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
}
