version: "1.5.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.transition"
    artifact_id: "transition"
    version: "1.5.0-rc01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.transition"
group_id: "androidx.transition"
artifact_id: "transition-ktx"
path: "/transition/transition-ktx"
sha: "edd19514b50734044a2a42cd9be3930fdf188b0f"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.transition-transition-ktx-all-12133442-1.5.0-rc01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.transition"
    artifact_id: "transition"
    version: "1.5.0-rc01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
