{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-common",
    "version": "2.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.9.0-alpha01-sources.jar",
          "url": "navigation-common-2.9.0-alpha01-sources.jar",
          "size": 90562,
          "sha512": "ddd5e22c7cf97a4905c3d7e267411d74ab616c1e15a81e8855ecc7388a7c41ab8c565f949cc9af778eba0e6399fddc414974ac156e974b5f5ada72a47d0ff559",
          "sha256": "590cac1640d2470ffe54cf10165bb58b84a77bae672b18ce05049fb9bacc58d5",
          "sha1": "7adf24455fc7f079ee03bb4b5221906e387296f8",
          "md5": "f086c886f1da379cb590384ce7583f21"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.9.0-alpha01.aar",
          "url": "navigation-common-2.9.0-alpha01.aar",
          "size": 363807,
          "sha512": "4e2ec27a7956b8011c7f0c30cab2eb4eedf7cfb35de3e1826d3bb305746a463af07c2f567b097596e4dcc74d4c16f3e335b6422e558842c1555fac15a79dcdf3",
          "sha256": "49e0f2da7ec95f220c1e421e18502deacdb04a34d2aba2d1ca2966b940941c6d",
          "sha1": "bc3df8af6e7677a888d9fca27280a57c28514557",
          "md5": "8495de7a93a5b35a68f7984cf043d0df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.6.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.9.0-alpha01.aar",
          "url": "navigation-common-2.9.0-alpha01.aar",
          "size": 363807,
          "sha512": "4e2ec27a7956b8011c7f0c30cab2eb4eedf7cfb35de3e1826d3bb305746a463af07c2f567b097596e4dcc74d4c16f3e335b6422e558842c1555fac15a79dcdf3",
          "sha256": "49e0f2da7ec95f220c1e421e18502deacdb04a34d2aba2d1ca2966b940941c6d",
          "sha1": "bc3df8af6e7677a888d9fca27280a57c28514557",
          "md5": "8495de7a93a5b35a68f7984cf043d0df"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha01"
          },
          "reason": "navigation-common is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-common-2.9.0-alpha01-versionMetadata.json",
          "url": "navigation-common-2.9.0-alpha01-versionMetadata.json",
          "size": 30141,
          "sha512": "9b781c58306c00dbf1e79a40d56e9c1ad6158ee09e128ad59d3948684fead6060698a0847de0e1514e8de1888bc56036cabf959d0e0cf3a58ce0b6a070d484cf",
          "sha256": "c388f54dfb09752b4db98db77a6d3bea2fcd4e7771fb192817c5c2534a39caae",
          "sha1": "912577134192e2a43bad6a94fb7fa4a773f9bcb4",
          "md5": "e2841302e98c1bf73ac2ece72c257c19"
        }
      ]
    }
  ]
}