version: "1.0.0-alpha06"
dependency_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha06"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha06"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.tools"
group_id: "androidx.privacysandbox.tools"
artifact_id: "tools-apicompiler"
path: "/privacysandbox/tools/tools-apicompiler"
sha: "0989b2705ed8f4d64c7830e7647c16b583668c21"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-privacysandbox-tools-11300958.zip"
project_zip_path: "per-project-zips/androidx.privacysandbox.tools-tools-apicompiler-all-11300958-1.0.0-alpha06.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha06"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apigenerator"
    version: "1.0.0-alpha06"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apipackager"
    version: "1.0.0-alpha06"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha06"
    is_tip_of_tree: true
  }
}
