version: "1.4.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.biometric"
    artifact_id: "biometric"
    version: "1.4.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.biometric"
group_id: "androidx.biometric"
artifact_id: "biometric-ktx"
path: "/biometric/biometric-ktx"
sha: "11786a3ed54689e0dc5ee62171e9877f4cbd4292"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.biometric-biometric-ktx-all-12257120-1.4.0-alpha02.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.biometric"
    artifact_id: "biometric"
    version: "1.4.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
