version: "1.2.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.appcompat"
    artifact_id: "appcompat"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.emoji"
    artifact_id: "emoji"
    version: "1.2.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13740253"
group_id: "androidx.emoji"
artifact_id: "emoji-appcompat"
path: "/emoji/emoji-appcompat"
sha: "50823057bff756367f94902b9f2de0aac14375cc"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.emoji-emoji-appcompat-all-13740253-1.2.0-alpha03.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "emoji-emoji-appcompatreleaseAndroidTest.xml"
test_module_names: ":emoji:emoji-appcompat:testReleaseUnitTest"
