version: "1.2.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.appcompat"
    artifact_id: "appcompat"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.emoji"
    artifact_id: "emoji"
    version: "1.2.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.emoji"
group_id: "androidx.emoji"
artifact_id: "emoji-appcompat"
path: "/emoji/emoji-appcompat"
sha: "82f7f4f17bdc4d685b50d2e00c06c920cf2b6572"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.emoji-emoji-appcompat-all-12437715-1.2.0-alpha03.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
