{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-appcompat",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 5633,
          "sha512": "fb397f9608101a4b17bec6e01a79befc2774fbe83690e910f50eacf9b42cc3ca343802fd6edd82703317f30e1b2c1373426a685758ad081c34525c3d261d867c",
          "sha256": "83a7a3dfbbc482463dfc31f628a5433933a01309eb3ebd4c8c29b4681772b215",
          "sha1": "bc15c5fa6cb6332775718d40ddd13f78a0a273d3",
          "md5": "bff2aa4f46e18031ff1209575499373b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 5633,
          "sha512": "fb397f9608101a4b17bec6e01a79befc2774fbe83690e910f50eacf9b42cc3ca343802fd6edd82703317f30e1b2c1373426a685758ad081c34525c3d261d867c",
          "sha256": "83a7a3dfbbc482463dfc31f628a5433933a01309eb3ebd4c8c29b4681772b215",
          "sha1": "bc15c5fa6cb6332775718d40ddd13f78a0a273d3",
          "md5": "bff2aa4f46e18031ff1209575499373b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "url": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "size": 4355,
          "sha512": "05730b58fb8391f28050b8cc51cfb42fdfc6c888cbb70b642d1e8b11f82b15946b65f05350de21d4f222e58f2e2d97ed4e195facd843c06552b784e7c4edd8ec",
          "sha256": "8c37ea1aefdd5d8e36d6fd5d7535c6fdfadd02b61fa51c1e4178b0cec49e6de0",
          "sha1": "6100352f9c99794e5ec330e4e428e344a7b3a245",
          "md5": "d708308a2084b09201efe840d9541b78"
        }
      ]
    }
  ]
}