{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-appcompat",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6947385"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 15746,
          "sha512": "d2c2b35b87c39c7e4ca9e2cde6e7c1993b14b015777b42f7ab11bf3810f1e8bda3ffd46e9531b9b4b32aeca4aa098c3a6e1f992a9f8494df3a3e6affa57ba037",
          "sha256": "fecbd69662150ffdde150ae1f1de984c4d16d7d7086beead537e8012907a2d75",
          "sha1": "a3288b780d78ecfef927d8903f81525cc7e39014",
          "md5": "892c390aa27c99042ad7e39c801b4dcc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 15746,
          "sha512": "d2c2b35b87c39c7e4ca9e2cde6e7c1993b14b015777b42f7ab11bf3810f1e8bda3ffd46e9531b9b4b32aeca4aa098c3a6e1f992a9f8494df3a3e6affa57ba037",
          "sha256": "fecbd69662150ffdde150ae1f1de984c4d16d7d7086beead537e8012907a2d75",
          "sha1": "a3288b780d78ecfef927d8903f81525cc7e39014",
          "md5": "892c390aa27c99042ad7e39c801b4dcc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "url": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "size": 4355,
          "sha512": "05730b58fb8391f28050b8cc51cfb42fdfc6c888cbb70b642d1e8b11f82b15946b65f05350de21d4f222e58f2e2d97ed4e195facd843c06552b784e7c4edd8ec",
          "sha256": "8c37ea1aefdd5d8e36d6fd5d7535c6fdfadd02b61fa51c1e4178b0cec49e6de0",
          "sha1": "6100352f9c99794e5ec330e4e428e344a7b3a245",
          "md5": "d708308a2084b09201efe840d9541b78"
        }
      ]
    }
  ]
}
