{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji-appcompat",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "url": "emoji-appcompat-1.2.0-alpha03-sources.jar",
          "size": 8494,
          "sha512": "d9ad785b91dd970f6142a015b3adb5631d320bba720c3801586830ee9f2438f68289651e30a01e158bbaf14454afd968df4e3b6ee3bde6c02ee1d270ac75617e",
          "sha256": "5403a3a7d7b843d8c51880d8c50169c3e2f7015b1631223ab709f20c8a959fb5",
          "sha1": "dbd501d7282f734211a63920074e5df73a201223",
          "md5": "fedad5ddce1362e79b6377512999c1fa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 8767,
          "sha512": "e13a4b4f8d23346e40eb6f8788721c8ae119130e84b34745cf46d4fb7b7ab3fc8112ac98317590667f99e56867d3c9e3704ce089ab75255c82da69c2333f9ca3",
          "sha256": "4263b2cea9dc254df61bede8ba956919c2a592169020ea6a424a938ad1c141ea",
          "sha1": "15de44ca3be6e53bf6981da2504bf7e384a32373",
          "md5": "4706af37b553f5e625724971c4e1ec98"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.emoji",
          "module": "emoji",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03.aar",
          "url": "emoji-appcompat-1.2.0-alpha03.aar",
          "size": 8767,
          "sha512": "e13a4b4f8d23346e40eb6f8788721c8ae119130e84b34745cf46d4fb7b7ab3fc8112ac98317590667f99e56867d3c9e3704ce089ab75255c82da69c2333f9ca3",
          "sha256": "4263b2cea9dc254df61bede8ba956919c2a592169020ea6a424a938ad1c141ea",
          "sha1": "15de44ca3be6e53bf6981da2504bf7e384a32373",
          "md5": "4706af37b553f5e625724971c4e1ec98"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "emoji-appcompat-1.2.0-alpha03-versionMetadata.json",
          "url": "emoji-appcompat-1.2.0-alpha03-versionMetadata.json",
          "size": 1272,
          "sha512": "08dcfc8f2c806c764fe561e91aaaaa496c789959c7debc5a34c8828d7e2278cb796ccf5f1d7dc8d10fb23a352e549068bb827a00be86880dd1292577b7172935",
          "sha256": "aeb57153f149ab35ee5d788052058bd8ee1379e9ad437856e85ad9cdfc530776",
          "sha1": "62f6a8bde71174872f32b6216907045f1dc7dc54",
          "md5": "7df902458677a225f108a55a8c533105"
        }
      ]
    }
  ]
}