{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget-proto",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2",
      "buildId:": "12676611"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-proto-1.2.0-alpha01.jar",
          "url": "glance-appwidget-proto-1.2.0-alpha01.jar",
          "size": 49288,
          "sha512": "8e2a4113d479d64f0c47d0916f626a51305438c52ee079d0b2c5943e1e69e25e968439351c41dc2044c310ea913c09769023c8db6d35a2a50d3b5e04acaaa872",
          "sha256": "a444d842557ebe472e38640e171b6c76f88ffd15e9d874f37ad586a7b8519643",
          "sha1": "ea01733acf192bc6d34e641975a92fd4bc0642d8",
          "md5": "2cd232679b5c6a99730d5e7e7bf3edbd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-proto-1.2.0-alpha01.jar",
          "url": "glance-appwidget-proto-1.2.0-alpha01.jar",
          "size": 49288,
          "sha512": "8e2a4113d479d64f0c47d0916f626a51305438c52ee079d0b2c5943e1e69e25e968439351c41dc2044c310ea913c09769023c8db6d35a2a50d3b5e04acaaa872",
          "sha256": "a444d842557ebe472e38640e171b6c76f88ffd15e9d874f37ad586a7b8519643",
          "sha1": "ea01733acf192bc6d34e641975a92fd4bc0642d8",
          "md5": "2cd232679b5c6a99730d5e7e7bf3edbd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget-proto is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-proto-1.2.0-alpha01-sources.jar",
          "url": "glance-appwidget-proto-1.2.0-alpha01-sources.jar",
          "size": 15071,
          "sha512": "147bb58835e1a990aca338d2e581cf5ad6105ed2145820351952688ebdca7511fdb2712ee8c0056b262c8fc0bdccd325b9170cac92165b49ccd66b452c0fbd00",
          "sha256": "ad9e53325b064060465c7efbef315db8c55ab24c369780d7643343c04a534f19",
          "sha1": "06684d561a4af586f322d7ef131899071e3dbcfe",
          "md5": "bed1f8d0cd0f9415d7f6f9e6e84ee5cc"
        }
      ]
    }
  ]
}