{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-core",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.2.0-alpha04.aar",
          "url": "material-icons-core-1.2.0-alpha04.aar",
          "size": 674790,
          "sha512": "ab95c63e7c8e482114d987b24a4482668a853dcd08ec3ba73ad57de054d6ab885232ba308231e58b366555c3633a44393c1ed3ff6f4909b72060d83bff95b444",
          "sha256": "ca643c7a14442040962dd853375c92ed3e168c233f0217319b9b6019c35760f5",
          "sha1": "948f4b69c37cad74d9ec8ddc7cb6ad9c6ddc6155",
          "md5": "3975579975782a380f1b93b11224ead5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-core-1.2.0-alpha04.aar",
          "url": "material-icons-core-1.2.0-alpha04.aar",
          "size": 674790,
          "sha512": "ab95c63e7c8e482114d987b24a4482668a853dcd08ec3ba73ad57de054d6ab885232ba308231e58b366555c3633a44393c1ed3ff6f4909b72060d83bff95b444",
          "sha256": "ca643c7a14442040962dd853375c92ed3e168c233f0217319b9b6019c35760f5",
          "sha1": "948f4b69c37cad74d9ec8ddc7cb6ad9c6ddc6155",
          "md5": "3975579975782a380f1b93b11224ead5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-core-1.2.0-alpha04-sources.jar",
          "url": "material-icons-core-1.2.0-alpha04-sources.jar",
          "size": 239477,
          "sha512": "40f2cbb3133f8ef8571c1625d2bcbf8d9a35db8b87e559ea0e117524c1725606944feffd6c8d365a8d1f1887fe3ec924b060f7d26ff0cf8d26c947f129f296a4",
          "sha256": "e2a1104cabf4c0555260742c9150c26116a530f8de1e52ca790c04cfb6c7dfbf",
          "sha1": "75cdc89520213df9220330f01e8a405be059759e",
          "md5": "84c64894f5c80fa8057de610c24f3ef6"
        }
      ]
    }
  ]
}
