version: "2.9.0-alpha09"
dependency_list {
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common"
    version: "2.9.0-alpha07"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime-testing"
    version: "2.9.0-alpha07"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel"
    version: "2.9.0-alpha07"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-savedstate"
    version: "2.9.0-alpha07"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-android"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-desktop"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-iosarm64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-iossimulatorarm64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-iosx64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-linuxarm64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-linuxx64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-macosarm64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing-macosx64"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13230537"
group_id: "androidx.navigation"
artifact_id: "navigation-testing"
path: "/navigation/navigation-testing"
sha: "10c9fbca13188630ccc3bd49bce48dd83d600ca5"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.navigation-navigation-testing-all-13230537-2.9.0-alpha09.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common-ktx"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-compose"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-fragment"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-runtime"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-compose"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-ktx"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-ktx"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-generator"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-gradle-plugin"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui-ktx"
    version: "2.9.0-alpha09"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "android"
kmp_children: "desktop"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "macosx64"
kmp_children: "macosarm64"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
test_module_names: ":navigation:navigation-testing:desktopTest"
test_module_names: ":navigation:navigation-testing:linuxX64Test"
test_module_names: ":navigation:navigation-testing:macosX64Test"
test_module_names: ":navigation:navigation-testing:macosArm64Test"
test_module_names: ":navigation:navigation-testing:iosX64Test"
test_module_names: ":navigation:navigation-testing:iosSimulatorArm64Test"
test_module_names: "navigation-navigation-testingandroidInstrumentedTest.xml"
test_module_names: ":navigation:navigation-testing:testAndroidUnitTest"
