{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression-pipeline",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha03-sources.jar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha03-sources.jar",
          "size": 75370,
          "sha512": "00c2ba49b3c40e97a525242c37cb42eff9503ef1f6489be43160b697df0f6beba71884e996cbe6a4670dcf5b147cd1b04de9fb6b07690b0d20e71fc8b74cd806",
          "sha256": "664ed70b882bd95dfd162c301cf9dccc1b84c5f67e8b88c777e8b59bbf3ab27b",
          "sha1": "90babb1f131efb311a66c0d38027f94902f72291",
          "md5": "3535fa9f4ba5b5109fd3a65334869907"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha03.aar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha03.aar",
          "size": 153425,
          "sha512": "d1605a7c08d6ecd2e0f9dc08e39f4ea58c818c4231d403e86fa1377814a96c351ee23cbfb4331d0c569e29a2c2e30a0b357e3bac91d7cdc1dec25af82ee353ae",
          "sha256": "7a045261afd9e133b4000aac2fb11821a059c623e9651988ba7723779242d67e",
          "sha1": "167600d691b344a18640ae38924b5c7d3dfed920",
          "md5": "6847e066dfdad2aad9649582a93d95df"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha03.aar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha03.aar",
          "size": 153425,
          "sha512": "d1605a7c08d6ecd2e0f9dc08e39f4ea58c818c4231d403e86fa1377814a96c351ee23cbfb4331d0c569e29a2c2e30a0b357e3bac91d7cdc1dec25af82ee353ae",
          "sha256": "7a045261afd9e133b4000aac2fb11821a059c623e9651988ba7723779242d67e",
          "sha1": "167600d691b344a18640ae38924b5c7d3dfed920",
          "md5": "6847e066dfdad2aad9649582a93d95df"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha03"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha03-versionMetadata.json",
          "url": "protolayout-expression-pipeline-1.3.0-alpha03-versionMetadata.json",
          "size": 5880,
          "sha512": "df667da0f4f4a20ef6b0e37c5b451e643df20db9758e9367d48c97860240391032d861a79d2e04b66fe74d0fb434c4685b497e88ed4a1eaf594f392076ea88f3",
          "sha256": "cf451ddbde3d3cfc6be15431fba32dcbe514791fe8f6bdb79e6d35b65eb870d5",
          "sha1": "994f9f70fb804c19386d7fc7724e0cf1a70e9886",
          "md5": "796c75c8c38591dae19cd077d6067b5a"
        }
      ]
    }
  ]
}