version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.8.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "13457307"
group_id: "androidx.appsearch"
artifact_id: "appsearch-builtin-types"
path: "/appsearch/appsearch-builtin-types"
sha: "6145f7b86ab4f341c688f916b8151d6c0c244ec0"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.appsearch-appsearch-builtin-types-all-13457307-1.2.0-alpha01.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-compiler"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-debug-view"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-external-protobuf"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-ktx"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-local-storage"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-platform-storage"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-play-services-storage"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "appsearch-appsearch-builtin-typesreleaseAndroidTest.xml"
test_module_names: ":appsearch:appsearch-builtin-types:testReleaseUnitTest"
