{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.16.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12877714"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.16.0-alpha01-sources.jar",
          "url": "core-ktx-1.16.0-alpha01-sources.jar",
          "size": 73838,
          "sha512": "fcfd594b917270fa58cb5887ca41a0a1fd301f984e72f3a471c6a1c073d198f61cd61e2cebd72abafa32cdf43289e43b8636c40ceaf9bebdc87ffd273c53f84f",
          "sha256": "1aadd1028ab3bad23c90cfed674d660e0743056db16076d7d35a99f9827c4d42",
          "sha1": "4fe42edd87c0aceaf871cf5dc50fabbcc74d5075",
          "md5": "78fbdb44dedfc8ef42149470098c3b9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.16.0-alpha01.aar",
          "url": "core-ktx-1.16.0-alpha01.aar",
          "size": 175569,
          "sha512": "d94d79a60333a95cc753f5351528b307927f52110121b8d8f3b2e8611ce88b8e3f818f95acfd98eb7db2abe3e6176350c64a09bd0bc6c79dc686bdd3e2f949fa",
          "sha256": "cdecc0e3b3fa166b07ada8aed9e932395a3faa6e88e939d7e19f34752c2f89de",
          "sha1": "d365dac44a5ecb278ef2c40a0659a1280fed4892",
          "md5": "5a7713d24ec4bafcd9f7a6c0f9b20b12"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.16.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.16.0-alpha01.aar",
          "url": "core-ktx-1.16.0-alpha01.aar",
          "size": 175569,
          "sha512": "d94d79a60333a95cc753f5351528b307927f52110121b8d8f3b2e8611ce88b8e3f818f95acfd98eb7db2abe3e6176350c64a09bd0bc6c79dc686bdd3e2f949fa",
          "sha256": "cdecc0e3b3fa166b07ada8aed9e932395a3faa6e88e939d7e19f34752c2f89de",
          "sha1": "d365dac44a5ecb278ef2c40a0659a1280fed4892",
          "md5": "5a7713d24ec4bafcd9f7a6c0f9b20b12"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-ktx-1.16.0-alpha01-versionMetadata.json",
          "url": "core-ktx-1.16.0-alpha01-versionMetadata.json",
          "size": 42717,
          "sha512": "c0ef67a8ad6615cd4747ca082c4a4fd3a37aa9e216744304504312d02d79531996daf71149fd95a9fc101aa612ac58c0d8f203234a18847c8a3ece0c8b79c1d1",
          "sha256": "544754134adada629ee9524e0af94b5a1b23a283ffb5b87defdf5c13987c4158",
          "sha1": "5ca8b99aa6799b826d1e0c8a9b01c28e96b2d28a",
          "md5": "f2d8eac5f01de36a31e22a3740da6843"
        }
      ]
    }
  ]
}