{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-ongoing",
    "version": "1.0.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-ongoing-1.0.0-alpha07.aar",
          "url": "wear-ongoing-1.0.0-alpha07.aar",
          "size": 27581,
          "sha512": "b5fb50efcdc5a9de3ad25a509202aefcde0838736728dcc56bf9f040f0122edda25b5b295f2463471bf9da4e03792ba7bc3c30dd7dd36e3c8f64023f4b06d1ce",
          "sha256": "13870e5651e1cb910acb6a0fb47952d24c1a5d1074de89c19fb887efe401a6f5",
          "sha1": "c8bfc01e626cf11c275e3a31c5cbf4f4a60884ab",
          "md5": "0e34392b5a92c54f632de662cf2eca3a"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "wear-ongoing-1.0.0-alpha07.aar",
          "url": "wear-ongoing-1.0.0-alpha07.aar",
          "size": 27581,
          "sha512": "b5fb50efcdc5a9de3ad25a509202aefcde0838736728dcc56bf9f040f0122edda25b5b295f2463471bf9da4e03792ba7bc3c30dd7dd36e3c8f64023f4b06d1ce",
          "sha256": "13870e5651e1cb910acb6a0fb47952d24c1a5d1074de89c19fb887efe401a6f5",
          "sha1": "c8bfc01e626cf11c275e3a31c5cbf4f4a60884ab",
          "md5": "0e34392b5a92c54f632de662cf2eca3a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-ongoing-1.0.0-alpha07-sources.jar",
          "url": "wear-ongoing-1.0.0-alpha07-sources.jar",
          "size": 19184,
          "sha512": "f47fc3d785fe6956eb9ce2277b712b65a1d801a683ac6f64094eebb7a2aea27eb2ed643f3ef99dd51cae1ca04feabf15f3031de5a98bffa0cf41c83e727d9d0e",
          "sha256": "86c6199cbbbfc298d0404f4f21276a8e52c20a663e2fc59860cadf02c54e3187",
          "sha1": "ab9454e815fe4f0fb8dce5a5fedcc4f43403a2b4",
          "md5": "77d461c6818d54c8f8235ea6437253ee"
        }
      ]
    }
  ]
}
