version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-experimental"
    version: "1.4.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window.extensions.core"
    artifact_id: "core"
    version: "1.0.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.window.extensions"
group_id: "androidx.window.extensions"
artifact_id: "extensions"
path: "/window/extensions/extensions"
sha: "053d412c8c43cdacfaac6a909bee7519bca8daf6"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-window-extensions-11316582.zip"
project_zip_path: "per-project-zips/androidx.window.extensions-extensions-all-11316582-1.4.0-alpha01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
