{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.1.0-alpha04.aar",
          "url": "material-1.1.0-alpha04.aar",
          "size": 2327709,
          "sha512": "d8250dec68109321bb828fac59fda9bde539998d417dcff6c9096bc1e2b490cb42c4d73a3ff80df5bbc4941f6c5d6f536b23cfe1a292144f5a0a9d06750c663c",
          "sha256": "bcee2479c1ab4c3d1ed33ea1430b23d556368af4a0c10ef8c7854ffe1d71d18b",
          "sha1": "edb594e7a2bc99321487104e597b5ba33e0d4e39",
          "md5": "0e1115aca7042419a8003f4c83a49109"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.1.0-alpha04.aar",
          "url": "material-1.1.0-alpha04.aar",
          "size": 2327709,
          "sha512": "d8250dec68109321bb828fac59fda9bde539998d417dcff6c9096bc1e2b490cb42c4d73a3ff80df5bbc4941f6c5d6f536b23cfe1a292144f5a0a9d06750c663c",
          "sha256": "bcee2479c1ab4c3d1ed33ea1430b23d556368af4a0c10ef8c7854ffe1d71d18b",
          "sha1": "edb594e7a2bc99321487104e597b5ba33e0d4e39",
          "md5": "0e1115aca7042419a8003f4c83a49109"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.1.0-alpha04-sources.jar",
          "url": "material-1.1.0-alpha04-sources.jar",
          "size": 172973,
          "sha512": "80ede7bb96023e1598b4dd1a0566d9776960e7fcc1ff50bcbcd02157907813a9c8b17a5e734c5d48c7ff63a3d581107907c7e0e1abdccd513f4443f6252eb1f9",
          "sha256": "a671dfd9f63f8907cfa58103905879e224033654ea021b5c32fce83c3c5c37dc",
          "sha1": "59a4a62dc6fedfde353b237243924f7e22ea7d9f",
          "md5": "e3ed5b06ee89b119a11393d19b5cb598"
        }
      ]
    }
  ]
}
