version: "1.7.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.7.0-rc01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.fragment"
group_id: "androidx.fragment"
artifact_id: "fragment-testing-manifest"
path: "/fragment/fragment-testing-manifest"
sha: "660d1c43f4805028b9a4d96ea2e8d5d8c29c3d34"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.fragment-fragment-testing-manifest-all-11623381-1.7.0-rc01.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment"
    version: "1.7.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-compose"
    version: "1.7.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.7.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing"
    version: "1.7.0-rc01"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
