{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12846222"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-rc01-sources.jar",
          "url": "credentials-1.5.0-rc01-sources.jar",
          "size": 250066,
          "sha512": "048da32faacfe7720251f1ca078de551c5bf2cff6c744b89472c29ac7108d1c959f2580beae863592255cdeacdc76c13cbeb7c0c08adf7d554ce6cef896eb564",
          "sha256": "b309e3b4391ca273cc518d7a5c9d43e0a4126a4bc254ff7f7c7ebc4f55972241",
          "sha1": "4d299a045632780167ca065f0181206a55855e63",
          "md5": "0c75a545bff02f6bace64e2abe795874"
        },
        {
          "name": "credentials-1.5.0-rc01-samples-sources.jar",
          "url": "credentials-1.5.0-rc01-samples-sources.jar",
          "size": 7243,
          "sha512": "4802d83b3197e0faf36b8968e23723ad598d1954bdc5353bbe7193cd28f00fb0d41e98b28df9cae41584153608b7e52215c29dc8089d8785b2a4b83f34e4a003",
          "sha256": "fe1e7e44cf21e3cfd6858d14fba9da11aff6a3dc9d25b2bb634afb5a7dae73ae",
          "sha1": "1c39e28debbbbfaf621ec1643048b3ae9e7c745e",
          "md5": "44b66a46acc1d1332daf97f2211fe1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-rc01.aar",
          "url": "credentials-1.5.0-rc01.aar",
          "size": 617579,
          "sha512": "f40b083f6180f8badc8e059b3575411d4af9c2c7098c53cd258d7376bcabf63f5c6a25cc6ad1481a6762ba519855e86ad117650a29f43980b7cb3a6f3a9dc669",
          "sha256": "8478dbd6f1fc53f343445b6e300d05415214bfd7c1c3655381c86bb6c633656e",
          "sha1": "ed8f2e54eaeaabd3905c9178c7dd851765a01a08",
          "md5": "5f83106ee3290a8172ea70bd6552d08a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-rc01.aar",
          "url": "credentials-1.5.0-rc01.aar",
          "size": 617579,
          "sha512": "f40b083f6180f8badc8e059b3575411d4af9c2c7098c53cd258d7376bcabf63f5c6a25cc6ad1481a6762ba519855e86ad117650a29f43980b7cb3a6f3a9dc669",
          "sha256": "8478dbd6f1fc53f343445b6e300d05415214bfd7c1c3655381c86bb6c633656e",
          "sha1": "ed8f2e54eaeaabd3905c9178c7dd851765a01a08",
          "md5": "5f83106ee3290a8172ea70bd6552d08a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-rc01-versionMetadata.json",
          "url": "credentials-1.5.0-rc01-versionMetadata.json",
          "size": 70797,
          "sha512": "25b993dff7bc31ae8cddbe1e7b38ed6cebf6c65c9689e57004402f10d40c9f9f2d164947dfd17863c596cba5f9de07ad7a6b9ca6d3d2f813c5c5098205f8c6b9",
          "sha256": "a0b5f04664ead1a97644619ad5eebdc5b01f87acc42c355689b12355208ff57b",
          "sha1": "6199469b10a22fcc174593e4ac1ecb26a6979348",
          "md5": "6f6e143c696a3abbe22d12f0bb4d998a"
        }
      ]
    }
  ]
}