{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.5.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13794652"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-beta02-sources.jar",
          "url": "camera-camera2-1.5.0-beta02-sources.jar",
          "size": 423921,
          "sha512": "1bd3899c292fed5a89f025841da80a392eec1371535db622f54bf583e12d106b004a004486cafcaddeba3de56bc30cfa32770e30e9b061ea3bd0061e263791a9",
          "sha256": "96a2ac29e37e950b4c948d3fb6a88698755b7d4b3e7fd237179dce1160b59131",
          "sha1": "6d0e4514e7a6f9e476dd7b32a7c784ba249491f8",
          "md5": "0791d16bae35bd59f1e2e97fed768cb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-beta02.aar",
          "url": "camera-camera2-1.5.0-beta02.aar",
          "size": 601776,
          "sha512": "6aefb0549ffb1e3fea076beab20e8444696b9f0bf26b455c05ec2e0771c15dd207d34e70b2a12ba0f4e3584941f8cfbf0481aa04c6591750a296239d72463316",
          "sha256": "4ef1ff4794d0d2332f306e4103987c2b0cae9e828c5777442859cd051e8c165a",
          "sha1": "6838ba7653cf6abebb8c0129788924a8ab5283b1",
          "md5": "0216226ccd947e2fa6a5616d58713286"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "androidx.camera.featurecombinationquery",
          "module": "featurecombinationquery",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-beta02.aar",
          "url": "camera-camera2-1.5.0-beta02.aar",
          "size": 601776,
          "sha512": "6aefb0549ffb1e3fea076beab20e8444696b9f0bf26b455c05ec2e0771c15dd207d34e70b2a12ba0f4e3584941f8cfbf0481aa04c6591750a296239d72463316",
          "sha256": "4ef1ff4794d0d2332f306e4103987c2b0cae9e828c5777442859cd051e8c165a",
          "sha1": "6838ba7653cf6abebb8c0129788924a8ab5283b1",
          "md5": "0216226ccd947e2fa6a5616d58713286"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-beta02-versionMetadata.json",
          "url": "camera-camera2-1.5.0-beta02-versionMetadata.json",
          "size": 3277,
          "sha512": "a28eec65edfaa21396676bec29ff0d5923ddf6483e79aa9cf04246c27ff9d1aa1e62020b3d61f9fe06aeb6a6cc6df88d12ad6596f0a8001789dfabc83be9d6e6",
          "sha256": "d1d3abe8f34c05ee0062c40f3c5c1378376695ac2c46259a70c6e92fe67bc31c",
          "sha1": "99913f5112cf028dcd7c23d4d81da8e74e8796d4",
          "md5": "a2976ec39310f25829ccfcd8766347b3"
        }
      ]
    }
  ]
}