{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-util",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ui-util-1.2.0-alpha04.aar",
          "url": "ui-util-1.2.0-alpha04.aar",
          "size": 7812,
          "sha512": "d8dd85a59f5267d260206b7ae62aadcf01fd17ef1724726dc96e6f5a1472c6f732ccd7acf4b432e6d1644f27ea38615f37c0bd3699b5d64ef5939f12f8c2e13f",
          "sha256": "6348ea5f82f721296a69ff342cb3f2eca557392540b3124ffa8d289d89c249e8",
          "sha1": "cab2f669874d72a52f0bb6cd0a58e336be53339c",
          "md5": "ab32e0d08f6771f126fc771dcf75eef6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "ui-util-1.2.0-alpha04.aar",
          "url": "ui-util-1.2.0-alpha04.aar",
          "size": 7812,
          "sha512": "d8dd85a59f5267d260206b7ae62aadcf01fd17ef1724726dc96e6f5a1472c6f732ccd7acf4b432e6d1644f27ea38615f37c0bd3699b5d64ef5939f12f8c2e13f",
          "sha256": "6348ea5f82f721296a69ff342cb3f2eca557392540b3124ffa8d289d89c249e8",
          "sha1": "cab2f669874d72a52f0bb6cd0a58e336be53339c",
          "md5": "ab32e0d08f6771f126fc771dcf75eef6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-util-1.2.0-alpha04-sources.jar",
          "url": "ui-util-1.2.0-alpha04-sources.jar",
          "size": 4738,
          "sha512": "95b730ea51df6152bad807db5a6134e14f16e12dea9483b14a18935269b742d5db32ef934da95b003bea7d1dcafe4f7290e5aca5e65661fd7b96816f8109783b",
          "sha256": "5d041026b4ff3159f2f0c727f621d20fd3833b4a80218c5fe2bd078db7c1f8c4",
          "sha1": "7c2c3f778883b267141811dd639236f3ab27dd85",
          "md5": "ea129d8bc5d6f4400290ae50bbb1624c"
        }
      ]
    }
  ]
}
