version: "1.5.0"
dependency_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13276378"
group_id: "androidx.collection"
artifact_id: "collection-ktx"
path: "/collection/collection-ktx"
sha: "021f53c827fe8bc41f634836f6ad36ec44ef2823"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.collection-collection-ktx-all-13276378-1.5.0.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":collection:collection-ktx:test"
