version: "1.9.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-android"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-jvmstubs"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-linuxx64stubs"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13006434"
group_id: "androidx.compose.runtime"
artifact_id: "runtime"
path: "/compose/runtime/runtime"
sha: "79d4ded60ba22f3beeeb7f3bbc918c93cb26c3f8"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.runtime-runtime-all-13006434-1.9.0-alpha01.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-lint"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-livedata"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava2"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava3"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-saveable"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-saveable-lint"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-tracing"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
kmp_children: "jvmStubs"
kmp_children: "linuxx64Stubs"
test_module_names: ":compose:runtime:runtime:jvmStubsTest"
test_module_names: ":compose:runtime:runtime:linuxx64StubsTest"
test_module_names: "compose-runtime-runtimereleaseAndroidTest.xml"
test_module_names: ":compose:runtime:runtime:testReleaseUnitTest"
