{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13026266"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "biometric-1.4.0-alpha02-sources.jar",
          "url": "biometric-1.4.0-alpha02-sources.jar",
          "size": 81572,
          "sha512": "bc691c375d8345afc8986fe11b52c34c7053e18e990e68b6005207c157625febd69f2f00e0ab7e1142643ccae22b3b2fa9b7a0d1f3c4910f207de0e58c57f6e4",
          "sha256": "5a6fba09116365bba3e2871fde950a284d19badefe3c0cd27d2f391a5caf4462",
          "sha1": "f7eefc804452ad4894f2e89b9d06f84c4dadb911",
          "md5": "e8db066500b983d23b3794aeb78fe757"
        },
        {
          "name": "biometric-1.4.0-alpha02-samples-sources.jar",
          "url": "biometric-1.4.0-alpha02-samples-sources.jar",
          "size": 7811,
          "sha512": "8656cc90c824f9e6dde1bf6780ef7a844fcf5e1a11fd3fd743ec6b02ec273a4e4fc70a5368494bc8661f55b6e6a0b461992a5bac33e8d3f78f7b37269d9b97e4",
          "sha256": "09077426c998d0cb71b3b50ae7d565b02e697ae749816726ef55240bb449f8da",
          "sha1": "b8c404d440c17f84670bdc6f1d26c852a917b826",
          "md5": "a3f36d9e7d7d3bad45ec50b4e82ee3a3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.4.0-alpha02.aar",
          "url": "biometric-1.4.0-alpha02.aar",
          "size": 281712,
          "sha512": "1428cc572ff5f826538769ab5b95ce055bb0e8e3b16651e33ce1646808e543a933e014f095d3ebb8d32699831a4b6a21e8cb2672adf0eb74329c32e26e127b40",
          "sha256": "676ae7c50c8477e71aac45d484a14c78c819058168f064a19edd1e21c98b7968",
          "sha1": "c70f8721be1d61aa5fe8557186be583b4302f004",
          "md5": "2de917a2ddfa546295792ad274a5507d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "biometric-1.4.0-alpha02.aar",
          "url": "biometric-1.4.0-alpha02.aar",
          "size": 281712,
          "sha512": "1428cc572ff5f826538769ab5b95ce055bb0e8e3b16651e33ce1646808e543a933e014f095d3ebb8d32699831a4b6a21e8cb2672adf0eb74329c32e26e127b40",
          "sha256": "676ae7c50c8477e71aac45d484a14c78c819058168f064a19edd1e21c98b7968",
          "sha1": "c70f8721be1d61aa5fe8557186be583b4302f004",
          "md5": "2de917a2ddfa546295792ad274a5507d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "biometric-1.4.0-alpha02-versionMetadata.json",
          "url": "biometric-1.4.0-alpha02-versionMetadata.json",
          "size": 15834,
          "sha512": "070b482c0d566eda60c1ab4c87895d12296d34b08483ff1bc3f0e3e42d2d64f6849b0364ba4af902acbe2a8d097ede82b375f74686086937bb44db12b874047f",
          "sha256": "eb10d9077de634dfce5f5b68c3f796fbafae85e1813f1a4a0a4446731c5c9f1a",
          "sha1": "2726374c55a338251fb17fc44a5b40edbbd326ff",
          "md5": "0bcb111afd3c6b3659bfcc9c58b52efa"
        }
      ]
    }
  ]
}