{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.biometric",
    "module": "biometric",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "biometric is in atomic group androidx.biometric"
        }
      ],
      "files": [
        {
          "name": "biometric-1.4.0-alpha02-sources.jar",
          "url": "biometric-1.4.0-alpha02-sources.jar",
          "size": 84610,
          "sha512": "4d3bcdca802c4ba2f4194ef45a2d17eb4381874ae56c536044588cc4724b9387c357b8c6a1e61b6a818187a8532fed6b98e72ae361e6cc261ac45e1956472f97",
          "sha256": "018892c0d16cc0468a7d454538d954255c1f4cc4db73241d62764a1e5b86b876",
          "sha1": "19224e4d9f753f2d19bfd782c7f0477693a4ac32",
          "md5": "35e69cc3455e2f012df27b9beb1b10db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "biometric is in atomic group androidx.biometric"
        }
      ],
      "files": [
        {
          "name": "biometric-1.4.0-alpha02.aar",
          "url": "biometric-1.4.0-alpha02.aar",
          "size": 245357,
          "sha512": "a7dca8937995675e2cb1f8cfcc4c44a60530c3bf32e21e495830aca1f6dcbbf1fe59be6774a9478ee7022ad46e8c9c88e607d65bae2ee7ad044fe36d497c034b",
          "sha256": "afa603152b8fe113407dc7e04d13706aa9532d30bcd5018360fc45035e4259db",
          "sha1": "90ea64aa40f0ece2f86d3bf9a56375e8ce38cf01",
          "md5": "2167db6e72512dc86c95e4ff560a9267"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.5"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "biometric is in atomic group androidx.biometric"
        }
      ],
      "files": [
        {
          "name": "biometric-1.4.0-alpha02.aar",
          "url": "biometric-1.4.0-alpha02.aar",
          "size": 245357,
          "sha512": "a7dca8937995675e2cb1f8cfcc4c44a60530c3bf32e21e495830aca1f6dcbbf1fe59be6774a9478ee7022ad46e8c9c88e607d65bae2ee7ad044fe36d497c034b",
          "sha256": "afa603152b8fe113407dc7e04d13706aa9532d30bcd5018360fc45035e4259db",
          "sha1": "90ea64aa40f0ece2f86d3bf9a56375e8ce38cf01",
          "md5": "2167db6e72512dc86c95e4ff560a9267"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "biometric is in atomic group androidx.biometric"
        }
      ],
      "files": [
        {
          "name": "biometric-1.4.0-alpha02-versionMetadata.json",
          "url": "biometric-1.4.0-alpha02-versionMetadata.json",
          "size": 15055,
          "sha512": "9ecebb126a6fcc59b22d21733077a3981ce838fe343287550ab88f66a8372d99f1be9b242caf043a2fce4f7342d7802fd3c5446dcbd834f4455de8c4a6923384",
          "sha256": "f73599c0a38b8f51334f9470915600f7c3bd945b34449ffd3beffee2f911ea7e",
          "sha1": "dd43a66581f166910834dd607dc5eb7e246129ea",
          "md5": "5fe56489cb9f0135a0fa00102fa05df3"
        }
      ]
    }
  ]
}