version: "1.4.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.appcompat"
    artifact_id: "appcompat"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.3.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment"
    version: "1.2.5"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common-java8"
    version: "2.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-livedata-core"
    version: "2.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel"
    version: "2.2.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.biometric"
group_id: "androidx.biometric"
artifact_id: "biometric"
path: "/biometric/biometric"
sha: "cba68203cb55fa2075a70d105a899b9b83a37a42"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.biometric-biometric-all-12469507-1.4.0-alpha02.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
