version: "3.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.arch.core"
    artifact_id: "core-common"
    version: "2.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-android"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-iosarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-iossimulatorarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-iosx64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-jvm"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-linuxarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-linuxx64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-macosarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-macosx64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-tvosarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-tvossimulatorarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-tvosx64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-watchosarm32"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-watchosarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-watchossimulatorarm64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-watchosx64"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.paging"
group_id: "androidx.paging"
artifact_id: "paging-common"
path: "/paging/paging-common"
sha: "11786a3ed54689e0dc5ee62171e9877f4cbd4292"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.paging-paging-common-all-12257120-3.4.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-common-ktx"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-compose"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-guava"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-runtime"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-runtime-ktx"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-rxjava2"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-rxjava2-ktx"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-rxjava3"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.paging"
    artifact_id: "paging-testing"
    version: "3.4.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
