version: "1.0.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.7.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-driver-android"
    version: "1.0.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-driver-jvm"
    version: "1.0.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "14059446"
group_id: "androidx.tracing"
artifact_id: "tracing-driver"
path: "/tracing/tracing-driver"
sha: "da32c20ed1a2ec422566c4a657945751631361a6"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.tracing-tracing-driver-all-1.0.0-alpha01.zip"
kotlin_version: "2.2.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-driver-wire"
    version: "1.0.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "jvm"
kmp_children: "android"
test_module_names: ":tracing:tracing-driver:jvmTest"
test_module_names: "tracing-tracing-driverandroidInstrumentedTest.xml"
test_module_names: ":tracing:tracing-driver:testAndroidHostTest"
