{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-core",
    "version": "1.4.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta03-sources.jar",
          "url": "camera-core-1.4.0-beta03-sources.jar",
          "size": 696269,
          "sha512": "b0ca5a12331b46ee512bbf1e060ee9a5f0edb9bbaf4890c1ef45b51ec73be62dc142881e3354c8e5517fd9d46e39d3b135da767b38a955842ab1c5daa51f73eb",
          "sha256": "8fd952332631287627e7e5ed6c13eaf03bd018b623efddbfabea04d459df166f",
          "sha1": "f38aac2029d5d85fc3598f973b84163aa260f273",
          "md5": "ab13761fd37167f40c727c4d9c4fb952"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta03.aar",
          "url": "camera-core-1.4.0-beta03.aar",
          "size": 922320,
          "sha512": "440b9c2cae52028ad6c61e7d3c116fd0125e4f63235da7ccf2f4e830e0e4190ca81bff052ba10f3fa2ecd40935fef3692f857f6bdc20ced3212acc345a385aae",
          "sha256": "04eba0c35efa3de59bb834a05625235b323ae587a97e4af2569fb5a09ae16961",
          "sha1": "92b3171358a7e1c5f1ad11d3de9af469f2969c2f",
          "md5": "62f4fa768d02c1c607e0b63ae9db79b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta03.aar",
          "url": "camera-core-1.4.0-beta03.aar",
          "size": 922320,
          "sha512": "440b9c2cae52028ad6c61e7d3c116fd0125e4f63235da7ccf2f4e830e0e4190ca81bff052ba10f3fa2ecd40935fef3692f857f6bdc20ced3212acc345a385aae",
          "sha256": "04eba0c35efa3de59bb834a05625235b323ae587a97e4af2569fb5a09ae16961",
          "sha1": "92b3171358a7e1c5f1ad11d3de9af469f2969c2f",
          "md5": "62f4fa768d02c1c607e0b63ae9db79b0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta03"
          },
          "reason": "camera-core is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-core-1.4.0-beta03-versionMetadata.json",
          "url": "camera-core-1.4.0-beta03-versionMetadata.json",
          "size": 38879,
          "sha512": "1ee9a42f68251b54425c846ef66e29858651abcec898e3a5d52b252cfcd6964ba8e0346c830f4200747bc0994baea4db73df06438f76a780dc802c6f13979322",
          "sha256": "eabfd9d5cf75d4bcb2b550e028faf0acb4a3c0452ab49d9f01a954cb221b0a9d",
          "sha1": "8bb0ed18804fcc608cd0bb639076a7870629990f",
          "md5": "59ca1e0b2c3ae92a9827a9fa41724231"
        }
      ]
    }
  ]
}