{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13882970"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha05-sources.jar",
          "url": "credentials-1.6.0-alpha05-sources.jar",
          "size": 267405,
          "sha512": "490ea6fbf361321c5aa5d02fb63cce37bf7d68cf12de15228e4c1e9d23ed583c68c0ee9caa32d1ea1d169827113e6d71f382945070816a05d8177a5ba4ab9d68",
          "sha256": "d45c4c108eea092e14cf236bf7a1ff495d1f0223daa41a7d62b42af366a9770f",
          "sha1": "e1d3cb5d412102c2b9d2f6b457f8f22d4fc6d393",
          "md5": "3e8cd685b874d94199e7f61f3def9ec3"
        },
        {
          "name": "credentials-1.6.0-alpha05-samples-sources.jar",
          "url": "credentials-1.6.0-alpha05-samples-sources.jar",
          "size": 7239,
          "sha512": "1ee633d1013b2183cef418dffdb9500b3a44d99e3c99793423a362924671ee4de542342eee40de11f1a2df2b629127d11c52848cedb23b23d0c70a012e95f920",
          "sha256": "96cd83931877cd1a45ca054fb691d132a2bea0e396cdacdf8662c6f48a88b458",
          "sha1": "a0b5f12eb38243c4331f41ab2fede931b1d6e4ad",
          "md5": "5eb1bb8e4567872e48582c79164f4b22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha05.aar",
          "url": "credentials-1.6.0-alpha05.aar",
          "size": 634268,
          "sha512": "628472162768e2238496afddc6dfeae93f7768cce44040c293d0c753b2a57db89c59fbed8b91df7f48b6a8a26e90fea9d1e79a31feb110be9d8f37a8bac25548",
          "sha256": "81da179b0618ea90f46d742c22cacbccc6cf37f2d7638e08d9ccffbc358acd0f",
          "sha1": "ba435d1d822d36d15dab4cbe299cff8e3a7aac0d",
          "md5": "50331ccb5afda0ff325d156606fdc1c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha05.aar",
          "url": "credentials-1.6.0-alpha05.aar",
          "size": 634268,
          "sha512": "628472162768e2238496afddc6dfeae93f7768cce44040c293d0c753b2a57db89c59fbed8b91df7f48b6a8a26e90fea9d1e79a31feb110be9d8f37a8bac25548",
          "sha256": "81da179b0618ea90f46d742c22cacbccc6cf37f2d7638e08d9ccffbc358acd0f",
          "sha1": "ba435d1d822d36d15dab4cbe299cff8e3a7aac0d",
          "md5": "50331ccb5afda0ff325d156606fdc1c2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha05-versionMetadata.json",
          "url": "credentials-1.6.0-alpha05-versionMetadata.json",
          "size": 74778,
          "sha512": "212d6e4de4c57fbfc44fa4821b66bcbe77c6e031526c45f8fae015a88091fbd5a307818ffe41291840a8426a0f86edb94d9c6f008791ae5085ec0f219baef155",
          "sha256": "b2964a8b802969db67718095540292d5fb8c5f209b9dd50337454858037576bc",
          "sha1": "7d3fce8aff3df3589fd09518f375a14cbb9fa27e",
          "md5": "1b7db4ebe00f5057fd25312a1371eeb6"
        }
      ]
    }
  ]
}