{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId:": "6455995"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.0-alpha07"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.0-alpha07.aar",
          "url": "navigation-runtime-2.3.0-alpha07.aar",
          "size": 46917,
          "sha512": "45421159fd77a3346664422fcec29578ad7c8d3e189ce48f44d64ec04b9834feb9b9a3b1b40c9e1a3774cd6dfb8a1007acbe5997bc8ced734c3f848e8d40da66",
          "sha256": "2bdb48d195703ba6998edb22e1855c8c88ceb2884d0b72847f21244f003d1544",
          "sha1": "cbf2581130b6fcd53a8faf7686d2be7415fd3e36",
          "md5": "14a4c4aa065acdeafc0af9da062376f5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.3.0-alpha07"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.3.0-alpha07.aar",
          "url": "navigation-runtime-2.3.0-alpha07.aar",
          "size": 46917,
          "sha512": "45421159fd77a3346664422fcec29578ad7c8d3e189ce48f44d64ec04b9834feb9b9a3b1b40c9e1a3774cd6dfb8a1007acbe5997bc8ced734c3f848e8d40da66",
          "sha256": "2bdb48d195703ba6998edb22e1855c8c88ceb2884d0b72847f21244f003d1544",
          "sha1": "cbf2581130b6fcd53a8faf7686d2be7415fd3e36",
          "md5": "14a4c4aa065acdeafc0af9da062376f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-runtime-2.3.0-alpha07-sources.jar",
          "url": "navigation-runtime-2.3.0-alpha07-sources.jar",
          "size": 34612,
          "sha512": "9c87df9b12b659f8b5cda430a6e45aabb9572836da59400b15d69799af45382dd00afe5e9f6bb138a4ad9996e00b365c1c09fe69327f00cc280dcca8543b52a6",
          "sha256": "9106d63a78f570eeb488d3e903f5dea5bf98ad496d6bed20c6a2099ffad915d5",
          "sha1": "2a115c30b10bae385fc7c60930f8714e719a54ac",
          "md5": "47684a659b3be5513ca79e33b96cf50b"
        }
      ]
    }
  ]
}
