version: "1.8.0-alpha08"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-android"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-jvmstubs"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-linuxx64stubs"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "12944746"
group_id: "androidx.compose.runtime"
artifact_id: "runtime"
path: "/compose/runtime/runtime"
sha: "ddc1fb7522a112c60225c3e4eb1d0f077375fa1c"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.runtime-runtime-all-12944746-1.8.0-alpha08.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-lint"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-livedata"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava2"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava3"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-saveable"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-saveable-lint"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-tracing"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
kmp_children: "jvmStubs"
kmp_children: "linuxx64Stubs"
test_module_names: ":compose:runtime:runtime:jvmStubsTest"
test_module_names: ":compose:runtime:runtime:linuxx64StubsTest"
test_module_names: "compose-runtime-runtimereleaseAndroidTest.xml"
test_module_names: ":compose:runtime:runtime:testReleaseUnitTest"
