{
  "formatVersion": "1.1",
  "component": {
    "url": "../../paging-compose/3.4.0-alpha01/paging-compose-3.4.0-alpha01.module",
    "group": "androidx.paging",
    "module": "paging-compose",
    "version": "3.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13621151"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-compose.aar",
          "url": "paging-compose-android-3.4.0-alpha01.aar",
          "size": 27147,
          "sha512": "155f0ff2836d7c113bfacad4510e7cc3e6da047506ce2d7ef0600c8ef1316e6fc9fa4ce0c056dd321ed7224c5ea3c8acbbe2a061d4130ba6d12c9d001d987e60",
          "sha256": "c52d10b93a85864e8ac2f514bc7edf8f255914e9f9f49a04256c5885cbfddab6",
          "sha1": "68e58a658671dcf1182cfb9a24259585baa3d416",
          "md5": "9b7e7741fe365e6561291bd1b98de4d6"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "paging-compose.aar",
          "url": "paging-compose-android-3.4.0-alpha01.aar",
          "size": 27147,
          "sha512": "155f0ff2836d7c113bfacad4510e7cc3e6da047506ce2d7ef0600c8ef1316e6fc9fa4ce0c056dd321ed7224c5ea3c8acbbe2a061d4130ba6d12c9d001d987e60",
          "sha256": "c52d10b93a85864e8ac2f514bc7edf8f255914e9f9f49a04256c5885cbfddab6",
          "sha1": "68e58a658671dcf1182cfb9a24259585baa3d416",
          "md5": "9b7e7741fe365e6561291bd1b98de4d6"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-guava",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-runtime-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava2-ktx",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-rxjava3",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        },
        {
          "group": "androidx.paging",
          "module": "paging-testing",
          "version": {
            "requires": "3.4.0-alpha01"
          },
          "reason": "paging-compose is in atomic group androidx.paging"
        }
      ],
      "files": [
        {
          "name": "paging-compose-android-3.4.0-alpha01-sources.jar",
          "url": "paging-compose-android-3.4.0-alpha01-sources.jar",
          "size": 11230,
          "sha512": "c5b4155923bd4e989c2c66a59c933422c9d620875def81d0a91d3e4bb34e2386f6bde76e824666349a13b15f83a0e68ba9e7689ccf5bb6d5199ee84dad2a207e",
          "sha256": "a2dc4153d822dd9b78287e1c3b3131af2ebcc25a8bdd046c7995fa3bf7f2698a",
          "sha1": "b521d3e5f2c36ac898dd386c67a1a1cbede75ed5",
          "md5": "e23cb0ce7c9d75163843ef4a44d57374"
        },
        {
          "name": "paging-compose-3.4.0-alpha01-samples-sources.jar",
          "url": "paging-compose-android-3.4.0-alpha01-samples-sources.jar",
          "size": 10343,
          "sha512": "799d05e945f4a99440b41c20bc3e8a0fd5496e81945dea3e3c8aba2ee3055604a5272e5f0159ec5bc36b91615ecca44d91cde83298fd5d249c0816b5cba8c5aa",
          "sha256": "04dae2fcceeb32a48d41d9db3c7895ddd0497b25e55d23cce4c215a2cfe68a83",
          "sha1": "9f605971897e5a35501e60536a3f483611b1b7fa",
          "md5": "d752e0088ff6688804d7a77f45d305aa"
        }
      ]
    }
  ]
}