version: "1.8.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.8.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing-manifest"
    version: "1.8.0-rc01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.fragment"
group_id: "androidx.fragment"
artifact_id: "fragment-testing"
path: "/fragment/fragment-testing"
sha: "3c401bfe18d105265b9545f8df0b77a56bf64912"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.fragment-fragment-testing-all-11899877-1.8.0-rc01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment"
    version: "1.8.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-compose"
    version: "1.8.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.8.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing-manifest"
    version: "1.8.0-rc01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
