{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-proto",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13842168"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.4.0-alpha01.jar",
          "url": "protolayout-proto-1.4.0-alpha01.jar",
          "size": 1252240,
          "sha512": "32c3394265c442a29140de4f74ecdfc9aed14b7442c424af85038614399a6168e0a5e34fa5cbb4c22ee5d0c55de87bf39ab1be89bfaa3259cca921fc7b5c3a38",
          "sha256": "2cf065ea132a030a74dc9f5ff57cf1e38bdf812926f5663a4696fc7542d1c530",
          "sha1": "7ad26c07a62292eb41fd08a61337f3531b89d580",
          "md5": "3e71778177e64325dc38adf4c9fecdff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.4.0-alpha01.jar",
          "url": "protolayout-proto-1.4.0-alpha01.jar",
          "size": 1252240,
          "sha512": "32c3394265c442a29140de4f74ecdfc9aed14b7442c424af85038614399a6168e0a5e34fa5cbb4c22ee5d0c55de87bf39ab1be89bfaa3259cca921fc7b5c3a38",
          "sha256": "2cf065ea132a030a74dc9f5ff57cf1e38bdf812926f5663a4696fc7542d1c530",
          "sha1": "7ad26c07a62292eb41fd08a61337f3531b89d580",
          "md5": "3e71778177e64325dc38adf4c9fecdff"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.4.0-alpha01-sources.jar",
          "url": "protolayout-proto-1.4.0-alpha01-sources.jar",
          "size": 315355,
          "sha512": "92f3b9373068f4f3da9b71a53aba56b799728a77d5fcf428baba71cf2704c678515335bd24e98a442bbc74c81987772a062bf96448fa179c2495d384a356649b",
          "sha256": "9b6654005ad5a26b206363c0700143ebae52d50083448597c5c3e9d349914313",
          "sha1": "1e7d35de774fbdd8d2a069d24ab544b9586262d8",
          "md5": "b8ef769afb4152c88a19a07603b6c0e6"
        }
      ]
    }
  ]
}