{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.4.0-alpha03.aar",
          "url": "material-1.4.0-alpha03.aar",
          "size": 2724553,
          "sha512": "3b881400b980b1333853f1bc5e8d1b9014190bae40c9125f9562adfaa9b22c52367dbe14f6404b45585a95bc9d68d5281ff7c356f3f4fde45d2fa01900787b04",
          "sha256": "93904ba97b5453401b45cdc0d7a6d40c2c232f97ca40893cfa57c54e982be355",
          "sha1": "13684337595caa36575fc035188421d3e12bd64c",
          "md5": "73f4182e4b552463ce3beaef0dde2532"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.4.0-alpha03.aar",
          "url": "material-1.4.0-alpha03.aar",
          "size": 2724553,
          "sha512": "3b881400b980b1333853f1bc5e8d1b9014190bae40c9125f9562adfaa9b22c52367dbe14f6404b45585a95bc9d68d5281ff7c356f3f4fde45d2fa01900787b04",
          "sha256": "93904ba97b5453401b45cdc0d7a6d40c2c232f97ca40893cfa57c54e982be355",
          "sha1": "13684337595caa36575fc035188421d3e12bd64c",
          "md5": "73f4182e4b552463ce3beaef0dde2532"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.4.0-alpha03-sources.jar",
          "url": "material-1.4.0-alpha03-sources.jar",
          "size": 215597,
          "sha512": "79dfc4b3c20c07376feb6c6ae7c47b6f50d0ed1b2237120f8bbdb37dfb808a1e734939b3a4474e7e59a1eb3f4bae6de7f1b7ad7d81b392b8acf3351fe4d89654",
          "sha256": "74fbb9a57e0df1ff67bb6e4d974e7a4890f486431279be4b064bacc31995aba6",
          "sha1": "ec52e352505a21af40499efe0e2f32b3ffe2bf84",
          "md5": "c39be965d1a6ee924af92a1b7de6a42b"
        }
      ]
    }
  ]
}