{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.4.0-alpha03.aar",
          "url": "material-1.4.0-alpha03.aar",
          "size": 2725718,
          "sha512": "a280d7742e93fee69f5053c68d68ce9331f1266a0b835a34da5793faba365558758d98709317be4fec8111b1223888cef09c6f83f5037719f62d2fb3facae137",
          "sha256": "6af576c61774b72207591d0243b3e2239e7f8a2f332c86744a13cf6af97d3137",
          "sha1": "ed61e741742be7d66358dcde2c14b83094229af7",
          "md5": "0c496054a72efe3687bb58f1346c8e63"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-1.4.0-alpha03.aar",
          "url": "material-1.4.0-alpha03.aar",
          "size": 2725718,
          "sha512": "a280d7742e93fee69f5053c68d68ce9331f1266a0b835a34da5793faba365558758d98709317be4fec8111b1223888cef09c6f83f5037719f62d2fb3facae137",
          "sha256": "6af576c61774b72207591d0243b3e2239e7f8a2f332c86744a13cf6af97d3137",
          "sha1": "ed61e741742be7d66358dcde2c14b83094229af7",
          "md5": "0c496054a72efe3687bb58f1346c8e63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-1.4.0-alpha03-sources.jar",
          "url": "material-1.4.0-alpha03-sources.jar",
          "size": 215564,
          "sha512": "79636028e4de15d756b908a0059cc9d37ac62337d492e46e74905d57eb8f31ae6643e47ea84be049b883448abbfbb1f3ce04a02423e2bb6ca16e91633379f6ba",
          "sha256": "a7b92cfad9ac5db2aded302544e6a6f29cbfb9cf583497af2e378ca238232f5b",
          "sha1": "1d1f97a0ddb80c399737a714374e713b18bc366f",
          "md5": "2d08a3ec0f78804191d28d6d02dd91f4"
        }
      ]
    }
  ]
}