{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2",
    "version": "1.4.0-beta05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.4.0-beta05.aar",
          "url": "emoji2-1.4.0-beta05.aar",
          "size": 143549,
          "sha512": "1a7dd38a46719074d5eb065d0076480e3da7d508f25a44cd00731fd072fb455a9fa4a5258aad07782f2f8ab1fbc5532382cbddea5ecaed66d83fe912db2abec2",
          "sha256": "18049792386bc10a3a31440f4481ee7e1ef32c7e71c0f6908d1ec73bc0ab3c6a",
          "sha1": "5816cf18f3a1fd0705a858a2178e84c8eb6591e4",
          "md5": "926b7172c535e31b5f839b501a16c1a1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-process",
          "version": {
            "requires": "2.4.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.4.0-beta05.aar",
          "url": "emoji2-1.4.0-beta05.aar",
          "size": 143549,
          "sha512": "1a7dd38a46719074d5eb065d0076480e3da7d508f25a44cd00731fd072fb455a9fa4a5258aad07782f2f8ab1fbc5532382cbddea5ecaed66d83fe912db2abec2",
          "sha256": "18049792386bc10a3a31440f4481ee7e1ef32c7e71c0f6908d1ec73bc0ab3c6a",
          "sha1": "5816cf18f3a1fd0705a858a2178e84c8eb6591e4",
          "md5": "926b7172c535e31b5f839b501a16c1a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta05"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.4.0-beta05"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-1.4.0-beta05-sources.jar",
          "url": "emoji2-1.4.0-beta05-sources.jar",
          "size": 57705,
          "sha512": "15a2fc30e23bd7a09b895b1e65cc0ba4fe4589ef41d352295de3f7a1cbfb770f8311899455d66e1e6bdc3cb747736600f36af45ac143544580b5b3a8943b3044",
          "sha256": "5db44eec9cee653ba403f0e88a02ce41ab6301a0b7dd7cb35fc32f9747f2228b",
          "sha1": "1be0982666eec9d16226fa2c9de9a20dbcbce70e",
          "md5": "0f7ed6908713156685b8a6738bb6be94"
        }
      ]
    }
  ]
}