{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6487324"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-alpha01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0-alpha01.aar",
          "url": "room-runtime-2.3.0-alpha01.aar",
          "size": 97868,
          "sha512": "d9d827cd994209450438dcc6a1ecdb206ad396dd7b204a57e349f3953d21b2adf5ef60b85b64bde72ddb44ad650d3c26aaf0b757e2f3786ce2f86d257ffd59da",
          "sha256": "09b2b2ee7f0447d39d6eed68e98eff1012d61db0b83e586d3abecc5c80974539",
          "sha1": "5f2caf7959eaf363e89f121c79436c4a034b6dac",
          "md5": "2d3fa4c3ec9c051211f4ff8c49d8a24d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-alpha01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0-rc01"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0-rc01"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0-alpha01.aar",
          "url": "room-runtime-2.3.0-alpha01.aar",
          "size": 97868,
          "sha512": "d9d827cd994209450438dcc6a1ecdb206ad396dd7b204a57e349f3953d21b2adf5ef60b85b64bde72ddb44ad650d3c26aaf0b757e2f3786ce2f86d257ffd59da",
          "sha256": "09b2b2ee7f0447d39d6eed68e98eff1012d61db0b83e586d3abecc5c80974539",
          "sha1": "5f2caf7959eaf363e89f121c79436c4a034b6dac",
          "md5": "2d3fa4c3ec9c051211f4ff8c49d8a24d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.3.0-alpha01-sources.jar",
          "url": "room-runtime-2.3.0-alpha01-sources.jar",
          "size": 68487,
          "sha512": "a295866ff709b6aae1c6235bf2cde4756d12382adbdd93e6750b45542b6573467e662111e8e2410a0ac0c65159c22b26bd16ef8137bbf1040d2145556949fd34",
          "sha256": "9f301c0bd06b95fbfb8c9acd71f6069045c32b802652e7763765488e67904bb7",
          "sha1": "cc7cb825ae1b0beb559224f0c78511d605053391",
          "md5": "25b55d764dcebe390edc0e18964389ed"
        }
      ]
    }
  ]
}
