version: "1.6.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "13808536"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "0f68348566b1ec6d869afcc8b151cddf0b7409be"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-13808536-1.6.0-alpha01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "annotation-annotation-experimentalreleaseAndroidTest.xml"
test_module_names: ":annotation:annotation-experimental:testReleaseUnitTest"
