{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.5.0-beta01/collection-1.5.0-beta01.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2",
      "buildId:": "12662063"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-beta01.jar",
          "url": "collection-jvm-1.5.0-beta01.jar",
          "size": 878079,
          "sha512": "95eaef9f43532f801ea0596d51d4a8b24f9c8653f8e0354fea358f429c93dabdaa415f73bd67bd5aa564c2fffc167c97d251d36031b5f6a9f7d75c2124c60be2",
          "sha256": "f0f33f2f4861092f543f0a72c68de0e712fd801d30e24f90805ed413ad29a69a",
          "sha1": "281c95b7970a06be25195f3b65fc20c86acf2260",
          "md5": "a82787cf13c78238cae7b1b5734bfa04"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-beta01.jar",
          "url": "collection-jvm-1.5.0-beta01.jar",
          "size": 878079,
          "sha512": "95eaef9f43532f801ea0596d51d4a8b24f9c8653f8e0354fea358f429c93dabdaa415f73bd67bd5aa564c2fffc167c97d251d36031b5f6a9f7d75c2124c60be2",
          "sha256": "f0f33f2f4861092f543f0a72c68de0e712fd801d30e24f90805ed413ad29a69a",
          "sha1": "281c95b7970a06be25195f3b65fc20c86acf2260",
          "md5": "a82787cf13c78238cae7b1b5734bfa04"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "collection is in atomic group androidx.collection"
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.5.0-beta01-sources.jar",
          "url": "collection-jvm-1.5.0-beta01-sources.jar",
          "size": 288353,
          "sha512": "a806d7c2f2bba7581b63c0413825b8e8b0d77802843b053fd861aa15192e178a3066e211e5416a859737630962deced648ea86a16efece17b299855915a1b5d5",
          "sha256": "9ae07d51a251f40a873d5e03d19d07e066d31d9c0d5bf53fb0337fae938be77d",
          "sha1": "dde7b3733220b96ea25b6480bd40522f20645e2e",
          "md5": "54ba37ddebce3b2612b279a544d4d7f0"
        }
      ]
    }
  ]
}