{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-testing",
    "version": "2.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6947385"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "work-testing-2.5.0-beta01.aar",
          "url": "work-testing-2.5.0-beta01.aar",
          "size": 21083,
          "sha512": "a9ecc68a94de84691e87baec422ca3c3a09064433920fbb213c17f0bd5de9b3eb2da2183f123d6843444ec0108244dfb7714d75ca80c385a513c2740b1ae77f5",
          "sha256": "9cca71fd059714f7fac02afa4f408f375d4de63f1f35d14622eb08ec59660888",
          "sha1": "1355aad00850a47cb005377353014d85c41eda2a",
          "md5": "11c51df3f167feee2cb7070649131a9e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.5.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "work-testing-2.5.0-beta01.aar",
          "url": "work-testing-2.5.0-beta01.aar",
          "size": 21083,
          "sha512": "a9ecc68a94de84691e87baec422ca3c3a09064433920fbb213c17f0bd5de9b3eb2da2183f123d6843444ec0108244dfb7714d75ca80c385a513c2740b1ae77f5",
          "sha256": "9cca71fd059714f7fac02afa4f408f375d4de63f1f35d14622eb08ec59660888",
          "sha1": "1355aad00850a47cb005377353014d85c41eda2a",
          "md5": "11c51df3f167feee2cb7070649131a9e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-testing-2.5.0-beta01-sources.jar",
          "url": "work-testing-2.5.0-beta01-sources.jar",
          "size": 17718,
          "sha512": "c491910a699c4540292e58009c52ea59a22d01fef452d75fd16a6d98e030a1bc7e7085ed12f8d57086c18b0e6c51a31c2e4bf9e4960543f96882909fa13ae96f",
          "sha256": "4473b54b09dea7ebc5946307fa8ef97c39092a6d0282d03209dfb38856ee70f1",
          "sha1": "e36bd27fc486e150bc67b53c24f870bac9877254",
          "md5": "1677aa33fb1dd3102332c0f6a987438b"
        }
      ]
    }
  ]
}
