{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13076784"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.9.0-alpha01-sources.jar",
          "url": "fragment-testing-1.9.0-alpha01-sources.jar",
          "size": 8845,
          "sha512": "7795c82a3de41b65f5ab16c08f258d3cddcb91aafa64063f4e6ec44a1ee32247306e4fef45da1c5718074d4521716a2d35762a02639ccef1c63e4eb0d76fe218",
          "sha256": "a681e94f889e424c00aae9100638340544cfd4dfc781ebf8db274653b4f0449b",
          "sha1": "63b1ab6984170347b8350e7bfab6855aff084605",
          "md5": "4f85b42e99a44626f7dd915abe17efcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.9.0-alpha01.aar",
          "url": "fragment-testing-1.9.0-alpha01.aar",
          "size": 31868,
          "sha512": "b185f85755f309a0a86a8309bd3c5a46865e12338b6a17e5f66e343cdd75a21fc442bf18332829133ae0a0891c4cd009eef6bc07c12ecc8042f8205addaaa6ac",
          "sha256": "647399c5bba5c5148cb2813701648eea053799570754fdeade66ba90ada463ff",
          "sha1": "54be2bcb857b97c450f96ce949ab538f1d58a71b",
          "md5": "2c83388750fdca055ca994b3b5345a48"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.test",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.9.0-alpha01.aar",
          "url": "fragment-testing-1.9.0-alpha01.aar",
          "size": 31868,
          "sha512": "b185f85755f309a0a86a8309bd3c5a46865e12338b6a17e5f66e343cdd75a21fc442bf18332829133ae0a0891c4cd009eef6bc07c12ecc8042f8205addaaa6ac",
          "sha256": "647399c5bba5c5148cb2813701648eea053799570754fdeade66ba90ada463ff",
          "sha1": "54be2bcb857b97c450f96ce949ab538f1d58a71b",
          "md5": "2c83388750fdca055ca994b3b5345a48"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing-manifest",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "fragment-testing is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-1.9.0-alpha01-versionMetadata.json",
          "url": "fragment-testing-1.9.0-alpha01-versionMetadata.json",
          "size": 6725,
          "sha512": "1c4db7961cdfb63ddbbd5f5e5b4e2cadab17a3004915e69689b5f9619fb04d2eaba61a12de38cbbea5de3283488e880d68ceb4731c5179d348fcd4d7fc995ae4",
          "sha256": "a8658ccbae6bd8d5ff466314d4cc21afa71d76e60a8fc7a4b7bc36e0b47e27ef",
          "sha1": "7b89bda49569db3b56212476f6335a9d1790a6d3",
          "md5": "6793c5bc60b1ef9643e9f6b2aaa6906f"
        }
      ]
    }
  ]
}