{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.8.0-beta06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta06-sources.jar",
          "url": "navigation-ui-ktx-2.8.0-beta06-sources.jar",
          "size": 4438,
          "sha512": "02efbaf8421c39158b7691d284b0496266ea751100bcb5d1d4d54480b4b4b9371ab806b5b1d269e1d4b1dfaf51aae104139e0540ba8b1a675531204037bc11f9",
          "sha256": "e63a83fb372493336615b76ee8755731a05e312f187f527a6a358f638377b25c",
          "sha1": "7a9a22bc053aaa0170c4952b0403a0b9b8f81e4d",
          "md5": "0977156890f566d39694a7cd2b627d07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta06.aar",
          "url": "navigation-ui-ktx-2.8.0-beta06.aar",
          "size": 5611,
          "sha512": "26747fc9e78427d3be98cf34be19c24b1c3eaa8edd109fdf247b537f3c1ae37b49a31376e6d35ce296386bd09b31d94cd8c55679d37b78b7bed1b3e196500b9c",
          "sha256": "6dc5bd058a15d8992e96b10f4c6c34741c25101627974b4b2c15d3731bed3504",
          "sha1": "9f29dab1b02ef543f9b9c2d8ab064c93e2bbe920",
          "md5": "e60055a377af51cd4dc2cdf56af367d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta06.aar",
          "url": "navigation-ui-ktx-2.8.0-beta06.aar",
          "size": 5611,
          "sha512": "26747fc9e78427d3be98cf34be19c24b1c3eaa8edd109fdf247b537f3c1ae37b49a31376e6d35ce296386bd09b31d94cd8c55679d37b78b7bed1b3e196500b9c",
          "sha256": "6dc5bd058a15d8992e96b10f4c6c34741c25101627974b4b2c15d3731bed3504",
          "sha1": "9f29dab1b02ef543f9b9c2d8ab064c93e2bbe920",
          "md5": "e60055a377af51cd4dc2cdf56af367d9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta06-versionMetadata.json",
          "url": "navigation-ui-ktx-2.8.0-beta06-versionMetadata.json",
          "size": 6082,
          "sha512": "fb0750efd222f3f11e47b60aad4ddd51f9a17365c98a1d5b7b82e6ddbc9d9c5435d87f27af46c2f1525de64dfd08752ee31283393a5a5a5c416b714270228abb",
          "sha256": "be5b0e997e90e2d3d35778ae22da0ae2652be0e401c16bec50c6401dbc690fe7",
          "sha1": "cd7941a9f68e29512f8c113226f398a7ccd3cc4b",
          "md5": "599b2555933a2ccf868aaddeee44b632"
        }
      ]
    }
  ]
}