{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-apigenerator",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12861657"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha10.jar",
          "url": "tools-apigenerator-1.0.0-alpha10.jar",
          "size": 1083587,
          "sha512": "db1482f6b6a64187b20a96c423cdd43dec58e3f22c72ccc0788157a7815b80f23f4c8008f70468ee25a4512cbaf92bd9ec5b644e7cd2890bb8bda287738bd3e3",
          "sha256": "72a5973e93e7ce2201ccf551d1647800478fb9e1a241e38e4bfd8fc4094e2f38",
          "sha1": "ce0ef7a44146ed8d947f911f82ebff167327150e",
          "md5": "e47f46d5bcc5d900ffaaf8e2d13c4dc6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha10.jar",
          "url": "tools-apigenerator-1.0.0-alpha10.jar",
          "size": 1083587,
          "sha512": "db1482f6b6a64187b20a96c423cdd43dec58e3f22c72ccc0788157a7815b80f23f4c8008f70468ee25a4512cbaf92bd9ec5b644e7cd2890bb8bda287738bd3e3",
          "sha256": "72a5973e93e7ce2201ccf551d1647800478fb9e1a241e38e4bfd8fc4094e2f38",
          "sha1": "ce0ef7a44146ed8d947f911f82ebff167327150e",
          "md5": "e47f46d5bcc5d900ffaaf8e2d13c4dc6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha10.jar",
          "url": "tools-apigenerator-1.0.0-alpha10.jar",
          "size": 1083587,
          "sha512": "db1482f6b6a64187b20a96c423cdd43dec58e3f22c72ccc0788157a7815b80f23f4c8008f70468ee25a4512cbaf92bd9ec5b644e7cd2890bb8bda287738bd3e3",
          "sha256": "72a5973e93e7ce2201ccf551d1647800478fb9e1a241e38e4bfd8fc4094e2f38",
          "sha1": "ce0ef7a44146ed8d947f911f82ebff167327150e",
          "md5": "e47f46d5bcc5d900ffaaf8e2d13c4dc6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apigenerator is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apigenerator-1.0.0-alpha10-sources.jar",
          "url": "tools-apigenerator-1.0.0-alpha10-sources.jar",
          "size": 14517,
          "sha512": "bf712c2d216ebab5910c56510c579facc8c3f9ee63bda28e4e2debaf1082809f032a23e4edd17a47f21f6bdac64e000442e228a5871759d144418ac1fac76561",
          "sha256": "4a39923193fcee58827d3934c8b9f967ac026f86ffdb7d9b841238e2614d2ba9",
          "sha1": "25a57513b15aaeffb6c11b156d8dfad12fafc052",
          "md5": "b2c7a445695aba56553fff0fc928fb59"
        }
      ]
    }
  ]
}