{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-ktx",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.3.0-alpha02.aar",
          "url": "tracing-ktx-1.3.0-alpha02.aar",
          "size": 5921,
          "sha512": "39d4933ed1ddcff2aff7f4ce38a4c80c95bede832503c696f6cccd55c15774a559d6c46541a439ff259868a76cf18620f43953c972c72b58495ce984d56f3ff6",
          "sha256": "752b06401802a1598b551b466bb3e9b011c80f7ce0c4e8450f5f7bc587818071",
          "sha1": "ad70683875fc7b35b4f83b972ec6e192dad3c1bf",
          "md5": "b2808b6016fb9f91f4d38a9d11067a83"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.3.0-alpha02.aar",
          "url": "tracing-ktx-1.3.0-alpha02.aar",
          "size": 5921,
          "sha512": "39d4933ed1ddcff2aff7f4ce38a4c80c95bede832503c696f6cccd55c15774a559d6c46541a439ff259868a76cf18620f43953c972c72b58495ce984d56f3ff6",
          "sha256": "752b06401802a1598b551b466bb3e9b011c80f7ce0c4e8450f5f7bc587818071",
          "sha1": "ad70683875fc7b35b4f83b972ec6e192dad3c1bf",
          "md5": "b2808b6016fb9f91f4d38a9d11067a83"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-ktx-1.3.0-alpha02-sources.jar",
          "url": "tracing-ktx-1.3.0-alpha02-sources.jar",
          "size": 1656,
          "sha512": "b24e54a7e3aa29abb281c89aa34fa9fe492063958b6c92778f8719415a88223e3075d82c03cc6c2a5c91e3e3d14b0d845c97eaf69a04b17b8b5c5e8ed57347e9",
          "sha256": "610a5837e1efa2ad4dc940f1b308bd020d2d6d2b02fcebdf27b0b7b23f5e0a5a",
          "sha1": "1c3ce12844007242d296d73e1188d076784b5183",
          "md5": "40b9479530f86f54fa37bd49d94d2b28"
        }
      ]
    }
  ]
}