version: "1.15.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.15.0-rc01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.core"
group_id: "androidx.core"
artifact_id: "core-ktx"
path: "/core/core-ktx"
sha: "cba68203cb55fa2075a70d105a899b9b83a37a42"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-ktx-all-12469507-1.15.0-rc01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.15.0-rc01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
