{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji",
    "module": "emoji",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7",
      "buildId:": "6947385"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-1.2.0-alpha03.aar",
          "url": "emoji-1.2.0-alpha03.aar",
          "size": 144791,
          "sha512": "980c15b18c9a6533ff7cc381b11815239eeebff284bcdc98b8414a3bb91c4439abed9d05b0577c6a44662ccf43e3835dc5e05b42130a1677d6ee66943f5430e8",
          "sha256": "5ecfd0577b91ccca9a46f5667a9c41bcc9cbd247c6880b1a175df4c6ef25ba17",
          "sha1": "3ad4fa82b8f6a9b442dc8c80aac65d072b773f5e",
          "md5": "e7c7197b87d1e3e2fb6b4ae3a30f6ff5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji-1.2.0-alpha03.aar",
          "url": "emoji-1.2.0-alpha03.aar",
          "size": 144791,
          "sha512": "980c15b18c9a6533ff7cc381b11815239eeebff284bcdc98b8414a3bb91c4439abed9d05b0577c6a44662ccf43e3835dc5e05b42130a1677d6ee66943f5430e8",
          "sha256": "5ecfd0577b91ccca9a46f5667a9c41bcc9cbd247c6880b1a175df4c6ef25ba17",
          "sha1": "3ad4fa82b8f6a9b442dc8c80aac65d072b773f5e",
          "md5": "e7c7197b87d1e3e2fb6b4ae3a30f6ff5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji-1.2.0-alpha03-sources.jar",
          "url": "emoji-1.2.0-alpha03-sources.jar",
          "size": 59664,
          "sha512": "afc83b9846da3bbdbcbbefd8eb769cfbb57461048808e9120b087b4a50cd64710d6fab2fdc44e45c7a233cd849a28038c57eb221e47bbfb6a900cd386b3bebb7",
          "sha256": "cbce464d96f00d70fba3d328e0d8037fd637bd8b8e37913a46e1952dcbc6f2a8",
          "sha1": "f0f4574b5671ecf1a0962cecea83787269b75c14",
          "md5": "947eb38381026a36ea99db1a9f992d9a"
        }
      ]
    }
  ]
}
