{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-provider",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha06.aar",
          "url": "ui-provider-1.0.0-alpha06.aar",
          "size": 18191,
          "sha512": "91cb927f500af379292772d7d13fcbff2da6a1e2197557626a5804015c2f2544e23e66b3cca5aed6628a698741a7dfd9a2dc161360d0eb123183dfb31803872d",
          "sha256": "a310ff1816049cd8eae82dc4b141557ccfe898f627dd28fac5e7b9aa6e7c389e",
          "sha1": "39c69cfd9385e8ea444a2b77714787fafd954fd3",
          "md5": "0b6f56eb02473c9b520141d34d17e8c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0-alpha05"
          }
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha06.aar",
          "url": "ui-provider-1.0.0-alpha06.aar",
          "size": 18191,
          "sha512": "91cb927f500af379292772d7d13fcbff2da6a1e2197557626a5804015c2f2544e23e66b3cca5aed6628a698741a7dfd9a2dc161360d0eb123183dfb31803872d",
          "sha256": "a310ff1816049cd8eae82dc4b141557ccfe898f627dd28fac5e7b9aa6e7c389e",
          "sha1": "39c69cfd9385e8ea444a2b77714787fafd954fd3",
          "md5": "0b6f56eb02473c9b520141d34d17e8c5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha06-sources.jar",
          "url": "ui-provider-1.0.0-alpha06-sources.jar",
          "size": 6278,
          "sha512": "d961c17a2d95b9d46c06534604b791656fb6c6e8c7817c6e075472949e5acc8fa50789d3a9855e82ce52cb816fec4cc1aaccaee3d276b1d5b8057c315be2aea7",
          "sha256": "3b032254b9ce91f5f72310f6435a3463f481f3251cdd9ccce72a1f5127d353ec",
          "sha1": "0ebb0059e281aeaa7633081dfe9ee1d5d7343ec6",
          "md5": "c748685ebdfdf4e03e03ecea881cd449"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha06"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha06-versionMetadata.json",
          "url": "ui-provider-1.0.0-alpha06-versionMetadata.json",
          "size": 498,
          "sha512": "0a9a816b96adbe6315a3ac408da4e2b3521357b71a2e1242b6265361234e5c9f941d0b8ff40b51c47a284c3d5f2957d041d465022b02f17edc065e43895cf61b",
          "sha256": "a7f7ec0ec742eda40839aabf96a199252d9d382fba44365ed1dfc6d20719c2bf",
          "sha1": "3e36cc56fbd4a680b28f59d22b704f5884b343cf",
          "md5": "861b76b1d4435eba1fe5a07cdd712e30"
        }
      ]
    }
  ]
}