version: "1.10.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.13.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-savedstate"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.profileinstaller"
    artifact_id: "profileinstaller"
    version: "1.4.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.2.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing"
    version: "1.0.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.activity"
group_id: "androidx.activity"
artifact_id: "activity"
path: "/activity/activity"
sha: "97dfc656433b630c22143768b4a4176f2e6ee205"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.activity-activity-all-12508510-1.10.0-alpha03.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity-compose"
    version: "1.10.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity-ktx"
    version: "1.10.0-alpha03"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
