version: "1.6.0-alpha08"
dependency_list {
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-core-android"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-core-desktop"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.material"
group_id: "androidx.compose.material"
artifact_id: "material-icons-core"
path: "/compose/material/material-icons-core"
sha: "088e251311b7eb503587d1129b796bfe3d2e6c6f"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-material-11015841.zip"
project_zip_path: "per-project-zips/androidx.compose.material-material-icons-core-all-11015841-1.6.0-alpha08.zip"
kotlin_version: "1.9.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-icons-extended"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material"
    artifact_id: "material-ripple"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
}
