{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.8.0-alpha01/runtime-saveable-1.8.0-alpha01.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.8.0-alpha01.aar",
          "size": 1124291,
          "sha512": "b0c7cd93a16eed5f74e56dfcd47212c05118ef354c7ee6b14291b69cfc10596ab06c7715e84b826a9bdde61ce62ebb8d63f2ebbf8516a021692db2544961a6b3",
          "sha256": "a69e675d568eb22d7b8de2cc4e2e3250200356a1417ef45b282349148fda9e1e",
          "sha1": "b0e5a86d55624cafa52e0e34f9571ee793a4c6ec",
          "md5": "f588ce875ad99fd83a31a62afa8ddf42"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.8.0-alpha01.aar",
          "size": 1124291,
          "sha512": "b0c7cd93a16eed5f74e56dfcd47212c05118ef354c7ee6b14291b69cfc10596ab06c7715e84b826a9bdde61ce62ebb8d63f2ebbf8516a021692db2544961a6b3",
          "sha256": "a69e675d568eb22d7b8de2cc4e2e3250200356a1417ef45b282349148fda9e1e",
          "sha1": "b0e5a86d55624cafa52e0e34f9571ee793a4c6ec",
          "md5": "f588ce875ad99fd83a31a62afa8ddf42"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-1.8.0-alpha01-samples-sources.jar",
          "url": "runtime-saveable-android-1.8.0-alpha01-samples-sources.jar",
          "size": 8597,
          "sha512": "509151aab0db321992be131dcaddd9bb3cc61b4060b6d9efad2f12c2e1c07fe96dd8b0e624dc0accdb6e1edf7f7773c1449a507302b9917c4970b753f9b45300",
          "sha256": "1540c1f764bfabc5ce175097db8fcbfc1519d9ceb42a7989ba3147f3e7b286c9",
          "sha1": "bad09107d9683f4d66fa2d27773cf5240a5c906a",
          "md5": "e92332855418830ce92356fe406e72fd"
        },
        {
          "name": "runtime-saveable-android-1.8.0-alpha01-sources.jar",
          "url": "runtime-saveable-android-1.8.0-alpha01-sources.jar",
          "size": 16244,
          "sha512": "35f6a14a1c5352b23e7714e0ecaa00b106a964f7bd7345df81d6138acba101319d5ef5d60b5e7fd483305c5cfe567960a5d86990ef208d096a0fef138e252ba1",
          "sha256": "6e087382f4afc8c338a4135844e3ab5351d04d1fb1913638c3f2c4609ea5bdf4",
          "sha1": "97a2dea9a53a307a0babc132a1c51507e93b5120",
          "md5": "c1a0750118d0b65631e75b8daa8b7926"
        }
      ]
    }
  ]
}