{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.collection",
    "module": "collection-ktx",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6836159"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha01.jar",
          "url": "collection-ktx-1.2.0-alpha01.jar",
          "size": 18881,
          "sha512": "3200dfbb4716d63ce117e699521cea849501a83621ba5d61d08c3d361c404b4016958c4e3882de85bb68dfbc88b866eed73b158f09ee03a3f2641d48de9f8143",
          "sha256": "a24c75085ac9202603cd1b36ac846ae1ebcbe1dcb06c1077cf6e40b4acf28c7f",
          "sha1": "b6b13d2405d557371976c8dc4da6e708baa2b60d",
          "md5": "15f83cc4afe9f6d631a4af91707d6800"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha01.jar",
          "url": "collection-ktx-1.2.0-alpha01.jar",
          "size": 18881,
          "sha512": "3200dfbb4716d63ce117e699521cea849501a83621ba5d61d08c3d361c404b4016958c4e3882de85bb68dfbc88b866eed73b158f09ee03a3f2641d48de9f8143",
          "sha256": "a24c75085ac9202603cd1b36ac846ae1ebcbe1dcb06c1077cf6e40b4acf28c7f",
          "sha1": "b6b13d2405d557371976c8dc4da6e708baa2b60d",
          "md5": "15f83cc4afe9f6d631a4af91707d6800"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "collection-ktx-1.2.0-alpha01-sources.jar",
          "url": "collection-ktx-1.2.0-alpha01-sources.jar",
          "size": 5947,
          "sha512": "7ebe8f7fb6c8d1b9247d07e3722540ca6535715c98c25af2dfb91e52ff6a3b500f3de5db34112203201d412703e136b9c568dd3c53e32df56e02f2391a0c0712",
          "sha256": "906a9d5a2cdf2f14813f597a573d0a1ccc6b0e42a2ee398208694fcead68dd08",
          "sha1": "7d7f3841485f3dc438d8b1f243c385a86ac34f90",
          "md5": "935054299ef8169fa22bc89312c4ec6b"
        }
      ]
    }
  ]
}
