{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions",
    "module": "extensions",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.2.0-alpha01.aar",
          "url": "extensions-1.2.0-alpha01.aar",
          "size": 38712,
          "sha512": "2b8564067d3780f8faa87c28b337d5fceae84e102e00107b9bbf29da8bf5e9d1067ad163263a0259f28122020b35db1210b18977e882171b9ad9998c12cb90b5",
          "sha256": "094d083e93c1b8808443958a36a9eace13d9de753a57155a17897ac9938c6b98",
          "sha1": "8c8da49b91df09617b8a041c357231e226c968bb",
          "md5": "26d0c47a36da6e437477b11388beceb9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.2.0-alpha01.aar",
          "url": "extensions-1.2.0-alpha01.aar",
          "size": 38712,
          "sha512": "2b8564067d3780f8faa87c28b337d5fceae84e102e00107b9bbf29da8bf5e9d1067ad163263a0259f28122020b35db1210b18977e882171b9ad9998c12cb90b5",
          "sha256": "094d083e93c1b8808443958a36a9eace13d9de753a57155a17897ac9938c6b98",
          "sha1": "8c8da49b91df09617b8a041c357231e226c968bb",
          "md5": "26d0c47a36da6e437477b11388beceb9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-1.2.0-alpha01-sources.jar",
          "url": "extensions-1.2.0-alpha01-sources.jar",
          "size": 41446,
          "sha512": "a8f20419c6313649e1c75aa96a964e3fd4a5a234df04676d943e7976c66cd5613cba001fb92b615d5bd8850dd1aa905a3d023792edd3cad34334f115abe8d804",
          "sha256": "d1677f81c39ed8b532bac52649b98cc9c387d3f9db6271eda39bff6cf291b162",
          "sha1": "6dfc7f2e11ef7cfee5475345910901ae09342ccc",
          "md5": "e2143167e725d137b39b3f8bb13d85e5"
        }
      ]
    }
  ]
}