version: "1.7.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-android"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-desktop"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.foundation"
group_id: "androidx.compose.foundation"
artifact_id: "foundation-layout"
path: "/compose/foundation/foundation-layout"
sha: "46d7879c3ab32ed4b4b9e7a6fad2647be0f40e7a"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-foundation-11235915.zip"
project_zip_path: "per-project-zips/androidx.compose.foundation-foundation-layout-all-11235915-1.7.0-alpha01.zip"
kotlin_version: "1.9.21"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation"
    version: "1.7.0-alpha01"
    is_tip_of_tree: true
  }
}
