{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sqlite-framework/2.6.0-alpha01/sqlite-framework-2.6.0-alpha01.module",
    "group": "androidx.sqlite",
    "module": "sqlite-framework",
    "version": "2.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13842168"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.aar",
          "url": "sqlite-framework-android-2.6.0-alpha01.aar",
          "size": 56935,
          "sha512": "fb7f42bf1276b212a0f8c99b6322a30e3e1ff7633801ee6cfbc9339a1592f46def9d110b273ff427871a870f767e454f0506c3acece5ac2ed857e0bdb0fa82a4",
          "sha256": "000338adf75cdca4edfa6708657f76621b0cffcaa13d7acaf2ddd25da12a06bd",
          "sha1": "d2b6d8065d650826ba58afd579b38b8cfa5b3b32",
          "md5": "c32428eec852f3739ea5e651f918d8e3"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "sqlite-framework.aar",
          "url": "sqlite-framework-android-2.6.0-alpha01.aar",
          "size": 56935,
          "sha512": "fb7f42bf1276b212a0f8c99b6322a30e3e1ff7633801ee6cfbc9339a1592f46def9d110b273ff427871a870f767e454f0506c3acece5ac2ed857e0bdb0fa82a4",
          "sha256": "000338adf75cdca4edfa6708657f76621b0cffcaa13d7acaf2ddd25da12a06bd",
          "sha1": "d2b6d8065d650826ba58afd579b38b8cfa5b3b32",
          "md5": "c32428eec852f3739ea5e651f918d8e3"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-bundled",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          },
          "reason": "sqlite-framework is in atomic group androidx.sqlite"
        }
      ],
      "files": [
        {
          "name": "sqlite-framework-android-2.6.0-alpha01-sources.jar",
          "url": "sqlite-framework-android-2.6.0-alpha01-sources.jar",
          "size": 24703,
          "sha512": "510cfeb256d4cfe5e633f5c4ca3720de7de78f8f97da93e0658902a9ed58e8d57cc5c45dafca1c43273864731d5b4ff7c897d0aa3d89a96a494c5e1b8d5c22cc",
          "sha256": "562204e66afc8cde04b2c06c1b88966a1c620d27a246928f799844b212520650",
          "sha1": "31055d63d819ca761d1d3bdddc6c508b2af91e6d",
          "md5": "3e1a1b41a1d840f5fdf8da0376c6ae85"
        }
      ]
    }
  ]
}