{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.12.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13649143"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha03-sources.jar",
          "url": "activity-compose-1.12.0-alpha03-sources.jar",
          "size": 16150,
          "sha512": "df25f58ae764544c7989a000b10c0fcf88cfc85dc7862788a854b492812858f266b7a95b4475419a207ab4d38437cfc21ca5562871fae8478d8986aba606b042",
          "sha256": "74ad502ba3148e797de9aee37e70677df0b29ef5a69685ea8d92fe34ee335e5e",
          "sha1": "6ce20141c5b63fe40ecf9db6d315258d1e26bbbd",
          "md5": "eb3782a4368b0d68ebdcc197bcd92f72"
        },
        {
          "name": "activity-compose-1.12.0-alpha03-samples-sources.jar",
          "url": "activity-compose-1.12.0-alpha03-samples-sources.jar",
          "size": 7851,
          "sha512": "9a989c99452f247373f0dd6350ad8f0feb2ff47d438df2c24a85340a5cca7ee3385fe7254c0ef621133e5e746e13c4796e2853b884c868cd2b142abd730afd8b",
          "sha256": "95289ac1dcb6073b439d440fe43935ad8e4a513a5511b66a647e678142dd45f0",
          "sha1": "09d83336b437e0d661e0925d0e84383bb9c19f65",
          "md5": "04d92c9bd78b5f89b85bed0e36326e08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha03.aar",
          "url": "activity-compose-1.12.0-alpha03.aar",
          "size": 1057717,
          "sha512": "a3a68458c45be5d1d094f7b16065c785d2601b8bc82534a23122a644ca5422001abedcbad82b3d22941439868edc513ebd278591b291b7165377cf203e52dcab",
          "sha256": "b215db0a0b862d8fdf8035b6f81f52ee7f9f668b6c92617a5103e03792a34186",
          "sha1": "f62dc4cb24976ee16186126b6ec21a62e74c2222",
          "md5": "117365a5ae0467e52f0c75e6470e57b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.navigationevent",
          "module": "navigationevent-compose",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha03.aar",
          "url": "activity-compose-1.12.0-alpha03.aar",
          "size": 1057717,
          "sha512": "a3a68458c45be5d1d094f7b16065c785d2601b8bc82534a23122a644ca5422001abedcbad82b3d22941439868edc513ebd278591b291b7165377cf203e52dcab",
          "sha256": "b215db0a0b862d8fdf8035b6f81f52ee7f9f668b6c92617a5103e03792a34186",
          "sha1": "f62dc4cb24976ee16186126b6ec21a62e74c2222",
          "md5": "117365a5ae0467e52f0c75e6470e57b1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.12.0-alpha03"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.12.0-alpha03-versionMetadata.json",
          "url": "activity-compose-1.12.0-alpha03-versionMetadata.json",
          "size": 4434,
          "sha512": "0c289c8791d95bf0417ce7c77251751ce7a39e52ee36aa90900d4af45796e827d2f867afc08cca65a2201e0f7230aac4c7888f5ac595570d05e383bfd7ee60cb",
          "sha256": "1669592d59dae42482d6530d9ec3f6906c1276d7af934ef6f26f821d4daba80d",
          "sha1": "79d61a81946fb8a24c5a80993d6f7dd8968bfc24",
          "md5": "4a4b5f2593404b25f10643ae26645e35"
        }
      ]
    }
  ]
}