{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3",
    "version": "1.0.0-alpha26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha26-sources.jar",
          "url": "compose-material3-1.0.0-alpha26-sources.jar",
          "size": 284953,
          "sha512": "f3e99cc0e2576ecfe2387ea19adcf24f232aa8f65d16972aa91e3a9982ea9b6a364a7b952ef37b10d5cdb20322e4f87ac4755ee49f808e38a1457793810dd742",
          "sha256": "0ea1024aca1a6f462b0b240708cb94986852db13092c0618792d0c8b9ab471af",
          "sha1": "cc33eeed74c0202b8881eb741675b74b902b25eb",
          "md5": "e0cb2a7493f1508ba2816166a93b3e92"
        },
        {
          "name": "compose-material3-1.0.0-alpha26-samples-sources.jar",
          "url": "compose-material3-1.0.0-alpha26-samples-sources.jar",
          "size": 49892,
          "sha512": "4530f628bb1763d1ab2633aa8600c708d25666edd4d698618ae37187130f01cda1e5f44a6adbd31f3a282bd4d85511eb6274ebccf659766ccfb9fae51cf8f904",
          "sha256": "4529f71f58f57ca2e2c021885553c8ec1242a61b77fc98dcf1ee4bb6279adc37",
          "sha1": "ec0866c0ee558ed03801b9b045f4ad21ddc9f1ae",
          "md5": "33c618020ec9201df8f524c94c48d928"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha26.aar",
          "url": "compose-material3-1.0.0-alpha26.aar",
          "size": 1986869,
          "sha512": "d8e5ae52ea77f627d29fc84a9e2dbeda475c5aa0b21929b62dc4005ce18dfde1599a1ced748b85de1bd70d90b206843d6387393498b4c13f6357ad4bd87d923e",
          "sha256": "760c7b86d8195b7dbca1c653b118de7938d7ca9facb9dab5c0515f0142e7e5cc",
          "sha1": "df46f5d5e98d1196e41af10399aa4ef0ec148e25",
          "md5": "037395e46b4df4679f825555f4367045"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.8.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha26.aar",
          "url": "compose-material3-1.0.0-alpha26.aar",
          "size": 1986869,
          "sha512": "d8e5ae52ea77f627d29fc84a9e2dbeda475c5aa0b21929b62dc4005ce18dfde1599a1ced748b85de1bd70d90b206843d6387393498b4c13f6357ad4bd87d923e",
          "sha256": "760c7b86d8195b7dbca1c653b118de7938d7ca9facb9dab5c0515f0142e7e5cc",
          "sha1": "df46f5d5e98d1196e41af10399aa4ef0ec148e25",
          "md5": "037395e46b4df4679f825555f4367045"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha26-versionMetadata.json",
          "url": "compose-material3-1.0.0-alpha26-versionMetadata.json",
          "size": 99511,
          "sha512": "be70f5dd224d2100d15a431da01298ff11a489cd9001774df276be1fa113f2501939e42591c6068f93b747eeb17965e1e84daa21d7a3e8d697f1a093075e3b14",
          "sha256": "6a30b00ad64ef41d6ca6bf0dd2f38e21cec49beabfa8fdb2b9ab3f5921986166",
          "sha1": "b9ed81d99bb128e9f86242a1c3800d03f55cbc5a",
          "md5": "37a037db6ce905773b50adf7ad69e641"
        }
      ]
    }
  ]
}