{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13042766"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query-play-services",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-alpha05-sources.jar",
          "url": "camera-camera2-1.5.0-alpha05-sources.jar",
          "size": 404895,
          "sha512": "40e5ffd745371d9bbe4ac8ecd0e2a9d978967c50dd84ebc535c4ed5dbf4ae593590901e1ac742bc280737b5368a8b4009cf642199abcf1b7a405f3342779b8d5",
          "sha256": "f1be9749a215208dd9981ca6b9a2fe6c8b216e9868b5f63ccb8866899c3ff036",
          "sha1": "c2c4d7dda67ee5b93fd80dbe37942d0253fa3609",
          "md5": "76140906ee475b0c192ac88ffedd3ac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query-play-services",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-alpha05.aar",
          "url": "camera-camera2-1.5.0-alpha05.aar",
          "size": 561209,
          "sha512": "3249d5aca117ea0acb9434b1b94453ba5a1adfee78f4846ba23571a079586a5a8db2dd09d8c129f7a2d869c0965bf2191395e6c4f75e9177ef269b638bce959b",
          "sha256": "c7997923c87497321e84f10e032332b7e3ff5fbcdb258a7e46a120784b497b42",
          "sha1": "34e286f129d752cf42af05b1be344ddee44b65cb",
          "md5": "e8b9fad6b25ba650c445500781fa7e8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query-play-services",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-alpha05.aar",
          "url": "camera-camera2-1.5.0-alpha05.aar",
          "size": 561209,
          "sha512": "3249d5aca117ea0acb9434b1b94453ba5a1adfee78f4846ba23571a079586a5a8db2dd09d8c129f7a2d869c0965bf2191395e6c4f75e9177ef269b638bce959b",
          "sha256": "c7997923c87497321e84f10e032332b7e3ff5fbcdb258a7e46a120784b497b42",
          "sha1": "34e286f129d752cf42af05b1be344ddee44b65cb",
          "md5": "e8b9fad6b25ba650c445500781fa7e8e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-feature-combination-query-play-services",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.5.0-alpha05-versionMetadata.json",
          "url": "camera-camera2-1.5.0-alpha05-versionMetadata.json",
          "size": 3277,
          "sha512": "a28eec65edfaa21396676bec29ff0d5923ddf6483e79aa9cf04246c27ff9d1aa1e62020b3d61f9fe06aeb6a6cc6df88d12ad6596f0a8001789dfabc83be9d6e6",
          "sha256": "d1d3abe8f34c05ee0062c40f3c5c1378376695ac2c46259a70c6e92fe67bc31c",
          "sha1": "99913f5112cf028dcd7c23d4d81da8e74e8796d4",
          "md5": "a2976ec39310f25829ccfcd8766347b3"
        }
      ]
    }
  ]
}