version: "1.1.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.5.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-core"
path: "/constraintlayout/constraintlayout-core"
sha: "b1b7fbbed2c8b175098c6280ea9270c183efce5d"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-constraintlayout-11204544.zip"
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-core-all-11204544-1.1.0-alpha13.zip"
kotlin_version: "1.9.21"
dependency_constraint_list {
}
