{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.drawerlayout",
    "module": "drawerlayout",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "drawerlayout-1.2.0-alpha01.aar",
          "url": "drawerlayout-1.2.0-alpha01.aar",
          "size": 33581,
          "sha512": "e72f3f376a3f310010730f33fa7fb5172c93187fa3ebcc3a5bcd3cd24f8a6438f755fd5a3501cab8537ea29b484fcf3b6603f9571828b040350e4edbc77a1257",
          "sha256": "eb92d6c901ebbf3657569ebba40f9a8d0403333bf0b041315265e7024e048a93",
          "sha1": "192b5914c814eba8882215f53d54389196abcae3",
          "md5": "86695715ff47f44ca09d29f43954c353"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "drawerlayout-1.2.0-alpha01.aar",
          "url": "drawerlayout-1.2.0-alpha01.aar",
          "size": 33581,
          "sha512": "e72f3f376a3f310010730f33fa7fb5172c93187fa3ebcc3a5bcd3cd24f8a6438f755fd5a3501cab8537ea29b484fcf3b6603f9571828b040350e4edbc77a1257",
          "sha256": "eb92d6c901ebbf3657569ebba40f9a8d0403333bf0b041315265e7024e048a93",
          "sha1": "192b5914c814eba8882215f53d54389196abcae3",
          "md5": "86695715ff47f44ca09d29f43954c353"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "drawerlayout-1.2.0-alpha01-sources.jar",
          "url": "drawerlayout-1.2.0-alpha01-sources.jar",
          "size": 20654,
          "sha512": "3256770f3f6c7c5f9ece3023f99d8e293efbcaf55d0ac942a2118a112a844240edc613c8f2e519d17b4e9a77b5ee1bde313876ee1e020376ba04b0afb676255c",
          "sha256": "419caa3619eead9a02109a67a691e136c93d2330cb424cddf654935f4048012f",
          "sha1": "b58a44c977456d3b7697972f19965022e0dc7fa3",
          "md5": "870d5379eb1384deb8c6da069c74dcba"
        }
      ]
    }
  ]
}
