{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 413853,
          "sha512": "bdcd0a1cc0e216f90d5c251f4626d497eb4e68d5d708c07e993471fa1354de9277faea97bbaca97f41db932a59d8524110f5f0ac48d6d721c822032dc54ba4fd",
          "sha256": "b5b4b008c575dbbef84d0d7d43f7e6db9f444ed828a16fe67e96b21739884ace",
          "sha1": "17055fed6822d7af0404acf907a50dd466a6e931",
          "md5": "1d21c63a143c0d29aaba68be5d45afc4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 413853,
          "sha512": "bdcd0a1cc0e216f90d5c251f4626d497eb4e68d5d708c07e993471fa1354de9277faea97bbaca97f41db932a59d8524110f5f0ac48d6d721c822032dc54ba4fd",
          "sha256": "b5b4b008c575dbbef84d0d7d43f7e6db9f444ed828a16fe67e96b21739884ace",
          "sha1": "17055fed6822d7af0404acf907a50dd466a6e931",
          "md5": "1d21c63a143c0d29aaba68be5d45afc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-sources.jar",
          "url": "recyclerview-1.4.0-alpha01-sources.jar",
          "size": 330679,
          "sha512": "75f3476265d61e36eb8ed40f62f38b161d61964de14c066c8b11ac9316a6e70a7c6f7ee45c888283d5d360831fafb4eef8e889651f9c9504c28634f5eabd4424",
          "sha256": "67d58ab5d6db9c01d7c6b588789d52af9e37d9b19b1bf7d804b1744d6d41b307",
          "sha1": "3b98cb53937e3b8921d80b33ede443d69aae78fd",
          "md5": "0dcd765a8228fc30cf5257e33bd96159"
        }
      ]
    }
  ]
}