{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0-alpha05"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 421919,
          "sha512": "7d47470c4caa16201bb24d27b466c00cb5c51473ca5692d2fd3cb2e543a09a50808eb7d3786c15d113cf245ca74faaed50cf1ff0cecd9024bf2d097fa474bfea",
          "sha256": "d8965cdc355f334f8b1d18d56b964c82af790e4379399459697ff0ed1996054f",
          "sha1": "e7faa7b2e4a75143f7f30a16b8dccf0e00b76d7d",
          "md5": "983c1eb3931520edc900bfd7f85d0d85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0-alpha05"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 421919,
          "sha512": "7d47470c4caa16201bb24d27b466c00cb5c51473ca5692d2fd3cb2e543a09a50808eb7d3786c15d113cf245ca74faaed50cf1ff0cecd9024bf2d097fa474bfea",
          "sha256": "d8965cdc355f334f8b1d18d56b964c82af790e4379399459697ff0ed1996054f",
          "sha1": "e7faa7b2e4a75143f7f30a16b8dccf0e00b76d7d",
          "md5": "983c1eb3931520edc900bfd7f85d0d85"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-sources.jar",
          "url": "recyclerview-1.4.0-alpha01-sources.jar",
          "size": 337039,
          "sha512": "32a7c82062dea1f8d56f9e0ffa5cd0b54466589a7afb45963ff534046bfe92be92560095127492c544414f24ba93ea179f28790033e2e50afe2e281a49c54978",
          "sha256": "b67710eaa3c870e2e9767c4c3517d8614523d38084940de991477527c91a63ca",
          "sha1": "ff5dfe8655b41c97fb35b7c0b3e36985334d23f8",
          "md5": "5d7b98fa3b6c6926be68bbe8633bb06f"
        }
      ]
    }
  ]
}