{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-sources.jar",
          "url": "recyclerview-1.4.0-alpha01-sources.jar",
          "size": 340731,
          "sha512": "74dc837285050bcaa789f9843a1de58295c2768f7cfb93b6a4f7c72b64fc97006f5ab0b266a6a8a3c89a05cc3fd87d7b8e25db26a58da3fda7ed8be40b7f90a5",
          "sha256": "d2fbdc1af69f5850a34419c775d60ebe24e1c54b78936ca2e8755d5b3b08217a",
          "sha1": "77e5d9a3314023ccb8df7fc7a26105e9fcb4f3de",
          "md5": "06e6b08e16256698f5cfafcc1d29c7cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 427355,
          "sha512": "e183da01f2d53a0435ca4bf9e94c3e3da258b3d9506877ddfc5e50a33a4820c7c7ee3d65ec143bd4f2074567b81f37beebe5422314d39cd7902862d4e63b2e86",
          "sha256": "78176efc0fde8e0e482c03b3afbb774963f41d3b6c7cecbe9dd7106087e42d8e",
          "sha1": "e6e55388bbe500e492512ef96e0a79b3c2f2304d",
          "md5": "1752de2d44b10a43a7a7c51bd73abcb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview-poolingcontainer",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.viewpager2",
          "module": "viewpager2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01.aar",
          "url": "recyclerview-1.4.0-alpha01.aar",
          "size": 427355,
          "sha512": "e183da01f2d53a0435ca4bf9e94c3e3da258b3d9506877ddfc5e50a33a4820c7c7ee3d65ec143bd4f2074567b81f37beebe5422314d39cd7902862d4e63b2e86",
          "sha256": "78176efc0fde8e0e482c03b3afbb774963f41d3b6c7cecbe9dd7106087e42d8e",
          "sha1": "e6e55388bbe500e492512ef96e0a79b3c2f2304d",
          "md5": "1752de2d44b10a43a7a7c51bd73abcb3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "recyclerview-1.4.0-alpha01-versionMetadata.json",
          "url": "recyclerview-1.4.0-alpha01-versionMetadata.json",
          "size": 75101,
          "sha512": "bc30150541e61678b0d3ccaf044a2b9e7f26846ab5f86a12d813748b439efc96cd77770736bafaf297223bd9d07f9e6d2c9f360b414b0321209b93b488c2d390",
          "sha256": "c704f5a13a8abbb95e8ecdc53a96725ff2c6fab94a26b57a537c035af5d77a8d",
          "sha1": "b99ab3d85ab5c949414e084b8bc41fa108ffc9a8",
          "md5": "14dc97d05aa07129f15a85fd7426487d"
        }
      ]
    }
  ]
}