{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6761364"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "constraintlayout",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.2.0-alpha01.aar",
          "url": "wear-1.2.0-alpha01.aar",
          "size": 266125,
          "sha512": "d55ac745d4ae5c9c62249618dc8b628f176747d4eb423ae5823d513187c693e883ca3b58fbc9f4434417526694886eb9ec9908cf0050ba2930ca4bf175eb03e8",
          "sha256": "950a5fb246084a046e334f2d5be1e833eda14b3a9dd9acc9ff1a3a3450cb7dee",
          "sha1": "38215afa031c2c302f3fc6719fc3e338ee2fde76",
          "md5": "6a91af59fcf6c6f61b9c3a9249c50f29"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "constraintlayout",
              "type": "aar",
              "extension": "aar"
            }
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.2.0-alpha01.aar",
          "url": "wear-1.2.0-alpha01.aar",
          "size": 266125,
          "sha512": "d55ac745d4ae5c9c62249618dc8b628f176747d4eb423ae5823d513187c693e883ca3b58fbc9f4434417526694886eb9ec9908cf0050ba2930ca4bf175eb03e8",
          "sha256": "950a5fb246084a046e334f2d5be1e833eda14b3a9dd9acc9ff1a3a3450cb7dee",
          "sha1": "38215afa031c2c302f3fc6719fc3e338ee2fde76",
          "md5": "6a91af59fcf6c6f61b9c3a9249c50f29"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-1.2.0-alpha01-sources.jar",
          "url": "wear-1.2.0-alpha01-sources.jar",
          "size": 111207,
          "sha512": "95c6f20151b40e68c1a3f7177fb000094fbd01625d8487b2d5bb7e3356afe3eb2f90beb6ab803c6caf18b36e9342c6c222ec4e98923165c0337a0240f64fb141",
          "sha256": "35037879120900170f314ef93d47c3a871b9514b2de8d6553ea29088db997024",
          "sha1": "2613f37bf4093da45ab9c55db49bba599f06df16",
          "md5": "ab020d5cb8a76b2dabf232bebcddea63"
        }
      ]
    }
  ]
}
