{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.5.0-beta06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13808536"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-beta06-sources.jar",
          "url": "compose-material-1.5.0-beta06-sources.jar",
          "size": 191330,
          "sha512": "870d3ee4a5c231119f56ba158ad75a80df8ef260ad7652ffd5b73574aa28a49791521b5e6096dd1dfd734f23b240d13b3aa57a5d3df32e2ddf1beef209c54578",
          "sha256": "ccfa322b2cfb0d64b0dec683e42306066fee723df0cda96522acaf662aefd512",
          "sha1": "803e62191411290c6773bdc4373e1a5b3158ab64",
          "md5": "d7d6a19949478019ad568b579fd21ca7"
        },
        {
          "name": "compose-material-1.5.0-beta06-samples-sources.jar",
          "url": "compose-material-1.5.0-beta06-samples-sources.jar",
          "size": 36664,
          "sha512": "d3090f174fb4651d894de116bfed6d33403daa213ba4e3b84f9c5f34cf45da2943282f310554c1ed220a23b148b90405bf8b0b953d3002c5f0461db634ea2b51",
          "sha256": "b772c455c5b1bdffe8881919c77997e882b2099d8575f5115d3cdc11b5e7c965",
          "sha1": "69ad02e5948d82fc42fc5c722605a8968cdc703f",
          "md5": "0f8a359ebcc0f17737574d854b41d805"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-beta06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-beta06.aar",
          "url": "compose-material-1.5.0-beta06.aar",
          "size": 1078337,
          "sha512": "a37095eb34eac0fa437360fa175bd7e64722f4646fa57fba8b44645174e6ab54467255d42129682fb9352f6566c96cf68b9258043f8bd8f673e0233c5a53fefa",
          "sha256": "9bc4fbdd4138ec1304da07fb92c714d23c7e13fdf95068d35df774e06d375cbf",
          "sha1": "b63ddb7e241f6fedaed26c3285c0aae6361e99ec",
          "md5": "21e67bd84e0744accafdf4f3c7ce30c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-beta06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-beta06.aar",
          "url": "compose-material-1.5.0-beta06.aar",
          "size": 1078337,
          "sha512": "a37095eb34eac0fa437360fa175bd7e64722f4646fa57fba8b44645174e6ab54467255d42129682fb9352f6566c96cf68b9258043f8bd8f673e0233c5a53fefa",
          "sha256": "9bc4fbdd4138ec1304da07fb92c714d23c7e13fdf95068d35df774e06d375cbf",
          "sha1": "b63ddb7e241f6fedaed26c3285c0aae6361e99ec",
          "md5": "21e67bd84e0744accafdf4f3c7ce30c9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material3",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-beta06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-beta06-versionMetadata.json",
          "url": "compose-material-1.5.0-beta06-versionMetadata.json",
          "size": 154118,
          "sha512": "ae18199a8b0373d64cc87b8009e09986ea195dc028905346a9544a58ea0250641e324f1763bcb27647264e9816f6e441c297a0879bf7a05d338bef56ca330f0e",
          "sha256": "e23511dccdf167795cadd2139bd35aaaa63f420938ca9a3ce99bd6ec5124a98e",
          "sha1": "66f9b4eb19b9dbbb74dd45786919949475dd2183",
          "md5": "df0bae492a02c0f2f62b764eed30d4b4"
        }
      ]
    }
  ]
}