{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices-java",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-alpha01"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-alpha01.aar",
          "url": "ads-adservices-java-1.1.0-alpha01.aar",
          "size": 52076,
          "sha512": "639d8eb076be98138013437cc8f341a003ad29c1d7b620f4219c9ee6a1081443a53bdd032667d98c7717e38c0af1bbcae6c551c8724166a3252c0d26f078cf92",
          "sha256": "e78f28795667d6f13081e5c31a7fcb6a8be1d2366e9b22d6eddd4a48e0b74a41",
          "sha1": "2f930e66429b538cec3d14e199b288410e56f8da",
          "md5": "18e9a5c97f11a92c41f876a600be2458"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-alpha01"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-alpha01.aar",
          "url": "ads-adservices-java-1.1.0-alpha01.aar",
          "size": 52076,
          "sha512": "639d8eb076be98138013437cc8f341a003ad29c1d7b620f4219c9ee6a1081443a53bdd032667d98c7717e38c0af1bbcae6c551c8724166a3252c0d26f078cf92",
          "sha256": "e78f28795667d6f13081e5c31a7fcb6a8be1d2366e9b22d6eddd4a48e0b74a41",
          "sha1": "2f930e66429b538cec3d14e199b288410e56f8da",
          "md5": "18e9a5c97f11a92c41f876a600be2458"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-alpha01"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-alpha01-sources.jar",
          "url": "ads-adservices-java-1.1.0-alpha01-sources.jar",
          "size": 13996,
          "sha512": "938cabfcae816cd94b18736982d711e76020792e492e5bee495a4ec35c3c059a64798a3c513a3f39ebac4141cbbef75c410696eea786611e87c7df1d918b8e93",
          "sha256": "bacef9fd378d3981989bd1109fdfbe937ed06896d64e882aff5ffe52e01a5e4b",
          "sha1": "4d3c21c8fd731bbd2aea5b9e0ed675a4c0741a90",
          "md5": "5494618e1e5149ae42f89bc9db90f8f1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-alpha01"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-alpha01-versionMetadata.json",
          "url": "ads-adservices-java-1.1.0-alpha01-versionMetadata.json",
          "size": 4092,
          "sha512": "2594414945de43c97b4a66c61e8f7dc9e10f17888ba71c899c52363ccd099ffe8981f09c26886d4cb4c97be94023d6ef975a61cd9a313b99538c59f0d722d8cc",
          "sha256": "1db501f5101be944d307b9a4f18d28b28b78d8e97ac001e04dd262f38aefd574",
          "sha1": "39885c824efdd1fdf3cd0dfed3cf4f220e4ff2ea",
          "md5": "e9c7214a6a0270cdf55b0c693c178957"
        }
      ]
    }
  ]
}