version: "1.5.0-beta03"
dependency_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0-beta03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13006434"
group_id: "androidx.collection"
artifact_id: "collection-ktx"
path: "/collection/collection-ktx"
sha: "79d4ded60ba22f3beeeb7f3bbc918c93cb26c3f8"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.collection-collection-ktx-all-13006434-1.5.0-beta03.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.5.0-beta03"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":collection:collection-ktx:test"
