{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime",
    "version": "2.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01.aar",
          "url": "navigation-runtime-2.8.0-alpha01.aar",
          "size": 129235,
          "sha512": "fe88b69c775ab743ba53ba9f4b440cfebafa2f4812245ebe58c184949d24f89bc1a1d6c28a5950ce756406e06e1074030833e24b5c82bde2b06c5b53c526d41c",
          "sha256": "d4fa6c157d271c6c939db67c656a5e2ea122ac879b21452b3d278f10049fc3a1",
          "sha1": "3d655922ef54511604ed8d9af27f5485fb74a154",
          "md5": "4ea42732b6b8cdbfeabdf185394a75c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01.aar",
          "url": "navigation-runtime-2.8.0-alpha01.aar",
          "size": 129235,
          "sha512": "fe88b69c775ab743ba53ba9f4b440cfebafa2f4812245ebe58c184949d24f89bc1a1d6c28a5950ce756406e06e1074030833e24b5c82bde2b06c5b53c526d41c",
          "sha256": "d4fa6c157d271c6c939db67c656a5e2ea122ac879b21452b3d278f10049fc3a1",
          "sha1": "3d655922ef54511604ed8d9af27f5485fb74a154",
          "md5": "4ea42732b6b8cdbfeabdf185394a75c0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01-sources.jar",
          "url": "navigation-runtime-2.8.0-alpha01-sources.jar",
          "size": 48377,
          "sha512": "a3dd693c3d69160582a1642a93ef64155c5894642d14110ea6f38bae67e99c5a6231008c2a4fead98178b0e83e9b326722349f0b741ad07b1dc0b0c5a6e644d4",
          "sha256": "377802fbb12594dd3159d468315122772f204bc089ce566ffe4fb1e65e8706f5",
          "sha1": "a0b4e90d71fba0e80cdd15606011718a34ea8c2b",
          "md5": "26c984de1922e56db7b6891017e5911d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "navigation-runtime is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-2.8.0-alpha01-versionMetadata.json",
          "url": "navigation-runtime-2.8.0-alpha01-versionMetadata.json",
          "size": 13202,
          "sha512": "4194749417df779b9193a79999f9a1bccf4dbd66caf0cc8230c15524aa8dcbafe101c697d2269d71cdb82a0b146626fbad4d08243fd29595b455d43778380196",
          "sha256": "0ed902b4db7364a681bd428624889970d62652f233ba92549b2b8777b524840e",
          "sha1": "866aab21d39f589fb65e8389b309ecdaf522de3c",
          "md5": "50f75a7f51fdedc8bc21df9ccfb8039e"
        }
      ]
    }
  ]
}