{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-core",
    "version": "2.4.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha04.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha04.aar",
          "size": 9452,
          "sha512": "bf53c6d8c8edcfe5bfdffbedae7626c2100ce18f591b7317a39bb83cbc7a68dc4def95b61b8f27955a5672ce01fde59b524fee2bc231e198c9f67e69e35910c1",
          "sha256": "d745a29675df04285bbf3c07f9820712b655038658dc2f6bf3309ad4f657ed85",
          "sha1": "07673e9d6bf12d6304170390fe6d04b6b717d359",
          "md5": "6a7d25e4a377ab4f36aa1f106434a68c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.4.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha04.aar",
          "url": "lifecycle-livedata-core-2.4.0-alpha04.aar",
          "size": 9452,
          "sha512": "bf53c6d8c8edcfe5bfdffbedae7626c2100ce18f591b7317a39bb83cbc7a68dc4def95b61b8f27955a5672ce01fde59b524fee2bc231e198c9f67e69e35910c1",
          "sha256": "d745a29675df04285bbf3c07f9820712b655038658dc2f6bf3309ad4f657ed85",
          "sha1": "07673e9d6bf12d6304170390fe6d04b6b717d359",
          "md5": "6a7d25e4a377ab4f36aa1f106434a68c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-core-2.4.0-alpha04-sources.jar",
          "url": "lifecycle-livedata-core-2.4.0-alpha04-sources.jar",
          "size": 6814,
          "sha512": "e41cbf39485d124f79536b444e5d0ee38d52e993422c7882b4a55bf7bbf573d2fb39eb52ebeeab71222f577bf71c5c1967ce7ac7b6f78108ef6b46d5fb55cfb5",
          "sha256": "a7260859d2991284ae553251a4ff9730f3b57c35d14128f9b079dd5db28958f1",
          "sha1": "38ecd5651d87b6db994df01f93fc72d6e59b846a",
          "md5": "1c8d3854faf03cbaa6d83d2f57345fa6"
        }
      ]
    }
  ]
}
