version: "1.0.0"
dependency_list {
}
release_checklist {
}
build_id: "androidx.tracing"
group_id: "androidx.tracing"
artifact_id: "tracing-perfetto-binary"
path: "/tracing/tracing-perfetto-binary"
sha: "97dfc656433b630c22143768b4a4176f2e6ee205"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.tracing-tracing-perfetto-binary-all-12508510-1.0.0.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-perfetto"
    version: "1.0.0"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-perfetto-handshake"
    version: "1.0.0"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
target: "androidx"
