version: "1.0.0"
dependency_list {
}
release_checklist {
}
build_id: "androidx.tracing"
group_id: "androidx.tracing"
artifact_id: "tracing-perfetto-binary"
path: "/tracing/tracing-perfetto-binary"
sha: "f81f28f6e2e782b92d26b531542dbdd537e1c690"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.tracing-tracing-perfetto-binary-all-12346335-1.0.0.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-perfetto"
    version: "1.0.0"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.tracing"
    artifact_id: "tracing-perfetto-handshake"
    version: "1.0.0"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
