version: "1.16.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.16.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "12976215"
group_id: "androidx.core"
artifact_id: "core-ktx"
path: "/core/core-ktx"
sha: "d1ec2613849f517c712bfd0c3d355dde0fdc631f"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-ktx-all-12976215-1.16.0-alpha02.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.16.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-ktxreleaseAndroidTest.xml"
test_module_names: ":core:core-ktx:testReleaseUnitTest"
