{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha03.aar",
          "url": "activity-1.7.0-alpha03.aar",
          "size": 124582,
          "sha512": "0f22228f1ed29d80c3f5c0dbcabcd6dd05cb381eb203112ca87c984f391aa74d1bf3e114a7141569c29252e1282d7b0af384c34353bbc933400fea8bec173776",
          "sha256": "8aa43f21c3fe3dd907e9e8776054bc002e337e05b943922626a60c87cf0b7aa4",
          "sha1": "59aa143ff3e38752489250747a02d3b080782f2b",
          "md5": "6f95b8d459cfcfeb2ba0080688cd0d9c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha03.aar",
          "url": "activity-1.7.0-alpha03.aar",
          "size": 124582,
          "sha512": "0f22228f1ed29d80c3f5c0dbcabcd6dd05cb381eb203112ca87c984f391aa74d1bf3e114a7141569c29252e1282d7b0af384c34353bbc933400fea8bec173776",
          "sha256": "8aa43f21c3fe3dd907e9e8776054bc002e337e05b943922626a60c87cf0b7aa4",
          "sha1": "59aa143ff3e38752489250747a02d3b080782f2b",
          "md5": "6f95b8d459cfcfeb2ba0080688cd0d9c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.7.0-alpha03-sources.jar",
          "url": "activity-1.7.0-alpha03-sources.jar",
          "size": 48298,
          "sha512": "5553302b6ae394b28fd27d09ee56f62597260b4cc1447970fa2df684644a1d7fbcde430f8f066960410f4603597751dec6414b886e49bc70036dd992227a2c74",
          "sha256": "d4330e7a28949e14ff6b49452ddf57d2a86079303a0d9227d84dc7c037766ded",
          "sha1": "c96b18ceda9a347df7b93e8af45b2ddae04bbc78",
          "md5": "1c9f033a4db5ddd8701e9568c6b74287"
        }
      ]
    }
  ]
}