{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.19.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13718522"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.19.0-alpha01-sources.jar",
          "url": "core-1.19.0-alpha01-sources.jar",
          "size": 987919,
          "sha512": "886cc80cd76238e8a720e4f725d47e0c5f8e4dc2ac23847867596aa23a624d7becdd7efff4714b3d636507e70f4ea0ee2c2c8cf1419ae2867771a5f58b25b98a",
          "sha256": "841f9f061ededc5edfdd61e22a0aa3d831fcbac3c97c2040e213f251c0fb6685",
          "sha1": "a9612028883e6b43819e922099411815d65e684a",
          "md5": "b18f35a8626681a1f5107352d6a85ca1"
        },
        {
          "name": "core-1.19.0-alpha01-samples-sources.jar",
          "url": "core-1.19.0-alpha01-samples-sources.jar",
          "size": 6272,
          "sha512": "a9246de87cc8f33a38346139c37243099d11256100fe035083f43341e6aefea350781a64679c00436d2539a6c65de2a8e0152eb40f07234005f46d98cef4e723",
          "sha256": "a487797562cc32e1233334574ca1681d36063ec9a4399c44e9d007a633dcd3a3",
          "sha1": "26479f91ea0d83ae369a781b380b9b9a54551741",
          "md5": "93b1b3eea236c8e04cd69e0d2853daf5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.19.0-alpha01.aar",
          "url": "core-1.19.0-alpha01.aar",
          "size": 1403767,
          "sha512": "9f8d35365ab102f896aed76595ed8fb6a7fb1e27f7e0d01f995493b82703a1698aaaad3a8f799a845591f09bcfcbd682c7e05695d12e5e41e66de0eaf2c1d85f",
          "sha256": "4ce7c106be34ecc18557989d164d6cfacc8ee877102a5f40a1a3f7dc7b634df5",
          "sha1": "a4b04e63c25a4575d6977da4f19caa79c2a59a3c",
          "md5": "1cfe7a2699a3ba630e2e96322275c638"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.19.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.19.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.19.0-alpha01.aar",
          "url": "core-1.19.0-alpha01.aar",
          "size": 1403767,
          "sha512": "9f8d35365ab102f896aed76595ed8fb6a7fb1e27f7e0d01f995493b82703a1698aaaad3a8f799a845591f09bcfcbd682c7e05695d12e5e41e66de0eaf2c1d85f",
          "sha256": "4ce7c106be34ecc18557989d164d6cfacc8ee877102a5f40a1a3f7dc7b634df5",
          "sha1": "a4b04e63c25a4575d6977da4f19caa79c2a59a3c",
          "md5": "1cfe7a2699a3ba630e2e96322275c638"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.19.0-alpha01-versionMetadata.json",
          "url": "core-1.19.0-alpha01-versionMetadata.json",
          "size": 273411,
          "sha512": "7c171068886408aad187ad86054ae5f7cb9c6b74b1b74a5ae3dd949dc494a2399226718cc54cd8021a31477a2ea010b7ff42fbdeb835a08ddc55102995e3e332",
          "sha256": "c66ba9b5de077773261f0650387336770e3829554ea56302d09fc2ce493c711b",
          "sha1": "59ad1a58f9bfccef2cc6f9567794518ce656fa57",
          "md5": "7d7124433d3b3f7baf477d43352187bd"
        }
      ]
    }
  ]
}