{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12976215"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.8.0-alpha01-sources.jar",
          "url": "appcompat-resources-1.8.0-alpha01-sources.jar",
          "size": 44324,
          "sha512": "5d05acddc92d0561d9ffc4f0fc78c845432adfa35a9206b5223c483d6ab873beb0fe326431d4ee8ed6166667930ba54c4a850d2ddd82fda93b6086f1e23bf125",
          "sha256": "be3b7aa14593024fe233ff1e0b33195d9ecf40433dfe3d46f0fdf85a6536082c",
          "sha1": "ce0197944e4da00667ccc4c63861942f87fe316d",
          "md5": "14c2f2b459bcb1fef79bcdfbc0c46c11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.8.0-alpha01.aar",
          "url": "appcompat-resources-1.8.0-alpha01.aar",
          "size": 72451,
          "sha512": "92370f8f338cf3bf8404715c04a84d786c2907a34630fb925bebbb933cecc4e1214007575efcdd328c95867cfc9dd35f8843808c794e6ab6ce68abc62fb3f112",
          "sha256": "202d1c51781622313612f9364f3e5ff1d52c1d74dc38e04cac3578ae7fd052ea",
          "sha1": "3fa350f74c7a2f987b3782cff25df4b9364aa68c",
          "md5": "bca16fbc949e2e12b575a37bec9da181"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.8.0-alpha01.aar",
          "url": "appcompat-resources-1.8.0-alpha01.aar",
          "size": 72451,
          "sha512": "92370f8f338cf3bf8404715c04a84d786c2907a34630fb925bebbb933cecc4e1214007575efcdd328c95867cfc9dd35f8843808c794e6ab6ce68abc62fb3f112",
          "sha256": "202d1c51781622313612f9364f3e5ff1d52c1d74dc38e04cac3578ae7fd052ea",
          "sha1": "3fa350f74c7a2f987b3782cff25df4b9364aa68c",
          "md5": "bca16fbc949e2e12b575a37bec9da181"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat-resources is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.8.0-alpha01-versionMetadata.json",
          "url": "appcompat-resources-1.8.0-alpha01-versionMetadata.json",
          "size": 4232,
          "sha512": "0b9d6b088cb3f14f3bcdff504d67004a682ffa28fee566ebe8b621fc850249914e344e7682e90202fa787dfb4bde6e6514dbd136cabf86645cb13025fbc4689c",
          "sha256": "a11db908ffcf1bd0275f2da342a3a539b7ce15faaaad5baa6b9fcf5505bd7440",
          "sha1": "54676f6f7bfb29f84dff1c1d7ce7c7b313af6fc2",
          "md5": "43bad3fd4f83703f93dbd92a0e222fd9"
        }
      ]
    }
  ]
}