{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-test-manifest",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.4.0-alpha03.aar",
          "url": "ui-test-manifest-1.4.0-alpha03.aar",
          "size": 9162,
          "sha512": "7aa898a986f0e9ca0cc257154a7ff69c772f98a4f4ca01f1d60aaa352b2d1d129202103c8f4067b731e7db2836fe21cc8a71cd3e58adf14e060ef53191d34667",
          "sha256": "1540c82250272c8d5cdc6b64ea5ee9a597596b35a6dd800bd2dc80fb16cc23db",
          "sha1": "066021e866108020efb3453589a4329e3bcc9fa4",
          "md5": "ca019d0a94f9e06fa3177f0f7e726140"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "ui-test-manifest-1.4.0-alpha03.aar",
          "url": "ui-test-manifest-1.4.0-alpha03.aar",
          "size": 9162,
          "sha512": "7aa898a986f0e9ca0cc257154a7ff69c772f98a4f4ca01f1d60aaa352b2d1d129202103c8f4067b731e7db2836fe21cc8a71cd3e58adf14e060ef53191d34667",
          "sha256": "1540c82250272c8d5cdc6b64ea5ee9a597596b35a6dd800bd2dc80fb16cc23db",
          "sha1": "066021e866108020efb3453589a4329e3bcc9fa4",
          "md5": "ca019d0a94f9e06fa3177f0f7e726140"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-test-manifest-1.4.0-alpha03-sources.jar",
          "url": "ui-test-manifest-1.4.0-alpha03-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}