{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera.featurecombinationquery",
    "module": "featurecombinationquery",
    "version": "1.5.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13588622"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera.featurecombinationquery",
          "module": "featurecombinationquery-play-services",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "featurecombinationquery is in atomic group androidx.camera.featurecombinationquery"
        }
      ],
      "files": [
        {
          "name": "featurecombinationquery-1.5.0-beta01-sources.jar",
          "url": "featurecombinationquery-1.5.0-beta01-sources.jar",
          "size": 19258,
          "sha512": "d860c1cc382f59bced985568a19063825694e5b13f263df6d31702f625955294031c32968891bed65cfb26ee1121be37f6bae4d8b6fa5d51d0cfdb5269b6c49b",
          "sha256": "dda46f7f2ad1e6ad0a10890a512c74a6da0506b47e24174bb7915ca4303c77e2",
          "sha1": "f4b9b5e27f105661f4868f7d7deb2d0cff9aa00a",
          "md5": "b39d234b67fc356b7ceb216bde7d6f4f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera.featurecombinationquery",
          "module": "featurecombinationquery-play-services",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "featurecombinationquery is in atomic group androidx.camera.featurecombinationquery"
        }
      ],
      "files": [
        {
          "name": "featurecombinationquery-1.5.0-beta01.aar",
          "url": "featurecombinationquery-1.5.0-beta01.aar",
          "size": 18297,
          "sha512": "efbb5bb84dfffa5ec916bfbf28792a4cfd597f3b212a6c791dbf8dc1794aa30c5ba8d1dac950a9c2da67d0674a549f71dc02ee6fa5ebe5c1e3f441714a326bf6",
          "sha256": "87a7fc37c6e4a9083bd8c88906b3b5280c34b958699a899042412c1f8357427f",
          "sha1": "1c99744d387c4c5dbd4cd3c1f3c484c2fa772aea",
          "md5": "5312f458e6296e5f7746c930ed86ca1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera.featurecombinationquery",
          "module": "featurecombinationquery-play-services",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "featurecombinationquery is in atomic group androidx.camera.featurecombinationquery"
        }
      ],
      "files": [
        {
          "name": "featurecombinationquery-1.5.0-beta01.aar",
          "url": "featurecombinationquery-1.5.0-beta01.aar",
          "size": 18297,
          "sha512": "efbb5bb84dfffa5ec916bfbf28792a4cfd597f3b212a6c791dbf8dc1794aa30c5ba8d1dac950a9c2da67d0674a549f71dc02ee6fa5ebe5c1e3f441714a326bf6",
          "sha256": "87a7fc37c6e4a9083bd8c88906b3b5280c34b958699a899042412c1f8357427f",
          "sha1": "1c99744d387c4c5dbd4cd3c1f3c484c2fa772aea",
          "md5": "5312f458e6296e5f7746c930ed86ca1a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera.featurecombinationquery",
          "module": "featurecombinationquery-play-services",
          "version": {
            "requires": "1.5.0-beta01"
          },
          "reason": "featurecombinationquery is in atomic group androidx.camera.featurecombinationquery"
        }
      ],
      "files": [
        {
          "name": "featurecombinationquery-1.5.0-beta01-versionMetadata.json",
          "url": "featurecombinationquery-1.5.0-beta01-versionMetadata.json",
          "size": 2863,
          "sha512": "c2a454c133e896e59e96189dc6bd0ac0daa682d2c2ea8aa1e782b99380ea16cdf88c5eab7bb5bd99b1dc80bc2cb3fcb9b1666fab3a4c23296d85be2d58dfaf6b",
          "sha256": "d4734284ec9991128132a34e132fb3ace7015ce40a4eb963a1831f82f7e7a75b",
          "sha1": "7a811531d6fbe5efa93f6f540edfdae8b08a84fe",
          "md5": "da1e97ba04a201a0b5a40b19f348cb39"
        }
      ]
    }
  ]
}