{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7080078"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.0-alpha01.aar",
          "url": "navigation-ui-2.4.0-alpha01.aar",
          "size": 90931,
          "sha512": "b0101b7f8f3c51d94c34f1b0dd9c52f051f956560699d88e5f85622122d4e72f6c45219307567ab09a51595c85facef722a6029c6ad58eb331f043dd44e3ea35",
          "sha256": "02269af0fc05be768d407dbfba36e1915b544e59eadb671228936544531b8989",
          "sha1": "78ccb0e9d628bcf1749b2f823ec2f7e43eb4a2c5",
          "md5": "6b0ffb9177e73b8687aa11d9ab7264d5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.transition",
          "module": "transition",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "navigation-ui-2.4.0-alpha01.aar",
          "url": "navigation-ui-2.4.0-alpha01.aar",
          "size": 90931,
          "sha512": "b0101b7f8f3c51d94c34f1b0dd9c52f051f956560699d88e5f85622122d4e72f6c45219307567ab09a51595c85facef722a6029c6ad58eb331f043dd44e3ea35",
          "sha256": "02269af0fc05be768d407dbfba36e1915b544e59eadb671228936544531b8989",
          "sha1": "78ccb0e9d628bcf1749b2f823ec2f7e43eb4a2c5",
          "md5": "6b0ffb9177e73b8687aa11d9ab7264d5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-ui-2.4.0-alpha01-sources.jar",
          "url": "navigation-ui-2.4.0-alpha01-sources.jar",
          "size": 13679,
          "sha512": "ea13b0787ded0e4bd95c52cfd91f9477b0d6ec8a89efd0bdbcb4a5b76211f2f9183fdd0e7f0b00162a867a3b51157c11934514b2243436f15bdc7e895faf8ea7",
          "sha256": "8faa2bed7d4acf1e7a8bbfc30f2cedf81df32caeeb31b16fc2eeaeeadb42e648",
          "sha1": "c3b1c72fb42a6c6ea70970fa444614a2aaa64742",
          "md5": "243d7ce3da37cfbd5c9fb705a4c7ea67"
        }
      ]
    }
  ]
}
