{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.interpolator",
    "module": "interpolator",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6761364"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 8053,
          "sha512": "7cc0d63ce4d75301219debe5f5a6ed3632afb457d6fcce8693b70431418e6eb43c73641b70d6335c4128060b58ef6bc1b92b9b8531388138addbc484ab864b9e",
          "sha256": "573f480148431c910e69d0d890f66be39a49c2fb88c733944b75252d2c18d7bb",
          "sha1": "d921eb0c315ca52e0a59e0d203d52f13901cf3fc",
          "md5": "1f84f8af2dc1d8a0616ac30ee04e9b19"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 8053,
          "sha512": "7cc0d63ce4d75301219debe5f5a6ed3632afb457d6fcce8693b70431418e6eb43c73641b70d6335c4128060b58ef6bc1b92b9b8531388138addbc484ab864b9e",
          "sha256": "573f480148431c910e69d0d890f66be39a49c2fb88c733944b75252d2c18d7bb",
          "sha1": "d921eb0c315ca52e0a59e0d203d52f13901cf3fc",
          "md5": "1f84f8af2dc1d8a0616ac30ee04e9b19"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01-sources.jar",
          "url": "interpolator-1.1.0-alpha01-sources.jar",
          "size": 6822,
          "sha512": "0bb7f6e999ad3f79ab6379b77ec8bf5f94013805109acafa4f2d5b2bed336f4a328986415686b274cfb6999cd93d6a5a3cf9da216e3edcae8bf31913c396828d",
          "sha256": "b424610869ff191adbc3fd5a3f978accd3de9aa4464032dd99b0f57eb8248a83",
          "sha1": "87c4b919f0886d09bd85d4626cadc9e08ef160af",
          "md5": "69943d660297c81234b76ece84a5db73"
        }
      ]
    }
  ]
}
