{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.interpolator",
    "module": "interpolator",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2.2",
      "buildId:": "6388794"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 7567,
          "sha512": "67ddce72c4b5296ccbcb6a16f762d91d43921bfa68677feb5353b246ccc8ba488a6dc7398cca5d8c019f7443973268c8cce1c7ae949cc04f36f31a79017d11c1",
          "sha256": "b0c7e1a65e3eaca7c4298429921dc040b0733e6004b34ab19db3c62019e6f427",
          "sha1": "f626d2149374ea3419cd0c9be40d751320efdd4f",
          "md5": "3eabc5471857fdabf6c785e9dcee58ec"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01.aar",
          "url": "interpolator-1.1.0-alpha01.aar",
          "size": 7567,
          "sha512": "67ddce72c4b5296ccbcb6a16f762d91d43921bfa68677feb5353b246ccc8ba488a6dc7398cca5d8c019f7443973268c8cce1c7ae949cc04f36f31a79017d11c1",
          "sha256": "b0c7e1a65e3eaca7c4298429921dc040b0733e6004b34ab19db3c62019e6f427",
          "sha1": "f626d2149374ea3419cd0c9be40d751320efdd4f",
          "md5": "3eabc5471857fdabf6c785e9dcee58ec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "interpolator-1.1.0-alpha01-sources.jar",
          "url": "interpolator-1.1.0-alpha01-sources.jar",
          "size": 6655,
          "sha512": "0b3db3faed43e581dee909fd2e11952cea0db6352da26b8606ecd26d7f5051fb31fbe52d0262d66718b87fdfcbff3f94d320055b36d0b71e6922435667440738",
          "sha256": "d1bf127815c9fd2059da2e02f34a6459acc51efa8355207435688d95ffb88fa5",
          "sha1": "bb2847110b6ee9bca95b9d6bae663ed5061bb575",
          "md5": "9d3fa67f41ef387dbb5a570d54680da4"
        }
      ]
    }
  ]
}
