{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto-handshake",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta01.jar",
          "url": "tracing-perfetto-handshake-1.0.0-beta01.jar",
          "size": 25921,
          "sha512": "9c020dbd9582b2ae5581c3de49a9743154a66716543ece845413cf65be72902cd40c4a8e5f9ab131ce45f94060177c0aeeac0b384f229d0f02ab1abe79f66d52",
          "sha256": "fefa3e9f14a079b38bb965f663780f8623945f6cef579e67ff21381f8776550b",
          "sha1": "894187be8d2dae178bb71612eb42712ee904c813",
          "md5": "33a3c72139d0d6c491da2e5708313118"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta01.jar",
          "url": "tracing-perfetto-handshake-1.0.0-beta01.jar",
          "size": 25921,
          "sha512": "9c020dbd9582b2ae5581c3de49a9743154a66716543ece845413cf65be72902cd40c4a8e5f9ab131ce45f94060177c0aeeac0b384f229d0f02ab1abe79f66d52",
          "sha256": "fefa3e9f14a079b38bb965f663780f8623945f6cef579e67ff21381f8776550b",
          "sha1": "894187be8d2dae178bb71612eb42712ee904c813",
          "md5": "33a3c72139d0d6c491da2e5708313118"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta01-sources.jar",
          "url": "tracing-perfetto-handshake-1.0.0-beta01-sources.jar",
          "size": 8797,
          "sha512": "d6fd8487e61809fdf1c413b064547f36db34ecefd5b7220bf525b56a0a856cf97749f2e6c4f1f33e7a4917a78ac453d78f7acb36ffd2f2aa98ff08129bb8d011",
          "sha256": "3d1dbcbc5b816e5f3a3772bfa995fcc3a9dd57ba43ff4ee9075a8352aff8bb20",
          "sha1": "3408ffa7145632bbe799a1b44b24f1498a546af4",
          "md5": "9eebb61019700e38d5ea92f3eb7365dd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta01"
          },
          "reason": "tracing-perfetto-handshake is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-handshake-1.0.0-beta01-versionMetadata.json",
          "url": "tracing-perfetto-handshake-1.0.0-beta01-versionMetadata.json",
          "size": 2772,
          "sha512": "44553852ef03bf30d4713bdffb43636c4ce1227df597f2189b8046e0cec62f9da3da82f10d80f793f52ca1d768577df69a3ad9c836d7553f46ec574e20e9a740",
          "sha256": "0183ba32b17d7be2c16383053da39b56a6535ef38a9e5843bb4e2ecc0367c6c3",
          "sha1": "99697dba6ae67530465998b8477cd8ee3db0ff2f",
          "md5": "c1b0f6e7f6459bac031072b951e576d9"
        }
      ]
    }
  ]
}