{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha05-sources.jar",
          "url": "credentials-1.5.0-alpha05-sources.jar",
          "size": 246671,
          "sha512": "d8c026d44a65bd691d11f473ceffb1c0e32d559aee9a1bfbfd0259e1c77dd402df5d02a074aa4846272ceccbd080ced7168f9b2e3e61e4e0b9adba601c11fa5e",
          "sha256": "ef69541d0339c6d4b9388ed51bee3d9d30421ffdcd2756443ebddc07465dac28",
          "sha1": "ce900da671a515a6bf9a6554eb9bedbf5297e35d",
          "md5": "cbcb0e6e91ae9a6c868b1e03bc773a72"
        },
        {
          "name": "credentials-1.5.0-alpha05-samples-sources.jar",
          "url": "credentials-1.5.0-alpha05-samples-sources.jar",
          "size": 7243,
          "sha512": "4802d83b3197e0faf36b8968e23723ad598d1954bdc5353bbe7193cd28f00fb0d41e98b28df9cae41584153608b7e52215c29dc8089d8785b2a4b83f34e4a003",
          "sha256": "fe1e7e44cf21e3cfd6858d14fba9da11aff6a3dc9d25b2bb634afb5a7dae73ae",
          "sha1": "1c39e28debbbbfaf621ec1643048b3ae9e7c745e",
          "md5": "44b66a46acc1d1332daf97f2211fe1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha05.aar",
          "url": "credentials-1.5.0-alpha05.aar",
          "size": 610378,
          "sha512": "463ff6bbe06b4485e57cb9c4e9f0269858935787b7008e5954fda5a603bc2cf7d9d57a3c8d75f39116a73cb3359d1588b61b29856b1c47eab57d487067d0bae1",
          "sha256": "a30e44119f925dda77a282e43be938851ddb466428695324c24b30708cc2006e",
          "sha1": "907d70b1577b37ff386277f5a18800d2e8075d8e",
          "md5": "71783bfa68e3160739b8a609e3325b19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha05.aar",
          "url": "credentials-1.5.0-alpha05.aar",
          "size": 610378,
          "sha512": "463ff6bbe06b4485e57cb9c4e9f0269858935787b7008e5954fda5a603bc2cf7d9d57a3c8d75f39116a73cb3359d1588b61b29856b1c47eab57d487067d0bae1",
          "sha256": "a30e44119f925dda77a282e43be938851ddb466428695324c24b30708cc2006e",
          "sha1": "907d70b1577b37ff386277f5a18800d2e8075d8e",
          "md5": "71783bfa68e3160739b8a609e3325b19"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha05-versionMetadata.json",
          "url": "credentials-1.5.0-alpha05-versionMetadata.json",
          "size": 71508,
          "sha512": "01363ca496f4e6e318e5d64c8e7ad86db067bc8d68d5c52ed567e373ec318329a960c7b3018a3b81fab3a351e3c0ba0fd9ac95a0203e81becebada98830ec020",
          "sha256": "38724e749dca4775144e05ea9c3438de7c36a55eda7ae94975e13cf4bd89edb0",
          "sha1": "21b0a69894da9ba1631e303b945b4bb49e57ea76",
          "md5": "de4169fe3a1dfdc196ce7655d3ab4e14"
        }
      ]
    }
  ]
}