version: "1.5.8"
dependency_list {
}
release_checklist {
}
build_id: "androidx.compose.compiler"
group_id: "androidx.compose.compiler"
artifact_id: "compiler-hosted"
path: "/compose/compiler/compiler-hosted"
sha: "3c5f8e10720b62ff8be6792821318a90bd2eb737"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-compiler-11267559.zip"
project_zip_path: "per-project-zips/androidx.compose.compiler-compiler-hosted-all-11267559-1.5.8.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.compiler"
    artifact_id: "compiler"
    version: "1.5.8"
    is_tip_of_tree: true
  }
}
