version: "1.5.8"
dependency_list {
}
release_checklist {
}
build_id: "androidx.compose.compiler"
group_id: "androidx.compose.compiler"
artifact_id: "compiler-hosted"
path: "/compose/compiler/compiler-hosted"
sha: "eb7d09496d10b5c94d9c736970be5e4316358f3e"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-compiler-11341084.zip"
project_zip_path: "per-project-zips/androidx.compose.compiler-compiler-hosted-all-11341084-1.5.8.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.compiler"
    artifact_id: "compiler"
    version: "1.5.8"
    is_tip_of_tree: true
  }
}
