version: "1.5.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "13115689"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "116bf3edf6cb0604a2cd55babf4fdeb279e5f3f7"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-13115689-1.5.0-alpha01.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "annotation-annotation-experimentalreleaseAndroidTest.xml"
test_module_names: ":annotation:annotation-experimental:testReleaseUnitTest"
