{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-proto",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12950933"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.3.0-alpha07.jar",
          "url": "protolayout-proto-1.3.0-alpha07.jar",
          "size": 1233906,
          "sha512": "bf47afc2003d9b8f369ffc9a4a6a06a38323d068abaac91ce772f3aae274b6b97850009659ea328adfec1d8090f346f674901c892c16bbe8411aa734c88658f5",
          "sha256": "d848adfb9de07b63433ee6065a5ccb299d2c10d977045520ebbc99d7bc1d8aae",
          "sha1": "c5251a6893de6a9b516c9a952a9da7e8a345d423",
          "md5": "a16250c2dbebc695836e9b35f1e4d29e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.3.0-alpha07.jar",
          "url": "protolayout-proto-1.3.0-alpha07.jar",
          "size": 1233906,
          "sha512": "bf47afc2003d9b8f369ffc9a4a6a06a38323d068abaac91ce772f3aae274b6b97850009659ea328adfec1d8090f346f674901c892c16bbe8411aa734c88658f5",
          "sha256": "d848adfb9de07b63433ee6065a5ccb299d2c10d977045520ebbc99d7bc1d8aae",
          "sha1": "c5251a6893de6a9b516c9a952a9da7e8a345d423",
          "md5": "a16250c2dbebc695836e9b35f1e4d29e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "protolayout-proto is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-proto-1.3.0-alpha07-sources.jar",
          "url": "protolayout-proto-1.3.0-alpha07-sources.jar",
          "size": 312245,
          "sha512": "124069d2abf68cc2ab700e12fa81057f342e0f7fd1d67e007d75d41ee33a8e7fa494645c855490ee2d3a92ef3b2cfcad606113afbd2929c02d2d27fe6f399d1b",
          "sha256": "bd4cdfc91e6304e0af76e5e0e9823dee31d1d21b89304dc01e12e02b4bd9330a",
          "sha1": "e6b15f945d48c392cdd858611126e2089b2c0188",
          "md5": "c8cf47846f396432b97f8431d572c11d"
        }
      ]
    }
  ]
}