{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.2.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7116071"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.2.0-beta01.aar",
          "url": "recyclerview-1.2.0-beta01.aar",
          "size": 393658,
          "sha512": "f21bc6e2d9147cc3b4770a12c367108449d92045a3c06bb30c68f2c9f38ee9eba9a8276a31b0dda3724d01a7900b79a7357351fef7025e6ae096173e70d167fe",
          "sha256": "5b45ea40d6a2e50f59f21bc0728130da439220c56c156d10ec0381422741c84d",
          "sha1": "398fee049b26b8bb0e52286c0047f29f231feaad",
          "md5": "c93f4a9fff677a4ade20942191ada3aa"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.2.0-beta01.aar",
          "url": "recyclerview-1.2.0-beta01.aar",
          "size": 393658,
          "sha512": "f21bc6e2d9147cc3b4770a12c367108449d92045a3c06bb30c68f2c9f38ee9eba9a8276a31b0dda3724d01a7900b79a7357351fef7025e6ae096173e70d167fe",
          "sha256": "5b45ea40d6a2e50f59f21bc0728130da439220c56c156d10ec0381422741c84d",
          "sha1": "398fee049b26b8bb0e52286c0047f29f231feaad",
          "md5": "c93f4a9fff677a4ade20942191ada3aa"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.2.0-beta01-sources.jar",
          "url": "recyclerview-1.2.0-beta01-sources.jar",
          "size": 321252,
          "sha512": "a7c449323d8e30c99e8f9d0b15db592ab03e64a474ff2f119d347500796741fe0fb69b8ea6ab1e5a89277f36e84ff3c631271e5b930ad17bf9cce1a5af1c30bc",
          "sha256": "0947f5207e3d320f7b8455c8debd3638ebc8309a4fb3d13a49c0dabf237a19f6",
          "sha1": "18e9deecb147fc3436421f7d77e65f0cf39a1a17",
          "md5": "74944e981ee738e3a9dc4137f4731c87"
        }
      ]
    }
  ]
}
