{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha01.aar",
          "url": "tiles-1.4.0-alpha01.aar",
          "size": 246146,
          "sha512": "20157398ee8613db45138cc053b2396711567bd6fdbb37cc05a0b6729ef21e954cd8cbcb753e5432e62ca91fb5dd30b4d79243fac250d8154d56381afad9a4f9",
          "sha256": "ee4c2bc61d1927c6569a8a1fd08fa580b85c546bbdfb5841a41e2a0d2691029b",
          "sha1": "87efa8a395e9b9106c6404a090f32eddf05e7992",
          "md5": "8f7f1a18b08c652f8b73fe7f291fc713"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha01.aar",
          "url": "tiles-1.4.0-alpha01.aar",
          "size": 246146,
          "sha512": "20157398ee8613db45138cc053b2396711567bd6fdbb37cc05a0b6729ef21e954cd8cbcb753e5432e62ca91fb5dd30b4d79243fac250d8154d56381afad9a4f9",
          "sha256": "ee4c2bc61d1927c6569a8a1fd08fa580b85c546bbdfb5841a41e2a0d2691029b",
          "sha1": "87efa8a395e9b9106c6404a090f32eddf05e7992",
          "md5": "8f7f1a18b08c652f8b73fe7f291fc713"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha01-sources.jar",
          "url": "tiles-1.4.0-alpha01-sources.jar",
          "size": 69875,
          "sha512": "cb949a0a461455e2ad9b6abaa51f7d086ce617256a2d4d0a3dc2786a2c60371ac1bb2ae730f613709486869f979bccaae1ab5b8e699ff375ea03accaff2cc65d",
          "sha256": "af70fda7b7e9faf2468972210444c1debb5afb890bb2df22b16c3171d950d631",
          "sha1": "135c4114c305b1dcee7731fcd3653be74d8914fd",
          "md5": "1cf32b1fe6e2d2c105fee4cb96ee4bce"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.4.0-alpha01-versionMetadata.json",
          "url": "tiles-1.4.0-alpha01-versionMetadata.json",
          "size": 69852,
          "sha512": "9cd9d05fa277256e60ce1a2e468ef1ac7705a989ce29dc15818db659f2d08d42d4e6052fa99c535398e35d0d0b632b81a14af5abebc5e13ceb3f94028e6ef296",
          "sha256": "c88a6a91a1509a3d843af26c244d997e43065bacf34ba5d47cf5b22d0ddd5502",
          "sha1": "89f02e2e49e72511246fde4d9d2984d52eaba704",
          "md5": "ea6012dbbb980491a0ed9b3746f9b5dd"
        }
      ]
    }
  ]
}