{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.material",
    "module": "material-icons-extended",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.4.0-alpha03.aar",
          "url": "material-icons-extended-1.4.0-alpha03.aar",
          "size": 32599941,
          "sha512": "a6533ef813402009b53369214dbef0d2efa1719744eb758d3fb88b7c2a99ef9f983067da1be70c21536b6e838f5524fd11d872cc04e14fe1330d51e8af05b6fa",
          "sha256": "006781417ef5c88087bbea82c2bfb6b117d88c15bcd4016692605304c4a5d330",
          "sha1": "37a4bd3dc8d7cbc6d31c123e04565ba4ada7aa40",
          "md5": "74580288584a382321be6426ad2d262c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "material-icons-extended-1.4.0-alpha03.aar",
          "url": "material-icons-extended-1.4.0-alpha03.aar",
          "size": 32599941,
          "sha512": "a6533ef813402009b53369214dbef0d2efa1719744eb758d3fb88b7c2a99ef9f983067da1be70c21536b6e838f5524fd11d872cc04e14fe1330d51e8af05b6fa",
          "sha256": "006781417ef5c88087bbea82c2bfb6b117d88c15bcd4016692605304c4a5d330",
          "sha1": "37a4bd3dc8d7cbc6d31c123e04565ba4ada7aa40",
          "md5": "74580288584a382321be6426ad2d262c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "material-icons-extended-1.4.0-alpha03-sources.jar",
          "url": "material-icons-extended-1.4.0-alpha03-sources.jar",
          "size": 11067229,
          "sha512": "96bf38e9e36d6e4711353256fbd476dd1cf31e788fc7682254ae975ec131f42e9126e2caed038bb4fb3262a6d02075303eaa9579d4d45e9c104f4d30204e6b19",
          "sha256": "01967bebfd54970d5d3eb678852400b652f90a30da8e439c668c7fdcf6b58991",
          "sha1": "f7f634aaf9e00d11c1f8ec3c7e3a364ee67d6f69",
          "md5": "c316a614924d452c10251659a10ad264"
        }
      ]
    }
  ]
}