{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-runtime",
    "version": "2.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6761364"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0-alpha02.aar",
          "url": "room-runtime-2.3.0-alpha02.aar",
          "size": 101414,
          "sha512": "6852d10eee11fc4a77831918a888f3acd9d12638a1c21fc4e6d16a9377e4a50f8d5f4aa2607e35b490730201ae1829948a11e6eeef4df81a4e856394cb3ca878",
          "sha256": "02201f7c3c031f08af764acfa63372454a000677a149be7687afdaa064906b54",
          "sha1": "65259f7a5233c8615af71d645755a76901800922",
          "md5": "8172df41ce5ca9f423647897d0acb39e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.3.0-alpha02"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "room-runtime-2.3.0-alpha02.aar",
          "url": "room-runtime-2.3.0-alpha02.aar",
          "size": 101414,
          "sha512": "6852d10eee11fc4a77831918a888f3acd9d12638a1c21fc4e6d16a9377e4a50f8d5f4aa2607e35b490730201ae1829948a11e6eeef4df81a4e856394cb3ca878",
          "sha256": "02201f7c3c031f08af764acfa63372454a000677a149be7687afdaa064906b54",
          "sha1": "65259f7a5233c8615af71d645755a76901800922",
          "md5": "8172df41ce5ca9f423647897d0acb39e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-runtime-2.3.0-alpha02-sources.jar",
          "url": "room-runtime-2.3.0-alpha02-sources.jar",
          "size": 70661,
          "sha512": "ebaa5921a6a2b21916cf5e25b8266664c0b7ae8d9df7d5caa843b8f2ad7ece04693a8727822f790b51cc9e793b9e6f20d370b4a169d2044a6448ab1aac9f3868",
          "sha256": "7466df70817761f8fbb22866b8b4836e6d6e8ce2cc30de33a20bd6f1ff9f08ef",
          "sha1": "eeadd20a2d2bc8d1ff87ba6061f400c411bd7d0e",
          "md5": "9da70b48ae01cdbb89aed832de13ba6b"
        }
      ]
    }
  ]
}
