{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.8.0-alpha01/annotation-1.8.0-alpha01.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.8.0-alpha01.jar",
          "url": "annotation-jvm-1.8.0-alpha01.jar",
          "size": 55415,
          "sha512": "b90098e3e21ac1d75d0d1b103e80d4676e6003c3800731bc3d8f23c81b7ad59b114ae5ed87081bee147156b92b5814c63469685b783fbc53c9f7d675998ce064",
          "sha256": "db85fa05056717865364804a615d40950c677c12ae9b57cc3944d3468f05040f",
          "sha1": "1683cbbf48ac85f2ca5c2199e55840435351c9f2",
          "md5": "04209526c6e6fb8c5564af099c11ee92"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.8.0-alpha01.jar",
          "url": "annotation-jvm-1.8.0-alpha01.jar",
          "size": 55415,
          "sha512": "b90098e3e21ac1d75d0d1b103e80d4676e6003c3800731bc3d8f23c81b7ad59b114ae5ed87081bee147156b92b5814c63469685b783fbc53c9f7d675998ce064",
          "sha256": "db85fa05056717865364804a615d40950c677c12ae9b57cc3944d3468f05040f",
          "sha1": "1683cbbf48ac85f2ca5c2199e55840435351c9f2",
          "md5": "04209526c6e6fb8c5564af099c11ee92"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotation-jvm-1.8.0-alpha01-sources.jar",
          "url": "annotation-jvm-1.8.0-alpha01-sources.jar",
          "size": 66347,
          "sha512": "0cd62c163bea0f60519c08c5af38ad6ed72352a08fafd953ca7c36fbe90b2934f5db8eff2dcc6d8e57f160b62770b5e8cda5bf897b975e244281a289323d123e",
          "sha256": "16c7326a3c286a32e85005984d206e1d3bbff7a24863b4e67b0d2545e1b94c75",
          "sha1": "61b8218cdefd4e8d5221733f6100940257c11642",
          "md5": "31b30d55ac41775ad282518e63e8c30f"
        }
      ]
    }
  ]
}