{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health",
    "module": "health-services-client",
    "version": "1.1.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13718522"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha05-sources.jar",
          "url": "health-services-client-1.1.0-alpha05-sources.jar",
          "size": 180858,
          "sha512": "92c10577845d4e42260636fb69ae3f3ed6bcbbe5481872b6dcd56353b16bdf37cf37820f1bfbb560a16ba643613bafbcc87283b9b235feaf73efabdfa391072e",
          "sha256": "abc69b20f90ce3a1b55eec7659ca9a94276b6e4f13a3f4d9ace4ff94f2c63996",
          "sha1": "c58bd360d25e78fccecd71a3a62d7133c7867319",
          "md5": "73929f3385bf1bed5e9712c6672862b6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha05.aar",
          "url": "health-services-client-1.1.0-alpha05.aar",
          "size": 589483,
          "sha512": "246af3eaee7879c4923638d96d1f26d4f52820935c4a08ddf4fbb59a52e0ab0f7099ad59bc9db9acf2c841ea79353a18a668d8e577d45bf1674f75e96cf6e08f",
          "sha256": "f2b16ddee818d917e0f2d1cb008acbb5812ce306c848889dcc890b86eac86960",
          "sha1": "6680da2a1e49d1d957618ba42b35162fef779460",
          "md5": "8e2cf084a41d30f4eb5c15651f774ae4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.health",
          "module": "health-services-client-proto",
          "version": {
            "requires": "1.1.0-alpha05"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha05.aar",
          "url": "health-services-client-1.1.0-alpha05.aar",
          "size": 589483,
          "sha512": "246af3eaee7879c4923638d96d1f26d4f52820935c4a08ddf4fbb59a52e0ab0f7099ad59bc9db9acf2c841ea79353a18a668d8e577d45bf1674f75e96cf6e08f",
          "sha256": "f2b16ddee818d917e0f2d1cb008acbb5812ce306c848889dcc890b86eac86960",
          "sha1": "6680da2a1e49d1d957618ba42b35162fef779460",
          "md5": "8e2cf084a41d30f4eb5c15651f774ae4"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha05-versionMetadata.json",
          "url": "health-services-client-1.1.0-alpha05-versionMetadata.json",
          "size": 57521,
          "sha512": "89dfe982410e9d8cd9002e7a6cecc61de08cce9f8f4974416f0055416caa5829372dccead9c51b6034ce6da612bf6ba1a97d3da52ffe96327d6d47fafb5fd13b",
          "sha256": "6fd25cb87bbb19a1d5489413f8a228116475d9cb9df4d261c4ad4f8f0cb25bbb",
          "sha1": "1f713f1a91539aad71690340b9c01edc71a51c3c",
          "md5": "1b5462d9a546d9e746390a4ae0f9416d"
        }
      ]
    }
  ]
}