{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-lifecycle-viewmodel-compose",
    "version": "1.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13808536"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01-sources.jar",
          "url": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01-sources.jar",
          "size": 6415,
          "sha512": "96dbfb4f266c3425f858b09571e20a606d835f5f6d241a73ac5a678da505b5e12e3dca5f2710065527ff8a09920750641399482bbbb46b103ba1a2731a874a44",
          "sha256": "131c0be20ad634049e70099ba91fcdabd5b3391c9f8de373043b25815498fd98",
          "sha1": "0ea48aea470b69d218d0b027df2b667131cae7bd",
          "md5": "b1fd3b8c12e357c827c84f64fb38f865"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-lifecycle-viewmodel",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.54"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01.aar",
          "url": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01.aar",
          "size": 9662,
          "sha512": "f1e40c3346d4010b92396b4a38c097ef63c940dbf4919edcb15968c1e84f9bd22b587c8b34300c66f6ccae769f243d3e3cb08b5d9b6a08360bb2f020eff6d0cb",
          "sha256": "ede117dbcdf7ab0dcacd3d3d138bfbf48e0a7532c9909b837660ead440025411",
          "sha1": "47b2f882b08483d18ac17a7211de8bb19d377ad8",
          "md5": "8434113a8284106a617ad7a45bc0cc6e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-lifecycle-viewmodel",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.54"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01.aar",
          "url": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01.aar",
          "size": 9662,
          "sha512": "f1e40c3346d4010b92396b4a38c097ef63c940dbf4919edcb15968c1e84f9bd22b587c8b34300c66f6ccae769f243d3e3cb08b5d9b6a08360bb2f020eff6d0cb",
          "sha256": "ede117dbcdf7ab0dcacd3d3d138bfbf48e0a7532c9909b837660ead440025411",
          "sha1": "47b2f882b08483d18ac17a7211de8bb19d377ad8",
          "md5": "8434113a8284106a617ad7a45bc0cc6e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01-versionMetadata.json",
          "url": "hilt-lifecycle-viewmodel-compose-1.3.0-beta01-versionMetadata.json",
          "size": 952,
          "sha512": "0bf56e8300892c291181ea402265917dd2e7f35aafe2ca27aa5d0128cb3ce2ee0a14ba088d88f614b13287c22ac32fc87395eab52d6191d6f4c4ff0cb61ff1c4",
          "sha256": "c75f164270731826f22a492788e88d896f575adb6c65f481d6206dea95f58d05",
          "sha1": "bda9c6283b1814a3eda70f6954f0d8a81ea80b6b",
          "md5": "d96892e74a6c78e9b258463aa5961bf7"
        }
      ]
    }
  ]
}