{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-testing",
    "version": "2.4.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "room-testing-2.4.0-alpha05.aar",
          "url": "room-testing-2.4.0-alpha05.aar",
          "size": 13601,
          "sha512": "9fbe79032f052ef6ead0551669c9dd30faa4dc8bd2143f3a542d12b11e72f08fb168c2cd9d8614ad19ded21c9cfae012befaeca666b79c011523206097db17ca",
          "sha256": "8ffaf902cf1e26bd2c8a9a0ff92be9b14d59e728b9f89bf7ef7a68d1a88b8eca",
          "sha1": "ab394943d42b34e2de5615902ed45796341febf4",
          "md5": "f60ea1ba254edfd60f1c22c90284aab2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.arch.core",
          "module": "core-runtime",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.4.0-alpha05"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.12"
          }
        }
      ],
      "files": [
        {
          "name": "room-testing-2.4.0-alpha05.aar",
          "url": "room-testing-2.4.0-alpha05.aar",
          "size": 13601,
          "sha512": "9fbe79032f052ef6ead0551669c9dd30faa4dc8bd2143f3a542d12b11e72f08fb168c2cd9d8614ad19ded21c9cfae012befaeca666b79c011523206097db17ca",
          "sha256": "8ffaf902cf1e26bd2c8a9a0ff92be9b14d59e728b9f89bf7ef7a68d1a88b8eca",
          "sha1": "ab394943d42b34e2de5615902ed45796341febf4",
          "md5": "f60ea1ba254edfd60f1c22c90284aab2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-testing-2.4.0-alpha05-sources.jar",
          "url": "room-testing-2.4.0-alpha05-sources.jar",
          "size": 7116,
          "sha512": "2491062cebf66bf64f6e726e351eeb02c6ead6c0ed7627e50e22a7dec8d4d7b8c91b88cf96eabfd0a15fb41e0d1c56f91af8e7cc49f469ca99e6d23292a1baff",
          "sha256": "e045aefd14e4111933799c45d583d7c97555431c4daf31d35697c95f2ebcdc21",
          "sha1": "026be93d7a7002bd9d8ff73c6333a47d26c703be",
          "md5": "8b7bf0ffdaeb7306d3d27506b7edc0f8"
        }
      ]
    }
  ]
}
