{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-remoteviews",
    "version": "1.1.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.1.0-beta01.aar",
          "url": "core-remoteviews-1.1.0-beta01.aar",
          "size": 55330,
          "sha512": "e9fe85ea256470afe9eb4a4d7f352411538d0ff434ed4627b356597b3678489d5604d189c33fd42203e7f8b60a1f63e4d362abc464ddbb2bfc6dd49dca3a1165",
          "sha256": "bcccac8404bba2c1a7ba66c3ab38540d86908dc07c6f0cecfc458fb335024861",
          "sha1": "96c6f839ca7d9b8ff493727152155f4329f59c20",
          "md5": "3fff8d546c81f36e42d7d955eb55b165"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.1.0-beta01.aar",
          "url": "core-remoteviews-1.1.0-beta01.aar",
          "size": 55330,
          "sha512": "e9fe85ea256470afe9eb4a4d7f352411538d0ff434ed4627b356597b3678489d5604d189c33fd42203e7f8b60a1f63e4d362abc464ddbb2bfc6dd49dca3a1165",
          "sha256": "bcccac8404bba2c1a7ba66c3ab38540d86908dc07c6f0cecfc458fb335024861",
          "sha1": "96c6f839ca7d9b8ff493727152155f4329f59c20",
          "md5": "3fff8d546c81f36e42d7d955eb55b165"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-remoteviews-1.1.0-beta01-versionMetadata.json",
          "url": "core-remoteviews-1.1.0-beta01-versionMetadata.json",
          "size": 28056,
          "sha512": "c138f2a0531b0b003e6faed04a49a913cbdfd7b85307509a3cddcc313b1b980261f3421475f461528ee90fdd1625b51964497f26d5cf0c96f64d418be9407947",
          "sha256": "268dfc74cd1e65c1d11e2d395243301d8cbf87a42d06526072db9f62d6211fa9",
          "sha1": "4f9db05b8075b71e329d7058c2c66fb324eceeef",
          "md5": "004664c9215f108e5cf22c172bf87ec5"
        }
      ]
    }
  ]
}