version: "1.8.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-android"
    version: "1.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-jvmstubs"
    version: "1.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-linuxx64stubs"
    version: "1.8.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.8.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.foundation"
group_id: "androidx.compose.foundation"
artifact_id: "foundation-layout"
path: "/compose/foundation/foundation-layout"
sha: "5aee86cca13a10a97d93540560cef9cb5ffa21ff"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.foundation-foundation-layout-all-12431612-1.8.0-alpha03.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation"
    version: "1.8.0-alpha03"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
