version: "1.6.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-android"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-iosarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-iossimulatorarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-iosx64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-jvm"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-linuxarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-linuxx64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-macosarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-macosx64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-tvosarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-tvossimulatorarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-tvosx64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-watchosarm32"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-watchosarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-watchossimulatorarm64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-core-watchosx64"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.window"
group_id: "androidx.window"
artifact_id: "window-core"
path: "/window/window-core"
sha: "f19a0312b5daaa98d1908d96fa15051112c7dbf1"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.window-window-core-all-12265946-1.6.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.window"
    artifact_id: "window"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-java"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-rxjava2"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-rxjava3"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.window"
    artifact_id: "window-testing"
    version: "1.6.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
