{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0-alpha03.aar",
          "url": "window-1.2.0-alpha03.aar",
          "size": 346218,
          "sha512": "b484868981ef86417da67d412211854e98202b756c45f29a6b0923f6df61528ecff6885edaf5b1d0eee2a40375ac443bec40ec0c0035ebf0f9470de072ebcdf6",
          "sha256": "42f4ba389750adfa0493899038ecf2e4fc5ad53186c40a7250d24cb74212a70d",
          "sha1": "db86af136f13769f545483e77b11dcf24f4b63dc",
          "md5": "7156cf6608cc028e7396cb439327bb3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0-alpha03.aar",
          "url": "window-1.2.0-alpha03.aar",
          "size": 346218,
          "sha512": "b484868981ef86417da67d412211854e98202b756c45f29a6b0923f6df61528ecff6885edaf5b1d0eee2a40375ac443bec40ec0c0035ebf0f9470de072ebcdf6",
          "sha256": "42f4ba389750adfa0493899038ecf2e4fc5ad53186c40a7250d24cb74212a70d",
          "sha1": "db86af136f13769f545483e77b11dcf24f4b63dc",
          "md5": "7156cf6608cc028e7396cb439327bb3c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0-alpha03-sources.jar",
          "url": "window-1.2.0-alpha03-sources.jar",
          "size": 146255,
          "sha512": "fd12b1df4f3148df8263dd1c6a9393773e1be073fc9a8660192a5c3037a859d4f7e0f9781a085d5c3dde26260e6f835524c89ce3b2d35dca1d4c69c9915c9ddc",
          "sha256": "75f167ac830ad869ce64c1826f7d39985cef497382b226373098675f9f139df8",
          "sha1": "2c7dffccbb685797d2b9ecddbb74e36efac5eaed",
          "md5": "b4025c48c66c52dd92dd1ef119b37030"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.2.0-alpha03-versionMetadata.json",
          "url": "window-1.2.0-alpha03-versionMetadata.json",
          "size": 24715,
          "sha512": "c517c34f900d56aca49547407cda23f6497e91e03ea1380ea6bfbad1fd054636d7f626cc0327221ad21028d2013127235f957aa01ecce55cc64eef5960cf260c",
          "sha256": "df28e0fc3d35277a5dada8ba2e66685dacbd4b294e8dd27ea8c1ff8a717d69bf",
          "sha1": "d8e71c2ace4c3951fe773faad7c3910ed3c7264e",
          "md5": "e89d796e8cdcdd98538d1c7017365c69"
        }
      ]
    }
  ]
}