version: "1.0.0-alpha10"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.12.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.customview"
    artifact_id: "customview-poolingcontainer"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common"
    version: "2.6.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.sdkruntime"
    artifact_id: "sdkruntime-client"
    version: "1.0.0-alpha14"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-core"
    version: "1.0.0-alpha10"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.ui"
group_id: "androidx.privacysandbox.ui"
artifact_id: "ui-client"
path: "/privacysandbox/ui/ui-client"
sha: "073ba66e837b493a7e0136379507f9fbb33f2ce9"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.ui-ui-client-all-12565334-1.0.0-alpha10.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-core"
    version: "1.0.0-alpha10"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-provider"
    version: "1.0.0-alpha10"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
