{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.4.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha02.aar",
          "url": "compose-material-1.4.0-alpha02.aar",
          "size": 1188883,
          "sha512": "64c1fa328582075c1da8aaa6dc0e05404b94656c677d3ee1c2c9bc96b52e18d96189682a4226d15cfe218adbf89e6a50f5dfd89e199028e9e4eae212fd6f471d",
          "sha256": "e3f8a98d4e65eccff1a65fac827af49185c59347b8e29e6f10d45cda4884b683",
          "sha1": "2d160b1dfdc3e53f197fbc3102fd4e307333654f",
          "md5": "084a4246d96266f5b097dc07553f5498"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha02.aar",
          "url": "compose-material-1.4.0-alpha02.aar",
          "size": 1188883,
          "sha512": "64c1fa328582075c1da8aaa6dc0e05404b94656c677d3ee1c2c9bc96b52e18d96189682a4226d15cfe218adbf89e6a50f5dfd89e199028e9e4eae212fd6f471d",
          "sha256": "e3f8a98d4e65eccff1a65fac827af49185c59347b8e29e6f10d45cda4884b683",
          "sha1": "2d160b1dfdc3e53f197fbc3102fd4e307333654f",
          "md5": "084a4246d96266f5b097dc07553f5498"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha02-sources.jar",
          "url": "compose-material-1.4.0-alpha02-sources.jar",
          "size": 172581,
          "sha512": "733595d24002480a895ea41cac3b194dcde08e9353809ce5bc23fc521a89f3f00f926bc5f79bf8cb219f94deaacb9e069edbad75f837fcc63e0870e7ecd20079",
          "sha256": "f46207e870bfdbb0b263d9b228f5750880e4ea9774dbac463dbbfca81db48e5d",
          "sha1": "c9b43d24f85c012165c0ad30c29b198d20457d20",
          "md5": "2d43c6bbfe10e3d97fc387ff24da1ebc"
        },
        {
          "name": "compose-material-1.4.0-alpha02-samples-sources.jar",
          "url": "compose-material-1.4.0-alpha02-samples-sources.jar",
          "size": 30732,
          "sha512": "cb1bf53247ed5e4d674ec60d7d5222bde75511e1a57fea9fd9d63ec95f97025f946dde5c28958bd4c46031bee4245abef83dcbc9a69c1160f22c50632a30a55e",
          "sha256": "ed1d70372861334ef1f7308d67fc09a3989ba7fbd3152f446e75e14ed970da07",
          "sha1": "f827b24338bc3b19529a395063a9d4343c01908e",
          "md5": "8ac94f65e1b67841a4e2c4bc0c8c3193"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha02"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.4.0-alpha02-versionMetadata.json",
          "url": "compose-material-1.4.0-alpha02-versionMetadata.json",
          "size": 78236,
          "sha512": "9abbde5afe9c9ac781b9e63cb4197f8354634aafdef28b4440b389b0bb267eea51ec2a969468883be69d62adc63fcbc8a25060e23a4464b928d7b4936535d35a",
          "sha256": "ad155d691ae0a0927d8dfd93a7cee1a0a6eb2d2cdd4ee956531b138e51e73fcd",
          "sha1": "43ec09d9c496f50914584bd1d8be0442ed08199d",
          "md5": "59a4d882ddf13b2695ceca1f8bff0d20"
        }
      ]
    }
  ]
}