{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch-builtin-types",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-builtin-types-1.1.0-alpha04.aar",
          "url": "appsearch-builtin-types-1.1.0-alpha04.aar",
          "size": 96354,
          "sha512": "db1476405cbe9652d4d5d95e307d329ce582b5454fe2273823e0feb2ee2c244241aafe9a896660a3baa782cdf616c1f846ffefcb0ed9c24b202167268172521c",
          "sha256": "c1e5746ead7f28e9402fdf79db0524815d8192604f5bb22355d94545559c4a04",
          "sha1": "a89ec520a25c7af1bf82b72b5a0624210ec61c19",
          "md5": "431cec5b7378c2be16f36f78ffa39291"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-builtin-types-1.1.0-alpha04.aar",
          "url": "appsearch-builtin-types-1.1.0-alpha04.aar",
          "size": 96354,
          "sha512": "db1476405cbe9652d4d5d95e307d329ce582b5454fe2273823e0feb2ee2c244241aafe9a896660a3baa782cdf616c1f846ffefcb0ed9c24b202167268172521c",
          "sha256": "c1e5746ead7f28e9402fdf79db0524815d8192604f5bb22355d94545559c4a04",
          "sha1": "a89ec520a25c7af1bf82b72b5a0624210ec61c19",
          "md5": "431cec5b7378c2be16f36f78ffa39291"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-builtin-types-1.1.0-alpha04-sources.jar",
          "url": "appsearch-builtin-types-1.1.0-alpha04-sources.jar",
          "size": 36150,
          "sha512": "a08c6ac8585199423af00be5930111af2fa70d6637f430d3be1b51edb6e66311d373884d0511f7beda21b62fcda660bb5cb5f97148a1e2857943903d01ec3d5e",
          "sha256": "996c96be49d61b4dca80c8eb08579b0a2db2a218ba36f1c02ecaae2137cb986d",
          "sha1": "3333e7e5ca1aa64ee66156d27cf9566ece274d57",
          "md5": "df528f0f09961016fa2294afe98dbaeb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-builtin-types is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-builtin-types-1.1.0-alpha04-versionMetadata.json",
          "url": "appsearch-builtin-types-1.1.0-alpha04-versionMetadata.json",
          "size": 22079,
          "sha512": "896871d2b78daf423ea3380bb022708d472cd6ab20c17f99c73c8451044c46df081722a79b277d91d484560b0d911c73c40c16a12ebf7860db388056db4dd594",
          "sha256": "486267a15b2fe44e08ee0ab73574a123ad3bb3caadaeb47d3b94b5dcd90a2692",
          "sha1": "ad380f455783bff4e241fa86da2a9e63dd700372",
          "md5": "f16a5e0f65bbab5d1283851f756da2bc"
        }
      ]
    }
  ]
}