{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions",
    "module": "extensions",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12773825"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-1.6.0-alpha01-sources.jar",
          "url": "extensions-1.6.0-alpha01-sources.jar",
          "size": 71868,
          "sha512": "1a3412c27351c3a8abd977e8c01c2564342df1c1194ed8152042298a49770215cc6b5b510c66d94c8b6962497a43daa94c92207ec5f671fde0e997592661196f",
          "sha256": "7afbf3f288703bc346ce258d1ca4a36dca7e514c7ebce0a59fc6c80e536437a8",
          "sha1": "9cddd1b31bad4859b67193c89386fd08f9f64489",
          "md5": "b5323bb562d1f413a3f3a3ccfc280ca2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.6.0-alpha01.aar",
          "url": "extensions-1.6.0-alpha01.aar",
          "size": 75761,
          "sha512": "fee8c0b817b62eab570896eebefb604a8a970983bcfa7b49cdb065426767090c589d9bf921c4be76d810a8b2a091970cd86f5875cb9ee498b3d2fc56beb0b9e3",
          "sha256": "6f0d374e69ec2eb5470ea59f9a1c6aa175fb221d47fb4a8a5b51c60004ff0d4b",
          "sha1": "2ebc322ef6c9a81e6b905f7dd734ff7bc3f99491",
          "md5": "597c5139f87fdf459d14b3c519b831dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.6.0-alpha01.aar",
          "url": "extensions-1.6.0-alpha01.aar",
          "size": 75761,
          "sha512": "fee8c0b817b62eab570896eebefb604a8a970983bcfa7b49cdb065426767090c589d9bf921c4be76d810a8b2a091970cd86f5875cb9ee498b3d2fc56beb0b9e3",
          "sha256": "6f0d374e69ec2eb5470ea59f9a1c6aa175fb221d47fb4a8a5b51c60004ff0d4b",
          "sha1": "2ebc322ef6c9a81e6b905f7dd734ff7bc3f99491",
          "md5": "597c5139f87fdf459d14b3c519b831dc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "extensions-1.6.0-alpha01-versionMetadata.json",
          "url": "extensions-1.6.0-alpha01-versionMetadata.json",
          "size": 24870,
          "sha512": "66a027d75f2aed2439bb3ad84419a0126323259de63491d5f9ff3dd7a07cee3be0a8182cc645c77a3c443a9cb56ed9633119f43b141e3d7b11a35987efbf056d",
          "sha256": "9381f860e028e218d0eac84f035899736386fb2881df43b5d76450434fd7a868",
          "sha1": "8d8815fab2fd000d93e78c47e8577184b03e4de9",
          "md5": "3971d6dc84830aed083010f7e54cb6b3"
        }
      ]
    }
  ]
}