{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views-helper",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.0.0-alpha03.aar",
          "url": "emoji2-views-helper-1.0.0-alpha03.aar",
          "size": 21400,
          "sha512": "96bb913a647aea5c97ed3c9ac0561237105fedf99f66338199ec894f6df4cd7653adccb7cc73e1fbe92f716d6fe99a737b0f0e84b731b4e0dcbe5737127f187d",
          "sha256": "3ac22dac43105d65c57785c3aacda77d312ae04ebb6df1e38cc1e10bec28e7b3",
          "sha1": "df24a00481b4d6c7307c7d7f05c5edf6dd4aa7ca",
          "md5": "ab9d0bc8eaed7a97bfa9a9c5588c0c70"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.0.0-alpha03"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.0.0-alpha03.aar",
          "url": "emoji2-views-helper-1.0.0-alpha03.aar",
          "size": 21400,
          "sha512": "96bb913a647aea5c97ed3c9ac0561237105fedf99f66338199ec894f6df4cd7653adccb7cc73e1fbe92f716d6fe99a737b0f0e84b731b4e0dcbe5737127f187d",
          "sha256": "3ac22dac43105d65c57785c3aacda77d312ae04ebb6df1e38cc1e10bec28e7b3",
          "sha1": "df24a00481b4d6c7307c7d7f05c5edf6dd4aa7ca",
          "md5": "ab9d0bc8eaed7a97bfa9a9c5588c0c70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "emoji2-views-helper-1.0.0-alpha03-sources.jar",
          "url": "emoji2-views-helper-1.0.0-alpha03-sources.jar",
          "size": 17124,
          "sha512": "a0aa98f0adce55040195ef74ad6bbf02ff579c0868a5086a91fd70387c3653a42c7847a21b9ba0050c44e94aa0157ad03fb3f661cd6b3395897eeda339ad333e",
          "sha256": "e70b96a2bcd53a14438998c9ca8ced8738094628f00de245d99acdb95073ae7b",
          "sha1": "fe5f4405ece74c236561cc0ccf56dc159af57a6c",
          "md5": "1ad31eb2d36a8cf72bb63b4829de2233"
        }
      ]
    }
  ]
}
