version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.7.5"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-compose-android"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-compose-jvmstubs"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-compose-linuxx64stubs"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13679201"
group_id: "androidx.savedstate"
artifact_id: "savedstate-compose"
path: "/savedstate/savedstate-compose"
sha: "fc138f68f0df68e213e6fba0926666a8826d5d78"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.savedstate-savedstate-compose-all-13679201-1.4.0-alpha01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-ktx"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
kmp_children: "jvmstubs"
kmp_children: "linuxx64stubs"
test_module_names: ":savedstate:savedstate-compose:jvmStubsTest"
test_module_names: ":savedstate:savedstate-compose:linuxx64StubsTest"
test_module_names: "savedstate-savedstate-composeandroidInstrumentedTest.xml"
test_module_names: ":savedstate:savedstate-compose:testAndroidHostTest"
