{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation-experimental",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01-sources.jar",
          "url": "annotation-experimental-1.4.0-rc01-sources.jar",
          "size": 5380,
          "sha512": "de91407b5044ad565b732692afac6d1d0dc5ae4ed0e37a81b804deec14d46574e5240fbe5c5da6bf7d2863bfd14f1b7e851f954bea97c7e69d1eb94dcca76c11",
          "sha256": "318f2d29e7c3037c601cf1ba19d60b8093e6db575815150f75b31282e4c05062",
          "sha1": "6b04796890cdf70edd292d53790253401d4b36bd",
          "md5": "0ca7d7665a5b2d0f5ad8b27872a85d43"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01.aar",
          "url": "annotation-experimental-1.4.0-rc01.aar",
          "size": 39611,
          "sha512": "14d2285464584dc2e76a0f163f0f7d096107ee4dbadee45394214e14ca5e048d698ba33c62919c9bad457c05590274435beda4719973c0a015c1077132b9d9a8",
          "sha256": "7bf74af817a3a8c77049cc94270fd28f8f500782e39f2840e146f03842ea3da8",
          "sha1": "6b5cf14d6369ea664b6d07ff8e059d7b5917f283",
          "md5": "4605e9404b6b46cd0a30e4bf1ba71f95"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01.aar",
          "url": "annotation-experimental-1.4.0-rc01.aar",
          "size": 39611,
          "sha512": "14d2285464584dc2e76a0f163f0f7d096107ee4dbadee45394214e14ca5e048d698ba33c62919c9bad457c05590274435beda4719973c0a015c1077132b9d9a8",
          "sha256": "7bf74af817a3a8c77049cc94270fd28f8f500782e39f2840e146f03842ea3da8",
          "sha1": "6b5cf14d6369ea664b6d07ff8e059d7b5917f283",
          "md5": "4605e9404b6b46cd0a30e4bf1ba71f95"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "annotation-experimental-1.4.0-rc01-versionMetadata.json",
          "url": "annotation-experimental-1.4.0-rc01-versionMetadata.json",
          "size": 1287,
          "sha512": "34e5b2bb9e8e57bb48de87c35da3e20276c85453804a6ba5c073b3a3ec553e1e6b9cc0e783da02278dcc445143a5eac5bc1851e0f1ee0321d85e18c841ce45b5",
          "sha256": "5c3e7593bdbd619e45f857f18051156b0163c7d26a4886f929a706668d27d5e8",
          "sha1": "49c73908cb59481260427de1bed1de97e1c94dd9",
          "md5": "6234d9bf6ddf64308dc62ed8acf51ea0"
        }
      ]
    }
  ]
}