version: "1.4.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "b37cc2a43ac31bd50a923bb3c27abc4ec528651d"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-annotation-11322178.zip"
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-11322178-1.4.0-rc01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
