version: "1.4.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "251347cb268ddfa1d319156f5fe5d483dffe0dbb"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-11525184-1.4.0-rc01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
should_publish_docs: true
