{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-tooling/1.10.0-alpha01/ui-tooling-1.10.0-alpha01.module",
    "group": "androidx.compose.ui",
    "module": "ui-tooling",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13770307"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling.aar",
          "url": "ui-tooling-android-1.10.0-alpha01.aar",
          "size": 198128,
          "sha512": "81476a9ed87bc0eb5d037da35c610d58c3103bbdb3682f05a0b5afa6eb55c81fbca21e8332187ab90e087b7aa69770c632bc4ad803e02681002e7da1952928b0",
          "sha256": "b3c1a0d22617df50d286674992b8970ade3d3b1ef7a553177d5bb53852c573e5",
          "sha1": "9cc57b2cafbd69374a5bc42e10123d4f3b54e24e",
          "md5": "0096bb2379e267151ccc602dcb4f199f"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-tooling.aar",
          "url": "ui-tooling-android-1.10.0-alpha01.aar",
          "size": 198128,
          "sha512": "81476a9ed87bc0eb5d037da35c610d58c3103bbdb3682f05a0b5afa6eb55c81fbca21e8332187ab90e087b7aa69770c632bc4ad803e02681002e7da1952928b0",
          "sha256": "b3c1a0d22617df50d286674992b8970ade3d3b1ef7a553177d5bb53852c573e5",
          "sha1": "9cc57b2cafbd69374a5bc42e10123d4f3b54e24e",
          "md5": "0096bb2379e267151ccc602dcb4f199f"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4-accessibility",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-lint",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "ui-tooling is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-tooling-android-1.10.0-alpha01-sources.jar",
          "url": "ui-tooling-android-1.10.0-alpha01-sources.jar",
          "size": 56196,
          "sha512": "d4c8906b2e3dd3da8f92e1c99f8872a9cbe9755863aba6f98fbe7753470d8c957f09192b68f48aade69836d2aae6cb2b1254d3083e2c367f152a21096ca1354a",
          "sha256": "a8db0e03e925ef237e612612e33f55674da0a2f22c42e70da704bf1ebed8c625",
          "sha1": "7f8ceb75e31cb72f980bdd6dbc514080705d1a93",
          "md5": "27e98b74302f1219817dbb05570a09cc"
        },
        {
          "name": "ui-tooling-1.10.0-alpha01-samples-sources.jar",
          "url": "ui-tooling-android-1.10.0-alpha01-samples-sources.jar",
          "size": 29628,
          "sha512": "d67bfb3caafb93eae5627ea9f92ffadd1c3cea2db1a67cb09b11b1176b391f8addff50099b4ad5a86e43f2f9a5da75a6d5e261d3d98fabcf76d3b0dcafdfa499",
          "sha256": "3ae4ccd9a81b8b07236a82c7d902778aab1eeed7fdb95d729e3f1cedc3628c80",
          "sha1": "923c4b569772330f6c6554bf1b4ec7a9ad0574d4",
          "md5": "63ecb7f82b659fc7a1fdaf851d896077"
        }
      ]
    }
  ]
}