{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01-sources.jar",
          "url": "glance-appwidget-1.2.0-alpha01-sources.jar",
          "size": 133921,
          "sha512": "4d528b8fa06fb14255a0d144fbfc000cc4a5a0ac4f88b887e8336a0b0486977bf51d4d59f1ad651636fdccd3ebcf027fa64a6383b0e8de5369c598d25e33738d",
          "sha256": "f4ba6d62ed5bfa26dbb71c29394a59e82100336e63fa8c37388bfce00646a0cc",
          "sha1": "d08fdc9ecbcbd04ea8dad481dbb02935bf78632d",
          "md5": "8090c24befd904aeee52885b1d2169b3"
        },
        {
          "name": "glance-appwidget-1.2.0-alpha01-samples-sources.jar",
          "url": "glance-appwidget-1.2.0-alpha01-samples-sources.jar",
          "size": 7272,
          "sha512": "1e33938e09c091878dfddd7b339b7dd174e014986dae20bc76dab0e3e065f0af94a3be971afe4ead111fe7837967d186d613d924e113ec915f49f54a6289d3c4",
          "sha256": "10c3ec48062d0d7e1616ece5b9e6ea3315a1977ae2eb82fb4d710503c05b8232",
          "sha1": "dad13940ea9ca608247e823ed9d3d292fad2c42e",
          "md5": "29810390862303555622711dc083681a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01.aar",
          "url": "glance-appwidget-1.2.0-alpha01.aar",
          "size": 1303190,
          "sha512": "484b2ec48a0e07a73e86284f8d98f60628f1f3e93c5ee936f61738dfde24e6a74fe8703c88dbc9109dbb1bc5e8a883f697cbc019e2eb2db5f734396136b52799",
          "sha256": "6d581498060275abc4b106fcccec0022d3279109a3646eac321d9bfa49ed7700",
          "sha1": "7c22ec4c2d21a8222f4a2869a072832cfce7162c",
          "md5": "6c7598ff9d72f817eb419c5f6bb90dea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-remoteviews",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01.aar",
          "url": "glance-appwidget-1.2.0-alpha01.aar",
          "size": 1303190,
          "sha512": "484b2ec48a0e07a73e86284f8d98f60628f1f3e93c5ee936f61738dfde24e6a74fe8703c88dbc9109dbb1bc5e8a883f697cbc019e2eb2db5f734396136b52799",
          "sha256": "6d581498060275abc4b106fcccec0022d3279109a3646eac321d9bfa49ed7700",
          "sha1": "7c22ec4c2d21a8222f4a2869a072832cfce7162c",
          "md5": "6c7598ff9d72f817eb419c5f6bb90dea"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01-versionMetadata.json",
          "url": "glance-appwidget-1.2.0-alpha01-versionMetadata.json",
          "size": 23917,
          "sha512": "eb1fb5732d7cbedf54f4d5f7467addad75df6455a32d6cc1ba94de6399c0c7c8e967ffaa49d4933487a0f0b93490078b0412581a43a14fa0dff1c3b68c19d910",
          "sha256": "85e3ca57557646e42a3f81242475a5fd5dea608ee8a3278d53708cb15eb74c05",
          "sha1": "c94b07ff2ea64109306b99e95132f03040973162",
          "md5": "2f8bb190079778b0fd617e1240bc7dc9"
        }
      ]
    }
  ]
}