{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-appwidget",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13381033"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01-sources.jar",
          "url": "glance-appwidget-1.2.0-alpha01-sources.jar",
          "size": 137297,
          "sha512": "3b48757b98c7da7ca09c853f300fc4ce7d350c302954d6304af63f947771b56eb38823f1e69b82278cfcb7d04bd69e08837ff96e98e2c74f01a4308f08ef4b00",
          "sha256": "031f5123d2b0e351c4ed51884d4c558c437c345ec8831525a83731c6b9f05c52",
          "sha1": "1bef80b4907234c21329ff0c61fb20eb8d160b88",
          "md5": "109eb34130a195ca60606ceb50941f36"
        },
        {
          "name": "glance-appwidget-1.2.0-alpha01-samples-sources.jar",
          "url": "glance-appwidget-1.2.0-alpha01-samples-sources.jar",
          "size": 7643,
          "sha512": "66b6cab65ab972012a0c48555b5098aa7aa35703899fa8cf5252f53730eb1073d317e59afc1914ff09cbbef832139438e86e0952a2e2e7038a2c4176d39e8826",
          "sha256": "399d9e76edd819165de1ef4ddebf35e557a65a69058bb51fb6c332eb7b2e1140",
          "sha1": "1c90dac5652c742ae616908bfd40b9f077100374",
          "md5": "10f86f4c3f739cdfd335cba8ac50f3d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01.aar",
          "url": "glance-appwidget-1.2.0-alpha01.aar",
          "size": 1227461,
          "sha512": "ae0006f6259f0c28f6ed05529f89d0c80496b4cdd85e64fcf430ad0ad6c769c9acfae2d51fbd71b962305ced6fae4c520efe4229624d65499aa357a57ea27508",
          "sha256": "8bc81751c3de25c368b99a50481380ab5ccdb0442a443014ed4e4ff1e7d452bc",
          "sha1": "e0062000180ed59e2b49f134767b2621f2b8ee41",
          "md5": "dc0b5bf5eef147ff16fd4ef82969506c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.4.3"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-remoteviews",
          "version": {
            "requires": "1.1.0-rc01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01.aar",
          "url": "glance-appwidget-1.2.0-alpha01.aar",
          "size": 1227461,
          "sha512": "ae0006f6259f0c28f6ed05529f89d0c80496b4cdd85e64fcf430ad0ad6c769c9acfae2d51fbd71b962305ced6fae4c520efe4229624d65499aa357a57ea27508",
          "sha256": "8bc81751c3de25c368b99a50481380ab5ccdb0442a443014ed4e4ff1e7d452bc",
          "sha1": "e0062000180ed59e2b49f134767b2621f2b8ee41",
          "md5": "dc0b5bf5eef147ff16fd4ef82969506c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-appwidget is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-appwidget-1.2.0-alpha01-versionMetadata.json",
          "url": "glance-appwidget-1.2.0-alpha01-versionMetadata.json",
          "size": 26036,
          "sha512": "46e210614369dcef214d5e597153526a6ffe80c3c55d80508067c6d88f9ffd9ae51528d976dd1e43fdaf74643efa67795ed788ffeab26bef7a50b3df4e72f2ee",
          "sha256": "85f91a85e1709bba200e96e7dd5cd63f3d9d2a76c2c8067b579878a2dc44d45b",
          "sha1": "e2aa15ec8f38142fa9fe0900a8d689b5e96eb56a",
          "md5": "2379ec59fb0479519d45265d2f96971c"
        }
      ]
    }
  ]
}