version: "1.0.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.12.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.graphics"
group_id: "androidx.graphics"
artifact_id: "graphics-path"
path: "/graphics/graphics-path"
sha: "5017fc891e879c6c32f7bb37057f5051fa2aa4bd"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-graphics-11149496.zip"
project_zip_path: "per-project-zips/androidx.graphics-graphics-path-all-11149496-1.0.0-beta01.zip"
kotlin_version: "1.9.20"
dependency_constraint_list {
}
