version: "1.3.0-alpha05"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-android"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-desktop"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-iosarm64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-iossimulatorarm64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-iosx64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-linuxarm64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-linuxx64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-macosarm64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-macosx64"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.savedstate"
group_id: "androidx.savedstate"
artifact_id: "savedstate"
path: "/savedstate/savedstate"
sha: "1d85a4c4bfb2573264fd25efd031e9366f8a33d8"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.savedstate-savedstate-all-12640564-1.3.0-alpha05.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-ktx"
    version: "1.3.0-alpha05"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "android"
kmp_children: "desktop"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "macosx64"
kmp_children: "macosarm64"
