version: "1.3.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.5.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.credentials"
group_id: "androidx.credentials"
artifact_id: "credentials"
path: "/credentials/credentials"
sha: "9186814436774218f17ea8489ea8cf9db1e7e832"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.credentials-credentials-all-11622509-1.3.0-alpha02.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
  dependency {
    group_id: "androidx.credentials"
    artifact_id: "credentials-play-services-auth"
    version: "1.3.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
