version: "1.3.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.5.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.credentials"
group_id: "androidx.credentials"
artifact_id: "credentials"
path: "/credentials/credentials"
sha: "457df361400255dbb9277b03559d6722ff0ed753"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.credentials-credentials-all-11589393-1.3.0-alpha02.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
  dependency {
    group_id: "androidx.credentials"
    artifact_id: "credentials-e2ee"
    version: "1.3.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.credentials"
    artifact_id: "credentials-play-services-auth"
    version: "1.3.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
