{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.percentlayout",
    "module": "percentlayout",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "percentlayout-1.1.0-alpha01.aar",
          "url": "percentlayout-1.1.0-alpha01.aar",
          "size": 13305,
          "sha512": "8456b9de50d94457965c0de53c473436a3f9dab78cf672421fca02bcb38dca030c6c6aa523ebaca064290ede86a5878e741beff747475d29bda1666ae08c14b2",
          "sha256": "87cdf767039e75fb059887a6e7d344b1bd22275a92dd2fbf365f3d7e918fa9fb",
          "sha1": "9ca89c2c33c233e023e8b8ad553c2e58eac743c7",
          "md5": "1bd74120964227d32f93edaefc1fa348"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "percentlayout-1.1.0-alpha01.aar",
          "url": "percentlayout-1.1.0-alpha01.aar",
          "size": 13305,
          "sha512": "8456b9de50d94457965c0de53c473436a3f9dab78cf672421fca02bcb38dca030c6c6aa523ebaca064290ede86a5878e741beff747475d29bda1666ae08c14b2",
          "sha256": "87cdf767039e75fb059887a6e7d344b1bd22275a92dd2fbf365f3d7e918fa9fb",
          "sha1": "9ca89c2c33c233e023e8b8ad553c2e58eac743c7",
          "md5": "1bd74120964227d32f93edaefc1fa348"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "percentlayout-1.1.0-alpha01-sources.jar",
          "url": "percentlayout-1.1.0-alpha01-sources.jar",
          "size": 11165,
          "sha512": "a59b5f34e6f8751dcf94794f4de6732e6d135e088becb3eba434ae5a455638e57e78397df5d03480856841341463e7158eb39e650c92041c033d73cd2df72ebf",
          "sha256": "f8486765b1409524ebe594edcc9cecd264fcfa377107b96c599a3128721f2838",
          "sha1": "a10000cdcd18b9a187b90af6d6b9e928eb850f9b",
          "md5": "b3ecd976c129924707634b4016c4f594"
        }
      ]
    }
  ]
}