{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.sdkruntime",
    "module": "sdkruntime-core",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13718522"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18-sources.jar",
          "url": "sdkruntime-core-1.0.0-alpha18-sources.jar",
          "size": 36485,
          "sha512": "a8bf8cdf03bec187e80f1baab09b5a53d8fee0df1aaf207850e14789d6e9959f698a38c0845f0a9c16338d312dd913ea61141587493721a72ea42688ab93fd70",
          "sha256": "55ebaa50a006e937f092054c2b592de9cf467080a68fee2e06322ed439c90a12",
          "sha1": "603ae5d8bd520231f62f53c2aa6386474eddb4e1",
          "md5": "11157980248307db9e834bbd9b4fa31c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18.aar",
          "url": "sdkruntime-core-1.0.0-alpha18.aar",
          "size": 76557,
          "sha512": "32a7d368a511d5bf61ae54e21825aadac37fca5b5fb86e20e7ca3caa8f89e22ded79acdb9b7be13430e4b7ce8b23f4c25019e2308248585bafa0c26a5d5940bf",
          "sha256": "980e721b168ed3e7047886aeaadf0b3601cc5dc83422f99154ad85cef19159c9",
          "sha1": "0fe50684b14dd676ad3e1224c2789cd95b591157",
          "md5": "ff22ece9dc46d18bd9c89888e86f2ac9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18.aar",
          "url": "sdkruntime-core-1.0.0-alpha18.aar",
          "size": 76557,
          "sha512": "32a7d368a511d5bf61ae54e21825aadac37fca5b5fb86e20e7ca3caa8f89e22ded79acdb9b7be13430e4b7ce8b23f4c25019e2308248585bafa0c26a5d5940bf",
          "sha256": "980e721b168ed3e7047886aeaadf0b3601cc5dc83422f99154ad85cef19159c9",
          "sha1": "0fe50684b14dd676ad3e1224c2789cd95b591157",
          "md5": "ff22ece9dc46d18bd9c89888e86f2ac9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18-versionMetadata.json",
          "url": "sdkruntime-core-1.0.0-alpha18-versionMetadata.json",
          "size": 5038,
          "sha512": "c33e396f094d45a75a322e7847001ff35c444216c98b956815874e49f59b6cc22b22da1b220d65e367c8dfbf1af2e93b471d3e8b493704e27b057df65a18d851",
          "sha256": "94e41a816a440943ebadda209659ac1222c9454182394984b3ed5d2ab31aaf77",
          "sha1": "6b4826383ba3f3c0159b14340e35ff234e650954",
          "md5": "3fbdc148ba2ae2e885dc4db9dff06a89"
        }
      ]
    }
  ]
}