{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.sdkruntime",
    "module": "sdkruntime-core",
    "version": "1.0.0-alpha18",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13808536"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18-sources.jar",
          "url": "sdkruntime-core-1.0.0-alpha18-sources.jar",
          "size": 37339,
          "sha512": "45cfd0413a159684363e86c06acc910b446ca0abb706e9add26e5ca3a6d84f1bb3e8193e5157cd80fc3c6756269382e4dd66777964f2a7540de2573971e213cc",
          "sha256": "541593790d8a5fadbfb48ee3f182122572d8f98a064b52bbad379f43b32cfd5c",
          "sha1": "6c775d22f8ec568b5f9e09b50c0befa436a9e5a2",
          "md5": "5e003edfd69236acdd33c828e0b0012d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18.aar",
          "url": "sdkruntime-core-1.0.0-alpha18.aar",
          "size": 76603,
          "sha512": "58b30aeadadd0f1227514913168474c01583ca2bbcbc242337cd5f240b5ac2fbfbd9aad542f3ef32298efbfca52ee90757eb4763182093c7d7f9dc4810fe878c",
          "sha256": "253e9471fc892e607c633f31a7a01d5a572c75e972d0b4f28b9215c02fa07056",
          "sha1": "ffe859dcc8f7859059529589031f875465ee671b",
          "md5": "02a9da88460d13464fa7c478d1fe42e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.3"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18.aar",
          "url": "sdkruntime-core-1.0.0-alpha18.aar",
          "size": 76603,
          "sha512": "58b30aeadadd0f1227514913168474c01583ca2bbcbc242337cd5f240b5ac2fbfbd9aad542f3ef32298efbfca52ee90757eb4763182093c7d7f9dc4810fe878c",
          "sha256": "253e9471fc892e607c633f31a7a01d5a572c75e972d0b4f28b9215c02fa07056",
          "sha1": "ffe859dcc8f7859059529589031f875465ee671b",
          "md5": "02a9da88460d13464fa7c478d1fe42e0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha18"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha18-versionMetadata.json",
          "url": "sdkruntime-core-1.0.0-alpha18-versionMetadata.json",
          "size": 5038,
          "sha512": "c33e396f094d45a75a322e7847001ff35c444216c98b956815874e49f59b6cc22b22da1b220d65e367c8dfbf1af2e93b471d3e8b493704e27b057df65a18d851",
          "sha256": "94e41a816a440943ebadda209659ac1222c9454182394984b3ed5d2ab31aaf77",
          "sha1": "6b4826383ba3f3c0159b14340e35ff234e650954",
          "md5": "3fbdc148ba2ae2e885dc4db9dff06a89"
        }
      ]
    }
  ]
}