{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-core",
    "version": "1.0.0-alpha13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13522428"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha13.jar",
          "url": "tools-core-1.0.0-alpha13.jar",
          "size": 190113,
          "sha512": "26d3b4870fac11b57d4cc8bdcebd6fdbd42288ac61becb72df3b08605b75419c80d496c99298965aae8c02684b643e24f102cbf9d9dd228d7b9f36cdf1128cd5",
          "sha256": "bcad06fe520823f96639b89bc9fc894bebebcae7bd236e026be70ce322e23560",
          "sha1": "3d5d8591709c36e71cff099fd0523df134e3ff77",
          "md5": "49b4ec0eaa01bc75f95a4d8b9dc1fea3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha13.jar",
          "url": "tools-core-1.0.0-alpha13.jar",
          "size": 190113,
          "sha512": "26d3b4870fac11b57d4cc8bdcebd6fdbd42288ac61becb72df3b08605b75419c80d496c99298965aae8c02684b643e24f102cbf9d9dd228d7b9f36cdf1128cd5",
          "sha256": "bcad06fe520823f96639b89bc9fc894bebebcae7bd236e026be70ce322e23560",
          "sha1": "3d5d8591709c36e71cff099fd0523df134e3ff77",
          "md5": "49b4ec0eaa01bc75f95a4d8b9dc1fea3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core-external-protobuf",
          "version": {
            "requires": "1.0.0-alpha13"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha13-sources.jar",
          "url": "tools-core-1.0.0-alpha13-sources.jar",
          "size": 58475,
          "sha512": "be14145f75a9c56c96d8de7255d564eb38a9d9a60933255cd8e0e1b102152f093eec886c6ecc9578ddd6389785c53fa108f5c0ea8964bfdecbc9cf36f82989d5",
          "sha256": "77c66d49738fba917e70969ae2aaac148971ab3e8bc8a71ca870eb44476a671d",
          "sha1": "439a7b0873dbc32b989bfdb0708a532fbcac4f71",
          "md5": "037aa9e8fbf0a69f137b8d9f5d37a949"
        }
      ]
    }
  ]
}