{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-provider",
    "version": "1.0.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha11-sources.jar",
          "url": "ui-provider-1.0.0-alpha11-sources.jar",
          "size": 17498,
          "sha512": "0a05ca2970205153f4ba406f94387c1d3e309bb61d926667a40795e3a9f92d5974600c53c14b86ecccaf5b2c6d73a6c677bca3b4231572547f57d0f2cd6d2794",
          "sha256": "07c0aa326106c7bac871e8b181a808941d01f01555ceed924d3e8ed84bf39036",
          "sha1": "eeb029fde9d79fc2e8c1a08cb03e72bfe0af2bcc",
          "md5": "dc6d0f69c1d6262e3cb493d60dea4fb6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha11.aar",
          "url": "ui-provider-1.0.0-alpha11.aar",
          "size": 48720,
          "sha512": "9a4fdb8bc253ecc3005aed3fc42b5de8b7d551779db7fea4199ee6004a1f7772303d2d9c203b2294e45e7aa6367214b960318f04f3b8f6cf082162d0a8569418",
          "sha256": "905b46f83b5f59c6cbbc6ad3c7f18960afa995ee1afa997800a94c8f9ec4d481",
          "sha1": "5a8217375498d2d846d59c58e3503f990ce67f85",
          "md5": "b681e655a83a200f3e2aa0825c11e129"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha11.aar",
          "url": "ui-provider-1.0.0-alpha11.aar",
          "size": 48720,
          "sha512": "9a4fdb8bc253ecc3005aed3fc42b5de8b7d551779db7fea4199ee6004a1f7772303d2d9c203b2294e45e7aa6367214b960318f04f3b8f6cf082162d0a8569418",
          "sha256": "905b46f83b5f59c6cbbc6ad3c7f18960afa995ee1afa997800a94c8f9ec4d481",
          "sha1": "5a8217375498d2d846d59c58e3503f990ce67f85",
          "md5": "b681e655a83a200f3e2aa0825c11e129"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-core",
          "version": {
            "requires": "1.0.0-alpha11"
          },
          "reason": "ui-provider is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-provider-1.0.0-alpha11-versionMetadata.json",
          "url": "ui-provider-1.0.0-alpha11-versionMetadata.json",
          "size": 1692,
          "sha512": "0034e283c78b0dfc10329688f3ac91969f0f735cf0e15e7a4c0488484245c246d6a3883fa1e5c6ea698cdbb8eae2a5b04e6f8029cb2fbaf2e341bc0da0797577",
          "sha256": "cfad7f2209152a9cf71e397fbf323c9b6dd00952b3d390ed43a19c5f3874d807",
          "sha1": "329d119413468389f3262e324c4b03db19098794",
          "md5": "e9a258f44beb159cf0906f4fdb6f58bc"
        }
      ]
    }
  ]
}