{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.recyclerview",
    "module": "recyclerview",
    "version": "1.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6668689"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.2.0-alpha04.aar",
          "url": "recyclerview-1.2.0-alpha04.aar",
          "size": 393362,
          "sha512": "a84eb5fd568f3272746541b068fa84c73c428b41216af1912b1e021bf6791edcb72a807c00d16adcfface3b349d2ad1ba9de32b8a15906ecf701106c6bc4a11c",
          "sha256": "0126d858caf9197369a8d90b0c30a9d84cc90a6592ec5f1416827e61e4cc5439",
          "sha1": "f9975e9c123053d0afc3ded10b62df1be51022bd",
          "md5": "704316846ada4e0927d27c4746f86e38"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "androidx.customview",
          "module": "customview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "recyclerview-1.2.0-alpha04.aar",
          "url": "recyclerview-1.2.0-alpha04.aar",
          "size": 393362,
          "sha512": "a84eb5fd568f3272746541b068fa84c73c428b41216af1912b1e021bf6791edcb72a807c00d16adcfface3b349d2ad1ba9de32b8a15906ecf701106c6bc4a11c",
          "sha256": "0126d858caf9197369a8d90b0c30a9d84cc90a6592ec5f1416827e61e4cc5439",
          "sha1": "f9975e9c123053d0afc3ded10b62df1be51022bd",
          "md5": "704316846ada4e0927d27c4746f86e38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "recyclerview-1.2.0-alpha04-sources.jar",
          "url": "recyclerview-1.2.0-alpha04-sources.jar",
          "size": 320935,
          "sha512": "e3eaf4ed73d8f632cad1b40e92dc78fa1eccdbc78aaab77dd1429e6bfb72764f7f15761bf0447b8dc1affc93594e3d665144acc5630c0bcb2ca8314d0b97853f",
          "sha256": "721dcf2696f21b9cb6da20869e63e5cd204463fff40dea9f5f8dc9714e55b56a",
          "sha1": "6fbbbd3dc06ab1a02151fd02f4897d5990cdd30c",
          "md5": "4bf2ac818121b7deba2b7b5d8f6f5b8a"
        }
      ]
    }
  ]
}
