{
  "formatVersion": "1.1",
  "component": {
    "url": "../../annotation/1.11.0-alpha01/annotation-1.11.0-alpha01.module",
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13318856"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.11.0-alpha01.jar",
          "url": "annotation-jvm-1.11.0-alpha01.jar",
          "size": 61493,
          "sha512": "3d7df48c6fb38f95bb7f10eefc9ecdcf929d2f66932f36706cb3921b01b10698692c412edcd970ef070f830ac64890f3459a9074a10dbe9ffa1a50291f7ba434",
          "sha256": "e7509f3f1c671661c0c71c7eaddc5eb8448f33a0d38f512ed2d2293f676901fd",
          "sha1": "ffc9fb12730bf7d06f41502fa480c1032559ff6e",
          "md5": "ccc2164f5b85442e4e659a74b85eacea"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-jvm-1.11.0-alpha01.jar",
          "url": "annotation-jvm-1.11.0-alpha01.jar",
          "size": 61493,
          "sha512": "3d7df48c6fb38f95bb7f10eefc9ecdcf929d2f66932f36706cb3921b01b10698692c412edcd970ef070f830ac64890f3459a9074a10dbe9ffa1a50291f7ba434",
          "sha256": "e7509f3f1c671661c0c71c7eaddc5eb8448f33a0d38f512ed2d2293f676901fd",
          "sha1": "ffc9fb12730bf7d06f41502fa480c1032559ff6e",
          "md5": "ccc2164f5b85442e4e659a74b85eacea"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotation-jvm-1.11.0-alpha01-sources.jar",
          "url": "annotation-jvm-1.11.0-alpha01-sources.jar",
          "size": 72344,
          "sha512": "a519cc06431045da47c4d13e502a6698da4fba41806118703725bb44a6160ab1d18e0fa88ef8eff17f29828740d3b7ba8222a4850fbabbd89e2f8670d6b6ab66",
          "sha256": "21ac2f11a58c543908304eacc4281854507ab6dd4c311fe48bc4ce9d25c3c6ea",
          "sha1": "c35ae7b3923621f24667eaca9bcca90d65a589d2",
          "md5": "47f9fc7d3926e38ba2069f3776c4070c"
        }
      ]
    }
  ]
}