version: "1.1.0-beta10"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.8.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.ads"
group_id: "androidx.privacysandbox.ads"
artifact_id: "ads-adservices"
path: "/privacysandbox/ads/ads-adservices"
sha: "f32c040a866abef69321d46b3aab8850733177f0"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.ads-ads-adservices-all-12276524-1.1.0-beta10.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices-java"
    version: "1.1.0-beta10"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
