{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.transition",
    "module": "transition",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7139798"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "transition-1.5.0-alpha01.aar",
          "url": "transition-1.5.0-alpha01.aar",
          "size": 182105,
          "sha512": "7dff84fbbcfc4bc8c1dd22a0d4c7466ef8db00e41c94c603d52a6eb1a128a9ea527fa5fc49926c20bfc1efc3a190fdcbe6f5bd8ddb8802ca0054f32b2d54cb18",
          "sha256": "168d8e04105d62f8ae729152a9733ec093b3dca1caba716743e31f00b033ae52",
          "sha1": "bec05612c94eac922c1b95d2436734346719c32e",
          "md5": "e4578e35a6480b18011ef812c6bb58bc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "transition-1.5.0-alpha01.aar",
          "url": "transition-1.5.0-alpha01.aar",
          "size": 182105,
          "sha512": "7dff84fbbcfc4bc8c1dd22a0d4c7466ef8db00e41c94c603d52a6eb1a128a9ea527fa5fc49926c20bfc1efc3a190fdcbe6f5bd8ddb8802ca0054f32b2d54cb18",
          "sha256": "168d8e04105d62f8ae729152a9733ec093b3dca1caba716743e31f00b033ae52",
          "sha1": "bec05612c94eac922c1b95d2436734346719c32e",
          "md5": "e4578e35a6480b18011ef812c6bb58bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transition-1.5.0-alpha01-sources.jar",
          "url": "transition-1.5.0-alpha01-sources.jar",
          "size": 132965,
          "sha512": "a64ab6c4347208e5135ffe0cd527370dcb5e2e2494e8de00fb8e334df958994b69cb5fd7dcb2faeeaad25c979fa0d3d8738daa8c8b31aabae1d9bd46f375269d",
          "sha256": "ee8d541185ac18bb94f7a1af696229446d946174d83e104de1bf49dcd71254a5",
          "sha1": "ada7076352a36522478c8421af9df9cd3e9e7c05",
          "md5": "c30ee4a58356e33800e34cce5c16f162"
        }
      ]
    }
  ]
}
