{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.mediarouter",
    "module": "mediarouter",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7116071"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.3.0-alpha01.aar",
          "url": "mediarouter-1.3.0-alpha01.aar",
          "size": 761197,
          "sha512": "0bd67fc4b093027d439d99c4616fce199ffc1e1723e2236885896f0eec87bab93f9108e7e72fa234d6df0a12809c619aa4cc222efec595e041de8dfddc20bfc7",
          "sha256": "a15cf0c6db7c15d1dcf1be5a710b7bb6eeee28e1697cd5f0f715005708bb1504",
          "sha1": "394d53dd22b11f0a68b8ddda20275815e9f1f6bb",
          "md5": "c2117abd205e576c3bee408ff93ea19e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mediarouter-1.3.0-alpha01.aar",
          "url": "mediarouter-1.3.0-alpha01.aar",
          "size": 761197,
          "sha512": "0bd67fc4b093027d439d99c4616fce199ffc1e1723e2236885896f0eec87bab93f9108e7e72fa234d6df0a12809c619aa4cc222efec595e041de8dfddc20bfc7",
          "sha256": "a15cf0c6db7c15d1dcf1be5a710b7bb6eeee28e1697cd5f0f715005708bb1504",
          "sha1": "394d53dd22b11f0a68b8ddda20275815e9f1f6bb",
          "md5": "c2117abd205e576c3bee408ff93ea19e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mediarouter-1.3.0-alpha01-sources.jar",
          "url": "mediarouter-1.3.0-alpha01-sources.jar",
          "size": 196490,
          "sha512": "42bdba4be2b973c5eb101f5790aeedf1461d8713237a9f48975d88f0af5740a0c0619c1f4d27235d928fdd25d292cfa7f47675c01944936834bcb42b200781c9",
          "sha256": "5e229c9dab1ad240cb7b7e69a598a57dabdd498469f8a8c9e2e9af45464bfbc3",
          "sha1": "ea16851dc3e60f3ca35360528bbfecec782fe2d2",
          "md5": "a6696167cd9f94b8570477e4f3181784"
        }
      ]
    }
  ]
}
