version: "1.1.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.5.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.customview"
group_id: "androidx.customview"
artifact_id: "customview-poolingcontainer"
path: "/customview/customview-poolingcontainer"
sha: "edd19514b50734044a2a42cd9be3930fdf188b0f"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.customview-customview-poolingcontainer-all-12133442-1.1.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
