{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-ktx",
    "version": "1.2.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6836159"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.0-alpha09.aar",
          "url": "activity-ktx-1.2.0-alpha09.aar",
          "size": 19799,
          "sha512": "8feff9434f152b2324633f234e2f53f8d6a04ab2ba43ff691e7047df2f879a95db4f911cb447d4ea97a49e0b77483f195c26108a770bdd686326aa9f72ba49c6",
          "sha256": "eecfe12462ccab958ba161e9e6ce73c84c99859c5faae0b190b22251dfcb628e",
          "sha1": "cac2fb1329f916c097db3d335fae2610248d7c29",
          "md5": "7358f7980deacb8f46e03264333dd7e5"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0-alpha09"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.3.0-beta01"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-ktx",
          "version": {
            "requires": "1.1.0-beta01"
          },
          "reason": "Mirror activity dependency graph for -ktx artifacts"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "activity-ktx-1.2.0-alpha09.aar",
          "url": "activity-ktx-1.2.0-alpha09.aar",
          "size": 19799,
          "sha512": "8feff9434f152b2324633f234e2f53f8d6a04ab2ba43ff691e7047df2f879a95db4f911cb447d4ea97a49e0b77483f195c26108a770bdd686326aa9f72ba49c6",
          "sha256": "eecfe12462ccab958ba161e9e6ce73c84c99859c5faae0b190b22251dfcb628e",
          "sha1": "cac2fb1329f916c097db3d335fae2610248d7c29",
          "md5": "7358f7980deacb8f46e03264333dd7e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-ktx-1.2.0-alpha09-sources.jar",
          "url": "activity-ktx-1.2.0-alpha09-sources.jar",
          "size": 6077,
          "sha512": "f54989f1aebf986a9e5bd8a128c04e2e4e2a2429d93fe24dddb8e1d86cf1738aad1067780c4d0125e70a8e80dd4233ece21e6d382d225447fe7b6a2c22fca60d",
          "sha256": "a3929f04f27931c0b72de048d7991f076af33cdfd71f21ba4c164fc18490b86a",
          "sha1": "8a296a81afe4b9766244c036ff5c667bbfe71bd3",
          "md5": "911ac9addf28d7fdca0ad2131fbb30d3"
        }
      ]
    }
  ]
}
