{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.transition",
    "module": "transition",
    "version": "1.4.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6836159"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "transition-1.4.0-rc01.aar",
          "url": "transition-1.4.0-rc01.aar",
          "size": 182056,
          "sha512": "d1e4684aff23dfb7ff231e654c27d953a101e59ef68496bd453f48099989ec1f87b56be7a7655dd8221309d5467efcf8675e118dc3e23fc9b71d19ef3f765d47",
          "sha256": "f74edf46f426707d67483fdab2fa55d8b1cf6ca412f165ce025bcf2abfd1a1bc",
          "sha1": "72a1f14a4637682e31c7a05cdca038cc32f9b7f9",
          "md5": "c786ccb783db0a47fd817261e9d4b42d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "transition-1.4.0-rc01.aar",
          "url": "transition-1.4.0-rc01.aar",
          "size": 182056,
          "sha512": "d1e4684aff23dfb7ff231e654c27d953a101e59ef68496bd453f48099989ec1f87b56be7a7655dd8221309d5467efcf8675e118dc3e23fc9b71d19ef3f765d47",
          "sha256": "f74edf46f426707d67483fdab2fa55d8b1cf6ca412f165ce025bcf2abfd1a1bc",
          "sha1": "72a1f14a4637682e31c7a05cdca038cc32f9b7f9",
          "md5": "c786ccb783db0a47fd817261e9d4b42d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transition-1.4.0-rc01-sources.jar",
          "url": "transition-1.4.0-rc01-sources.jar",
          "size": 132962,
          "sha512": "6d54bc5fa0e51cb4aa8e0bbb52e9b2b1e05a221f8676f2cbfff7ee9bfa5f99bc2325f9265b2f80ed61e49dda0733805c3b647d318f3a2e59a2fd38a4b3797599",
          "sha256": "63cfb28328617ba0d2f7cc2939ed89002d30a64a7f6ca0623ecad0e1a02aad38",
          "sha1": "5fd3ac10f999d49779419fd57a5c4168b7f94053",
          "md5": "fd0d16223afef30ce519b3dd289f7f47"
        }
      ]
    }
  ]
}
