{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-testing",
    "version": "2.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13718522"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.11.0-alpha01-sources.jar",
          "url": "work-testing-2.11.0-alpha01-sources.jar",
          "size": 25247,
          "sha512": "348fd7d53601974b5ddba1f8897a44b1dc314e5d7dc8f1dc912c371ab959bf00065975d1178ac6f7cad5ef3aa391908cd927fb93a9e91938474b43b110831497",
          "sha256": "9374ddff318ed96dc4d89304e7ab05e5606bfe0efea7fd75b5cc4b94a8daffb5",
          "sha1": "80d41db53dd76b69b254967f6e20ec630c98bc6f",
          "md5": "0d48a23865a64eca94bf5da00062f159"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.11.0-alpha01.aar",
          "url": "work-testing-2.11.0-alpha01.aar",
          "size": 39092,
          "sha512": "53346b53634ee02255b8e5dd0db2cbbc9fcfa99a05204c6a4f8e860be0a7cf705c964792d81f9c76d78f60f1216e279c9e483231e5d60138bdd24a30824a931a",
          "sha256": "7e9453e6049679a0c3fb1f4496471b9812fb084978631b98ad31672c94e3a258",
          "sha1": "044941cee5799b7c1f277bea5c692b6125fc3f2b",
          "md5": "f93d9b11794a6c75cc74116897f6e6d8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.11.0-alpha01.aar",
          "url": "work-testing-2.11.0-alpha01.aar",
          "size": 39092,
          "sha512": "53346b53634ee02255b8e5dd0db2cbbc9fcfa99a05204c6a4f8e860be0a7cf705c964792d81f9c76d78f60f1216e279c9e483231e5d60138bdd24a30824a931a",
          "sha256": "7e9453e6049679a0c3fb1f4496471b9812fb084978631b98ad31672c94e3a258",
          "sha1": "044941cee5799b7c1f277bea5c692b6125fc3f2b",
          "md5": "f93d9b11794a6c75cc74116897f6e6d8"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-testing is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-testing-2.11.0-alpha01-versionMetadata.json",
          "url": "work-testing-2.11.0-alpha01-versionMetadata.json",
          "size": 4553,
          "sha512": "efa7f674d2e86a36d540aad41019fc7be221bc1c3443b28b16a96642f05e0288e1fcb8052a6ab96a30a3d59cf6aa3afda8077027639cfdcc9124ddca712593f1",
          "sha256": "d63362d9137caa28517c516ea86b44187e953b738607c792b83ca2fc5d54f5b8",
          "sha1": "a1d6781addc87ca52b7a29bb401667846a2a918f",
          "md5": "de0d09550c067edeed7572d8c274fc18"
        }
      ]
    }
  ]
}