{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13882970"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.4.0-alpha01-sources.jar",
          "url": "protolayout-1.4.0-alpha01-sources.jar",
          "size": 115768,
          "sha512": "10d6f3bda1e13f9b61b6a566a488844599bacba2de4963140b2dd9e8db6b95e4b0b6ddff5c07b9f148975aa384a053523d6241dff7a183cf32072fd37214db0d",
          "sha256": "a2644b3749fa5378890f4afde1252f9c9c6c00a1b27c84acfe0072502c378588",
          "sha1": "e6d38615ac3c050cff67f2256c9cc7e9d0350e28",
          "md5": "d49ae3eb9ba8f9d9837610a4d3b27cbb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.4.0-alpha01.aar",
          "url": "protolayout-1.4.0-alpha01.aar",
          "size": 454946,
          "sha512": "98ccd9bd08aa6d9392d2965f535d0db23e4afca06ab26c4dfcbc87b6768c790c46d16b2e3103b7a5d8180ff0d012cc0d109bfa4417ca953ad4e1a7549663fcbe",
          "sha256": "e7a5e52561bfcb3b30e08ff41473a3843873b1f78696f4f11fbff47803bbeec3",
          "sha1": "5af40c4d61805939b68aa22c2c4d8f4ee7af1ed7",
          "md5": "96ecc13639fa948f6bb5b4a5d141f8c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.4.0-alpha01.aar",
          "url": "protolayout-1.4.0-alpha01.aar",
          "size": 454946,
          "sha512": "98ccd9bd08aa6d9392d2965f535d0db23e4afca06ab26c4dfcbc87b6768c790c46d16b2e3103b7a5d8180ff0d012cc0d109bfa4417ca953ad4e1a7549663fcbe",
          "sha256": "e7a5e52561bfcb3b30e08ff41473a3843873b1f78696f4f11fbff47803bbeec3",
          "sha1": "5af40c4d61805939b68aa22c2c4d8f4ee7af1ed7",
          "md5": "96ecc13639fa948f6bb5b4a5d141f8c6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression-pipeline",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "protolayout is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-1.4.0-alpha01-versionMetadata.json",
          "url": "protolayout-1.4.0-alpha01-versionMetadata.json",
          "size": 90563,
          "sha512": "efb9b38a52f17e5b111f61e904616af84005de1c4eaf644926cd9968f3eb795ee8939eb69f820045f9f7c15034be4a5c3c3ca13eccc5d93ff37f1a89988904e9",
          "sha256": "1b4c7fa6fceb400b4aa6b656b7f79b82dec9e0eddf68698080bd1c8ba0aaa1bd",
          "sha1": "55add8231343326b45e1e462b86d7afef701fb01",
          "md5": "2cdf723cbdeff1b4f915555b3b09451c"
        }
      ]
    }
  ]
}