{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing/1.3.0-rc01/tracing-1.3.0-rc01.module",
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13882970"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing.aar",
          "url": "tracing-android-1.3.0-rc01.aar",
          "size": 13645,
          "sha512": "82614b04306d3e73a9694da9c6e1708f73fabacc5a3ed3ae102f62002670eeb850791e942d7fa94bd3512263020a82edd916db17899d98007cd31be35e7072fe",
          "sha256": "6474d470b825c9565f09b056fa26136b3fcece1debeaf9f062662a6305c429a8",
          "sha1": "985c4d58048614764b33cd9ca71341ab3b9fbb0d",
          "md5": "d23a1b435a7b4b1c188f9443bc664a53"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing.aar",
          "url": "tracing-android-1.3.0-rc01.aar",
          "size": 13645,
          "sha512": "82614b04306d3e73a9694da9c6e1708f73fabacc5a3ed3ae102f62002670eeb850791e942d7fa94bd3512263020a82edd916db17899d98007cd31be35e7072fe",
          "sha256": "6474d470b825c9565f09b056fa26136b3fcece1debeaf9f062662a6305c429a8",
          "sha1": "985c4d58048614764b33cd9ca71341ab3b9fbb0d",
          "md5": "d23a1b435a7b4b1c188f9443bc664a53"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-android-1.3.0-rc01-sources.jar",
          "url": "tracing-android-1.3.0-rc01-sources.jar",
          "size": 11465,
          "sha512": "b856e9384480fe4981abc4868520cf81dcdd80f731de8b73500dcaa258ce9f7686cc3073f091dc0cded2f36fff17303a3a0e2aaccb9c12b836c8015f639f3ac9",
          "sha256": "c294266f78954522204b87c76b8ea765bd6dd98615675b20950787f77d5910ee",
          "sha1": "dae0bf85e1d12c5cd59845846fc624729e3506dd",
          "md5": "ec3f9a887567fa764c98c70ec4d76027"
        }
      ]
    }
  ]
}