{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing/1.3.0-rc01/tracing-1.3.0-rc01.module",
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.3.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13522428"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing.aar",
          "url": "tracing-android-1.3.0-rc01.aar",
          "size": 14073,
          "sha512": "9d9c8aa07eaf41319ae4799ab15fa70fed48c2e6212515cd2ab9d514ddbffed760794f9f18240bd3f17e9d5f0ee5ffc53da8db731ea4bb86b56ae74732a6e242",
          "sha256": "c14294484af71623e3116a977721cb8bbce87613a9b743513d6830ee7f47850b",
          "sha1": "f778efc06e35fcaeff3bb9a7dacc1e5b1394af8e",
          "md5": "658afd1bd6d382f8e93d8c2405718915"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing.aar",
          "url": "tracing-android-1.3.0-rc01.aar",
          "size": 14073,
          "sha512": "9d9c8aa07eaf41319ae4799ab15fa70fed48c2e6212515cd2ab9d514ddbffed760794f9f18240bd3f17e9d5f0ee5ffc53da8db731ea4bb86b56ae74732a6e242",
          "sha256": "c14294484af71623e3116a977721cb8bbce87613a9b743513d6830ee7f47850b",
          "sha1": "f778efc06e35fcaeff3bb9a7dacc1e5b1394af8e",
          "md5": "658afd1bd6d382f8e93d8c2405718915"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          },
          "reason": "tracing is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-android-1.3.0-rc01-sources.jar",
          "url": "tracing-android-1.3.0-rc01-sources.jar",
          "size": 11456,
          "sha512": "4d61d6692230cb55f2fd6c95fa294007dd6fa5bdcf58ade739b92a8e62242f85988bef0abcd49ed785d86fbc69f5bd64053ba110cf89cdb0ff907d2ea619c7ec",
          "sha256": "324ed67f9b4303d8f9159feeede9dc05a185ac059a8bb88fc9f0fb956f0f783a",
          "sha1": "d421716292270602cf1b203c8acbabb487b6ddc9",
          "md5": "2e60b09f88c10ba7ac868541b10cc608"
        }
      ]
    }
  ]
}