{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-integration",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-media3-effect",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "size": 302638,
          "sha512": "4fcf68b24df11319a6192cede407fc1e3dbf1dd4ad649ee7de23004f0681b4f14b2a1e8c310ca7a2794d9238cb7d71f2ff90e03045dc4641ae31230cebd306ca",
          "sha256": "07e5ec869e5d76f2e5c786e8218a6efe05a0b6d9c56b63614fcbe22dbf8d9d0e",
          "sha1": "05e12d0572c5877da7a6d093591929d2a29cbac7",
          "md5": "5fef164cd79f0ee2a62c0f7d35b7e7ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-media3-effect",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 1032766,
          "sha512": "03748eb9537954f4721c45af1e66922be2bb68c9d219922bacfda6cb8b9c88086d4e2f699b3e0002e699c1fdaab0c3cc9ee3b99865b416e43db7e11565e349f3",
          "sha256": "9dde9902958f559789574450c75bb1268c9b101086a9b26a8260b77c80fd75eb",
          "sha1": "6559e639676cbe5e1a8c7694699547437414ae52",
          "md5": "e4b7f7acc35a6ac036cce048b07ca212"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-alpha02"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.49"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-media3-effect",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 1032766,
          "sha512": "03748eb9537954f4721c45af1e66922be2bb68c9d219922bacfda6cb8b9c88086d4e2f699b3e0002e699c1fdaab0c3cc9ee3b99865b416e43db7e11565e349f3",
          "sha256": "9dde9902958f559789574450c75bb1268c9b101086a9b26a8260b77c80fd75eb",
          "sha1": "6559e639676cbe5e1a8c7694699547437414ae52",
          "md5": "e4b7f7acc35a6ac036cce048b07ca212"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-media3-effect",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "size": 4017,
          "sha512": "efd9809e75691f3ad946b1adc1369b1cfeb3d2f976e7a813bc26df8216745a18a4341792c27280bf08c51fa0443f651ffd8a5c36829e579462ca6a0e96391e48",
          "sha256": "cf64f3ef620f0dd2254bc60c6fac846012d25fd518b3a8253029712ace321a3c",
          "sha1": "8fa26dc17e7d5dafff21916b28a69e2597fa654f",
          "md5": "7b1a3f19da1f03bb292b1980f447e23b"
        }
      ]
    }
  ]
}