{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2-pipe-integration",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13621151"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-sources.jar",
          "size": 333598,
          "sha512": "7227b844a9a3ee5f6de6f19cc7aee71c03d46ce2398230e814ba28784a36a6deb2b8a963a0e7cd09e8307e52206e8c1f21c9a98f11398f3dfb36f0b393f3326a",
          "sha256": "51e818429535562c062ebb6bfdfd13eb3649ceb1bf79e30f6961b0830dfcb7ff",
          "sha1": "dec59c2ebc7844844cf4b336dd253c2376bee86a",
          "md5": "4011b36fb0ee395e6e8b13116416800c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 1107441,
          "sha512": "d0532a05cefc565cffcc67fae32029302e4465e213d95840084cc2f668ed865dd85e54cb22629cdaded774c1db3e211f2d5d10e427b6496ac15cb86d6f00e146",
          "sha256": "25250c62cbc7358381dc0487eea1aa5ece1c45ffe931ac9cf2d0f0f0eb857517",
          "sha1": "052f959cb488e61fa9a8a86cb26fcce9ca9ed880",
          "md5": "85bfaf8de1652da6b1191c0cb612f92d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "dagger",
          "version": {
            "requires": "2.54"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.27.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01.aar",
          "size": 1107441,
          "sha512": "d0532a05cefc565cffcc67fae32029302e4465e213d95840084cc2f668ed865dd85e54cb22629cdaded774c1db3e211f2d5d10e427b6496ac15cb86d6f00e146",
          "sha256": "25250c62cbc7358381dc0487eea1aa5ece1c45ffe931ac9cf2d0f0f0eb857517",
          "sha1": "052f959cb488e61fa9a8a86cb26fcce9ca9ed880",
          "md5": "85bfaf8de1652da6b1191c0cb612f92d"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2-pipe",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-testing",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "camera-camera2-pipe-integration is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "url": "camera-camera2-pipe-integration-1.0.0-alpha01-versionMetadata.json",
          "size": 4017,
          "sha512": "c71b57115cb92b552e0ca5576e7cabeaa2ffca908e4b72fdcb3683d7f51d2061c38389031133930179233b2e69cd159554179a7c5d4087b79f542d0d2fa5de62",
          "sha256": "d00fdd9adb8eb88252bc34fad3f16bf5de59cae84ba397f11baf5fc8925e241e",
          "sha1": "9a7447ea7d998842228b9a5871dab2e563f405d0",
          "md5": "b994dc54bdbda11fccd4fee51b2e75a8"
        }
      ]
    }
  ]
}