{
  "formatVersion": "1.1",
  "component": {
    "url": "../../animation/1.9.0-alpha01/animation-1.9.0-alpha01.module",
    "group": "androidx.compose.animation",
    "module": "animation",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12976215"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation.aar",
          "url": "animation-android-1.9.0-alpha01.aar",
          "size": 1430905,
          "sha512": "d940edea317255572646218cd3f8fff55ccdead459628591e811e05adaac8dcb2ea562c1ebb8708346e82f3f1b543c49c41b51df475350d5db2594bab04daa23",
          "sha256": "d00d21b6e305bea436964dcb1762fff1eb5b2c257f52cf0a0740ed936b14b538",
          "sha1": "8688e5f938823130fcf44d1111fcb5715d48d806",
          "md5": "d54e6383c0bb1e944bf2eade5b777eb2"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.5.0-beta03"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.9.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "animation.aar",
          "url": "animation-android-1.9.0-alpha01.aar",
          "size": 1430905,
          "sha512": "d940edea317255572646218cd3f8fff55ccdead459628591e811e05adaac8dcb2ea562c1ebb8708346e82f3f1b543c49c41b51df475350d5db2594bab04daa23",
          "sha256": "d00d21b6e305bea436964dcb1762fff1eb5b2c257f52cf0a0740ed936b14b538",
          "sha1": "8688e5f938823130fcf44d1111fcb5715d48d806",
          "md5": "d54e6383c0bb1e944bf2eade5b777eb2"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.animation",
          "module": "animation-lint",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-core-lint",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-tooling-internal",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.9.0-alpha01"
          },
          "reason": "animation is in atomic group androidx.compose.animation"
        }
      ],
      "files": [
        {
          "name": "animation-android-1.9.0-alpha01-sources.jar",
          "url": "animation-android-1.9.0-alpha01-sources.jar",
          "size": 82004,
          "sha512": "144a7882e8095c8a62ed0c1041b9baa0eb6d089fd5bb163b4042f90b79176d53c4aa79eb5453ceae0a99c85b9128999c9e804c803b17f042a2581e30553355e4",
          "sha256": "36516e3f24e2b4f7b58b54a93a090bd45739a0c3e0a71be90736e69ff8789b9d",
          "sha1": "1a12eb9bcc5a90f85cbe133a5c07d5425d61b476",
          "md5": "a4602d5580e96998a7b864d283de2244"
        },
        {
          "name": "animation-1.9.0-alpha01-samples-sources.jar",
          "url": "animation-android-1.9.0-alpha01-samples-sources.jar",
          "size": 29633,
          "sha512": "6abb3490b2d6b3749dd3827bfecab6fc077b51023160f2367c8d140bb7fa7b0076d8ec2297d112d820d2515b53ac73d9b6770d0a143283a5c694e616526c9a3d",
          "sha256": "e3d1c47f7fdc3a701f56326e75fa6487a34be4281c732bc862fef61573f72957",
          "sha1": "26ada0949567233f766dbdb25f2f089ad5d86a14",
          "md5": "dbd92d69be73dff7da004ad55ba39a08"
        }
      ]
    }
  ]
}