version: "1.1.0-alpha04"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.health"
    artifact_id: "health-services-client-external-protobuf"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.health"
group_id: "androidx.health"
artifact_id: "health-services-client-proto"
path: "/health/health-services-client-proto"
sha: "ea99794a17d8def2c12524dd923d733c89343a42"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.health-health-services-client-proto-all-12529414-1.1.0-alpha04.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: false
is_kmp: false
target: "androidx"
