version: "1.1.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.window.extensions.core"
group_id: "androidx.window.extensions.core"
artifact_id: "core"
path: "/window/extensions/core/core"
sha: "914968fcd19f67905549a32390f97ab1976594f6"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.window.extensions.core-core-all-12312442-1.1.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
