version: "1.1.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.6.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.window.extensions.core"
group_id: "androidx.window.extensions.core"
artifact_id: "core"
path: "/window/extensions/core/core"
sha: "6572e3ea3db977c61823be63521fce4fbfa9a53b"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-window-extensions-core-11348044.zip"
project_zip_path: "per-project-zips/androidx.window.extensions.core-core-all-11348044-1.1.0-alpha01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
