{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/1.4.0-alpha10/material3-window-size-class-1.4.0-alpha10.module",
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.4.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13276378"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class.aar",
          "url": "material3-window-size-class-android-1.4.0-alpha10.aar",
          "size": 21816,
          "sha512": "385f77db6d1bf331709877c183e0ce0c63323b0c7a446a2477ec73eddd7dd2e46e1b549d09542490ee902f00f965d225bf86763d1e1b35924de5ac1a31dde114",
          "sha256": "be7669d8f1b62585a3502657992d484ce794bc1028af85497bd467456676543d",
          "sha1": "655a1b4fd579a0af31311ce2d75c6d2eff3772a9",
          "md5": "86b8334d67ed6bc5b1d1deac70ad9d64"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class.aar",
          "url": "material3-window-size-class-android-1.4.0-alpha10.aar",
          "size": 21816,
          "sha512": "385f77db6d1bf331709877c183e0ce0c63323b0c7a446a2477ec73eddd7dd2e46e1b549d09542490ee902f00f965d225bf86763d1e1b35924de5ac1a31dde114",
          "sha256": "be7669d8f1b62585a3502657992d484ce794bc1028af85497bd467456676543d",
          "sha1": "655a1b4fd579a0af31311ce2d75c6d2eff3772a9",
          "md5": "86b8334d67ed6bc5b1d1deac70ad9d64"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha10"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-android-1.4.0-alpha10-sources.jar",
          "url": "material3-window-size-class-android-1.4.0-alpha10-sources.jar",
          "size": 12864,
          "sha512": "a9c21a7b1968ad179a95750c0ce7b96c82eceafaca6c10422d7189413e6b41ff9fddb8add3df2b1823c95086fbd1aaa072f3f0e0cf2bd44479d419a1577aaa14",
          "sha256": "67cc34ca6db9319e18be823161ff75acd112bec25ecea879ffafe0420134d98b",
          "sha1": "26ab6d9b1a356ad6db1b05d6efce1245afa8e172",
          "md5": "79f5cb1e99e9a189ac96ff3b2c142d55"
        },
        {
          "name": "material3-window-size-class-1.4.0-alpha10-samples-sources.jar",
          "url": "material3-window-size-class-android-1.4.0-alpha10-samples-sources.jar",
          "size": 6513,
          "sha512": "69547dd36fa8f2bcca298c97383d4b3f488404fd3579fbabec0d68f4af515d39d83ac8a2282874de93e2c1e0b7ab64e845b7e1d906b3c6f4b1d9047fdcdc1884",
          "sha256": "b319045da15bf9ed8003d4636702cf83fd322e1ee164955d28b2cffb3a591818",
          "sha1": "0eda4b3d6cc1b0383cc1379a157d7c19eb462c20",
          "md5": "aa6a2af64c7d4a06d0cea72d570dcd0c"
        }
      ]
    }
  ]
}