{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-apipackager",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apipackager-1.0.0-alpha10.jar",
          "url": "tools-apipackager-1.0.0-alpha10.jar",
          "size": 15749,
          "sha512": "eca8be031bb2ae7af71538c93e3b614ca42fcda9db081f873605498fbe6a2708151b07df7cbbead84731bfb8d9e95e8aacc84f55e72a961ad485fc9e29d44998",
          "sha256": "b9af7a44d79975cd68c54f92db649903a70bb84efa960a36156f421414516c67",
          "sha1": "190cfe3506f8ac82117264bb170303492827f3eb",
          "md5": "7193bdab3a45f9518dc4266f1b0f4ced"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apipackager-1.0.0-alpha10.jar",
          "url": "tools-apipackager-1.0.0-alpha10.jar",
          "size": 15749,
          "sha512": "eca8be031bb2ae7af71538c93e3b614ca42fcda9db081f873605498fbe6a2708151b07df7cbbead84731bfb8d9e95e8aacc84f55e72a961ad485fc9e29d44998",
          "sha256": "b9af7a44d79975cd68c54f92db649903a70bb84efa960a36156f421414516c67",
          "sha1": "190cfe3506f8ac82117264bb170303492827f3eb",
          "md5": "7193bdab3a45f9518dc4266f1b0f4ced"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apipackager is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apipackager-1.0.0-alpha10-sources.jar",
          "url": "tools-apipackager-1.0.0-alpha10-sources.jar",
          "size": 7733,
          "sha512": "71a70b82fa3f41f206b907d9914ae48636a67fb6100faade4d1559646e45dd390ffff2cb01c2728884cd90394ed87ab87cd9fe47c15d77598a6c43225982e0cf",
          "sha256": "b91aa1b7f6835abe6afc95908f6308637fd2c54ca49b868669ae64cd1887fe47",
          "sha1": "addd30ac6f91ec8385bb961391e39ea27b7d2618",
          "md5": "87bc78733289abf803c840b99878b95c"
        }
      ]
    }
  ]
}