{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health",
    "module": "health-services-client",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha04-sources.jar",
          "url": "health-services-client-1.1.0-alpha04-sources.jar",
          "size": 180899,
          "sha512": "c3cf74c7fa34e7f1260591e86d4365c176b1d9cf4ada69625021d04ac5b75da0cd9e2dd454185c7eeb44ee996b2e2fe87dc26ed5a684804bedaa9d63f3886f78",
          "sha256": "ea7a6526cc8cc467fbc58edcf56059b71668ce721c4fc3cb2085a27804fc1fc5",
          "sha1": "2a0a4ea6e03debf97da2a8dfed22fdb0f51e5345",
          "md5": "4a9b6fa76291da7e005fdb429c4793ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha04.aar",
          "url": "health-services-client-1.1.0-alpha04.aar",
          "size": 593922,
          "sha512": "7d72ca7832fb026f4c808729868e11c932156eba7f21fcdfc314f28a2aa4bf9de7ddd64dc0fc33632c2020a461b454604613f337eb646888b48666928725c3ea",
          "sha256": "a46f61f6d5a4a4e97c8364d9ef541a343a1afb92388c6a06d2c59352befda45d",
          "sha1": "acc25fd015f26bac86d419967e376ab9e2f1d434",
          "md5": "fcca17550b632f6dad231e807ae99cbc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.health",
          "module": "health-services-client-proto",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha04.aar",
          "url": "health-services-client-1.1.0-alpha04.aar",
          "size": 593922,
          "sha512": "7d72ca7832fb026f4c808729868e11c932156eba7f21fcdfc314f28a2aa4bf9de7ddd64dc0fc33632c2020a461b454604613f337eb646888b48666928725c3ea",
          "sha256": "a46f61f6d5a4a4e97c8364d9ef541a343a1afb92388c6a06d2c59352befda45d",
          "sha1": "acc25fd015f26bac86d419967e376ab9e2f1d434",
          "md5": "fcca17550b632f6dad231e807ae99cbc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "health-services-client-1.1.0-alpha04-versionMetadata.json",
          "url": "health-services-client-1.1.0-alpha04-versionMetadata.json",
          "size": 57774,
          "sha512": "f760c9e6b57ea9f8ac2176720eb6db7927ccb4790cc643175a800ca79bafa3a2613aeefa64df6c7fd852c14b13a41a7f24889ab9027d20f724a509b03da1c3da",
          "sha256": "a2be32a212a8fdf9dbee81124f830a0b0484232487065eb9b494b536e246424e",
          "sha1": "d70f086fdc7bf4cd6a8b2f38503a78c296d560ac",
          "md5": "e9f5e0b5a4ac2fdd5a8338f797f6a7d0"
        }
      ]
    }
  ]
}