version: "1.6.0-alpha08"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-android"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-data"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-desktop"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-preview"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.ui"
group_id: "androidx.compose.ui"
artifact_id: "ui-tooling"
path: "/compose/ui/ui-tooling"
sha: "088e251311b7eb503587d1129b796bfe3d2e6c6f"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-ui-11015841.zip"
project_zip_path: "per-project-zips/androidx.compose.ui-ui-tooling-all-11015841-1.6.0-alpha08.zip"
kotlin_version: "1.9.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-geometry"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-graphics"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-junit4"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-manifest"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-google-fonts"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-data"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-preview"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-util"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-viewbinding"
    version: "1.6.0-alpha08"
    is_tip_of_tree: true
  }
}
