version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13457307"
group_id: "androidx.savedstate"
artifact_id: "savedstate-ktx"
path: "/savedstate/savedstate-ktx"
sha: "6145f7b86ab4f341c688f916b8151d6c0c244ec0"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.savedstate-savedstate-ktx-all-13457307-1.4.0-alpha01.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-compose"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "savedstate-savedstate-ktxreleaseAndroidTest.xml"
test_module_names: ":savedstate:savedstate-ktx:testReleaseUnitTest"
