version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13842168"
group_id: "androidx.savedstate"
artifact_id: "savedstate-ktx"
path: "/savedstate/savedstate-ktx"
sha: "7ceb138d49622d882b103d960594301ad0a735f6"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.savedstate-savedstate-ktx-all-13842168-1.4.0-alpha01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-compose"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-testing"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "savedstate-savedstate-ktxreleaseAndroidTest.xml"
test_module_names: ":savedstate:savedstate-ktx:testReleaseUnitTest"
