version: "1.2.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.appcompat"
    artifact_id: "appcompat"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.interpolator"
    artifact_id: "interpolator"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.leanback"
    artifact_id: "leanback-grid"
    version: "1.0.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.media"
    artifact_id: "media"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.recyclerview"
    artifact_id: "recyclerview"
    version: "1.3.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.vectordrawable"
    artifact_id: "vectordrawable-animated"
    version: "1.1.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.leanback"
group_id: "androidx.leanback"
artifact_id: "leanback"
path: "/leanback/leanback"
sha: "97fd01bf7de3c278bfbb840840f7fcc0bd3ea99f"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.leanback-leanback-all-12408798-1.2.0-beta01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
