{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01.aar",
          "url": "window-1.4.0-alpha01.aar",
          "size": 436913,
          "sha512": "7fdda7f79f142cfa3b6eb544752314f5c3f27a5859184d294b0670c781870a41bc88543e1161369c56d1c3a30c92cc9c0ea0b48a00419e19c4170f8e8273d45e",
          "sha256": "1df0e62445f4120ba4ac279695e5d0a3f6052e98231b249290dae36be2e2e218",
          "sha1": "f10ea8245272c9f1eeca5ab098acd027590298c0",
          "md5": "449069734f2f40d9000b7a7f970451b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01.aar",
          "url": "window-1.4.0-alpha01.aar",
          "size": 436913,
          "sha512": "7fdda7f79f142cfa3b6eb544752314f5c3f27a5859184d294b0670c781870a41bc88543e1161369c56d1c3a30c92cc9c0ea0b48a00419e19c4170f8e8273d45e",
          "sha256": "1df0e62445f4120ba4ac279695e5d0a3f6052e98231b249290dae36be2e2e218",
          "sha1": "f10ea8245272c9f1eeca5ab098acd027590298c0",
          "md5": "449069734f2f40d9000b7a7f970451b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01-sources.jar",
          "url": "window-1.4.0-alpha01-sources.jar",
          "size": 182509,
          "sha512": "a578b5bbbaa82f33abb8906dd3bfb627fbe2e487e048179e9c9199927d9aa535ef3ceb6b4b6e7f9201e5d7d1046ca3bd00b32b8495802b8bb436a04ab8c31f7d",
          "sha256": "8f66722e804ba560b28676398de3308d7dec9f0033b7dcf211858ea418c62e3a",
          "sha1": "c3c947570eb210e78716aea4e4885c951728809c",
          "md5": "5599ac0815a69f7054fe0e84162e66bf"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01-versionMetadata.json",
          "url": "window-1.4.0-alpha01-versionMetadata.json",
          "size": 31161,
          "sha512": "a9fba24368580e4f4af9625fc7bcb0d428a69ba382197401d517f6282b393b78cabd39540409c76a79815efaf2cbe75c57045d53f2e39c531a713b05b3cbc5fb",
          "sha256": "85bbc9073200c1fbee17375e8fca53484781627582fc0ebcbc31b10c985db0f9",
          "sha1": "8d1a898518c7d771c6b6bce4da18cfaf4f7177bd",
          "md5": "9147ea2196cbdfade0831374b7076549"
        }
      ]
    }
  ]
}