{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01.aar",
          "url": "window-1.4.0-alpha01.aar",
          "size": 422641,
          "sha512": "c0c820e36aeab4239d9a7ba1ca7823a8455528145352ef6fd67b0ad8b2455eec5a3ddd5e18dea5cf5075142959d46198c166eb059dd4cb7db815d94197c3449e",
          "sha256": "3a72e785c11befd0621ce77f6baa9cd7b427e394eb4267dc8e48ff835802d392",
          "sha1": "d1083546b5eccd04991127a0d9b4826ce2eac097",
          "md5": "61a36a971aac9a231bf955196be64f6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01.aar",
          "url": "window-1.4.0-alpha01.aar",
          "size": 422641,
          "sha512": "c0c820e36aeab4239d9a7ba1ca7823a8455528145352ef6fd67b0ad8b2455eec5a3ddd5e18dea5cf5075142959d46198c166eb059dd4cb7db815d94197c3449e",
          "sha256": "3a72e785c11befd0621ce77f6baa9cd7b427e394eb4267dc8e48ff835802d392",
          "sha1": "d1083546b5eccd04991127a0d9b4826ce2eac097",
          "md5": "61a36a971aac9a231bf955196be64f6d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01-sources.jar",
          "url": "window-1.4.0-alpha01-sources.jar",
          "size": 181620,
          "sha512": "e80d9d7b726b3646a1d2d1ca3ef29ec278c81591c2143372ee7bd8d37fea9c86b975b8f2941b7216bd36be877cca577b62c7504bcca0926140c9c608ea919813",
          "sha256": "425664cac740c8378c9b67db76e2aa336611cc7df153ef398c2c0ae358573cf7",
          "sha1": "d87113e71b2c7371a4bd166682cecbaa4de940de",
          "md5": "61253530b9ea3775f0000810b6e38e80"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.4.0-alpha01-versionMetadata.json",
          "url": "window-1.4.0-alpha01-versionMetadata.json",
          "size": 31164,
          "sha512": "549946a9f79e8248fb0ed860b12ca58ae06b8e497fdc64dd5c7784751525b647378490a0081bcd918cec6fa8567403b166bc05a63faf05c56c7d5eeebaf3d0a8",
          "sha256": "518fe4d64dfa2ddb9d05752c1d355f39c2909e1af3663561262b816c0371e092",
          "sha1": "e6a7f08d50b552721edfc5c79eda70c25fcb000d",
          "md5": "9d1179f57c30d0eaf63bb8d6c7eeecec"
        }
      ]
    }
  ]
}