version: "1.1.0-alpha14"
dependency_list {
  dependency {
    group_id: "androidx.constraintlayout"
    artifact_id: "constraintlayout-compose-android"
    version: "1.1.0-alpha14"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-compose"
path: "/constraintlayout/constraintlayout-compose"
sha: "94d8045d9090858f7e3e31c64a6c2af17aefa0a2"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-compose-all-12121015-1.1.0-alpha14.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: true
