version: "1.8.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-android"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-jvmstubs"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-linuxx64stubs"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.runtime"
group_id: "androidx.compose.runtime"
artifact_id: "runtime"
path: "/compose/runtime/runtime"
sha: "42c278861bdd75412e9a5b165a4dfcaeae597612"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.runtime-runtime-all-12354822-1.8.0-alpha02.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-livedata"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava2"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-rxjava3"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime-saveable"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
