{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity",
    "version": "1.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha01.aar",
          "url": "activity-1.7.0-alpha01.aar",
          "size": 111237,
          "sha512": "a71d510520e30b941747cf472e754fea1aede33d309de96804a1712ec4174e004ae2349e72954b07df3c7e1c63b19bea9783ceb400a12a6397efec9985fa2572",
          "sha256": "79ac34969641853e1cbaacbbddd2540b377c425553f07aa92856b910dd798990",
          "sha1": "5ec0bd3cbdcfb3a04ac92b5450b984018bd5bf9c",
          "md5": "fd3385b7ee7b7b395d7ebb367fccf54a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-savedstate",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.7.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "activity-1.7.0-alpha01.aar",
          "url": "activity-1.7.0-alpha01.aar",
          "size": 111237,
          "sha512": "a71d510520e30b941747cf472e754fea1aede33d309de96804a1712ec4174e004ae2349e72954b07df3c7e1c63b19bea9783ceb400a12a6397efec9985fa2572",
          "sha256": "79ac34969641853e1cbaacbbddd2540b377c425553f07aa92856b910dd798990",
          "sha1": "5ec0bd3cbdcfb3a04ac92b5450b984018bd5bf9c",
          "md5": "fd3385b7ee7b7b395d7ebb367fccf54a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "activity-1.7.0-alpha01-sources.jar",
          "url": "activity-1.7.0-alpha01-sources.jar",
          "size": 43786,
          "sha512": "9d72146c19f7ef5b77744c109a8b878e99e97848fcd6ea89b3f173fa232321c7b6963fc2a4832fcc0e6d5dcb09f31e48a6dc36b2022570d40bad54a3f0d78951",
          "sha256": "4d675dd551e7824a75ba04c1679fb952a0510ba91beddcd315a2b4a1014d4717",
          "sha1": "8af90d35b111258f964b0f3743a695a8deb574a0",
          "md5": "356dc1d47fb68ceb846d6167b6db7623"
        }
      ]
    }
  ]
}