version: "1.16.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.16.0-beta01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13076784"
group_id: "androidx.core"
artifact_id: "core-ktx"
path: "/core/core-ktx"
sha: "b59dd011af04591679cf78abe1ed912e145662e7"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-ktx-all-13076784-1.16.0-beta01.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.16.0-beta01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-ktxreleaseAndroidTest.xml"
test_module_names: ":core:core-ktx:testReleaseUnitTest"
