{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-1.4.0-alpha01-sources.jar",
          "url": "wear-1.4.0-alpha01-sources.jar",
          "size": 149734,
          "sha512": "a5745d5ca8a0566018ff19f9241adf894788a1b7d4184fec79b04a394a39d4f84d3a6cb83c3998b22df732c442544913d74c7d3eddc57a8ab9cb8688b6765424",
          "sha256": "bccb0bd0158cc0049c982fff95144c241c46cd07d0dcfafbe44b62e0aeea499a",
          "sha1": "dfa513e22cf5876a4b6a13818b66a81d09fbdca1",
          "md5": "87e3e646c7ccf554e58a4badf783552b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.4.0-alpha01.aar",
          "url": "wear-1.4.0-alpha01.aar",
          "size": 316198,
          "sha512": "45903085bf43a8c9e77b2683b1f76fa94346167ac0058563f01d3849697fed6bee88edf2e45136c9c8344eb7c5f186bb89ceb8d296730671833592ea9cf050b5",
          "sha256": "6438d12b94d0e45fc8ea3f059500463d2e46f4493b2a9cb448e0bb2ea2aa97a4",
          "sha1": "5e526eb0def9af571891305bcc059d6c183a40d0",
          "md5": "d22904e77c3a442fffc261a3d13fc048"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.2.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-1.4.0-alpha01.aar",
          "url": "wear-1.4.0-alpha01.aar",
          "size": 316198,
          "sha512": "45903085bf43a8c9e77b2683b1f76fa94346167ac0058563f01d3849697fed6bee88edf2e45136c9c8344eb7c5f186bb89ceb8d296730671833592ea9cf050b5",
          "sha256": "6438d12b94d0e45fc8ea3f059500463d2e46f4493b2a9cb448e0bb2ea2aa97a4",
          "sha1": "5e526eb0def9af571891305bcc059d6c183a40d0",
          "md5": "d22904e77c3a442fffc261a3d13fc048"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "wear-1.4.0-alpha01-versionMetadata.json",
          "url": "wear-1.4.0-alpha01-versionMetadata.json",
          "size": 27752,
          "sha512": "173d1ad1b3fe8865316b8c2f3e47c99c7096eb4ad15db70a7f7abe99ad7e28993a5657d75d614fb856e849f80670c2dcde559e66b5f2e8635b3b347132ac6ca3",
          "sha256": "a9efbf6830664fa98ea15b0f52cf0c59ab0352c70660d493c7036f805bf70528",
          "sha1": "d3e0d784f8fbc21ecd3404c25c0778258882d3f9",
          "md5": "0e9eb4dd2813da422d600f8b89825b1a"
        }
      ]
    }
  ]
}