{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13588622"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-sources.jar",
          "url": "tracing-perfetto-1.0.0-sources.jar",
          "size": 18687,
          "sha512": "80430f177ef20f47159027318e426f1135fb3e067366fa2bdd30e261186734c076abc0f87916ce409da6ae0f3a53701ca346db58532dce1a4b88fe421252ee9a",
          "sha256": "21dbe4dcd69c0ef76c8d99ad9603bdf1062095292a844330841668d98e664f5a",
          "sha1": "915d2e528b5ed74ea37fa372e8b1b5d682384ec8",
          "md5": "e0e3c2e20c25b0b4e13c8170741da8d6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0.aar",
          "url": "tracing-perfetto-1.0.0.aar",
          "size": 38214,
          "sha512": "df7910a5985ecbf397c905c68a7932c74be59c63e21724006f7ca5fcf4e866904186f7196df39c0aaede4a44630edf7f2509a5c60ab5ca3f678a2959d43a101c",
          "sha256": "6eb22fac04535fd3f03f7178bf91aa88d07942ae72874066530a0350b1968fa2",
          "sha1": "db7c2135da7b3f95bd3471b2dec6f45bafc0db49",
          "md5": "ed59e9f29b327e03fa05830ed052732a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0.aar",
          "url": "tracing-perfetto-1.0.0.aar",
          "size": 38214,
          "sha512": "df7910a5985ecbf397c905c68a7932c74be59c63e21724006f7ca5fcf4e866904186f7196df39c0aaede4a44630edf7f2509a5c60ab5ca3f678a2959d43a101c",
          "sha256": "6eb22fac04535fd3f03f7178bf91aa88d07942ae72874066530a0350b1968fa2",
          "sha1": "db7c2135da7b3f95bd3471b2dec6f45bafc0db49",
          "md5": "ed59e9f29b327e03fa05830ed052732a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-versionMetadata.json",
          "url": "tracing-perfetto-1.0.0-versionMetadata.json",
          "size": 559,
          "sha512": "fd15b9a4da1c7e479e4396688cb315094f17d9052dafe54c0c61fa72c954f6dd1aa0fd268a66b1344c9b573247e0b811b37c7ecf7e6c69cc822102d75b3af57e",
          "sha256": "bbf999fab93fd8c8f15a6f526c60b92e7ead47f8cbacdce0549a0ac5f1b8f631",
          "sha1": "fc95da7d4eff7967fa5dd14cd9ac675ab1e44b4b",
          "md5": "814a4102c1e7900eae3742337d5087c6"
        }
      ]
    }
  ]
}