{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-template",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06-sources.jar",
          "url": "glance-template-1.0.0-alpha06-sources.jar",
          "size": 23957,
          "sha512": "f83582d1082af3948f902c753186ca1bab977df7055621717f51e7328800453016abb92330b62f41f23d104089c5c624f8d8d6d3f25fab3ef14642f72458b6b8",
          "sha256": "b6948e4a9c6594e5f24be85a9409c417234daa11a6b6a5fbab37de17c49beffb",
          "sha1": "bb4fe379329a85fb7631df2554630d5c8b500733",
          "md5": "c4c2f267339bab90367407fa6e8beb6d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06.aar",
          "url": "glance-template-1.0.0-alpha06.aar",
          "size": 164746,
          "sha512": "566dfb45baa57b3ac91897c27f6ff11d909e0f1799198a280073e7e298135fc97b035ecd4937263143fc41dbe951d4512813b8d3be9e6d240068f383e7ed05b1",
          "sha256": "75e8ce792bb12bc8e01465357d119f45e416f5c898522acd8a10fe32293abdfa",
          "sha1": "d1a50380ac6e8915cab5532f91a1d2e6aa625e21",
          "md5": "a7f5726d316e8481bfa688f0eb8ac3fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06.aar",
          "url": "glance-template-1.0.0-alpha06.aar",
          "size": 164746,
          "sha512": "566dfb45baa57b3ac91897c27f6ff11d909e0f1799198a280073e7e298135fc97b035ecd4937263143fc41dbe951d4512813b8d3be9e6d240068f383e7ed05b1",
          "sha256": "75e8ce792bb12bc8e01465357d119f45e416f5c898522acd8a10fe32293abdfa",
          "sha1": "d1a50380ac6e8915cab5532f91a1d2e6aa625e21",
          "md5": "a7f5726d316e8481bfa688f0eb8ac3fd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "glance-template-1.0.0-alpha06-versionMetadata.json",
          "url": "glance-template-1.0.0-alpha06-versionMetadata.json",
          "size": 10173,
          "sha512": "93b0b77e2e6879d910d8872f622e3425a67525c619480e7803634092ce6a8012c84a19beb7a240128ffe5341bb4422e7f8ca7af84d9940007c98df9063c17f6f",
          "sha256": "bfc3e00e411b75c142c488480b9662bb656a559bae73c2ffe630f4c91478a131",
          "sha1": "c08ee97466de52b1d8f118db73ebad79aa83c6c8",
          "md5": "a085ddcbce63dca5936d7ef69e63ac97"
        }
      ]
    }
  ]
}