{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.emoji2",
    "module": "emoji2-views-helper",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.4.0-beta01.aar",
          "url": "emoji2-views-helper-1.4.0-beta01.aar",
          "size": 22068,
          "sha512": "e8ac59010d4faef224de7e97dd9f32d5d217ba85206ed82aa650eb03eb83755348fa3b884153ee063caa81e360b9a78e5bc34860f47d842f841cce79a2c19629",
          "sha256": "75b2c6956a64d9d52daba91004d77c34008388e4d78bcc01f768468b38dfcd85",
          "sha1": "71c6d415552d042ef812ebf38619d26889cf0c14",
          "md5": "bbd538de21b147a339805f6778c6a05e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.4.0-beta01.aar",
          "url": "emoji2-views-helper-1.4.0-beta01.aar",
          "size": 22068,
          "sha512": "e8ac59010d4faef224de7e97dd9f32d5d217ba85206ed82aa650eb03eb83755348fa3b884153ee063caa81e360b9a78e5bc34860f47d842f841cce79a2c19629",
          "sha256": "75b2c6956a64d9d52daba91004d77c34008388e4d78bcc01f768468b38dfcd85",
          "sha1": "71c6d415552d042ef812ebf38619d26889cf0c14",
          "md5": "bbd538de21b147a339805f6778c6a05e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.emoji2",
          "module": "emoji2-emojipicker",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-bundled",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "emoji2-views-helper-1.4.0-beta01-sources.jar",
          "url": "emoji2-views-helper-1.4.0-beta01-sources.jar",
          "size": 17378,
          "sha512": "6fe7a0e06ed4ed17b7a0242ad71970933b09be863c1fc3eebc40374357049bb922c38e00b1c7e5f5b6e94d7075c579006fbbc389b074e1c12409cb2e89f02c0a",
          "sha256": "c815bad75750d5017012b777985fa71e5ee5b6f87612a5feed820da46b4ea48e",
          "sha1": "52c6792c91cac91c84b75270e9a4ac161aaa0c41",
          "md5": "6f760cf38d33db99f3aa7ca87908aa6b"
        }
      ]
    }
  ]
}