version: "1.1.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "13108931"
group_id: "androidx.core"
artifact_id: "core-viewtree"
path: "/core/core-viewtree"
sha: "13cbfde9ec718a772ac59d7237ab17796e3ee2fa"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-viewtree-all-13108931-1.1.0-alpha01.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-viewtreereleaseAndroidTest.xml"
test_module_names: ":core:core-viewtree:testReleaseUnitTest"
