version: "1.3.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime"
    version: "2.5.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "13649143"
group_id: "androidx.hilt"
artifact_id: "hilt-navigation"
path: "/hilt/hilt-navigation"
sha: "4419db999407267f2ea4c9563a0a65c2728cd56d"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.hilt-hilt-navigation-all-13649143-1.3.0-alpha01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "hilt-hilt-navigationreleaseAndroidTest.xml"
test_module_names: ":hilt:hilt-navigation:testReleaseUnitTest"
