version: "1.0.0"
dependency_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-animation"
    version: "1.0.0"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "14059446"
group_id: "androidx.core"
artifact_id: "core-animation-testing"
path: "/core/core-animation-testing"
sha: "da32c20ed1a2ec422566c4a657945751631361a6"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-animation-testing-all-1.0.0.zip"
kotlin_version: "2.2.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-animation-testingreleaseAndroidTest.xml"
test_module_names: ":core:core-animation-testing:testReleaseUnitTest"
