version: "1.0.0"
dependency_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-animation"
    version: "1.0.0"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13291458"
group_id: "androidx.core"
artifact_id: "core-animation-testing"
path: "/core/core-animation-testing"
sha: "f7310b9889c3082fc00034dbf282c09da8a6d1c5"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-animation-testing-all-13291458-1.0.0.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-animation-testingreleaseAndroidTest.xml"
test_module_names: ":core:core-animation-testing:testReleaseUnitTest"
