version: "1.3.0-beta01"
dependency_list {
}
release_checklist {
}
build_id: "13842168"
group_id: "androidx.hilt"
artifact_id: "hilt-lifecycle-viewmodel"
path: "/hilt/hilt-lifecycle-viewmodel"
sha: "7ceb138d49622d882b103d960594301ad0a735f6"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.hilt-hilt-lifecycle-viewmodel-all-13842168-1.3.0-beta01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "hilt-hilt-lifecycle-viewmodelreleaseAndroidTest.xml"
test_module_names: ":hilt:hilt-lifecycle-viewmodel:testReleaseUnitTest"
