{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13381033"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01-sources.jar",
          "url": "appcompat-1.8.0-alpha01-sources.jar",
          "size": 505400,
          "sha512": "24b010eee28abbad6f048851a6fe8dde8a7d4c97eade251e9d7f356e978b30951e33d58d7418caddbdab6d606df967eaabcb8fdbc633cd74e93c5d451a0e12c1",
          "sha256": "1d4e0fcb6441d99f5c6127760fd4837feb1fade11d81a755b87f1502ca5959be",
          "sha1": "6ed30d15e8cb041f9f2446d750e41b936ba34dc1",
          "md5": "f4cbf17e0b67ca817cc8fdb81e0bbf46"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01.aar",
          "url": "appcompat-1.8.0-alpha01.aar",
          "size": 1209082,
          "sha512": "f8e682e3536839b42b11869529e855e0dc6168b66f903e9c8a21f5f27b696833958745084e94e89e123dc423b0b5efcb66bd52a516f2fb91eba19906f62d4bf2",
          "sha256": "1b8ef36b63b7ffaec1c42723a2eb273ef3c169ffac52541421e48892972d995a",
          "sha1": "31272875999718fdb905d4f270f1c0d50923d8b8",
          "md5": "81a9f9888a6fa08975160e6231ce7a28"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01.aar",
          "url": "appcompat-1.8.0-alpha01.aar",
          "size": 1209082,
          "sha512": "f8e682e3536839b42b11869529e855e0dc6168b66f903e9c8a21f5f27b696833958745084e94e89e123dc423b0b5efcb66bd52a516f2fb91eba19906f62d4bf2",
          "sha256": "1b8ef36b63b7ffaec1c42723a2eb273ef3c169ffac52541421e48892972d995a",
          "sha1": "31272875999718fdb905d4f270f1c0d50923d8b8",
          "md5": "81a9f9888a6fa08975160e6231ce7a28"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01-versionMetadata.json",
          "url": "appcompat-1.8.0-alpha01-versionMetadata.json",
          "size": 65991,
          "sha512": "5ce04400ce562500651a7f6f8606f103142878115d463961ef96a77fde01650735a08a134e833004c6c8ed1b505bceac1e57a66cae376030255973bc55106940",
          "sha256": "e68ec8279ea81bc3a5ff4a6c9b1fb973b7f150afdbdb8d25bbe419ca6eb32eda",
          "sha1": "7247237cfba7f7533c980ebe8759ec340cf5e204",
          "md5": "41510b2fe0ce2fc2a94a2d60e86a642f"
        }
      ]
    }
  ]
}