{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01-sources.jar",
          "url": "appcompat-1.8.0-alpha01-sources.jar",
          "size": 502693,
          "sha512": "21ecaa63cb3b97fe37e69ccc08eddb73bde48555f0b73c08ed826e1c973a8bb7edc41c22dc445187e92401a83ae1c71cbd031b26d1543ddd3c68a5da12ee354d",
          "sha256": "8942b0e77b9200a894ca7a0660c8ce2c65e6e9a113c283fdbe5667b4b96c9fea",
          "sha1": "381e743203800a6b2b918bb8869b130434f7d5d7",
          "md5": "c5716c4f283a1de1a30ec1f7cdbdb722"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01.aar",
          "url": "appcompat-1.8.0-alpha01.aar",
          "size": 1155012,
          "sha512": "c55ff0010301f4c934f33e4b7cb1be13f1c35bc9a79400d09d1431308d8d63f67cf45857f57eb5a049a65382fb99b86398be73e6648323114da3cbc72dfacc9f",
          "sha256": "297d1e3e688673b7055f52bb372466f9887abc2be79887f95ecb56056dde32f5",
          "sha1": "ee57d2e8a1494d79681d7f8680e4303520af48fb",
          "md5": "78134bbe86c6e778e0f1e3b5454ec0c5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01.aar",
          "url": "appcompat-1.8.0-alpha01.aar",
          "size": 1155012,
          "sha512": "c55ff0010301f4c934f33e4b7cb1be13f1c35bc9a79400d09d1431308d8d63f67cf45857f57eb5a049a65382fb99b86398be73e6648323114da3cbc72dfacc9f",
          "sha256": "297d1e3e688673b7055f52bb372466f9887abc2be79887f95ecb56056dde32f5",
          "sha1": "ee57d2e8a1494d79681d7f8680e4303520af48fb",
          "md5": "78134bbe86c6e778e0f1e3b5454ec0c5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "appcompat is in atomic group androidx.appcompat"
        }
      ],
      "files": [
        {
          "name": "appcompat-1.8.0-alpha01-versionMetadata.json",
          "url": "appcompat-1.8.0-alpha01-versionMetadata.json",
          "size": 69127,
          "sha512": "7450faa2c2c9bf5f6b6939657dc5c39c3cfa7b2752ed1be35be42810bd03adba9e35c1c3ac6c97d9cf8779bcc324d5ab11ea1a20ad18e834cb9f46a0f8ca9156",
          "sha256": "459af625ed36e0178909efe08b6b06e9527bfc627ffe493384fd308755cce825",
          "sha1": "b5c4acf438046953f906ffa773785d5fdef026fa",
          "md5": "890b08c0e89b2dbd09f7fc40fdf1a9f7"
        }
      ]
    }
  ]
}