{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slice",
    "module": "slice-builders",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6732122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-builders-1.1.0-alpha02.aar",
          "url": "slice-builders-1.1.0-alpha02.aar",
          "size": 70314,
          "sha512": "09f559e04481fb3007fa0485d18b4210e346aee61d1a4f77a273296e4a96624391d0ca46b8fbfa8cfa113cc6598907259a382713ffc5ab2dc82a2526bee1d21d",
          "sha256": "9e31ff95aa08b77440cbbdeceef7ae21e79cb555cb53e569eed190ff2450d079",
          "sha1": "0023df87b5c065a03d7ef5ad91e3b0dd406c2b89",
          "md5": "073d7cf7288f5446d4a098678e64fd0b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.slice",
          "module": "slice-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.remotecallback",
          "module": "remotecallback",
          "version": {
            "requires": "1.0.0-alpha02"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-builders-1.1.0-alpha02.aar",
          "url": "slice-builders-1.1.0-alpha02.aar",
          "size": 70314,
          "sha512": "09f559e04481fb3007fa0485d18b4210e346aee61d1a4f77a273296e4a96624391d0ca46b8fbfa8cfa113cc6598907259a382713ffc5ab2dc82a2526bee1d21d",
          "sha256": "9e31ff95aa08b77440cbbdeceef7ae21e79cb555cb53e569eed190ff2450d079",
          "sha1": "0023df87b5c065a03d7ef5ad91e3b0dd406c2b89",
          "md5": "073d7cf7288f5446d4a098678e64fd0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slice-builders-1.1.0-alpha02-sources.jar",
          "url": "slice-builders-1.1.0-alpha02-sources.jar",
          "size": 40288,
          "sha512": "a213abfc40288df9cac3a239d4c88e02e6a28997736706b1a0d51254592c93dde147f63b0f1775a9cbb8d86ed4864df163161ce3104575f750eebfd25130cbf5",
          "sha256": "b36a24a7df45d43520d5a789730e3acda42373563b0dfb538d1d445bac3b8b1c",
          "sha1": "9a82177177cc4abfe98b4ced288a8e13f53f4df6",
          "md5": "d0d721c4e1a28e2d6a39250d68955328"
        }
      ]
    }
  ]
}
