{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.tiles",
    "module": "tiles",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14028488"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.6.0-alpha01-sources.jar",
          "url": "tiles-1.6.0-alpha01-sources.jar",
          "size": 84499,
          "sha512": "58fb45e35b5e6f4d2f0c7216c20eca48b9f6c7288a69e7ec9ffaa31fe97111b19692a412a2e91e01bf49e465f9b5644bb73460b0840a57adda9074dea634d331",
          "sha256": "2d61e873061f3e0d4caf014c770dad32a5874fdda5f729f350114ca79a7760d7",
          "sha1": "398cbf96d0995e3b9343e8b59e5b19e101d735ba",
          "md5": "f2fee76d26f31c915118432ad062ef80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.6.0-alpha01.aar",
          "url": "tiles-1.6.0-alpha01.aar",
          "size": 295400,
          "sha512": "add5d01a54cb561c3a935c5781e900e4e29a35117c39ed95962238ddf5287f4fd114d8908d66076c4791190f7bc351f1123ef7bdd6b23dcf5970fac243f67319",
          "sha256": "527067bfa60620ae296e7ad1346a2da2c2f053061d1e763c2582e26e97cf9695",
          "sha1": "3198b5893f1e038d6c0166124fedbe8bd6994247",
          "md5": "be256de93e19988651174feb8da5f483"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.6.0-alpha01.aar",
          "url": "tiles-1.6.0-alpha01.aar",
          "size": 295400,
          "sha512": "add5d01a54cb561c3a935c5781e900e4e29a35117c39ed95962238ddf5287f4fd114d8908d66076c4791190f7bc351f1123ef7bdd6b23dcf5970fac243f67319",
          "sha256": "527067bfa60620ae296e7ad1346a2da2c2f053061d1e763c2582e26e97cf9695",
          "sha1": "3198b5893f1e038d6c0166124fedbe8bd6994247",
          "md5": "be256de93e19988651174feb8da5f483"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-material",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-proto",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-renderer",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "tiles is in atomic group androidx.wear.tiles"
        }
      ],
      "files": [
        {
          "name": "tiles-1.6.0-alpha01-versionMetadata.json",
          "url": "tiles-1.6.0-alpha01-versionMetadata.json",
          "size": 68998,
          "sha512": "1964adaa82d6b96c8785d18f02f0bfc0917c6f4cadc04ec720f06735e713fef3a2cfe61688758b06ecf0fe07d7381ad9d71e47ba120c6ec289849f4db2de291e",
          "sha256": "9afbc091be5fafc7156bbeaab802dbb7a6db5c0965ceece699f0493fb08fe67c",
          "sha1": "0d192c1afe2269ba29388cd7bf4d36e528f3ad64",
          "md5": "2b5459ab3d55d4f6e871380e9eca8ea2"
        }
      ]
    }
  ]
}