version: "1.2.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "13412782"
group_id: "androidx.hilt"
artifact_id: "hilt-common"
path: "/hilt/hilt-common"
sha: "0fbdce2530fad7d34ac65ef453b17d9ccc68e4c2"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.hilt-hilt-common-all-13412782-1.2.0-rc01.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":hilt:hilt-common:test"
