version: "1.13.0-alpha03"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.13.0-alpha03"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.core"
group_id: "androidx.core"
artifact_id: "core-ktx"
path: "/core/core-ktx"
sha: "7c74f6025670578d35b8344bbe1b52b2cdbcd588"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-core-11273968.zip"
project_zip_path: "per-project-zips/androidx.core-core-ktx-all-11273968-1.13.0-alpha03.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.13.0-alpha03"
    is_tip_of_tree: true
  }
}
