{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.textclassifier",
    "module": "textclassifier",
    "version": "1.0.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6761364"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "textclassifier-1.0.0-alpha03.aar",
          "url": "textclassifier-1.0.0-alpha03.aar",
          "size": 286048,
          "sha512": "173b8ddbe30be00f8cf27608a96faeb7852a587406fc5f06b69b45f4d8f35439497e9a9c3dd9899e96702085122366f47b4cab8f1d8632b1c539e8a649fe3019",
          "sha256": "829c828764d72e2d5e5a90263457d515c17595898b96c0c3dfa47156e6004ba7",
          "sha1": "3f7ac0a83624f3b28cce2c5196b6d42c0a429971",
          "md5": "506168d798c024ac855bf106077882db"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "textclassifier-1.0.0-alpha03.aar",
          "url": "textclassifier-1.0.0-alpha03.aar",
          "size": 286048,
          "sha512": "173b8ddbe30be00f8cf27608a96faeb7852a587406fc5f06b69b45f4d8f35439497e9a9c3dd9899e96702085122366f47b4cab8f1d8632b1c539e8a649fe3019",
          "sha256": "829c828764d72e2d5e5a90263457d515c17595898b96c0c3dfa47156e6004ba7",
          "sha1": "3f7ac0a83624f3b28cce2c5196b6d42c0a429971",
          "md5": "506168d798c024ac855bf106077882db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "textclassifier-1.0.0-alpha03-sources.jar",
          "url": "textclassifier-1.0.0-alpha03-sources.jar",
          "size": 81645,
          "sha512": "3af5cde8ad86ba7103c99734ebfbd5b78840c50d0dd30a76f5ee4c5056e4ed5d2a56162e52fd7249899bd91243bc428b1148e184d3e8202c9029ce4865cb58ef",
          "sha256": "a9c8f7320f1255bf633077130e20e9bbe46eff9cf67552a02fb1aecd3c79a772",
          "sha1": "a0990ebfe30173e2b760a162f67b2c368f509250",
          "md5": "6eefbb55e5c4123ed963df56456ef9e3"
        }
      ]
    }
  ]
}
