version: "1.1.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-core"
path: "/constraintlayout/constraintlayout-core"
sha: "6ddbf71a81eca2ba00cec3adfa4702337310637c"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-core-all-12295974-1.1.0-beta01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
