{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.5.0-alpha11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13170929"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha11-sources.jar",
          "url": "compose-material-1.5.0-alpha11-sources.jar",
          "size": 183929,
          "sha512": "710ec7203738105e77e0a54923e04ee30cdac7a3d89e3acc81408777a522906a60ad05c8357234bb7b88ab5058d96b6b2a34a29561e8a17325b351df62734a63",
          "sha256": "5a650b81c196bac9a7f025d5fa5e11354e0d6582b44bdafd4d4250f8da2e641d",
          "sha1": "2980a30b2e04608f83bcd80d5e334f2789519e06",
          "md5": "d1a6c18fc8dfce44d2d8538fe76185b0"
        },
        {
          "name": "compose-material-1.5.0-alpha11-samples-sources.jar",
          "url": "compose-material-1.5.0-alpha11-samples-sources.jar",
          "size": 36690,
          "sha512": "9dd98986e224a2a662d85dc8ccc544a73296d979dff8683c7824bcc646de23e6c0312e750d601cf5ca1f2ff3fcfd3ded05132aa049ab874549b2dcc10a38b066",
          "sha256": "35fbeaa1b0f3b1e1cf26102f643a636b1d17a4c2f2f1966195d5786a2b775339",
          "sha1": "f52c084273532fd4c98565a2af00761763285d23",
          "md5": "42cd363100ee613946683a94307d7f09"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha11"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha11.aar",
          "url": "compose-material-1.5.0-alpha11.aar",
          "size": 1026722,
          "sha512": "fb14883b7f0429af1730d20bf698d795ade4d610541d4576f12c114d441503338b56f37491166b94b700c4c54a6bd36ca66076d52caa3b20697383e2c8e42f0c",
          "sha256": "1b4ed3a44e5854d6ba8ca21b848f81695123f8dfd25af3be15565680ab48a2af",
          "sha1": "8a5a3b7efa285d1508db81f5cc1b6bf62df867ba",
          "md5": "a979e6b1a80d45235087efc09c25dc07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha11"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha11"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha11.aar",
          "url": "compose-material-1.5.0-alpha11.aar",
          "size": 1026722,
          "sha512": "fb14883b7f0429af1730d20bf698d795ade4d610541d4576f12c114d441503338b56f37491166b94b700c4c54a6bd36ca66076d52caa3b20697383e2c8e42f0c",
          "sha256": "1b4ed3a44e5854d6ba8ca21b848f81695123f8dfd25af3be15565680ab48a2af",
          "sha1": "8a5a3b7efa285d1508db81f5cc1b6bf62df867ba",
          "md5": "a979e6b1a80d45235087efc09c25dc07"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha11"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha11-versionMetadata.json",
          "url": "compose-material-1.5.0-alpha11-versionMetadata.json",
          "size": 83442,
          "sha512": "69d47ad5078e82ab28295af55b39b8eb9e53abd32dd75a102e8ae9e45b23fb61d7c485f83a7897765c86254a31a2afeb49cfe0b640ee6a957154117d9ba930e9",
          "sha256": "6c98052906b1c09cd540895e0d7cb5ee3446766bcd6de8d6a2e41b3238b244c6",
          "sha1": "fa4b5f9e70b357d4c92140b520685d103dbbcd0f",
          "md5": "3cdddaedb7ce93e1ca1898f955efe8b8"
        }
      ]
    }
  ]
}