{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.3.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha08"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.3.0-alpha08.aar",
          "url": "compose-material-1.3.0-alpha08.aar",
          "size": 1153819,
          "sha512": "3462c08ec48fb65673b0716e90107fb0581a8285f760e735c24ceccaa164c82a13ce5443135dae03abac3ad0764e7403404bec8e6b65688f48aa388377a9fc4a",
          "sha256": "dd238784ab7ebd3b299149eed115338f9d0b0667a4d5aac43c4fa029d9e70d6c",
          "sha1": "5ed3502eb5915115b41104c504e8f4d7a208878a",
          "md5": "2455d9e1acacdd3446dc21a58527bc8e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha08"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.3.0-alpha08.aar",
          "url": "compose-material-1.3.0-alpha08.aar",
          "size": 1153819,
          "sha512": "3462c08ec48fb65673b0716e90107fb0581a8285f760e735c24ceccaa164c82a13ce5443135dae03abac3ad0764e7403404bec8e6b65688f48aa388377a9fc4a",
          "sha256": "dd238784ab7ebd3b299149eed115338f9d0b0667a4d5aac43c4fa029d9e70d6c",
          "sha1": "5ed3502eb5915115b41104c504e8f4d7a208878a",
          "md5": "2455d9e1acacdd3446dc21a58527bc8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.3.0-alpha08-sources.jar",
          "url": "compose-material-1.3.0-alpha08-sources.jar",
          "size": 168214,
          "sha512": "88dea868bd5565cb1b9df29f19b11566dea38296bf02e66266dadeee0a839abb5cbd7ede2f4779c8b54600ff366be06f4b5f98b445a9495cc8a10bad5e60efec",
          "sha256": "3acadc23a3f9a06c8535e91ded7fe49283602862c7d38baa095d8801070497cb",
          "sha1": "87539ab72dbc04834c33b7938f7293b804ac5831",
          "md5": "9ab51a11bc4ba82aecd755f1ed43623f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha08"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.3.0-alpha08-versionMetadata.json",
          "url": "compose-material-1.3.0-alpha08-versionMetadata.json",
          "size": 78611,
          "sha512": "58e24d9e1a3cd59bcc77bebb7e05bfd33035ea6ff7fdd7d788716f80e683dc86d596e517cb7da861731092bdcbc079d0feb1c4afbe112f62bd207c888e798333",
          "sha256": "4c83685f7722c164b8b41930f697ea8df33fa568ca670bd76283ada8cfd02dee",
          "sha1": "ffae5dae1d00432b634198837bcdcd152a4826f5",
          "md5": "9f87844e31ba45f4ad45038114e21d3a"
        }
      ]
    }
  ]
}