{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime",
    "version": "3.2.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.2.0-alpha04"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.2.0-alpha04"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.2.0-alpha04.aar",
          "url": "paging-runtime-3.2.0-alpha04.aar",
          "size": 78874,
          "sha512": "c22c7b60fcb09e2557022ca56a0385b3a73f6870a577309a6fb3d4c9a1f7a1636f9b064d0606df0bbea601726826af18cacf5719939f14509d7c335fe03b94ff",
          "sha256": "81199a626b55418181c431d14d2648e5477c3b1e6a3678d9710fcbf9836889e0",
          "sha1": "847881aaacd297c020b478c8f8b5ed80ecc1d157",
          "md5": "63a90825224b28e513d087bc68baac2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.2.0-alpha04"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.2.0-alpha04"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.2.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.2.0-alpha04.aar",
          "url": "paging-runtime-3.2.0-alpha04.aar",
          "size": 78874,
          "sha512": "c22c7b60fcb09e2557022ca56a0385b3a73f6870a577309a6fb3d4c9a1f7a1636f9b064d0606df0bbea601726826af18cacf5719939f14509d7c335fe03b94ff",
          "sha256": "81199a626b55418181c431d14d2648e5477c3b1e6a3678d9710fcbf9836889e0",
          "sha1": "847881aaacd297c020b478c8f8b5ed80ecc1d157",
          "md5": "63a90825224b28e513d087bc68baac2c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-3.2.0-alpha04-sources.jar",
          "url": "paging-runtime-3.2.0-alpha04-sources.jar",
          "size": 37524,
          "sha512": "ba2893a9d2b0330b75ddfcf05c965bb034e7bac4e8c71160db0cb3dc6fa98798cb42a3bcfe7210fff2cd1f9f9837c36c34b393060e0ac1f25f77788fe9c3219c",
          "sha256": "88156c166d7dbec0fd093cf19caf403a9ea06c28f901510c88ffae2a4631ce81",
          "sha1": "27f53a9998ebaa6be13a3d394235e9c2ee7e191c",
          "md5": "59244acb699cd8390b3427527666f786"
        }
      ]
    }
  ]
}