{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.savedstate",
    "module": "savedstate-ktx",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14059446"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0-alpha03-sources.jar",
          "url": "savedstate-ktx-1.4.0-alpha03-sources.jar",
          "size": 4426,
          "sha512": "470b68b1ba0bbefe5afcf0a072635a72e5080f040860d900c972c9797c1ab4c2402ad6a622477ea916ecc6ece19b0290e15a391f7f1a0ea00c612b1da3ea6d82",
          "sha256": "b1e8d78600a68fb3c0029793146ac07ea0335819f813554e85c568caa35cb5e4",
          "sha1": "d281a4d66d1b5ed25c21373dedb46a67918618d9",
          "md5": "c7dd8c25948273de8256385c8a05e3d7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0-alpha03.aar",
          "url": "savedstate-ktx-1.4.0-alpha03.aar",
          "size": 5772,
          "sha512": "13f192bd8516ecf74453c2c223c720f770a508d2ea0c0d01182bf2e90090f1f59f05aa477b4b819edffc6bed765fbe13e14aeee8568eafeb4371db890e281b03",
          "sha256": "65391d3ee50274247f166bdceac6ad620b71ffc07c7740827b4b4f8adc6d4781",
          "sha1": "b4aa0ad2f58f4d58bbda077487191b2c39221870",
          "md5": "ad9eb7720edfc56d2c5260ea26c91cee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0-alpha03.aar",
          "url": "savedstate-ktx-1.4.0-alpha03.aar",
          "size": 5772,
          "sha512": "13f192bd8516ecf74453c2c223c720f770a508d2ea0c0d01182bf2e90090f1f59f05aa477b4b819edffc6bed765fbe13e14aeee8568eafeb4371db890e281b03",
          "sha256": "65391d3ee50274247f166bdceac6ad620b71ffc07c7740827b4b4f8adc6d4781",
          "sha1": "b4aa0ad2f58f4d58bbda077487191b2c39221870",
          "md5": "ad9eb7720edfc56d2c5260ea26c91cee"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-compose",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate-testing",
          "version": {
            "requires": "1.4.0-alpha03"
          },
          "reason": "savedstate-ktx is in atomic group androidx.savedstate"
        }
      ],
      "files": [
        {
          "name": "savedstate-ktx-1.4.0-alpha03-versionMetadata.json",
          "url": "savedstate-ktx-1.4.0-alpha03-versionMetadata.json",
          "size": 191,
          "sha512": "225072cf1e54fc7479700f5339019ceafe1f9e4d514a8893a626190d42dfb31b35804c73597292ee864e5f3034bc73b4c5806109ed130eb268c531948a4be4b7",
          "sha256": "ff1847220d3c526a133e4f76baed2060de09a72ac96f5b8e1fef2ab1d21ba85e",
          "sha1": "a1a2692ed79fa0caa20fafeb33e56bd48993f6de",
          "md5": "57c4eed7a9c15485d30d344fdc944a0a"
        }
      ]
    }
  ]
}