version: "1.1.0-beta10"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.concurrent"
    artifact_id: "concurrent-futures"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices"
    version: "1.1.0-beta10"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.ads"
group_id: "androidx.privacysandbox.ads"
artifact_id: "ads-adservices-java"
path: "/privacysandbox/ads/ads-adservices-java"
sha: "82f7f4f17bdc4d685b50d2e00c06c920cf2b6572"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.ads-ads-adservices-java-all-12437715-1.1.0-beta10.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices"
    version: "1.1.0-beta10"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
