version: "2.9.0-alpha07"
dependency_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.4.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-common"
    version: "2.8.7"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime"
    version: "2.8.7"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel"
    version: "2.8.7"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-android"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-desktop"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-iosarm64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-iossimulatorarm64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-iosx64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-linuxarm64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-linuxx64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-macosarm64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-macosx64"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13115689"
group_id: "androidx.navigation"
artifact_id: "navigation-runtime"
path: "/navigation/navigation-runtime"
sha: "116bf3edf6cb0604a2cd55babf4fdeb279e5f3f7"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.navigation-navigation-runtime-all-13115689-2.9.0-alpha07.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-common-ktx"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-compose"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-fragment"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-dynamic-features-runtime"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-compose"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-fragment-ktx"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-runtime-ktx"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-generator"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-safe-args-gradle-plugin"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-testing"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigation"
    artifact_id: "navigation-ui-ktx"
    version: "2.9.0-alpha07"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "android"
kmp_children: "desktop"
kmp_children: "macosx64"
kmp_children: "macosarm64"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
test_module_names: ":navigation:navigation-runtime:desktopTest"
test_module_names: ":navigation:navigation-runtime:macosX64Test"
test_module_names: ":navigation:navigation-runtime:macosArm64Test"
test_module_names: ":navigation:navigation-runtime:linuxX64Test"
test_module_names: ":navigation:navigation-runtime:iosX64Test"
test_module_names: ":navigation:navigation-runtime:iosSimulatorArm64Test"
test_module_names: "navigation-navigation-runtimereleaseAndroidTest.xml"
test_module_names: ":navigation:navigation-runtime:testReleaseUnitTest"
