version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core-okio"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-iosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-iossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-iosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-jvm"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-linuxarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-linuxx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-macosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-macosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-tvosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-tvossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-tvosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-watchosarm32"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-watchosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-watchossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core-watchosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.datastore"
group_id: "androidx.datastore"
artifact_id: "datastore-preferences-core"
path: "/datastore/datastore-preferences-core"
sha: "073ba66e837b493a7e0136379507f9fbb33f2ce9"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.datastore-datastore-preferences-core-all-12565334-1.2.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core-okio"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-guava"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-external-protobuf"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "jvm"
kmp_children: "macosx64"
kmp_children: "macosarm64"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "watchosx64"
kmp_children: "watchosarm64"
kmp_children: "watchossimulatorarm64"
kmp_children: "tvosx64"
kmp_children: "tvosarm64"
kmp_children: "tvossimulatorarm64"
