{
  "formatVersion": "1.1",
  "component": {
    "url": "../../datastore-preferences-core/1.2.0-alpha01/datastore-preferences-core-1.2.0-alpha01.module",
    "group": "androidx.datastore",
    "module": "datastore-preferences-core",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-jvm-1.2.0-alpha01.jar",
          "url": "datastore-preferences-core-jvm-1.2.0-alpha01.jar",
          "size": 37340,
          "sha512": "d79f765fffc6be651f662f4dc0a9ba6a72239daf1cc71193a96ee1494fe98ea9d78533228303963566a1e6f643f3cfd8a8a28f240b28ae30bc0d17035c8c399e",
          "sha256": "9b38f1492ebfcb43f943e81d89a0007e11d59174084e5825963cc4a9c97822b3",
          "sha1": "aec3ed5b10eff3d1bec454360cb2663b395874b4",
          "md5": "3db09e8cf63ec1ed8dc3ecf1256f8e1c"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-jvm-1.2.0-alpha01.jar",
          "url": "datastore-preferences-core-jvm-1.2.0-alpha01.jar",
          "size": 37340,
          "sha512": "d79f765fffc6be651f662f4dc0a9ba6a72239daf1cc71193a96ee1494fe98ea9d78533228303963566a1e6f643f3cfd8a8a28f240b28ae30bc0d17035c8c399e",
          "sha256": "9b38f1492ebfcb43f943e81d89a0007e11d59174084e5825963cc4a9c97822b3",
          "sha1": "aec3ed5b10eff3d1bec454360cb2663b395874b4",
          "md5": "3db09e8cf63ec1ed8dc3ecf1256f8e1c"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "datastore-preferences-core is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-core-jvm-1.2.0-alpha01-sources.jar",
          "url": "datastore-preferences-core-jvm-1.2.0-alpha01-sources.jar",
          "size": 19746,
          "sha512": "a9cb9996c87a1a7aa4f04274ddf998ae1d910cd05e4d50b77100558f370d6c0ffc4ccd0db5decbdb4d689f3edc94722828c498a203261e52e6fd2c5c9a7d7fc1",
          "sha256": "e2363911277bcc88e04f57ba80f56451beb19b275184bd81dae9f0bbc01c9813",
          "sha1": "bab5f055dd048164c8f7eb05f6efc841ef724231",
          "md5": "cf63eadfb64887cee6f2e90b8e176e9a"
        }
      ]
    }
  ]
}