{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat",
    "version": "1.7.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-alpha03.aar",
          "url": "appcompat-1.7.0-alpha03.aar",
          "size": 1174284,
          "sha512": "27b26f440f4af1c4d1508a407cfe85c9bb9101e83ab4c1198e9143338ac8879cf953178509344f7f04278c8155c2cf0c2ba618135bdcd58661b48746ab7d4705",
          "sha256": "9e7f613c0c6f03dfcabfd44a384b478b2a363d9184fbbb0d2865c5e4c4cd679a",
          "sha1": "61e5bca0f30622389059343c8cc5b4b62ffee03d",
          "md5": "74cb99c587fb2041246a09ce8ef411b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.cursoradapter",
          "module": "cursoradapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.drawerlayout",
          "module": "drawerlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.emoji2",
          "module": "emoji2-views-helper",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.resourceinspection",
          "module": "resourceinspection-annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.savedstate",
          "module": "savedstate",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-alpha03.aar",
          "url": "appcompat-1.7.0-alpha03.aar",
          "size": 1174284,
          "sha512": "27b26f440f4af1c4d1508a407cfe85c9bb9101e83ab4c1198e9143338ac8879cf953178509344f7f04278c8155c2cf0c2ba618135bdcd58661b48746ab7d4705",
          "sha256": "9e7f613c0c6f03dfcabfd44a384b478b2a363d9184fbbb0d2865c5e4c4cd679a",
          "sha1": "61e5bca0f30622389059343c8cc5b4b62ffee03d",
          "md5": "74cb99c587fb2041246a09ce8ef411b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat-resources",
          "version": {
            "requires": "1.7.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-1.7.0-alpha03-sources.jar",
          "url": "appcompat-1.7.0-alpha03-sources.jar",
          "size": 503376,
          "sha512": "ffed669b29948c692f2283c07e1803d79cf41a4a3383c28a2d97d85f91568c9170ab820f6054bdf0bbd05f919569389502895ede07fc2cc63622e5b1769ebe4d",
          "sha256": "80161d0d59369f770719911adb2ee9bc9776a2802addca9d7c2354e8d1011c41",
          "sha1": "6cbfbd8bba44c4a8514c58a7432aceb06a43af92",
          "md5": "d54432a39473aaac0d27688d647851ed"
        }
      ]
    }
  ]
}