version: "1.4.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "d6116feb5432ed04fb1e0a117abfbfac2fbe9d87"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-annotation-11134599.zip"
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-11134599-1.4.0-alpha01.zip"
kotlin_version: "1.9.20"
dependency_constraint_list {
}
