{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13842168"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.10-1.0.24"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.8.0-alpha01.jar",
          "url": "room-compiler-processing-2.8.0-alpha01.jar",
          "size": 937191,
          "sha512": "9826cc2870efd066b134513f959ddd73d7cec93384927e16b9727880dd05662a49abb910d0c41037b7eef2c3985133c5bc22099eddb912b1d8210a2b9fd608de",
          "sha256": "d694530f4c138b2e9ac3bea41cabd9d18bf1d4bd65e1dc0698ecc8fa405d2424",
          "sha1": "85b597329736bb7c5727a04351a96ba709709e15",
          "md5": "99cf06eaaeeb4b4a601c9f0413e71e7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.10-1.0.24"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.2.1-jre"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet-javapoet",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.8.0-alpha01.jar",
          "url": "room-compiler-processing-2.8.0-alpha01.jar",
          "size": 937191,
          "sha512": "9826cc2870efd066b134513f959ddd73d7cec93384927e16b9727880dd05662a49abb910d0c41037b7eef2c3985133c5bc22099eddb912b1d8210a2b9fd608de",
          "sha256": "d694530f4c138b2e9ac3bea41cabd9d18bf1d4bd65e1dc0698ecc8fa405d2424",
          "sha1": "85b597329736bb7c5727a04351a96ba709709e15",
          "md5": "99cf06eaaeeb4b4a601c9f0413e71e7a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-sqlite-wrapper",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.8.0-alpha01"
          },
          "reason": "room-compiler-processing is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.8.0-alpha01-sources.jar",
          "url": "room-compiler-processing-2.8.0-alpha01-sources.jar",
          "size": 280748,
          "sha512": "212bd90f938b5e881e4e124ffcb63198aaac2cac3071cbef4d20f91d7ea140924a0be8e5f4b1fd56d3668b822faad39a7260ff88425f44122b16545bde6989d4",
          "sha256": "227e1be04d5f55226f70992d4571a7212f5883312073afa5c4e2bb37b680738a",
          "sha1": "2fc3ff35688a7a4255c75ee676d8f992367577f6",
          "md5": "02e6aaa99072954c663e7f4a40b5b320"
        }
      ]
    }
  ]
}