{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.leanback",
    "module": "leanback-grid",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12877714"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "leanback-grid-1.0.0-beta01-sources.jar",
          "url": "leanback-grid-1.0.0-beta01-sources.jar",
          "size": 82009,
          "sha512": "2c1d5593129acee548e4b25adbf39d8b54a77f5c49400fb89c4a41de61c820ce1792e6fe5bcdd0a18ac35c0aefb58315f44accaaf5df817e298299e31a49d01f",
          "sha256": "e72ad9903e95302864358394f19f165d27f678a11757fe5184344be3c9e72cb8",
          "sha1": "74434dd9fed77915ac74a4c0b236cabfe2efa973",
          "md5": "c58559aed399e84250ec3b0868dd6666"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "leanback-grid-1.0.0-beta01.aar",
          "url": "leanback-grid-1.0.0-beta01.aar",
          "size": 103727,
          "sha512": "ad5edf9976b9d5f8f7dd200cd8a5c7defc0ca31b1ca722c30deddfc5fb746dac2d7aeb2be9944fa1b17ef9b4dfb8b448ff25206181b04da2462f513f016b2b13",
          "sha256": "40a89727bdc9cabf71a5c2520a6461eb7c79efa5fb4d8e14ea343b7fba7bfcc3",
          "sha1": "9d030f4d7201dea62ef3105c987b6636805858bc",
          "md5": "ac3cfc22fa44f646eadfd85e8b591139"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.2.0-beta01"
          }
        }
      ],
      "files": [
        {
          "name": "leanback-grid-1.0.0-beta01.aar",
          "url": "leanback-grid-1.0.0-beta01.aar",
          "size": 103727,
          "sha512": "ad5edf9976b9d5f8f7dd200cd8a5c7defc0ca31b1ca722c30deddfc5fb746dac2d7aeb2be9944fa1b17ef9b4dfb8b448ff25206181b04da2462f513f016b2b13",
          "sha256": "40a89727bdc9cabf71a5c2520a6461eb7c79efa5fb4d8e14ea343b7fba7bfcc3",
          "sha1": "9d030f4d7201dea62ef3105c987b6636805858bc",
          "md5": "ac3cfc22fa44f646eadfd85e8b591139"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "leanback-grid-1.0.0-beta01-versionMetadata.json",
          "url": "leanback-grid-1.0.0-beta01-versionMetadata.json",
          "size": 13607,
          "sha512": "6f26974a8f53a66b63442d6d2c10fc66e7cb57008a7c8c36ae61fbe67da326d121626ac37c33bfeeb8cb7cc243d5cfd0fe95b72e073f2b2d70030c96b634a5ca",
          "sha256": "d51f06833e4aa1abb8719317a269ce2b843d7b7949d456bc6e03f5ba5ac85fd3",
          "sha1": "86d24e5a0105dc8d840c5d618961d97228cd6706",
          "md5": "96d5d9fd799fb4e555846cf496a0e0da"
        }
      ]
    }
  ]
}