version: "1.1.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.6.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.versionedparcelable"
    artifact_id: "versionedparcelable"
    version: "1.1.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.wear"
group_id: "androidx.wear"
artifact_id: "wear-ongoing"
path: "/wear/wear-ongoing"
sha: "f81f28f6e2e782b92d26b531542dbdd537e1c690"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.wear-wear-ongoing-all-12346335-1.1.0-alpha02.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
