{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear",
    "module": "wear-ongoing",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-ongoing-1.1.0-alpha02.aar",
          "url": "wear-ongoing-1.1.0-alpha02.aar",
          "size": 27882,
          "sha512": "4fbbf4d7eaea2bcd39de67e0efe876dc5b66fd6e0b835c94a4b274bab398dcd616728597ce5adc9c18ae2bc257acfeb4fa211a49a942f6df0018c134d6c5e0fa",
          "sha256": "7f318a7dff51e1cd81fea6322677075d7475dd8a83a5c7ca5a95c33156a59bbe",
          "sha1": "3c25f4f0d9e86afb0635f57165e3b3c863497c10",
          "md5": "4584cb1b6e1b6a3aef75da99800b453e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "wear-ongoing-1.1.0-alpha02.aar",
          "url": "wear-ongoing-1.1.0-alpha02.aar",
          "size": 27882,
          "sha512": "4fbbf4d7eaea2bcd39de67e0efe876dc5b66fd6e0b835c94a4b274bab398dcd616728597ce5adc9c18ae2bc257acfeb4fa211a49a942f6df0018c134d6c5e0fa",
          "sha256": "7f318a7dff51e1cd81fea6322677075d7475dd8a83a5c7ca5a95c33156a59bbe",
          "sha1": "3c25f4f0d9e86afb0635f57165e3b3c863497c10",
          "md5": "4584cb1b6e1b6a3aef75da99800b453e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wear-ongoing-1.1.0-alpha02-sources.jar",
          "url": "wear-ongoing-1.1.0-alpha02-sources.jar",
          "size": 19792,
          "sha512": "0a15c37828a8df494419b69df1579146943c4af2239ca5c580318ed39c3c8461d1f2bb5e56972fc95ca8fa864fefe80eacb781d548ad431a2f2d2566582e6d56",
          "sha256": "48b5dd7a6e21a2ab4cb87fc719d1032a99658c0bef0171d7955ef42d193065e4",
          "sha1": "c4e343f5fce44026319db8997b6b0bd438c5006d",
          "md5": "5b10943c7fa7be9394ed2219783d98e0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "wear-ongoing-1.1.0-alpha02-versionMetadata.json",
          "url": "wear-ongoing-1.1.0-alpha02-versionMetadata.json",
          "size": 5289,
          "sha512": "9fa721b4883460d6e8794264f41d18e4fa6534c461c752cc833f7e95a658d8d3495e8223f9072cf95a754fbf5854df970b2a77a7954614145e8a024416d8fe5d",
          "sha256": "0736d274aa07e7ef60a5bc8e2fbb901f59af12ccbb7f7456339108463e2e591c",
          "sha1": "3940392c0e15af7028509eeced50a19db1568565",
          "md5": "f1d2b93060f089c428da41a50e175457"
        }
      ]
    }
  ]
}