version: "1.0.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "14059446"
group_id: "androidx.privacysandbox.tools"
artifact_id: "tools-apipackager"
path: "/privacysandbox/tools/tools-apipackager"
sha: "da32c20ed1a2ec422566c4a657945751631361a6"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.tools-tools-apipackager-all-1.0.0-alpha13.zip"
kotlin_version: "2.2.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apicompiler"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apigenerator"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core-external-protobuf"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
target: "androidx"
test_module_names: ":privacysandbox:tools:tools-apipackager:test"
