version: "1.0.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.12.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.graphics"
group_id: "androidx.graphics"
artifact_id: "graphics-path"
path: "/graphics/graphics-path"
sha: "11c19be60ea117818f91632bc01913a62f9ea42d"
require_same_version_group_build: false
group_zip_path: "per-group-zips/gmaven-androidx-graphics-11392413.zip"
project_zip_path: "per-project-zips/androidx.graphics-graphics-path-all-11392413-1.0.0-rc01.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
