{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.4.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.4.0-alpha03.aar",
          "url": "foundation-1.4.0-alpha03.aar",
          "size": 3169025,
          "sha512": "367e00286d0bc61c1f52c992e50858a482b5456aebfdef6bc0084f19c34470c87939eb4af62509d0f3cfba56f7bb61b1fc205c16807ee71dff95af94ea4f75b2",
          "sha256": "227085a70504e9db3cf7d1a60833dd952fb63830ff239eb86510addc7619fee1",
          "sha1": "060b78a0b3ef58d9bb29e002bd03b7c8aef76ff2",
          "md5": "3f4ad19486c0f6753087655c0b499f80"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-alpha03"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.21"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.4.0-alpha03.aar",
          "url": "foundation-1.4.0-alpha03.aar",
          "size": 3169025,
          "sha512": "367e00286d0bc61c1f52c992e50858a482b5456aebfdef6bc0084f19c34470c87939eb4af62509d0f3cfba56f7bb61b1fc205c16807ee71dff95af94ea4f75b2",
          "sha256": "227085a70504e9db3cf7d1a60833dd952fb63830ff239eb86510addc7619fee1",
          "sha1": "060b78a0b3ef58d9bb29e002bd03b7c8aef76ff2",
          "md5": "3f4ad19486c0f6753087655c0b499f80"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-1.4.0-alpha03-sources.jar",
          "url": "foundation-1.4.0-alpha03-sources.jar",
          "size": 434604,
          "sha512": "25e37f2c5d33cd54df9b25273f5e60c9a11ce9402c74403e7c5d7d61ea80e89b0d30f44bebd21fe2d482b74ad71e4f39a503a5d866aeb333bccaac5d68710901",
          "sha256": "dc80205693098ae21996e6809fb555cc1d06126211ecaec01add04589eebba0b",
          "sha1": "65c0aba7a647980097f72ca1379ed6730e99b758",
          "md5": "1716b1c45c27bfe995e0cdc75fdf3a34"
        }
      ]
    }
  ]
}