version: "1.1.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.constraintlayout"
    artifact_id: "constraintlayout-compose-android"
    version: "1.1.0-alpha13"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-compose"
path: "/constraintlayout/constraintlayout-compose"
sha: "c51dbd6a1ccf75fe56e39fcf5a13bb52b5faf250"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-compose-all-11691180-1.1.0-alpha13.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: true
