version: "1.1.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.constraintlayout"
    artifact_id: "constraintlayout-compose-android"
    version: "1.1.0-alpha13"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-compose"
path: "/constraintlayout/constraintlayout-compose"
sha: "60fc71cca80acbb8d9a484e05653423ad8aeade4"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-compose-all-11621902-1.1.0-alpha13.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
}
should_publish_docs: true
