{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler-hosted",
    "version": "1.5.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler",
          "version": {
            "requires": "1.5.11"
          },
          "reason": "compiler-hosted is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-hosted-1.5.11.jar",
          "url": "compiler-hosted-1.5.11.jar",
          "size": 1152377,
          "sha512": "e1457575887276c4326c1b5f570d8327906733bcc5b3be394b4e969f74b36196b2080eb4ab500e532c13f79f11c558b5ca046de4c13d35ade6d576f7be2ee1a2",
          "sha256": "1c341b635ea725ed315bbb4e65cc0675d01db1559b1713c470f5f7e2fdb9ec30",
          "sha1": "08cdfb2fa3c19655dd059cd6db0350e17129a95b",
          "md5": "14de7498b2bf68e7d3b1381624fabb62"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler",
          "version": {
            "requires": "1.5.11"
          },
          "reason": "compiler-hosted is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-hosted-1.5.11.jar",
          "url": "compiler-hosted-1.5.11.jar",
          "size": 1152377,
          "sha512": "e1457575887276c4326c1b5f570d8327906733bcc5b3be394b4e969f74b36196b2080eb4ab500e532c13f79f11c558b5ca046de4c13d35ade6d576f7be2ee1a2",
          "sha256": "1c341b635ea725ed315bbb4e65cc0675d01db1559b1713c470f5f7e2fdb9ec30",
          "sha1": "08cdfb2fa3c19655dd059cd6db0350e17129a95b",
          "md5": "14de7498b2bf68e7d3b1381624fabb62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.compiler",
          "module": "compiler",
          "version": {
            "requires": "1.5.11"
          },
          "reason": "compiler-hosted is in atomic group androidx.compose.compiler"
        }
      ],
      "files": [
        {
          "name": "compiler-hosted-1.5.11-sources.jar",
          "url": "compiler-hosted-1.5.11-sources.jar",
          "size": 235318,
          "sha512": "8d1290816ea5070088f793f582d056645de7b4df489790d35f1496511374138927baf757d08571668db520dd8da2c20ed0fbea9fd4272016e5b80d55330e1da5",
          "sha256": "e36e8cd69fea989fd299202202a8c3612b55040872428871a10944ce78f84ab3",
          "sha1": "edb84bcd1152a2485e20ee9b45867f8d1b939b6b",
          "md5": "7fd5124c89ab14f70cd1124b08d07b54"
        }
      ]
    }
  ]
}