{
  "formatVersion": "1.1",
  "component": {
    "url": "../../collection/1.3.0-alpha03/collection-1.3.0-alpha03.module",
    "group": "androidx.collection",
    "module": "collection",
    "version": "1.3.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.3.0-alpha03.jar",
          "url": "collection-jvm-1.3.0-alpha03.jar",
          "size": 89953,
          "sha512": "871bed547241cf866514804d22b0d331ccf199b723cbc7eb6d028c83aa0297752514958e34d875cb66650601692a0da7f38361d6d7f3155c77ccd80d75736e46",
          "sha256": "e406c7e441377a008dd4b49fd5028a39545f40775dfe79972f24632ccb097fde",
          "sha1": "536afa5b2b71cd138c59f93408f208dc5a3c3d65",
          "md5": "54174193d20dcbd5aef5cb827a1d9ba6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.collection",
          "module": "collection-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "collection-jvm-1.3.0-alpha03.jar",
          "url": "collection-jvm-1.3.0-alpha03.jar",
          "size": 89953,
          "sha512": "871bed547241cf866514804d22b0d331ccf199b723cbc7eb6d028c83aa0297752514958e34d875cb66650601692a0da7f38361d6d7f3155c77ccd80d75736e46",
          "sha256": "e406c7e441377a008dd4b49fd5028a39545f40775dfe79972f24632ccb097fde",
          "sha1": "536afa5b2b71cd138c59f93408f208dc5a3c3d65",
          "md5": "54174193d20dcbd5aef5cb827a1d9ba6"
        }
      ]
    }
  ]
}