version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.datastore"
group_id: "androidx.datastore"
artifact_id: "datastore-rxjava2"
path: "/datastore/datastore-rxjava2"
sha: "1929d57d40d841536fd9e29a3f715d64cf3bc798"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.datastore-datastore-rxjava2-all-12691003-1.2.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core-okio"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-guava"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-external-protobuf"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
