version: "1.9.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativearm32"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativearm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativex64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativex86"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-iosarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-iossimulatorarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-iosx64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-js"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-jvm"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-linuxarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-linuxx64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-macosarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-macosx64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-mingwx64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-tvosarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-tvossimulatorarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-tvosx64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-wasm-js"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-watchosarm32"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-watchosarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-watchosdevicearm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-watchossimulatorarm64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-watchosx64"
    version: "1.9.0-rc01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation"
path: "/annotation/annotation"
sha: "1d85a4c4bfb2573264fd25efd031e9366f8a33d8"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-all-12640564-1.9.0-rc01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "androidNativeX86"
kmp_children: "androidNativeX64"
kmp_children: "androidNativeArm64"
kmp_children: "androidNativeArm32"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "js"
kmp_children: "jvm"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "macosx64"
kmp_children: "macosarm64"
kmp_children: "mingwx64"
kmp_children: "tvosx64"
kmp_children: "tvosarm64"
kmp_children: "tvossimulatorarm64"
kmp_children: "wasmJs"
kmp_children: "watchosx64"
kmp_children: "watchosarm64"
kmp_children: "watchosdevicearm64"
kmp_children: "watchossimulatorarm64"
