{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.5.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12929033"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha08-sources.jar",
          "url": "compose-material-core-1.5.0-alpha08-sources.jar",
          "size": 36869,
          "sha512": "5beaef18561d97efd66da76d3ee1bb718319be4c6a499a533cc4ab825ebbacab41bf86c861ae0378ce80cf693009df0cf067ad4a0ff3c255a5bc0d970587b1de",
          "sha256": "01f3241fd5b00f865406552d9448d85023cec6f2fa7c0f3e09bddd43a2278b34",
          "sha1": "92affe3840156f476714de7aa1f79d04efa50206",
          "md5": "98901e9dee64a2f66e364fe8d0cfbe7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha08.aar",
          "url": "compose-material-core-1.5.0-alpha08.aar",
          "size": 190866,
          "sha512": "5c686b84ee9a8f5f1b5a711109305186cc0a721b146468825ec8928550e2a8ba343714273e04bd147ddb52cca00e49e89d97058c99ae054a65605f7558a7bb84",
          "sha256": "5f433af76f267d9358714c402f1e053ab90a59d10df7818432f1c54a555a4253",
          "sha1": "eb7846d53d8ee959a6e136c8ac1d39a2a1306ebf",
          "md5": "e92378dc3bbc250a75fe2b5f9d688a10"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha08.aar",
          "url": "compose-material-core-1.5.0-alpha08.aar",
          "size": 190866,
          "sha512": "5c686b84ee9a8f5f1b5a711109305186cc0a721b146468825ec8928550e2a8ba343714273e04bd147ddb52cca00e49e89d97058c99ae054a65605f7558a7bb84",
          "sha256": "5f433af76f267d9358714c402f1e053ab90a59d10df7818432f1c54a555a4253",
          "sha1": "eb7846d53d8ee959a6e136c8ac1d39a2a1306ebf",
          "md5": "e92378dc3bbc250a75fe2b5f9d688a10"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha08"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.5.0-alpha08-versionMetadata.json",
          "url": "compose-material-core-1.5.0-alpha08-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}