{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-core",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10-sources.jar",
          "url": "ui-core-1.0.0-alpha10-sources.jar",
          "size": 17898,
          "sha512": "d8505af763d0ca02116ad65d05f5bd85c5a56293f2e757d0de2417f5170e8aee6b0022f4e1fed1d5af71c39edb8f975cc98eb006d4c27049a86eeae8c45efde7",
          "sha256": "e92e36fa98bf8f51f1709150f58dff6296994be309a08bc6cc3b708af01292d8",
          "sha1": "1889f5989f66a67933681803e3334ec447bb89e9",
          "md5": "7442c3c43a0a1a847f5873f523a7ae41"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10.aar",
          "url": "ui-core-1.0.0-alpha10.aar",
          "size": 60453,
          "sha512": "8e591cb6f196ded45a909ceeb61187d0bbb18d1fbea2a8e4541f01ecb168bae410436dbd3946f07067088123ad8c3dae3c49b25728e881f7efd3e6ca9c615d64",
          "sha256": "2988b6978677094745737e8d554e3fb29143edec42d0c5d9edcf4df248792448",
          "sha1": "38348fdbeec9e438db1a643a4490d5b9b699eb08",
          "md5": "355d3e59198353d97495091156b77387"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10.aar",
          "url": "ui-core-1.0.0-alpha10.aar",
          "size": 60453,
          "sha512": "8e591cb6f196ded45a909ceeb61187d0bbb18d1fbea2a8e4541f01ecb168bae410436dbd3946f07067088123ad8c3dae3c49b25728e881f7efd3e6ca9c615d64",
          "sha256": "2988b6978677094745737e8d554e3fb29143edec42d0c5d9edcf4df248792448",
          "sha1": "38348fdbeec9e438db1a643a4490d5b9b699eb08",
          "md5": "355d3e59198353d97495091156b77387"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha10-versionMetadata.json",
          "url": "ui-core-1.0.0-alpha10-versionMetadata.json",
          "size": 5254,
          "sha512": "009e0e1c4e62bb268b9476d62bf88ef43c226b4a6fae69246a6d7bff8b5b2c8bc102d8992a780cbb0924f87066e75328d49d6bd7432c59bee99ad853af9e3eae",
          "sha256": "87861899d6d2b5f10ac1e4c1e282d0d3a01e22ae99992796bf01d07808b23fd7",
          "sha1": "92f5eef72adb9ba6d82ceac3c20b3ad49eb01b89",
          "md5": "f4b8e2cc995bf2805fd64dd8127a1bf4"
        }
      ]
    }
  ]
}