version: "1.1.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.constraintlayout"
    artifact_id: "constraintlayout-compose-android"
    version: "1.1.0-beta01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-compose"
path: "/constraintlayout/constraintlayout-compose"
sha: "15bdb72fcaacf762145cc16fe725037fca9bcee2"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-compose-all-12550422-1.1.0-beta01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
