version: "1.1.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.constraintlayout"
    artifact_id: "constraintlayout-compose-android"
    version: "1.1.0-beta01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.constraintlayout"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-compose"
path: "/constraintlayout/constraintlayout-compose"
sha: "53bce536bce3e861b1ec75d900704c563f84fab9"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-compose-all-12064410-1.1.0-beta01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: true
