{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-client-guava",
    "version": "1.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.3.0-alpha04-sources.jar",
          "url": "watchface-client-guava-1.3.0-alpha04-sources.jar",
          "size": 10089,
          "sha512": "a819ac6e439c6df877f7f9b0edf935bc584e7918d4306a2ecfd64cbf3832347a3b8912c4514f7e46cdf8176d38b936e15135e1701879a12b0e264309ec8da3c0",
          "sha256": "569bf3b442df8195f16f1582f323ff900a0fd20c926b4d15a0b5fc5dc17ef354",
          "sha1": "8165d33302df1f5dcf428c36c6654539faed4b94",
          "md5": "08bc3b0387fd9d9fccec541a276c0537"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.3.0-alpha04.aar",
          "url": "watchface-client-guava-1.3.0-alpha04.aar",
          "size": 29827,
          "sha512": "f46b211c46d3c5e76dd6a4fac19351066ab5b6f52725559fda8a0ee99a906c814121ea5111d2ab71c77cf2df181225be8f221c73874fc2b27eb9c6916abbfd4a",
          "sha256": "090676fdeaffd2c82add5c371335de8df3d427d64cc0aa04c3448a581b4ebf38",
          "sha1": "dc983365d3f82c4618d471bf9385c1d8d5f82599",
          "md5": "a717a28680cd9976a41f3dd4af75ffe3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.3.0-alpha04.aar",
          "url": "watchface-client-guava-1.3.0-alpha04.aar",
          "size": 29827,
          "sha512": "f46b211c46d3c5e76dd6a4fac19351066ab5b6f52725559fda8a0ee99a906c814121ea5111d2ab71c77cf2df181225be8f221c73874fc2b27eb9c6916abbfd4a",
          "sha256": "090676fdeaffd2c82add5c371335de8df3d427d64cc0aa04c3448a581b4ebf38",
          "sha1": "dc983365d3f82c4618d471bf9385c1d8d5f82599",
          "md5": "a717a28680cd9976a41f3dd4af75ffe3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "watchface-client-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-client-guava-1.3.0-alpha04-versionMetadata.json",
          "url": "watchface-client-guava-1.3.0-alpha04-versionMetadata.json",
          "size": 4248,
          "sha512": "c4a699e2f078adcd495bf5234f3c0694a4ea1ece64059b709b5abf22dbf94cc51a714f136e80915f1358bf6cdb8a5fe35bdc4b66577007d44a50082391afcfb4",
          "sha256": "70562caf9d38b7a7676f4f991f09b122593f4cfcccbc2f3c3b9fb8bf8412d0fe",
          "sha1": "64bf0ec5f4735da207efc934c3025e574c18beb5",
          "md5": "800e6ac3a92d15eee94f4f2b0212f10f"
        }
      ]
    }
  ]
}