{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.16.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13169796"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.16.0-beta01-sources.jar",
          "url": "core-1.16.0-beta01-sources.jar",
          "size": 972039,
          "sha512": "68f78b4fa81c6f0674ed57a736586de2b62778c83950f623e710444436131f011964639019762042ffc1c6c9d4b9b3c472000d17bd3beba7c9ae2e197d31a78a",
          "sha256": "a7aef6ec4c75621dc83db30b4650d6be5b820b50f3599654f046cf7927ad811e",
          "sha1": "b373fee4229f997f9b28e3b9bb78da811958f873",
          "md5": "5b413e819fbdf007d6568a7df7228fa6"
        },
        {
          "name": "core-1.16.0-beta01-samples-sources.jar",
          "url": "core-1.16.0-beta01-samples-sources.jar",
          "size": 6272,
          "sha512": "924ae5a6b8388f097b80b00a2bb7e094f5c4bcbb08df69cdc15770e97b575e6ec8bc77dd4ac50d927fbad2bd22bf9d73622984b4a761d94ef86839c3e28f2a70",
          "sha256": "7b42513b7a33535365c4606d46e5dd9c0c747ed704bcdc39ae1db665c3d00b8d",
          "sha1": "7a746abb87119c59f68b3274f0692e3a0390a4aa",
          "md5": "96f5c93bc127f664fd6906f5045af6ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.16.0-beta01.aar",
          "url": "core-1.16.0-beta01.aar",
          "size": 1377177,
          "sha512": "d7277a16d22deb0dc276632fb27c2823e7488d88138dd4bb4c0f3d03d8653d4644a4b8618ff92f17e8a910affd353a441f0dbf6fef75c4139fda29ca85907700",
          "sha256": "36f7b8c9a783468647e447838469115ce427cabbe62f393bb6c128e7f6e36dc2",
          "sha1": "1b07c1232d95a563367a20157c9a138214b2ef28",
          "md5": "f52c28ec810231246192766f8a1a8536"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0-beta01"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0-beta01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.16.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.16.0-beta01.aar",
          "url": "core-1.16.0-beta01.aar",
          "size": 1377177,
          "sha512": "d7277a16d22deb0dc276632fb27c2823e7488d88138dd4bb4c0f3d03d8653d4644a4b8618ff92f17e8a910affd353a441f0dbf6fef75c4139fda29ca85907700",
          "sha256": "36f7b8c9a783468647e447838469115ce427cabbe62f393bb6c128e7f6e36dc2",
          "sha1": "1b07c1232d95a563367a20157c9a138214b2ef28",
          "md5": "f52c28ec810231246192766f8a1a8536"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.16.0-beta01-versionMetadata.json",
          "url": "core-1.16.0-beta01-versionMetadata.json",
          "size": 268348,
          "sha512": "3c937969104465915c56f3955e9783d393ffca5b663052335dee076a633840977b65f04945b44dac4f9e4aa0149d07488f1d66ab9783e592eceb6f72969c82ca",
          "sha256": "a8ed61a19a02a214fcb0cfa8339307e0a994b664d3dcff60555a1ef990868ff0",
          "sha1": "c0a9907415b633cde20af6149d98658fde18676c",
          "md5": "9f64af818d7b469678382ccbfdbe6bf8"
        }
      ]
    }
  ]
}