{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.runtime",
    "module": "runtime-tracing",
    "version": "1.9.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13551675"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-tracing-1.9.0-alpha04-sources.jar",
          "url": "runtime-tracing-1.9.0-alpha04-sources.jar",
          "size": 6050,
          "sha512": "9606a1b38a5ecf8b6466140ea4ebb761db4814d00615380bd50f038ff3ca2974a664eaf3768883ccc0f4a596304f911797e095d57e26bd86f21a3dbfc874d905",
          "sha256": "2e662a45f09a115de40b373220e2ff9cc718a3344feb0a88b30dc80ee9f67b46",
          "sha1": "5bde17de2333b9f31a8d381b9ede7e4aa0998a49",
          "md5": "e6709e83810dbc9e6a6a628078e55f11"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-tracing-1.9.0-alpha04.aar",
          "url": "runtime-tracing-1.9.0-alpha04.aar",
          "size": 8675,
          "sha512": "f42fca5865aee5a318add5e1cd1c0dc3ef97b4590643cdb237e0231dd25d11dbb62dc6b1f03ba6c8b00effa928174071c334b2fa4d2e47345f0bfef2147250b0",
          "sha256": "8c9f4d6da0db9f0448a90b71dc8d1a95db9c6a7423d397cb0aa52a1e8685a22c",
          "sha1": "ca0ae1adeb2506908572cb7897c40d3a7252b29a",
          "md5": "664bfa093ce7228f393d83ea9a83ecd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-tracing-1.9.0-alpha04.aar",
          "url": "runtime-tracing-1.9.0-alpha04.aar",
          "size": 8675,
          "sha512": "f42fca5865aee5a318add5e1cd1c0dc3ef97b4590643cdb237e0231dd25d11dbb62dc6b1f03ba6c8b00effa928174071c334b2fa4d2e47345f0bfef2147250b0",
          "sha256": "8c9f4d6da0db9f0448a90b71dc8d1a95db9c6a7423d397cb0aa52a1e8685a22c",
          "sha1": "ca0ae1adeb2506908572cb7897c40d3a7252b29a",
          "md5": "664bfa093ce7228f393d83ea9a83ecd7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-annotation",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable-lint",
          "version": {
            "requires": "1.9.0-alpha04"
          },
          "reason": "runtime-tracing is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-tracing-1.9.0-alpha04-versionMetadata.json",
          "url": "runtime-tracing-1.9.0-alpha04-versionMetadata.json",
          "size": 282,
          "sha512": "a19a2d1507a2aea2197d8bff88dfd54b7a9861200e466fe1fba2be80a7153f9150c492649b7647f6a9f0d6a576deb200b8f224674ab4320ad61b4068fcf60e4f",
          "sha256": "1b02562bb867ef510db32b6b4e082547f2fd4a31a196b5f92c8c5acffda7fbee",
          "sha1": "8de790eb18c697bb965628a81c8a250e0e7d6847",
          "md5": "48c2869594930d5f14584671c0a2bb0e"
        }
      ]
    }
  ]
}