version: "1.1.0-alpha05"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.health"
    artifact_id: "health-services-client-external-protobuf"
    version: "1.1.0-alpha05"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13042766"
group_id: "androidx.health"
artifact_id: "health-services-client-proto"
path: "/health/health-services-client-proto"
sha: "504b4b8d94722fb3fcb520fa1e2bda4e2832dcab"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.health-health-services-client-proto-all-13042766-1.1.0-alpha05.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
}
should_publish_docs: false
is_kmp: false
target: "androidx"
test_module_names: ":health:health-services-client-proto:test"
