{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ui-graphics/1.6.0-alpha05/ui-graphics-1.6.0-alpha05.module",
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.6.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha05"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-release.aar",
          "url": "ui-graphics-android-1.6.0-alpha05.aar",
          "size": 1460414,
          "sha512": "3f10041e6e193fbc92b667347c6aea6ea3c3bb377c003a96ad75f01eb972b7c29b2124254ea76d73d47d2a900f18b9ebbc890af43ca2690a9c426425c8994bc3",
          "sha256": "93d081e6c25197a34039f980310b5ed0ae4486a80305b40c9ed9ec9fdac2cdbf",
          "sha1": "33ff83236a82707c95ee52008da0cbb9affef8c6",
          "md5": "e6cdc54c474121a30afc0a57fd6acb72"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-release.aar",
          "url": "ui-graphics-android-1.6.0-alpha05.aar",
          "size": 1460414,
          "sha512": "3f10041e6e193fbc92b667347c6aea6ea3c3bb377c003a96ad75f01eb972b7c29b2124254ea76d73d47d2a900f18b9ebbc890af43ca2690a9c426425c8994bc3",
          "sha256": "93d081e6c25197a34039f980310b5ed0ae4486a80305b40c9ed9ec9fdac2cdbf",
          "sha1": "33ff83236a82707c95ee52008da0cbb9affef8c6",
          "md5": "e6cdc54c474121a30afc0a57fd6acb72"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-junit4",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-test-manifest",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-data",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-viewbinding",
          "version": {
            "requires": "1.6.0-alpha05"
          },
          "reason": "ui-graphics is in atomic group androidx.compose.ui"
        }
      ],
      "files": [
        {
          "name": "ui-graphics-android-1.6.0-alpha05-sources.jar",
          "url": "ui-graphics-android-1.6.0-alpha05-sources.jar",
          "size": 181069,
          "sha512": "b33e406e1634ef0ab8a0cdc113ea8bba43f5c48396c782ea650a74b5b6a68cca88703a3afcd92f779fdb80f0d6cead511eeeaf08dea93b70adb14ffd2ee855c0",
          "sha256": "862c7e739365d53c6ff02185f1ec43f2055ebdcd368d09bc45de76c84fde83ef",
          "sha1": "744ccb29fb2e179ec260bf4460a8c337df1a7907",
          "md5": "f89b2e004dc56d9dea9d0880bb965a1f"
        }
      ]
    }
  ]
}