{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-material",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13882970"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material-1.2.0-alpha01-sources.jar",
          "url": "glance-material-1.2.0-alpha01-sources.jar",
          "size": 5881,
          "sha512": "6228829e8df5fd43fb310dd2088547ce84a4c9250a455abff1f4814b50f5a50c93787c638a8f093ad1c5dc7621968299ffcaa9b8f7750de6c294209b49235efe",
          "sha256": "303afc9004e81f12a563aeba56fcbe40af5cf78c7d6ac0223dce91f2d80bd01d",
          "sha1": "7d3626b2c833d317570b163c8b1a6ddb6dd6ed38",
          "md5": "01e2f5e97f6ea2268df535ab4ece67e6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material-1.2.0-alpha01.aar",
          "url": "glance-material-1.2.0-alpha01.aar",
          "size": 8014,
          "sha512": "2bf252e9f5920ab2d30bc65f63f87310b21ba4a2b5143b33c760dde2416dc6f1c769349da10ad7e3e7e515f6fe2a74cc9b49f6106debbd1569416eec08ba3983",
          "sha256": "93b825b23b128a4e9c95f8b1067dbefbfb1a7c698074bf9e1057b8e8db9f1313",
          "sha1": "a3d958c2c135de6f3ef9b5a8a7338f7ab1c4a489",
          "md5": "d6a49acf84e8b4a9b85604c381d1c1a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "glance-material-1.2.0-alpha01.aar",
          "url": "glance-material-1.2.0-alpha01.aar",
          "size": 8014,
          "sha512": "2bf252e9f5920ab2d30bc65f63f87310b21ba4a2b5143b33c760dde2416dc6f1c769349da10ad7e3e7e515f6fe2a74cc9b49f6106debbd1569416eec08ba3983",
          "sha256": "93b825b23b128a4e9c95f8b1067dbefbfb1a7c698074bf9e1057b8e8db9f1313",
          "sha1": "a3d958c2c135de6f3ef9b5a8a7338f7ab1c4a489",
          "md5": "d6a49acf84e8b4a9b85604c381d1c1a0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance-material is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-material-1.2.0-alpha01-versionMetadata.json",
          "url": "glance-material-1.2.0-alpha01-versionMetadata.json",
          "size": 290,
          "sha512": "b416a1f58478a66bb3bf06e70f73e01c02ede1c3b01076890df9fdca5e46944343a670c5f28a04100d50e7b7ba1b097857a95ab00b5b279509036c3739d301a4",
          "sha256": "364f183253c698e52151b1110661eb0d0f03778d3245efd063f34652e6f68366",
          "sha1": "716d12ae418efd112733f9ffcbf31a9e30c94a4c",
          "md5": "269c907c483b6964b6fe595e636aadad"
        }
      ]
    }
  ]
}