{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tvprovider",
    "module": "tvprovider",
    "version": "1.1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6495117"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tvprovider-1.1.0-alpha01.aar",
          "url": "tvprovider-1.1.0-alpha01.aar",
          "size": 70109,
          "sha512": "57213f9c3da982524fc901ed0279ba3b0cbd7138df3ebcd75c3a309af93c1df364e0998b6160730a28dee976375fdcac914c3fc28411999c8f0d5e2736b44e3f",
          "sha256": "455ccde377cb771982d40e84d71b2301b0f03c0319d47055d588e9c70f071baa",
          "sha1": "3eeb067878670e7cd9576fad721f0a1d3a4db456",
          "md5": "a45d0bbaac0ca4fb9d71510221ce142e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "tvprovider-1.1.0-alpha01.aar",
          "url": "tvprovider-1.1.0-alpha01.aar",
          "size": 70109,
          "sha512": "57213f9c3da982524fc901ed0279ba3b0cbd7138df3ebcd75c3a309af93c1df364e0998b6160730a28dee976375fdcac914c3fc28411999c8f0d5e2736b44e3f",
          "sha256": "455ccde377cb771982d40e84d71b2301b0f03c0319d47055d588e9c70f071baa",
          "sha1": "3eeb067878670e7cd9576fad721f0a1d3a4db456",
          "md5": "a45d0bbaac0ca4fb9d71510221ce142e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tvprovider-1.1.0-alpha01-sources.jar",
          "url": "tvprovider-1.1.0-alpha01-sources.jar",
          "size": 60806,
          "sha512": "8cba3b12860791d14fe7f566fabe39ddab598d376b07dafbb24421c40fbd90b39913f7083c8e961ccb769a3f90e6e19995b76c77f0f21a8d99c523873710db47",
          "sha256": "2dda300f1038d17466822f37fa03e4df1b6f072943b599094e17df5e08bf5602",
          "sha1": "28389d881b8dc7a854a95d17dc53116d0783aa55",
          "md5": "55a0fdab5136d8d5c6407c9b6ea30077"
        }
      ]
    }
  ]
}
