{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-video",
    "version": "1.5.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13808536"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.5.0-beta02-sources.jar",
          "url": "camera-video-1.5.0-beta02-sources.jar",
          "size": 309923,
          "sha512": "f713e112ba8931b6a1b5c30bf1735135f67e51b63d3c5d871360e7e4988d695770ecc94fc417939bf27a6fdc084f6180d85a2d5fa258eea295981875a250fdc1",
          "sha256": "9c79091c157d5303e922067403e2278c7be429e9ed08efc50a27cf9a24d4154d",
          "sha1": "fb6e57c80dae85d57ac784ebbe61aff99dfefd59",
          "md5": "f74aa6c38af7bb7dcaf46b0ce8791035"
        },
        {
          "name": "camera-video-1.5.0-beta02-samples-sources.jar",
          "url": "camera-video-1.5.0-beta02-samples-sources.jar",
          "size": 6508,
          "sha512": "1a5c82751c07edd999afb5f366ab71040c630d9d5e3c08fcae3630e45b911b6f462486afa9e699fde9b9b0022dab2192ecad3bfdb07e0154454cbd04591b4212",
          "sha256": "3e69412f0e6b394d60b2e602d2b5eeec440baaf32651a662e98ec75a51377b5d",
          "sha1": "324d2672177f17b16105097624dce2f4764bcb8f",
          "md5": "64171facd7d519b83f89d5fad54dd548"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.5.0-beta02.aar",
          "url": "camera-video-1.5.0-beta02.aar",
          "size": 454923,
          "sha512": "e7aac2a9d31836b31174d0f44b1be9230ebe83a9d314c9b5084da79ae70f6005d54e5b853db6e3a7278737cc524b1fa8f5af0db965d407951efffb0be6892695",
          "sha256": "4f8e91eff0bde5500c1e160e6b3029a793540ba1d95c37ac0f4889288b5a4747",
          "sha1": "e760a870cc82659a1cf7a2b9ecb21992b9a35bcf",
          "md5": "8bf7e5058d589ee08523b210f7488e99"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.arch.core",
          "module": "core-common",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.5.0-beta02.aar",
          "url": "camera-video-1.5.0-beta02.aar",
          "size": 454923,
          "sha512": "e7aac2a9d31836b31174d0f44b1be9230ebe83a9d314c9b5084da79ae70f6005d54e5b853db6e3a7278737cc524b1fa8f5af0db965d407951efffb0be6892695",
          "sha256": "4f8e91eff0bde5500c1e160e6b3029a793540ba1d95c37ac0f4889288b5a4747",
          "sha1": "e760a870cc82659a1cf7a2b9ecb21992b9a35bcf",
          "md5": "8bf7e5058d589ee08523b210f7488e99"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-compose",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0-beta02"
          },
          "reason": "camera-video is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-video-1.5.0-beta02-versionMetadata.json",
          "url": "camera-video-1.5.0-beta02-versionMetadata.json",
          "size": 12127,
          "sha512": "ff54f59b8626a47a844b94e3af6e12de9c4820a85b92c0a75b2d88662a0126825ec9ada2ed3ae195ac0ee9672a8b9b6725e8ed40a630254d333b20279880f909",
          "sha256": "7ab2616fac3cac559d8a1a63bff43f8410b76bceaf782d18967976513e7c4769",
          "sha1": "a25b302af87829fa5a18bcc6528c149af162d682",
          "md5": "f83e419f152e6409557b155d459d0156"
        }
      ]
    }
  ]
}