version: "1.1.0-alpha04"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.1.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.appsearch"
group_id: "androidx.appsearch"
artifact_id: "appsearch-compiler"
path: "/appsearch/compiler"
sha: "edd19514b50734044a2a42cd9be3930fdf188b0f"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.appsearch-appsearch-compiler-all-12133442-1.1.0-alpha04.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-builtin-types"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-debug-view"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-external-protobuf"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-ktx"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-local-storage"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-platform-storage"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.appsearch"
    artifact_id: "appsearch-play-services-storage"
    version: "1.1.0-alpha04"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
