{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-foundation",
    "version": "1.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.3.0-alpha04.aar",
          "url": "compose-foundation-1.3.0-alpha04.aar",
          "size": 499853,
          "sha512": "6bfdce1fcee7e895102da04b26d32457726f752b2d70a84df07a28a2e9c2b1d9593385737e3c6ba250806f937a4e9b123c5ee0af0fca62b928bcd39863525ed4",
          "sha256": "a34410e8e0a0de3e6c22b1d48b352487ba749b7760abb39541f981a0a6f51390",
          "sha1": "5fd1887da1c7382be0f9765db4428dbcf076d48c",
          "md5": "db8c93405a372ac4826675a5cd871dbf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.0-alpha04"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.11.0-beta02"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.3.0-alpha04.aar",
          "url": "compose-foundation-1.3.0-alpha04.aar",
          "size": 499853,
          "sha512": "6bfdce1fcee7e895102da04b26d32457726f752b2d70a84df07a28a2e9c2b1d9593385737e3c6ba250806f937a4e9b123c5ee0af0fca62b928bcd39863525ed4",
          "sha256": "a34410e8e0a0de3e6c22b1d48b352487ba749b7760abb39541f981a0a6f51390",
          "sha1": "5fd1887da1c7382be0f9765db4428dbcf076d48c",
          "md5": "db8c93405a372ac4826675a5cd871dbf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.3.0-alpha04-sources.jar",
          "url": "compose-foundation-1.3.0-alpha04-sources.jar",
          "size": 93928,
          "sha512": "9b7fa9c9f04c4e547b0dabb5752a02d8fe1548f9c5d4ad5082f732313cf89c111a8e5fd46834bfbfd41fd60f4951fa332fade6dd90f504a727da779cdb02e62a",
          "sha256": "3de9705c256f1e74710ef8861881e93beba8dba4f002ce419e45c5f60aaaae84",
          "sha1": "d8f1f0f427ae43065523890377291a47f06ff0ba",
          "md5": "df648e6ae64a94dba40e49b63d270fe3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.3.0-alpha04"
          },
          "reason": "compose-foundation is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-foundation-1.3.0-alpha04-versionMetadata.json",
          "url": "compose-foundation-1.3.0-alpha04-versionMetadata.json",
          "size": 26511,
          "sha512": "f5daff3ccc78f67ae1789fde61cafe962f9481d1fe8a410a0c259591d291af2c7e56c0b98d60aad2ed400a2bccb4b3cb16eba5215d9e80a400d7ad5029f96707",
          "sha256": "b65392a37e2ed07872c50e2b27b987ab4318cdc703c7bbf2e65da31a899f7216",
          "sha1": "d66049566d060e7fbc31c955dddc95273910fd47",
          "md5": "c6e03ed8a23a86017d24fe5a3040ad68"
        }
      ]
    }
  ]
}