{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.test.uiautomator",
    "module": "uiautomator",
    "version": "2.3.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "uiautomator-2.3.0-alpha04.aar",
          "url": "uiautomator-2.3.0-alpha04.aar",
          "size": 125968,
          "sha512": "03c28417e3aaff3de70884bec474ec7018ec4c564d7e403273bed294413d061727314a579db7fefbf7cd9168d941eb1ecd82c888eaaa4e77169d3019710ff1e4",
          "sha256": "8561890030e5ad8e193a55196625335a410f7b23894ca1c0ab4a3cdda6872710",
          "sha1": "4a45c7ba5e1ba5185f6b84f0d9dd0e7cea9f2f32",
          "md5": "cb4175a9e1d0226d6a5eea1df4926473"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "uiautomator-2.3.0-alpha04.aar",
          "url": "uiautomator-2.3.0-alpha04.aar",
          "size": 125968,
          "sha512": "03c28417e3aaff3de70884bec474ec7018ec4c564d7e403273bed294413d061727314a579db7fefbf7cd9168d941eb1ecd82c888eaaa4e77169d3019710ff1e4",
          "sha256": "8561890030e5ad8e193a55196625335a410f7b23894ca1c0ab4a3cdda6872710",
          "sha1": "4a45c7ba5e1ba5185f6b84f0d9dd0e7cea9f2f32",
          "md5": "cb4175a9e1d0226d6a5eea1df4926473"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "uiautomator-2.3.0-alpha04-sources.jar",
          "url": "uiautomator-2.3.0-alpha04-sources.jar",
          "size": 92098,
          "sha512": "4766451be320dfa82f0833979d28098e79c2fe8b806118e8495e776733f00b936e6215340e2b10ff3fbd3585cb1985a5192931af9a7bfd54f63a2fd6b52089ad",
          "sha256": "f42fa9fd9cfab8e85b872db0812c82d6c26075052c3aa0fbcf0ac639650d1b23",
          "sha1": "7cb4d13c664a4d3606d7d1128c7e8392b9614da6",
          "md5": "ae4c4fe1df4bb1972a686645e9f817bc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "uiautomator-2.3.0-alpha04-versionMetadata.json",
          "url": "uiautomator-2.3.0-alpha04-versionMetadata.json",
          "size": 27186,
          "sha512": "09bcba5926da94a7f832ee71fc8c9b21eeb61b6afa685a23bff70e4eb96554b7be01cfa4c5699517174f6d1527c30e060b1ff39ad2512eb349900c970555d453",
          "sha256": "6d0a6c879b262a81785286337c55834225488e9256dcfc8cfce982e20f1a3220",
          "sha1": "c9b996654893861e3d14e45fe367861719b669ae",
          "md5": "0546982de22cc8638fdd530ee3404c4e"
        }
      ]
    }
  ]
}