{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.ui",
    "module": "ui-graphics",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.1.0-alpha04.aar",
          "url": "ui-graphics-1.1.0-alpha04.aar",
          "size": 1387279,
          "sha512": "0030b84d2b9a147fb7615c0bf6413cfbf25fcb7050194566e16c7eb6483fd559f5df620f037c777d54e3a3a3ffa05c5975e38431b0feee53c56397d886194bcb",
          "sha256": "402e24714f49811d9769e13ede473df16bc8b212c519a7d9a9ba97a77a5d12aa",
          "sha1": "9ce20f2c70382a8bdbbfc8dd8468bba22f5283a7",
          "md5": "df29dd9106cea0fc87e2be44f1795082"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "ui-graphics-1.1.0-alpha04.aar",
          "url": "ui-graphics-1.1.0-alpha04.aar",
          "size": 1387279,
          "sha512": "0030b84d2b9a147fb7615c0bf6413cfbf25fcb7050194566e16c7eb6483fd559f5df620f037c777d54e3a3a3ffa05c5975e38431b0feee53c56397d886194bcb",
          "sha256": "402e24714f49811d9769e13ede473df16bc8b212c519a7d9a9ba97a77a5d12aa",
          "sha1": "9ce20f2c70382a8bdbbfc8dd8468bba22f5283a7",
          "md5": "df29dd9106cea0fc87e2be44f1795082"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ui-graphics-1.1.0-alpha04-sources.jar",
          "url": "ui-graphics-1.1.0-alpha04-sources.jar",
          "size": 159685,
          "sha512": "497cb6e548a6ffeded2d0aac0b53272f07a0239b0780f34135127146a3c75115ff2308cb9ac98b9c00300dbc67bf6a13f8e1942dcb2c1025302941f1afd2be0e",
          "sha256": "44d0ce53c31f3ff3c6f3a039928f7ab6898e5d374a4426717897525a9017c91e",
          "sha1": "21b54f3730edf10ee2dc2cd448b4657fea80d3d2",
          "md5": "94b44d89b3607e1de768b82dbf27fb6d"
        }
      ]
    }
  ]
}
