version: "2.5.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-android"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-iosarm64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-iossimulatorarm64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-iosx64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-linuxarm64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-linuxx64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-macosarm64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-macosx64"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13042766"
group_id: "androidx.sqlite"
artifact_id: "sqlite-framework"
path: "/sqlite/sqlite-framework"
sha: "504b4b8d94722fb3fcb520fa1e2bda4e2832dcab"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.sqlite-sqlite-framework-all-13042766-2.5.0-beta01.zip"
kotlin_version: "2.1.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-bundled"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-ktx"
    version: "2.5.0-beta01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "android"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "macosx64"
kmp_children: "macosarm64"
test_module_names: ":sqlite:sqlite-framework:iosX64Test"
test_module_names: ":sqlite:sqlite-framework:iosSimulatorArm64Test"
test_module_names: ":sqlite:sqlite-framework:linuxX64Test"
test_module_names: ":sqlite:sqlite-framework:macosX64Test"
test_module_names: ":sqlite:sqlite-framework:macosArm64Test"
test_module_names: "sqlite-sqlite-frameworkreleaseAndroidTest.xml"
test_module_names: ":sqlite:sqlite-framework:testReleaseUnitTest"
