version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "12958663"
group_id: "androidx.constraintlayout"
artifact_id: "constraintlayout-core"
path: "/constraintlayout/constraintlayout-core"
sha: "7b9c01964c34698a8fdf83210a5ffd2765512f1a"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.constraintlayout-constraintlayout-core-all-12958663-1.2.0-alpha01.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":constraintlayout:constraintlayout-core:test"
