{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.annotation",
    "module": "annotation",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-1.6.0-alpha01-sources.jar",
          "url": "annotation-1.6.0-alpha01-sources.jar",
          "size": 61741,
          "sha512": "7472f3114bc696465e37588123ddbb90036607e7cbd509d8e8f5db5bb3f40595e5b8010a86ef8ea06041788f632b7edd155abc74f45808a1a997d83fae167e88",
          "sha256": "ec2ec035989bac5541542f5d49eb668524e5c61267f05f1ddb9a5ef8a6411e36",
          "sha1": "b789a431f90a18e4d7313bcdf2379086ee91aa4b",
          "md5": "88de5dcb54138ac067fb6890f5fe7e16"
        }
      ]
    },
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "annotation-metadata-1.6.0-alpha01.jar",
          "url": "annotation-1.6.0-alpha01.jar",
          "size": 671,
          "sha512": "9e8235407476525f968892cc95cf6a235fc7d814d4280633d80c7a3eaf8ad0de5aeff2b5afaba5288931a0bd2e98a76f8a91f95fb6076e07b9a5c939587a593a",
          "sha256": "6739f09629e3ebdafc9f6592e7764ee7dba58575b9bd49570c8fe6bfbd77f0f5",
          "sha1": "0f13e6c1eb222ad405529fdfe3d0910cae68255a",
          "md5": "4c1b981b7fd946e6281e3090801d9517"
        }
      ]
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.6.0-alpha01/annotation-jvm-1.6.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.6.0-alpha01"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../annotation-jvm/1.6.0-alpha01/annotation-jvm-1.6.0-alpha01.module",
        "group": "androidx.annotation",
        "module": "annotation-jvm",
        "version": "1.6.0-alpha01"
      }
    }
  ]
}