version: "1.0.0-alpha06"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.4.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.1.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.glance"
group_id: "androidx.glance"
artifact_id: "glance-preview"
path: "/glance/glance-preview"
sha: "69887df099e9061bbe5382fc2872ce64481c0212"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.glance-glance-preview-all-11635875-1.0.0-alpha06.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
}
should_publish_docs: true
