version: "1.2.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.datastore"
group_id: "androidx.datastore"
artifact_id: "datastore-preferences-external-protobuf"
path: "/datastore/datastore-preferences-external-protobuf"
sha: "99a8f8b105bda1c72aabdbd00954b48c1a9b5ac6"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.datastore-datastore-preferences-external-protobuf-all-12372457-1.2.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core-okio"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-guava"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
is_kmp: false
