{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-core",
    "version": "1.0.0-alpha08",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08.jar",
          "url": "tools-core-1.0.0-alpha08.jar",
          "size": 317934,
          "sha512": "38f95fb81cff3d4c7482830da3752cba8da492ee177a12eb228afb987489fc0544ae7215ccd03e17b01d14f6d46e51c1f5439a2905832a82fc93a8af921ae10a",
          "sha256": "689d69f42a615b0ddcd89ae3ff558beab966ef52118ff79d4fecc1ae7e8e4eaf",
          "sha1": "2b6c0f1cb8d3d7ade561e7626524a313f5b4e7ad",
          "md5": "929255631ab955251ddebbe58c6a85f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-jre"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.22.3"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08.jar",
          "url": "tools-core-1.0.0-alpha08.jar",
          "size": 317934,
          "sha512": "38f95fb81cff3d4c7482830da3752cba8da492ee177a12eb228afb987489fc0544ae7215ccd03e17b01d14f6d46e51c1f5439a2905832a82fc93a8af921ae10a",
          "sha256": "689d69f42a615b0ddcd89ae3ff558beab966ef52118ff79d4fecc1ae7e8e4eaf",
          "sha1": "2b6c0f1cb8d3d7ade561e7626524a313f5b4e7ad",
          "md5": "929255631ab955251ddebbe58c6a85f8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apicompiler",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha08"
          },
          "reason": "tools-core is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-core-1.0.0-alpha08-sources.jar",
          "url": "tools-core-1.0.0-alpha08-sources.jar",
          "size": 55976,
          "sha512": "0e501ba638b56a8a902ab022efc5b4b9f137801dc3f4c8229914813fb88131d9052ea9ab8f4a47cfa25e04fafc0d742e5afb8eb935b91844607333fd4d2d1d22",
          "sha256": "24ff89e32c18f6a2412dfe5bb6c01a632fed2db252eaea7421872a7d3c6c3a54",
          "sha1": "2372d067e15323fdd7457cf405f0b3ef847a0204",
          "md5": "ad6c536df1b596f0a6c3a645601794ed"
        }
      ]
    }
  ]
}