{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.car.app",
    "module": "app",
    "version": "1.8.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13522428"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha01-sources.jar",
          "url": "app-1.8.0-alpha01-sources.jar",
          "size": 473609,
          "sha512": "2dffd8884a0e2c8321fe9b64c6a5cefbc36fbc3b6d4e5701f4e0d1b3053613ae81882dee33bcec04e99fd46f986200144624d104426b2a528e51946a72876e8c",
          "sha256": "d99e91f4935efb6a1070683688dd7281099ab56fe5530c7e61b1af890baf1ca2",
          "sha1": "6d124155930e97c45623b6b3b929397752bca982",
          "md5": "28ae5f9c9b3cefc18a70754edcc67b66"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha01.aar",
          "url": "app-1.8.0-alpha01.aar",
          "size": 639429,
          "sha512": "6c716062790eec8abd91406f8a441d103c9e251daee369b7c7a3cd6825464c97996806125f4f0db1690582dfd6051a1bcb90c0c32db132693fd66dfe920dc00b",
          "sha256": "e64de340c7321733bce3b0f20faaa4415c7f1b0134da34c101820a636605c9a1",
          "sha1": "ea99bcc56757bbc49c0f8b241af94f2303bf8c21",
          "md5": "f8d1e0c09090fda1a2da09502ea06589"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha01.aar",
          "url": "app-1.8.0-alpha01.aar",
          "size": 639429,
          "sha512": "6c716062790eec8abd91406f8a441d103c9e251daee369b7c7a3cd6825464c97996806125f4f0db1690582dfd6051a1bcb90c0c32db132693fd66dfe920dc00b",
          "sha256": "e64de340c7321733bce3b0f20faaa4415c7f1b0134da34c101820a636605c9a1",
          "sha1": "ea99bcc56757bbc49c0f8b241af94f2303bf8c21",
          "md5": "f8d1e0c09090fda1a2da09502ea06589"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha01"
          },
          "reason": "app is in atomic group androidx.car.app"
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha01-versionMetadata.json",
          "url": "app-1.8.0-alpha01-versionMetadata.json",
          "size": 126887,
          "sha512": "bbf5c3bbef1f60249df9e1e9249648c18c9d2ea4a6db391474a776b96444db3023b06ba8fe381464b38e7c1d53b429fd5afcd3483b39197627b2ee2926b01c0c",
          "sha256": "00e1505642e8465211471b8628cf4e79b9a384a4d43b5c2ec0fdfd70658dfefa",
          "sha1": "0533cef5f4175673de83e164f83a6103b357b365",
          "md5": "3eac6c966665fbc0a02cec2c38e948d5"
        }
      ]
    }
  ]
}