{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.5.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha06-sources.jar",
          "url": "compose-material-1.5.0-alpha06-sources.jar",
          "size": 183545,
          "sha512": "1a6b15cab38e2ee1f8446f13cf596e4b344c2b8e48f5f7a6323f66d8ddaf83d9a27ad065fbb0096abb741e6485bf8baf6f1409d33509a8f006d9713c7a9e785e",
          "sha256": "9a4b14681cf2211cf8ba66d659496705096723f8abc9262346dd0f42dd16aff7",
          "sha1": "3127332919ba5a21b907813272b38ee06bc96efe",
          "md5": "80d419448066ad4ec2ff0c62f954c61d"
        },
        {
          "name": "compose-material-1.5.0-alpha06-samples-sources.jar",
          "url": "compose-material-1.5.0-alpha06-samples-sources.jar",
          "size": 36724,
          "sha512": "ba5d8df79298d9dc20589e93e9be034533faf53ab64e1b9e90757ebe544e3c155d8f55c66ca7c235eb1dd7801c0b2e36dfb711d1146aef1cc035f0d0b144c6df",
          "sha256": "bc71700c8350e291e2d7f09bdff5327d1a569cb3d30e368ce3949c97935825d8",
          "sha1": "bf2c202837ff7dd9a57d5b456630f07c7565969f",
          "md5": "aeebf129c8414ff21ea5ce0025123c6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha06.aar",
          "url": "compose-material-1.5.0-alpha06.aar",
          "size": 1284629,
          "sha512": "b331bf8355565f1b2ad065db7c227197a7d5067417bea4c5df6a77c7ef55e0ce6f84450f1ec7dea9f8857ab9986643320d46f2f9d82b120d38a936b5c793b6ed",
          "sha256": "d784308d74379c7e486aab5b09bba654d2feaa0f57eef2fe00d4c71e5be65cba",
          "sha1": "9ba6f71d390ff72f85185cec38df2849b7cc58ec",
          "md5": "0761be73f049c1ac5325b55e46a56d9e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha06.aar",
          "url": "compose-material-1.5.0-alpha06.aar",
          "size": 1284629,
          "sha512": "b331bf8355565f1b2ad065db7c227197a7d5067417bea4c5df6a77c7ef55e0ce6f84450f1ec7dea9f8857ab9986643320d46f2f9d82b120d38a936b5c793b6ed",
          "sha256": "d784308d74379c7e486aab5b09bba654d2feaa0f57eef2fe00d4c71e5be65cba",
          "sha1": "9ba6f71d390ff72f85185cec38df2849b7cc58ec",
          "md5": "0761be73f049c1ac5325b55e46a56d9e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha06"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha06-versionMetadata.json",
          "url": "compose-material-1.5.0-alpha06-versionMetadata.json",
          "size": 81701,
          "sha512": "112d6b3d3bf7b3d67a0551dcf4f334dcfbb96ff6cfb0dd10d5b5c299b7893e96811c9223648b4e6ed57402a3d006341d3b34c7bfd324c09e3f05402b352a7da5",
          "sha256": "6dc5b1ddd42bb26a125fadda1659e7e8d0707a3d0b1f53535df62ba25f0be053",
          "sha1": "a05018eb32825ab0666ab84141c19460dd1c199a",
          "md5": "06b9fa37fc0043c3f4db2d4f0dfe2458"
        }
      ]
    }
  ]
}