{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ui",
    "module": "ui-core",
    "version": "1.0.0-alpha16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13649143"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client-compose",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha16-sources.jar",
          "url": "ui-core-1.0.0-alpha16-sources.jar",
          "size": 26830,
          "sha512": "b4c7e5ed9e179aa16418524d84e950dfd38285086f88103b2529bb4f5e3012d5944fe1b84576f917378cfb1e9f8929735b6e641a892a2623b540900148e873ec",
          "sha256": "d8be189ec6f8032f915a88860909ad96650fd4eaa53fb599107044aed5f92413",
          "sha1": "e5edcb19ad19d0368fc61ea4c3f1eb5c66dce802",
          "md5": "8b0f6472edb2ba2b3f085bbba3b48be7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client-compose",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha16.aar",
          "url": "ui-core-1.0.0-alpha16.aar",
          "size": 88255,
          "sha512": "36294ddff1b7c6b535b82b150987059e5c69bfa2028ec28351d3ad593970e5ee8882f6fae0e5f8953b08b9e7591bbf095af9e14171d4ef0f61d154e2321656fb",
          "sha256": "3ed6749c6975a6362bca5e683473a31bc8155b1d16bf7a820343ea6fda4b77e6",
          "sha1": "e5c48b1c3bc2445b46b83894f55ddfbaef5579fe",
          "md5": "accf26de0736d3deaf93d64c53d05b6b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client-compose",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha16.aar",
          "url": "ui-core-1.0.0-alpha16.aar",
          "size": 88255,
          "sha512": "36294ddff1b7c6b535b82b150987059e5c69bfa2028ec28351d3ad593970e5ee8882f6fae0e5f8953b08b9e7591bbf095af9e14171d4ef0f61d154e2321656fb",
          "sha256": "3ed6749c6975a6362bca5e683473a31bc8155b1d16bf7a820343ea6fda4b77e6",
          "sha1": "e5c48b1c3bc2445b46b83894f55ddfbaef5579fe",
          "md5": "accf26de0736d3deaf93d64c53d05b6b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-client-compose",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        },
        {
          "group": "androidx.privacysandbox.ui",
          "module": "ui-provider",
          "version": {
            "requires": "1.0.0-alpha16"
          },
          "reason": "ui-core is in atomic group androidx.privacysandbox.ui"
        }
      ],
      "files": [
        {
          "name": "ui-core-1.0.0-alpha16-versionMetadata.json",
          "url": "ui-core-1.0.0-alpha16-versionMetadata.json",
          "size": 6575,
          "sha512": "9ab0c581e7cfe193c5aea0e0f10a6641bf19391da76eb1460cbb73cfd2757411cbd8465b3c039fba3cafc963ebdf1f05829d4cb3819699d7f425ff9d4b64f0b2",
          "sha256": "c85373a77e0716de0dd7baf583b4a9832e4f14acd3cb531ae47d6608b85cc08a",
          "sha1": "c4c91a6964fb34e8c97a425742c7c9f4cd6f596f",
          "md5": "d789299d6649181b43c7751aecf1c806"
        }
      ]
    }
  ]
}