{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appcompat",
    "module": "appcompat-resources",
    "version": "1.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7139798"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.0-beta01.aar",
          "url": "appcompat-resources-1.3.0-beta01.aar",
          "size": 65253,
          "sha512": "29a25757388d34fa9bc8fcad887e9dd5a7204d31dacc2a0f7ca31cc46c556148895bcf6650c628eb1272a20bc990e6c4f2490ce8dea25f5cf8f56cbd4599dfcd",
          "sha256": "1177e566f8c43715e58320721dc4bf62f09d77b5f4d31ec581c90a8d722590cf",
          "sha1": "ed75695c077fb5f3ca35101a71f22ed4508451b9",
          "md5": "28b72a751881a7b0652b4bc91da06805"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable-animated",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "appcompat-resources-1.3.0-beta01.aar",
          "url": "appcompat-resources-1.3.0-beta01.aar",
          "size": 65253,
          "sha512": "29a25757388d34fa9bc8fcad887e9dd5a7204d31dacc2a0f7ca31cc46c556148895bcf6650c628eb1272a20bc990e6c4f2490ce8dea25f5cf8f56cbd4599dfcd",
          "sha256": "1177e566f8c43715e58320721dc4bf62f09d77b5f4d31ec581c90a8d722590cf",
          "sha1": "ed75695c077fb5f3ca35101a71f22ed4508451b9",
          "md5": "28b72a751881a7b0652b4bc91da06805"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "appcompat-resources-1.3.0-beta01-sources.jar",
          "url": "appcompat-resources-1.3.0-beta01-sources.jar",
          "size": 39771,
          "sha512": "74468531b69f9c0ae550a7e84def80d98d2de325c6ed36043a50ea8c090f94045901823c256c3ec31dcf68d01e5e92e73fe57066def2330eb2e89c214826914d",
          "sha256": "26455b2dbdbd4326c5ad406960005e48dcdb7fc495b0a3a22aa3a703a18ed302",
          "sha1": "fa1169a9b404f7e905756330af6d13e27dcee50e",
          "md5": "b8ebde19acd29c203a88d334c5d629b4"
        }
      ]
    }
  ]
}
