{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.8.0-beta07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta07-sources.jar",
          "url": "navigation-ui-ktx-2.8.0-beta07-sources.jar",
          "size": 4438,
          "sha512": "02efbaf8421c39158b7691d284b0496266ea751100bcb5d1d4d54480b4b4b9371ab806b5b1d269e1d4b1dfaf51aae104139e0540ba8b1a675531204037bc11f9",
          "sha256": "e63a83fb372493336615b76ee8755731a05e312f187f527a6a358f638377b25c",
          "sha1": "7a9a22bc053aaa0170c4952b0403a0b9b8f81e4d",
          "md5": "0977156890f566d39694a7cd2b627d07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta07.aar",
          "url": "navigation-ui-ktx-2.8.0-beta07.aar",
          "size": 5610,
          "sha512": "63c8834d66d766abfee2d96fbf0007b4178b0cb45d64a9daf4eefeb1aeb4015d44b7e4f55a3d415cca8527587730269e319336e256120854b598265054796977",
          "sha256": "76383ad2c11f3ca17f7a8d18e10a54ecaee2b380ff8bd856897cd2f9e1bba827",
          "sha1": "d4a3c2158ae1b13a0b439b8714f919ce644c91a8",
          "md5": "2f12c1f71bc808cd9c2d1d0ba16ed9ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "Mirror navigation-ui dependency graph for -ktx artifacts"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta07"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta07.aar",
          "url": "navigation-ui-ktx-2.8.0-beta07.aar",
          "size": 5610,
          "sha512": "63c8834d66d766abfee2d96fbf0007b4178b0cb45d64a9daf4eefeb1aeb4015d44b7e4f55a3d415cca8527587730269e319336e256120854b598265054796977",
          "sha256": "76383ad2c11f3ca17f7a8d18e10a54ecaee2b380ff8bd856897cd2f9e1bba827",
          "sha1": "d4a3c2158ae1b13a0b439b8714f919ce644c91a8",
          "md5": "2f12c1f71bc808cd9c2d1d0ba16ed9ec"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.8.0-beta07"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.8.0-beta07-versionMetadata.json",
          "url": "navigation-ui-ktx-2.8.0-beta07-versionMetadata.json",
          "size": 6082,
          "sha512": "fb0750efd222f3f11e47b60aad4ddd51f9a17365c98a1d5b7b82e6ddbc9d9c5435d87f27af46c2f1525de64dfd08752ee31283393a5a5a5c416b714270228abb",
          "sha256": "be5b0e997e90e2d3d35778ae22da0ae2652be0e401c16bec50c6401dbc690fe7",
          "sha1": "cd7941a9f68e29512f8c113226f398a7ccd3cc4b",
          "md5": "599b2555933a2ccf868aaddeee44b632"
        }
      ]
    }
  ]
}