{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance-wear-tiles",
    "version": "1.0.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13259688"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "glance-wear-tiles-1.0.0-alpha06-sources.jar",
          "url": "glance-wear-tiles-1.0.0-alpha06-sources.jar",
          "size": 35355,
          "sha512": "b6e0b8ec97e577ac5f40713f9cf388bb943f3ff5a1276212a1cd5c31dcfa98e8e6bbdfcb01f66a10648754cfb660e3a75ff850f955d0d2a5572dac9f4725068d",
          "sha256": "1eff73e48450b38a29c4cdd6d2ee3afee3651db1b8c9a6cc75d8d3bc0698be2c",
          "sha1": "8a6834976e31f09518591cd800be9c6c962f1921",
          "md5": "b2c392b6a4eebba465497728f36b7c72"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-template",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "glance-wear-tiles-1.0.0-alpha06.aar",
          "url": "glance-wear-tiles-1.0.0-alpha06.aar",
          "size": 216777,
          "sha512": "6fcd6dc0c1b9e7a7247b52bc45c0d05bf244dd7bfc3ab460a22f88fcbbe6a38c221bf8d1a8af5f3bd67a65f4333db38b31cf9145541c6284793f4122cd1c21cd",
          "sha256": "f4c91c2a05d50d152eb486430ea3656587e9ced42a3239fb1bd6f8c64ce4d1f5",
          "sha1": "b056816c57cb8c72532c530e21a1a9604769daa2",
          "md5": "c86bbea3c2c4906afb6ccf4aea4c17e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.glance",
          "module": "glance-template",
          "version": {
            "requires": "1.0.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-service",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "androidx.wear.tiles",
          "module": "tiles",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "glance-wear-tiles-1.0.0-alpha06.aar",
          "url": "glance-wear-tiles-1.0.0-alpha06.aar",
          "size": 216777,
          "sha512": "6fcd6dc0c1b9e7a7247b52bc45c0d05bf244dd7bfc3ab460a22f88fcbbe6a38c221bf8d1a8af5f3bd67a65f4333db38b31cf9145541c6284793f4122cd1c21cd",
          "sha256": "f4c91c2a05d50d152eb486430ea3656587e9ced42a3239fb1bd6f8c64ce4d1f5",
          "sha1": "b056816c57cb8c72532c530e21a1a9604769daa2",
          "md5": "c86bbea3c2c4906afb6ccf4aea4c17e0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "glance-wear-tiles-1.0.0-alpha06-versionMetadata.json",
          "url": "glance-wear-tiles-1.0.0-alpha06-versionMetadata.json",
          "size": 9978,
          "sha512": "05dbe6e621a4ceb58108117c6a78a50f729f6e5a81bbfb30614ce3aa8ef61209220f32eb0a96efda2f67fc441dcbc69b08baf51c05531e2081cfbeec9aa35064",
          "sha256": "95809e3846ba660768aafada25aecd66c4000e0dca500401cf7fc77217859cf7",
          "sha1": "096569f61941a79a91d7ba258761e6e81d1e7158",
          "md5": "9b75c7b97828ae211f19c8ebd74aad63"
        }
      ]
    }
  ]
}