{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.paging",
    "module": "paging-runtime",
    "version": "3.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6487324"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0-alpha01"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.0.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0-alpha03"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.0.0-alpha01.aar",
          "url": "paging-runtime-3.0.0-alpha01.aar",
          "size": 69954,
          "sha512": "c528cb322a0ac0dd67f9be232d2d328c6495e155bc6c042ab8ae5e4f2b04845b6d71ce34bae256eadc5e292bdd8ed3422ec7db377f610adab154acf7bdbdb850",
          "sha256": "5f3bd0747fd710652d76f3a7dcea575df2ece83e5a849aa416b55ffa81386e71",
          "sha1": "339b0acbf86b79b36e2af116161fa26cafd9d5f5",
          "md5": "d289be6ef2d3577beca921c9fe053f3e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.paging",
          "module": "paging-common",
          "version": {
            "requires": "3.0.0-alpha01"
          }
        },
        {
          "group": "androidx.paging",
          "module": "paging-common-ktx",
          "version": {
            "requires": "3.0.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.3.0-alpha03"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.3.0-alpha03"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "paging-runtime-3.0.0-alpha01.aar",
          "url": "paging-runtime-3.0.0-alpha01.aar",
          "size": 69954,
          "sha512": "c528cb322a0ac0dd67f9be232d2d328c6495e155bc6c042ab8ae5e4f2b04845b6d71ce34bae256eadc5e292bdd8ed3422ec7db377f610adab154acf7bdbdb850",
          "sha256": "5f3bd0747fd710652d76f3a7dcea575df2ece83e5a849aa416b55ffa81386e71",
          "sha1": "339b0acbf86b79b36e2af116161fa26cafd9d5f5",
          "md5": "d289be6ef2d3577beca921c9fe053f3e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "paging-runtime-3.0.0-alpha01-sources.jar",
          "url": "paging-runtime-3.0.0-alpha01-sources.jar",
          "size": 26911,
          "sha512": "e506070a21c3fb43378a06a3b80a1649f55dece2c342d5db41feefd5bee34c2ecc8b61ddd0155462b2bc0b776ae01c9b810dee2a14483d743b0e21c4e79644e9",
          "sha256": "66412fc9b3be9b0d9f0b3521a5be7448ff6dd227984328833f6df54a415da0a2",
          "sha1": "7158727b6741bd1d5af12d536cd3ec7a92fc0c74",
          "md5": "98fbe54e165a1affc6dc1899af37d661"
        }
      ]
    }
  ]
}
