{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.browser",
    "module": "browser",
    "version": "1.9.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13042766"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "browser-1.9.0-alpha01-sources.jar",
          "url": "browser-1.9.0-alpha01-sources.jar",
          "size": 135505,
          "sha512": "6905c4d557644f93b46c621819f4e689127dce9509dfdf2b34443771f09469ca9433708ccce8dc1455845ae149ce5051d5083d99c0c8e346c60a42cb16700b38",
          "sha256": "b9620e84ae821d120a4f5b770c08bcb89470be396fdd4967684ea1ed70f024d2",
          "sha1": "4b0508d3c82641036299cdfe937cbb774f68f0c0",
          "md5": "901b71a1cdf1edb57a80f3ff52405211"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.9.0-alpha01.aar",
          "url": "browser-1.9.0-alpha01.aar",
          "size": 277953,
          "sha512": "683c15010bbe86866550162d08aff241bb6c75de8f8d2a5b9cfa78c0f49039f66e66068256c5aa6f834677c1a52d22006aa8c6f6315b170f1e48da0a2ac2aa72",
          "sha256": "0c30f6dda4f33565609a5101ed44842193b74ce416af275c52c7f5f0713cc011",
          "sha1": "00ea6e75586704d195db1c276cbca6ad47fc3d12",
          "md5": "16a87639a2283f40f07c18318162125b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.9.0-alpha01.aar",
          "url": "browser-1.9.0-alpha01.aar",
          "size": 277953,
          "sha512": "683c15010bbe86866550162d08aff241bb6c75de8f8d2a5b9cfa78c0f49039f66e66068256c5aa6f834677c1a52d22006aa8c6f6315b170f1e48da0a2ac2aa72",
          "sha256": "0c30f6dda4f33565609a5101ed44842193b74ce416af275c52c7f5f0713cc011",
          "sha1": "00ea6e75586704d195db1c276cbca6ad47fc3d12",
          "md5": "16a87639a2283f40f07c18318162125b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "browser-1.9.0-alpha01-versionMetadata.json",
          "url": "browser-1.9.0-alpha01-versionMetadata.json",
          "size": 41108,
          "sha512": "19e6e82f3b75db8b0d1eea9e9cfc7eb0356c08b79a4f4f508aad2234f95cc5c7da4f127a1b797e0e4a2faf4612228b6a81171fcdbd51f2c2de13bbe5db2531c4",
          "sha256": "2711d2e773ac7cf5abcee36654f6ca7d779fce4d7434cf11d3ab7876ce8ec788",
          "sha1": "87bd91c4fc69d195519bd2711865c069fce8abc4",
          "md5": "5ad9d7fef9abe808080c807efaaa813b"
        }
      ]
    }
  ]
}