{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-animation",
    "version": "1.0.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-1.0.0-rc01.aar",
          "url": "core-animation-1.0.0-rc01.aar",
          "size": 122145,
          "sha512": "1186599954d249399770728d895e7d751ec733d1784e267f40d305daa8cf262d65cf3efc920dc7e3467bfb5f08df142cc0b50e5690b725be233b8994bafb8912",
          "sha256": "2593e7e4996207e9e9d0fdf22e103f22103197e3f9e8540c1ce26c8e6864cdbf",
          "sha1": "a67fd91de08a55dc1cbf4142884ab13ac3422d9a",
          "md5": "f3c4ce98053e70352b15382ee24fd33f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0-beta01"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-animation-1.0.0-rc01.aar",
          "url": "core-animation-1.0.0-rc01.aar",
          "size": 122145,
          "sha512": "1186599954d249399770728d895e7d751ec733d1784e267f40d305daa8cf262d65cf3efc920dc7e3467bfb5f08df142cc0b50e5690b725be233b8994bafb8912",
          "sha256": "2593e7e4996207e9e9d0fdf22e103f22103197e3f9e8540c1ce26c8e6864cdbf",
          "sha1": "a67fd91de08a55dc1cbf4142884ab13ac3422d9a",
          "md5": "f3c4ce98053e70352b15382ee24fd33f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-animation-1.0.0-rc01-sources.jar",
          "url": "core-animation-1.0.0-rc01-sources.jar",
          "size": 115942,
          "sha512": "27c69f53b4970085618090c2bbf1bc838afc0a662e9fdef095d444ffa48732e0997dbbbe480e985cd5ea904eb6d45eac9e00acbd20d6d769916eeed39e592acd",
          "sha256": "d624a7ac204e2d5b351a4d58fabe5ee39696dab8e036baa19a3ae195edc74334",
          "sha1": "f369e89643e2710b875a2db1a838e7b648c2b5cd",
          "md5": "e50d483bc83fcae47f8e92ffb47e20eb"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-animation-1.0.0-rc01-versionMetadata.json",
          "url": "core-animation-1.0.0-rc01-versionMetadata.json",
          "size": 23332,
          "sha512": "421d940c78e0fcdb462b6ed8e5cfddf9bc102ed99094cabd04ed1b55b1a96b00e3663c7c6b5274f70f1684b0c945b59c2137ba4209dfd7d26d98eecd6d47e2b4",
          "sha256": "288cecc89ee82237df3703672e97d6fb47a5052c9c32bc5f8312c4234bca264f",
          "sha1": "6d56aca820eca3d83c6f43b514791da6b2df11bc",
          "md5": "c577a80c27c4e578714a8f49a348a751"
        }
      ]
    }
  ]
}