{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch-platform-storage",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.1.0-alpha04-sources.jar",
          "url": "appsearch-platform-storage-1.1.0-alpha04-sources.jar",
          "size": 51722,
          "sha512": "730089ba89e24a5683afba7702bae25c7fafb1d534c08c5623060ec6159da10614fcb06ddb7468b6efed9ee5628ca8913751d637b5706659e33a421d85e93c8f",
          "sha256": "eed9bbbb16266fa89d289c74e985a448fd96083cae478e0998a37e870655fb75",
          "sha1": "584fb67237b0eb925c9b784b69d41ffcf97baa3f",
          "md5": "039180c65e7d33f8ed39b0d636780565"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.1.0-alpha04.aar",
          "url": "appsearch-platform-storage-1.1.0-alpha04.aar",
          "size": 79339,
          "sha512": "606bb55c376cefc7fd013503e8243734c9cda6c1dc62e1b4522cc81a08d1e75920aed389b03b73cf779c6394998de439169d53353b01fe3f8a4c805642889a36",
          "sha256": "f7559ad75f2e8af4a6ff7bbac781168a09a12cf08041bb909ec1a3f747e93573",
          "sha1": "f0b2974d49189ae4298129421fc8d49007e357aa",
          "md5": "541b3303176694764e442d9de0c052d5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.1.0-alpha04.aar",
          "url": "appsearch-platform-storage-1.1.0-alpha04.aar",
          "size": 79339,
          "sha512": "606bb55c376cefc7fd013503e8243734c9cda6c1dc62e1b4522cc81a08d1e75920aed389b03b73cf779c6394998de439169d53353b01fe3f8a4c805642889a36",
          "sha256": "f7559ad75f2e8af4a6ff7bbac781168a09a12cf08041bb909ec1a3f747e93573",
          "sha1": "f0b2974d49189ae4298129421fc8d49007e357aa",
          "md5": "541b3303176694764e442d9de0c052d5"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.1.0-alpha04"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.1.0-alpha04-versionMetadata.json",
          "url": "appsearch-platform-storage-1.1.0-alpha04-versionMetadata.json",
          "size": 1680,
          "sha512": "e650cb97f2a3ac3441efcfe9579cd7aca0ab0abfa4c5f7a0eb0fb16e106908ad4d83f0a55e6128d530a129cad43e81f4d981d7eec31d8a4f7ec6dc6f4c4a277c",
          "sha256": "76179ecb5c7ddf65e9e77fa8f87a4ac4b02aaa17b37aee557506f33a1025efa2",
          "sha1": "ce7c011b4840bca4273f9a38bdef9a64fd6db9b4",
          "md5": "72e4559873c23baaf26e875a082683ad"
        }
      ]
    }
  ]
}