{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.6.0-alpha01/runtime-saveable-1.6.0-alpha01.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.6.0-alpha01.aar",
          "size": 1113099,
          "sha512": "6ace5d7a4199336a0459564198c069756023d765fe1062537092e5f80cedd2530c4f1d3d3a0ab0964f9d36456c3dfd89df3ef3eff96274e180a5d9e243b3fe27",
          "sha256": "c697e0ec7525a8e0dbf8c546d666b8f8d4b1fe1ea89f7d22645bbcc26d4222ab",
          "sha1": "e947ff662cd4543620c9c9f2abc3474f1995ff13",
          "md5": "17e8d0dd36d41ecef358d4e4b90a948d"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.6.0-alpha01.aar",
          "size": 1113099,
          "sha512": "6ace5d7a4199336a0459564198c069756023d765fe1062537092e5f80cedd2530c4f1d3d3a0ab0964f9d36456c3dfd89df3ef3eff96274e180a5d9e243b3fe27",
          "sha256": "c697e0ec7525a8e0dbf8c546d666b8f8d4b1fe1ea89f7d22645bbcc26d4222ab",
          "sha1": "e947ff662cd4543620c9c9f2abc3474f1995ff13",
          "md5": "17e8d0dd36d41ecef358d4e4b90a948d"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-android-1.6.0-alpha01-sources.jar",
          "url": "runtime-saveable-android-1.6.0-alpha01-sources.jar",
          "size": 11261,
          "sha512": "353dbd37e0e705e4f546553816aa3044ff6f6dc9196a969f054fcc76eb6f0941b888cd18a899032a93fb93b37d1f72e0dd3c4cd3a0c609f8f9af2663dc11c0b6",
          "sha256": "7ca054d45e49e3e3b2dadf9801283baa460c61b1696f0f58b9c1e5dfb23a137e",
          "sha1": "9199ad94957308ea897703746d098f7d6f1feddd",
          "md5": "787c5dfd9b7e3d0f5489148a2490a248"
        }
      ]
    }
  ]
}