{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6836159"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.5.0-alpha02.aar",
          "url": "work-runtime-ktx-2.5.0-alpha02.aar",
          "size": 21932,
          "sha512": "1bcac3d650b1cf1d8e2c4d15e0db5c772b6cf6b2c489e071d4145d62507f6914ab3b8f5629276fb560eb2bf5f4c7e1b268b05f74425d7f752ece20ebdc4e70e8",
          "sha256": "9f5ad6d3f41f3bd75f80bafd6d57d4c4bc8404aec62ccd8d08b6154621b56245",
          "sha1": "18f4714fdd61eb77282a8fa58dda8c2d9f8310f2",
          "md5": "88a891d9fdceea7c701916cf51b15931"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.7"
          }
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.5.0-alpha02.aar",
          "url": "work-runtime-ktx-2.5.0-alpha02.aar",
          "size": 21932,
          "sha512": "1bcac3d650b1cf1d8e2c4d15e0db5c772b6cf6b2c489e071d4145d62507f6914ab3b8f5629276fb560eb2bf5f4c7e1b268b05f74425d7f752ece20ebdc4e70e8",
          "sha256": "9f5ad6d3f41f3bd75f80bafd6d57d4c4bc8404aec62ccd8d08b6154621b56245",
          "sha1": "18f4714fdd61eb77282a8fa58dda8c2d9f8310f2",
          "md5": "88a891d9fdceea7c701916cf51b15931"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-runtime-ktx-2.5.0-alpha02-sources.jar",
          "url": "work-runtime-ktx-2.5.0-alpha02-sources.jar",
          "size": 7188,
          "sha512": "098e8e676700583994fdb4f41ec8dbfe11d2c2398b5e1c486b90c0d47cfb61b251c78934c8b335bb1e04b68277da6566d783218d366b1e31469929e0c718798f",
          "sha256": "26a54cd703c6c298e7dda4ba9cd02d8802798786de1aee9c2dd002850e53b234",
          "sha1": "23637dc3b512d05e0f2b73bcb4a7b80251df9533",
          "md5": "5077cda39a0c42638438d50df90beda7"
        }
      ]
    }
  ]
}
