{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.graphics",
    "module": "graphics-path",
    "version": "1.0.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "graphics-path-1.0.0-beta02.aar",
          "url": "graphics-path-1.0.0-beta02.aar",
          "size": 38126,
          "sha512": "e42b6e882d958b346bf11fb104f37af63f7ab5783fdce1c9247bde90d5bfc5804d2ef360753a4d1a7f200ee35e9d354eeb06cf106870626b3a78972fae976d86",
          "sha256": "40bebac3cc64771ae87b84eb5f79169c7893a5cc87726c43ca97d13dad7a98b5",
          "sha1": "d54754ed98764b8d616dfe370308bc92a3bed9a7",
          "md5": "019aed39d9795fa15a2446da4464525f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "graphics-path-1.0.0-beta02.aar",
          "url": "graphics-path-1.0.0-beta02.aar",
          "size": 38126,
          "sha512": "e42b6e882d958b346bf11fb104f37af63f7ab5783fdce1c9247bde90d5bfc5804d2ef360753a4d1a7f200ee35e9d354eeb06cf106870626b3a78972fae976d86",
          "sha256": "40bebac3cc64771ae87b84eb5f79169c7893a5cc87726c43ca97d13dad7a98b5",
          "sha1": "d54754ed98764b8d616dfe370308bc92a3bed9a7",
          "md5": "019aed39d9795fa15a2446da4464525f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "graphics-path-1.0.0-beta02-sources.jar",
          "url": "graphics-path-1.0.0-beta02-sources.jar",
          "size": 9877,
          "sha512": "a60f9b155d835f231f4a76fc0f06bc98e61e4987e0c66b2be720c5b2f24e64f559b768cbdb80fa843088da4339dea18d7c372a073884ebd7e349c0da50201725",
          "sha256": "d556a5a02e4d0545d1c2aafe98b14d9f88ed0a866bab0454ca1054ba968876be",
          "sha1": "4b6077e75d90af181a6e130311c3bb7baa89285a",
          "md5": "2507f01eb74af3007588cd8da2ff4e68"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "graphics-path-1.0.0-beta02-versionMetadata.json",
          "url": "graphics-path-1.0.0-beta02-versionMetadata.json",
          "size": 2284,
          "sha512": "3ac4421902468a9931e32070e4cb65451417b178038f5f086277378ecd7b56907ccd5062771f79ee08b3e0aa35d695bf54b48be00e0f57e45805edcf5d9106a8",
          "sha256": "e5bf2330045ad308f91d8b7b7b9825d887fbdbeeb23880944374a07dd3a8f715",
          "sha1": "b61acb47e5c06cfabb363839ab7a49dff0a096ee",
          "md5": "35fcdbfc6b843261433ee313fbbcc338"
        }
      ]
    }
  ]
}