{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.sdkruntime",
    "module": "sdkruntime-core",
    "version": "1.0.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha14-sources.jar",
          "url": "sdkruntime-core-1.0.0-alpha14-sources.jar",
          "size": 31992,
          "sha512": "52111a667f44e742862e39e0d8fec7e57132fce89a48afa5460963c6c0e4b96df50b3482020c88810518d3f293392957e7e28c75f9ca03eff796c709c206a08a",
          "sha256": "d1658e4bcef73a4dfad2e3f3eee3ea1ee4962b7eb7cab91c388cf9a385ab300a",
          "sha1": "747d5becb566872c2fdc1a929d2680a625ed13e0",
          "md5": "2dd4bfeae055b34cc4ba8aac6f73e236"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha14.aar",
          "url": "sdkruntime-core-1.0.0-alpha14.aar",
          "size": 65753,
          "sha512": "ff7e5c5b08a3625ff25d7b41bd004785b35c841f16ce8d6ef8a5b824952b985a4b482e5668b8891abc02478a374cdce055349119edf3dc61421c86fb53a3389a",
          "sha256": "ab1c2c37b5a946affc2e94090dee1b685c20f5d49423ea714f5ffce39d21af09",
          "sha1": "9219e3a5364f4438884baf8a47660570a2476a7c",
          "md5": "8c59fabf90f63779db62f4dc2e7e85ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha14.aar",
          "url": "sdkruntime-core-1.0.0-alpha14.aar",
          "size": 65753,
          "sha512": "ff7e5c5b08a3625ff25d7b41bd004785b35c841f16ce8d6ef8a5b824952b985a4b482e5668b8891abc02478a374cdce055349119edf3dc61421c86fb53a3389a",
          "sha256": "ab1c2c37b5a946affc2e94090dee1b685c20f5d49423ea714f5ffce39d21af09",
          "sha1": "9219e3a5364f4438884baf8a47660570a2476a7c",
          "md5": "8c59fabf90f63779db62f4dc2e7e85ee"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha14"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha14-versionMetadata.json",
          "url": "sdkruntime-core-1.0.0-alpha14-versionMetadata.json",
          "size": 4152,
          "sha512": "b2836ee79eb709c495ec1f53d49c10a3802de4a90c59f4d5ba393dc357863c7beb5cca1efc138a7a0c2c03d7812b1c4f073fc5782fdd9765404e4484629da8ba",
          "sha256": "e0f3eac2b812935cea5f7a0e657e44b760439e57a3bb44da46ffff3057048366",
          "sha1": "4d929e6660e7723304340ca4ae65b463a1a91349",
          "md5": "1e2543b252fee73af3538ba527ef2090"
        }
      ]
    }
  ]
}