{
  "formatVersion": "1.1",
  "component": {
    "url": "../../runtime-saveable/1.7.0-alpha05/runtime-saveable-1.7.0-alpha05.module",
    "group": "androidx.compose.runtime",
    "module": "runtime-saveable",
    "version": "1.7.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.7.0-alpha05.aar",
          "size": 1105848,
          "sha512": "386dce08ed631ad1ac392f2d853c32ba3128fd32879f339db9df86c171469f4772a90a84b108b2140537c954e1ad90194c6097fdc55a8d63d15ecdb97dd8fe52",
          "sha256": "5b71d5abcc8b39a9450743cf292a9d8804f19dabae8670d9c35e1847527feef1",
          "sha1": "6109f87587edb6ab1c95a3fe970d26972cb868d6",
          "md5": "8c3e53e92d85abfa33182f0ada9921d2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-release.aar",
          "url": "runtime-saveable-android-1.7.0-alpha05.aar",
          "size": 1105848,
          "sha512": "386dce08ed631ad1ac392f2d853c32ba3128fd32879f339db9df86c171469f4772a90a84b108b2140537c954e1ad90194c6097fdc55a8d63d15ecdb97dd8fe52",
          "sha256": "5b71d5abcc8b39a9450743cf292a9d8804f19dabae8670d9c35e1847527feef1",
          "sha1": "6109f87587edb6ab1c95a3fe970d26972cb868d6",
          "md5": "8c3e53e92d85abfa33182f0ada9921d2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "fake-sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava2",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-rxjava3",
          "version": {
            "requires": "1.7.0-alpha05"
          },
          "reason": "runtime-saveable is in atomic group androidx.compose.runtime"
        }
      ],
      "files": [
        {
          "name": "runtime-saveable-android-1.7.0-alpha05-sources.jar",
          "url": "runtime-saveable-android-1.7.0-alpha05-sources.jar",
          "size": 11663,
          "sha512": "326baea73bb95d4df655daa5b2b8f44613671b930581886d54885fc55955ca5feb72aecdd55922847c444861600de704d9f04e896d1e857bafd328977fd60c35",
          "sha256": "c1730d3a69eb62ad819b12835591d0a8d7676de0b6d4257a38fa28daebbb8399",
          "sha1": "f4b8bdb1cd75cb3c61bc1a3996fe6eff4382e836",
          "md5": "084246caa2aa3053867c6bf8c5b79b6d"
        },
        {
          "name": "runtime-saveable-1.7.0-alpha05-samples-sources.jar",
          "url": "runtime-saveable-android-1.7.0-alpha05-samples-sources.jar",
          "size": 4242,
          "sha512": "e5f63bc82457d1c674a170db0a329465d93b190448a285c5ab6ba21ac4dcafed89579d908c2adf5f2cc8da805f8e2c734fae396cd0d337cab26479675d8413a9",
          "sha256": "798fb6b311ed459c2028126a3deb7596b2742d8a0694db5fc93e236aa2a1316b",
          "sha1": "f455c0e1f32983bec40d871459943835e3d10c96",
          "md5": "54da7c450cadd9706f836a217bfa469f"
        }
      ]
    }
  ]
}