{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.tools",
    "module": "tools-apicompiler",
    "version": "1.0.0-alpha10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apicompiler-1.0.0-alpha10.jar",
          "url": "tools-apicompiler-1.0.0-alpha10.jar",
          "size": 94594,
          "sha512": "b7f55d79e1267769f9ad5798a7c8cc38b59c698a75f3c8fdce9567698d28774e4ee0e7ca9631feaa8f9597ffd76c4d03d5c9f8f51f5b45cfb83ed86dabca7564",
          "sha256": "83ef926f8bec3de30c13f65ff7eda7cac3c7704689dd38b9753bdbf7c3822c58",
          "sha1": "184e852920e0e202cc18dc6fd8d66e8aaf3242b1",
          "md5": "bb34582e2540971f46fd48c7baef943b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "2.0.10-1.0.24"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.14.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apicompiler-1.0.0-alpha10.jar",
          "url": "tools-apicompiler-1.0.0-alpha10.jar",
          "size": 94594,
          "sha512": "b7f55d79e1267769f9ad5798a7c8cc38b59c698a75f3c8fdce9567698d28774e4ee0e7ca9631feaa8f9597ffd76c4d03d5c9f8f51f5b45cfb83ed86dabca7564",
          "sha256": "83ef926f8bec3de30c13f65ff7eda7cac3c7704689dd38b9753bdbf7c3822c58",
          "sha1": "184e852920e0e202cc18dc6fd8d66e8aaf3242b1",
          "md5": "bb34582e2540971f46fd48c7baef943b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apigenerator",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-apipackager",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        },
        {
          "group": "androidx.privacysandbox.tools",
          "module": "tools-core",
          "version": {
            "requires": "1.0.0-alpha10"
          },
          "reason": "tools-apicompiler is in atomic group androidx.privacysandbox.tools"
        }
      ],
      "files": [
        {
          "name": "tools-apicompiler-1.0.0-alpha10-sources.jar",
          "url": "tools-apicompiler-1.0.0-alpha10-sources.jar",
          "size": 20685,
          "sha512": "4729c6541b9b840c4f8d6ce905684e09aabe849112d28cfd5c113b1c6c9f55e784a7397a1bbeab89f189ae29c9ce0ca3908c7cff8923db16906af705ae1d58b6",
          "sha256": "7e7fdbcc28de9eb2b26c25f1098d59f9f473787a6fc47defd2e39b8b922d6adc",
          "sha1": "0b4e20aae0ad194fc8544396558e04b5e47cb2b7",
          "md5": "15a41587b3130fa60ae4bc5a069a764f"
        }
      ]
    }
  ]
}