{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-rxjava2",
    "version": "1.1.0-beta02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.1.0-beta02.aar",
          "url": "datastore-preferences-rxjava2-1.1.0-beta02.aar",
          "size": 15100,
          "sha512": "1b6818cc020c78bd6f30802e309845c2c9860fca24ed169c2056a67cae64b20297a3e682971564246cc6c4cf799f1178cd12587ea9eddc0fbc3f159dd3eb66f8",
          "sha256": "c3eb28f30257d4ea3c5321e7281b08bf4d516b3f628f0103126fd9642adc67a2",
          "sha1": "b4b1fb46a864aa7ff70ab9dc69606082c6ff5998",
          "md5": "3c3a863be15e4f2b4eafe3527501c9c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta02"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.1.0-beta02.aar",
          "url": "datastore-preferences-rxjava2-1.1.0-beta02.aar",
          "size": 15100,
          "sha512": "1b6818cc020c78bd6f30802e309845c2c9860fca24ed169c2056a67cae64b20297a3e682971564246cc6c4cf799f1178cd12587ea9eddc0fbc3f159dd3eb66f8",
          "sha256": "c3eb28f30257d4ea3c5321e7281b08bf4d516b3f628f0103126fd9642adc67a2",
          "sha1": "b4b1fb46a864aa7ff70ab9dc69606082c6ff5998",
          "md5": "3c3a863be15e4f2b4eafe3527501c9c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.1.0-beta02-sources.jar",
          "url": "datastore-preferences-rxjava2-1.1.0-beta02-sources.jar",
          "size": 5014,
          "sha512": "2b9a98f6a75fa1b63982a6140877e3fcd893d7c368e77ea81bee735bf1676f92c45bb922dae974071aea1bffde134d2a6d14e7a393769c907964dccfe9015edd",
          "sha256": "0197c051bd77239a9437a2bd90a37717a8f65c7c3d686e4bb85b852ed1c45eac",
          "sha1": "33f3c428807233a63d2c7b3a9c0abb74394446a7",
          "md5": "0a49e6bae66c1e6be633ae9a6c61352f"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.1.0-beta02"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.1.0-beta02-versionMetadata.json",
          "url": "datastore-preferences-rxjava2-1.1.0-beta02-versionMetadata.json",
          "size": 1400,
          "sha512": "9338cc10fd4b7008c71c6f08b626d361f2aa5b9e6d2dab1f6353920f915e4252cd1192fa078bd5028b4f4f2fe25a0b768c6930fb0fa4125d0e5f176f67746624",
          "sha256": "8bc4d626be686f6118b1a0fa10e6cd374bdd56298dedd40bc39e9a8ba1ca6600",
          "sha1": "422f2bcee02796bfccce1ef788d28ecb11f3fb48",
          "md5": "8a9f99e851fd043ab33d38bbc56c3c5a"
        }
      ]
    }
  ]
}