{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera",
    "module": "camera-camera2",
    "version": "1.4.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8-rc-1"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01-sources.jar",
          "url": "camera-camera2-1.4.0-beta01-sources.jar",
          "size": 367211,
          "sha512": "cef098a32daafab526890cd1d2da538a82f2e5f5880e863d7bb12fc55566f0dd52005edee40c0475d8c01fb3ed4893541cb5f86997220a56a55516bd2c0d939c",
          "sha256": "95530d39adea2f465bdf973b9301cbd789bea7168cd5513f9518b0fe66f94658",
          "sha1": "27ba38d73bca90893d98837576575190d13e8cf7",
          "md5": "a8be088be69d62201246972d78f24eac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01.aar",
          "url": "camera-camera2-1.4.0-beta01.aar",
          "size": 466568,
          "sha512": "5576d5166f975839a1ea27c67b92fd0123436157a279433006430693faf635937d007e7e5d3077d39ea08496d7db82afa197dc0f5e683fa1f5c4790e0afee753",
          "sha256": "8d84a8d964439aa431f8ffd3638ad9e48af3421f302a2e1b2a21e40fbbaa8f0c",
          "sha1": "df906850dbec40db5cf7569686e48f8b58c917b5",
          "md5": "4fd9d0a66978fa3e988e94b33cba234a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01.aar",
          "url": "camera-camera2-1.4.0-beta01.aar",
          "size": 466568,
          "sha512": "5576d5166f975839a1ea27c67b92fd0123436157a279433006430693faf635937d007e7e5d3077d39ea08496d7db82afa197dc0f5e683fa1f5c4790e0afee753",
          "sha256": "8d84a8d964439aa431f8ffd3638ad9e48af3421f302a2e1b2a21e40fbbaa8f0c",
          "sha1": "df906850dbec40db5cf7569686e48f8b58c917b5",
          "md5": "4fd9d0a66978fa3e988e94b33cba234a"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-effects",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-extensions",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-mlkit-vision",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.4.0-beta01"
          },
          "reason": "camera-camera2 is in atomic group androidx.camera"
        }
      ],
      "files": [
        {
          "name": "camera-camera2-1.4.0-beta01-versionMetadata.json",
          "url": "camera-camera2-1.4.0-beta01-versionMetadata.json",
          "size": 3277,
          "sha512": "3457aaf1daae3c23df1afa125444b2c9febccd6c8eee62fddb37b74e4d217ea8183aafd55fe757191cd7be2d45e078616d54dbb1f172558a02fe063cbec75f1f",
          "sha256": "d8cec82581880afa10cba43907db64357c3f6a765fd7598a042eb7943b1019f4",
          "sha1": "f1e5deb7118484ad497eec922b64b108f5993b67",
          "md5": "6d6e3a9187e23ee6c4cd6dfcaa04b2b9"
        }
      ]
    }
  ]
}