{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.5.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13649143"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha02-sources.jar",
          "url": "window-1.5.0-alpha02-sources.jar",
          "size": 215632,
          "sha512": "386e059ed7af0a0e79cbc1293ab204076b081d01ef9b0fa9c2c1e8ce81f1ba19b7ef70c802c33aae6a73a3cd1b6b8625073eda6efacb33f80709278e0be78070",
          "sha256": "cec990c7a79bf8afca6c3345a23b385b9cf440523853fe11c0b9d4cca361d3d7",
          "sha1": "defff91125ad35085d239677c155b0cfcab2e415",
          "md5": "0d0d475bb52318cfc4ee09c5454fdfc5"
        },
        {
          "name": "window-1.5.0-alpha02-samples-sources.jar",
          "url": "window-1.5.0-alpha02-samples-sources.jar",
          "size": 11043,
          "sha512": "b0df533459467ffd3efcb3768b240986d55d72c1056ad8fbef7c577ffd1a34a1e140a0156a060c5458e5dacfab9a19612dd0602d95f340de7e243f0c9dd479ea",
          "sha256": "78d7db2d1392f884e22181fc4692ff360fe007c1fb0131b12f18edaea7ace25f",
          "sha1": "847286072aca2a5a6e527590b369453a53c61671",
          "md5": "abdfae2cc061067e4d75b8f17dd0ac85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha02.aar",
          "url": "window-1.5.0-alpha02.aar",
          "size": 485775,
          "sha512": "78ee8a7d2eba4fa2d8fe95abdc18fb9b14c9312aac13deae96e303a2948d52e244aaa9de3ac4f892a5f016fde5c3f63596334b4fd3d0d04e623826c46755128a",
          "sha256": "6ffb03e7a2bb2f9fce2d35fdd8dc2048cb123d764ba072d69e63c6dc87b1790c",
          "sha1": "37286643dbc49afcd775a455f7b42c4ebe2988ad",
          "md5": "f33d80ace27f9a1f44ae970b25897ea2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha02.aar",
          "url": "window-1.5.0-alpha02.aar",
          "size": 485775,
          "sha512": "78ee8a7d2eba4fa2d8fe95abdc18fb9b14c9312aac13deae96e303a2948d52e244aaa9de3ac4f892a5f016fde5c3f63596334b4fd3d0d04e623826c46755128a",
          "sha256": "6ffb03e7a2bb2f9fce2d35fdd8dc2048cb123d764ba072d69e63c6dc87b1790c",
          "sha1": "37286643dbc49afcd775a455f7b42c4ebe2988ad",
          "md5": "f33d80ace27f9a1f44ae970b25897ea2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.5.0-alpha02"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.5.0-alpha02-versionMetadata.json",
          "url": "window-1.5.0-alpha02-versionMetadata.json",
          "size": 29620,
          "sha512": "0c018da017f984f7b5ab2cb2c8aca5db106bd5d8a19094fa3f5e1afe4a26d618ffa17c0aec90dac37cbc294b0a6b4ca05f0db8c91c807cdcb18595735a3499ef",
          "sha256": "6b51ee42a4c156662b80f3b4c6ead4d3882896ee16dc62b4e6179126527b8762",
          "sha1": "88d7ba10fcc0038378db4e65937d5d73764e2568",
          "md5": "4581d10586e85dbe615bb4dc8a285137"
        }
      ]
    }
  ]
}