version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-android"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-iosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-iossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-iosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-jvm"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-linuxarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-linuxx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-macosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-macosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.datastore"
group_id: "androidx.datastore"
artifact_id: "datastore-preferences"
path: "/datastore/datastore-preferences"
sha: "d3d9ab3bace349227f12e907dccb240d59e18937"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.datastore-datastore-preferences-all-12158610-1.2.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core-okio"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-external-protobuf"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
