version: "1.2.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-android"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-iosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-iossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-iosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-jvm"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-linuxarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-linuxx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-macosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-macosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-tvosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-tvossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-tvosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-watchosarm32"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-watchosarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-watchosdevicearm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-watchossimulatorarm64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-watchosx64"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.datastore"
group_id: "androidx.datastore"
artifact_id: "datastore-preferences"
path: "/datastore/datastore-preferences"
sha: "92fff33a773dd88ed4f75a9cbd9935de137ca813"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.datastore-datastore-preferences-all-12640356-1.2.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-core-okio"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-guava"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-core"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-external-protobuf"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-proto"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-preferences-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava2"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.datastore"
    artifact_id: "datastore-rxjava3"
    version: "1.2.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "jvm"
kmp_children: "macosx64"
kmp_children: "macosarm64"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "watchosx64"
kmp_children: "watchosarm64"
kmp_children: "watchosdevicearm64"
kmp_children: "watchossimulatorarm64"
kmp_children: "tvosx64"
kmp_children: "tvosarm64"
kmp_children: "tvossimulatorarm64"
kmp_children: "android"
