{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-ui-ktx",
    "version": "2.9.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "13006434"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.9.0-alpha06-sources.jar",
          "url": "navigation-ui-ktx-2.9.0-alpha06-sources.jar",
          "size": 4438,
          "sha512": "02efbaf8421c39158b7691d284b0496266ea751100bcb5d1d4d54480b4b4b9371ab806b5b1d269e1d4b1dfaf51aae104139e0540ba8b1a675531204037bc11f9",
          "sha256": "e63a83fb372493336615b76ee8755731a05e312f187f527a6a358f638377b25c",
          "sha1": "7a9a22bc053aaa0170c4952b0403a0b9b8f81e4d",
          "md5": "0977156890f566d39694a7cd2b627d07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.9.0-alpha06.aar",
          "url": "navigation-ui-ktx-2.9.0-alpha06.aar",
          "size": 5782,
          "sha512": "1e0b1e29228f0dfaff85c716f8144ecfa64cc9210c2e225e727d6a72bf800b357567286fb124803bec16b3ee63b7f3440421105c2f42d7510af28f688515f7e2",
          "sha256": "ec7a032b2ea3e33292b59aebc78274c25385005eb50b1ade391c83b535ae79a4",
          "sha1": "a49468c18802733e0ed24669b0529820150de946",
          "md5": "5088261c1b9b7290a9e8b04ecdb5c1d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha06"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.9.0-alpha06.aar",
          "url": "navigation-ui-ktx-2.9.0-alpha06.aar",
          "size": 5782,
          "sha512": "1e0b1e29228f0dfaff85c716f8144ecfa64cc9210c2e225e727d6a72bf800b357567286fb124803bec16b3ee63b7f3440421105c2f42d7510af28f688515f7e2",
          "sha256": "ec7a032b2ea3e33292b59aebc78274c25385005eb50b1ade391c83b535ae79a4",
          "sha1": "a49468c18802733e0ed24669b0529820150de946",
          "md5": "5088261c1b9b7290a9e8b04ecdb5c1d3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha06"
          },
          "reason": "navigation-ui-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-ui-ktx-2.9.0-alpha06-versionMetadata.json",
          "url": "navigation-ui-ktx-2.9.0-alpha06-versionMetadata.json",
          "size": 6082,
          "sha512": "8576b37f0ebabd2f0339fade3dfec3f95bd39040b3833cec2ac942a0800e6d3f5f47bc0d9f2cecdf5ad1cc8500a7e41c5d6aad1850ac508572d97b3132c68f55",
          "sha256": "c3c32741da0cf12ef0924ef329d1e506cdf9c8d377e1fee9693ee501d219bdd2",
          "sha1": "e104dacb74c61e055d19bdb4df68105c328faa7e",
          "md5": "9c2f4a61ea6960d56d85da82ec6af38a"
        }
      ]
    }
  ]
}