version: "1.0.0-alpha16"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.12.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-core"
    version: "1.0.0-alpha16"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13621151"
group_id: "androidx.privacysandbox.ui"
artifact_id: "ui-provider"
path: "/privacysandbox/ui/ui-provider"
sha: "01c729916ecab8a9b289a8f1dfb87680841cee41"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.ui-ui-provider-all-13621151-1.0.0-alpha16.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-client"
    version: "1.0.0-alpha16"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-client-compose"
    version: "1.0.0-alpha16"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.ui"
    artifact_id: "ui-core"
    version: "1.0.0-alpha16"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "privacysandbox-ui-ui-providerreleaseAndroidTest.xml"
test_module_names: ":privacysandbox:ui:ui-provider:testReleaseUnitTest"
