{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.slice",
    "module": "slice-view",
    "version": "1.1.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6732122"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-view-1.1.0-alpha02.aar",
          "url": "slice-view-1.1.0-alpha02.aar",
          "size": 275295,
          "sha512": "25ec1ab2a02e1a5996b3c57f48da18e01fddffbf93bc5ff45c7b7abefb1c03eac53db2d7b3b23960133ba3a822562c706c07d27faf4cb621501fa7ed32e4ac4f",
          "sha256": "d74b2500ed9401d7a5f08a81c776ba1df03cec9fe1274459fc1ca4b6d21945c2",
          "sha1": "460bda64ec796457ebff4e3601108d841e3917d5",
          "md5": "e916029d5e957f38ea2edd2849aa21d2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.slice",
          "module": "slice-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0-alpha05"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "slice-view-1.1.0-alpha02.aar",
          "url": "slice-view-1.1.0-alpha02.aar",
          "size": 275295,
          "sha512": "25ec1ab2a02e1a5996b3c57f48da18e01fddffbf93bc5ff45c7b7abefb1c03eac53db2d7b3b23960133ba3a822562c706c07d27faf4cb621501fa7ed32e4ac4f",
          "sha256": "d74b2500ed9401d7a5f08a81c776ba1df03cec9fe1274459fc1ca4b6d21945c2",
          "sha1": "460bda64ec796457ebff4e3601108d841e3917d5",
          "md5": "e916029d5e957f38ea2edd2849aa21d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "slice-view-1.1.0-alpha02-sources.jar",
          "url": "slice-view-1.1.0-alpha02-sources.jar",
          "size": 101452,
          "sha512": "5edc0e5dfca401adee9d6eb62c4a5e53c06389633255b7fe5c241d283901b80db1624a4db8f6d77bcf10054c3890155f8f4d378238d6a95055b03838e5cf3592",
          "sha256": "90f4bc9c4285a08f9d2782c4d5da0e1c67d4511dfac189d0f85e3f364ce42ff6",
          "sha1": "7bcf74518b04f4411c8be294e447d4078bfd59ab",
          "md5": "16d002fb10be19ef4fc16969dd6281c4"
        }
      ]
    }
  ]
}
