version: "1.0.0-alpha07"
dependency_list {
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.9.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-android"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-desktop"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-iosarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-iossimulatorarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-iosx64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-js"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-linuxarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-linuxx64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-macosarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-macosx64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-mingwx64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-tvosarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-tvossimulatorarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-tvosx64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-wasm-js"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-watchosarm32"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-watchosarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-watchosdevicearm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-watchossimulatorarm64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-compose-watchosx64"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "13986476"
group_id: "androidx.navigationevent"
artifact_id: "navigationevent-compose"
path: "/navigationevent/navigationevent-compose"
sha: "c506a16ba09762f704dc84c4df29090f48baa268"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.navigationevent-navigationevent-compose-all-1.0.0-alpha07.zip"
kotlin_version: "2.2.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.navigationevent"
    artifact_id: "navigationevent-testing"
    version: "1.0.0-alpha07"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx_multiplatform_mac"
kmp_children: "android"
kmp_children: "desktop"
kmp_children: "macosx64"
kmp_children: "macosarm64"
kmp_children: "linuxarm64"
kmp_children: "linuxx64"
kmp_children: "iosx64"
kmp_children: "iosarm64"
kmp_children: "iossimulatorarm64"
kmp_children: "watchosx64"
kmp_children: "watchosarm32"
kmp_children: "watchosarm64"
kmp_children: "watchosdevicearm64"
kmp_children: "watchossimulatorarm64"
kmp_children: "tvosx64"
kmp_children: "tvosarm64"
kmp_children: "tvossimulatorarm64"
kmp_children: "mingwx64"
kmp_children: "js"
kmp_children: "wasm-js"
test_module_names: ":navigationevent:navigationevent-compose:desktopTest"
test_module_names: ":navigationevent:navigationevent-compose:macosX64Test"
test_module_names: ":navigationevent:navigationevent-compose:macosArm64Test"
test_module_names: ":navigationevent:navigationevent-compose:linuxX64Test"
test_module_names: ":navigationevent:navigationevent-compose:iosX64Test"
test_module_names: ":navigationevent:navigationevent-compose:iosSimulatorArm64Test"
test_module_names: ":navigationevent:navigationevent-compose:watchosX64Test"
test_module_names: ":navigationevent:navigationevent-compose:watchosSimulatorArm64Test"
test_module_names: ":navigationevent:navigationevent-compose:tvosX64Test"
test_module_names: ":navigationevent:navigationevent-compose:tvosSimulatorArm64Test"
test_module_names: ":navigationevent:navigationevent-compose:mingwX64Test"
test_module_names: ":navigationevent:navigationevent-compose:jsBrowserTest"
test_module_names: ":navigationevent:navigationevent-compose:wasmJsBrowserTest"
test_module_names: "navigationevent-navigationevent-composeandroidInstrumentedTest.xml"
test_module_names: ":navigationevent:navigationevent-compose:testAndroidHostTest"
