{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-editor-guava",
    "version": "1.3.0-alpha07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13351945"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-guava-1.3.0-alpha07-sources.jar",
          "url": "watchface-editor-guava-1.3.0-alpha07-sources.jar",
          "size": 7477,
          "sha512": "bb6f556bdb3f317dfafbb7b4e6c24f6e51ebc0da6977fa94e0491c71f901a4c1fdeabb266c601a71d76950f3b717dba7b16fe2c768f193a0548554327e9f6dff",
          "sha256": "f2a5e1082a7adaad7932aaa77cc8c5fcd6123742dd5d1b69f9cac0aa3ffc845c",
          "sha1": "ac00678b4d1f202da706bf706e03afbd5ae25a6c",
          "md5": "cd2ad68a46c9141084eeabc63ab960c0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-guava-1.3.0-alpha07.aar",
          "url": "watchface-editor-guava-1.3.0-alpha07.aar",
          "size": 17576,
          "sha512": "0a418a071b95fcf07ab5bb5123b8a3ea05a8cc04134029e22194038d36e78e2739f22f41beff89b19a3f832fab053eddc2c81276dfe3f377ed60e3c5e8794b8c",
          "sha256": "070714fc20bf96117c458899629ce8239d84ee46bfdb78c8088a22eb460e88ae",
          "sha1": "bbe5aafdf3f6e424e87eb4bdbc07ef23a56db662",
          "md5": "fa5cbaa64d2e51444c608b3d7d34922e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-guava-1.3.0-alpha07.aar",
          "url": "watchface-editor-guava-1.3.0-alpha07.aar",
          "size": 17576,
          "sha512": "0a418a071b95fcf07ab5bb5123b8a3ea05a8cc04134029e22194038d36e78e2739f22f41beff89b19a3f832fab053eddc2c81276dfe3f377ed60e3c5e8794b8c",
          "sha256": "070714fc20bf96117c458899629ce8239d84ee46bfdb78c8088a22eb460e88ae",
          "sha1": "bbe5aafdf3f6e424e87eb4bdbc07ef23a56db662",
          "md5": "fa5cbaa64d2e51444c608b3d7d34922e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-push",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha07"
          },
          "reason": "watchface-editor-guava is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-guava-1.3.0-alpha07-versionMetadata.json",
          "url": "watchface-editor-guava-1.3.0-alpha07-versionMetadata.json",
          "size": 2876,
          "sha512": "898bbecb2eab98ff358cdf2db5969584190f55574a76498fc3fc2f0c0884cbad77cee5b2304684e654a74ffc63af4902de97c0a2d2f2cb8d0799c3d158b679c0",
          "sha256": "a62d7b10bffa01b7b6a39f2b50714c9ef65563380bb9969da3da1cb53ce8aa36",
          "sha1": "1a65fad5751b3080739cb34ce751018399b0f16b",
          "md5": "d4defd727cb86096d4d3bb0c6ae4dd84"
        }
      ]
    }
  ]
}