{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.health",
    "module": "health-services-client-external-protobuf",
    "version": "1.1.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "health-services-client-external-protobuf-1.1.0-alpha04.jar",
          "url": "health-services-client-external-protobuf-1.1.0-alpha04.jar",
          "size": 1048442,
          "sha512": "cec8b0480e6c3ad191af456c3e8e5788973c1f05696445f7e33d4c69fad550f313296c81c746352b28ea8323d81c24b7f6db48a2e68d820a3f1f60c38733b119",
          "sha256": "723078eb75aa9fa1d7735c47b3adf9ccd4e462bdc90c295ed6de8ae4f36f22d3",
          "sha1": "cc1431a4712b12d4ca2dd3c59f1951cf18bcf83a",
          "md5": "96a20e6a055b008bb29fca3f45b70b46"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "health-services-client-external-protobuf-1.1.0-alpha04.jar",
          "url": "health-services-client-external-protobuf-1.1.0-alpha04.jar",
          "size": 1048442,
          "sha512": "cec8b0480e6c3ad191af456c3e8e5788973c1f05696445f7e33d4c69fad550f313296c81c746352b28ea8323d81c24b7f6db48a2e68d820a3f1f60c38733b119",
          "sha256": "723078eb75aa9fa1d7735c47b3adf9ccd4e462bdc90c295ed6de8ae4f36f22d3",
          "sha1": "cc1431a4712b12d4ca2dd3c59f1951cf18bcf83a",
          "md5": "96a20e6a055b008bb29fca3f45b70b46"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "health-services-client-external-protobuf-1.1.0-alpha04-sources.jar",
          "url": "health-services-client-external-protobuf-1.1.0-alpha04-sources.jar",
          "size": 1683,
          "sha512": "4d46b98557648a8b42626f195cb45d3a604053ea63cb11c3a14a2f0ffd2038c3b74534e05974f114a9dd778a887fceb4ad85ee042e99e5046e1e23e43bf1ee74",
          "sha256": "9cde3bcecf0fcd31877ed817445ccf5fd1575682c2c973ccf1c7aff0b65ca0e8",
          "sha1": "c987c258406cc9f68f9d7292e70abeb203f18ebb",
          "md5": "fc28a5381bf32a1b824ac3b2aa4d1100"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "health-services-client-external-protobuf-1.1.0-alpha04-versionMetadata.json",
          "url": "health-services-client-external-protobuf-1.1.0-alpha04-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}