{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-preferences-rxjava2",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "14059446"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.2.0-alpha03-sources.jar",
          "url": "datastore-preferences-rxjava2-1.2.0-alpha03-sources.jar",
          "size": 9237,
          "sha512": "d09a0abadfe66d015fb76acca588ba38cc834b82f3222f65e2b51eaec83c8aa7c8fa27c9193d74131db573f8aaecece0118b14d01ad466f1642694bb782ccb5e",
          "sha256": "8890a73f796aa96d44e0476a2965f077488f13717472787c726a13ea499f95b6",
          "sha1": "82448f0b33409a245eb797a7e024c7926ccc993e",
          "md5": "80bb9c7b2373f43f4169e43f2004e189"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.2.0-alpha03.aar",
          "url": "datastore-preferences-rxjava2-1.2.0-alpha03.aar",
          "size": 17094,
          "sha512": "23f3c626228178d6e35ddb150d1a1b8d00ace9227b5215b5d457955fe1cdadd3a4ec25211036faaa76e81135af3bd1129e33487f35789b57afe0cbbd2a29efc4",
          "sha256": "5dd50d1b51f5c4234506a2d5d642c7bd19a89ee8d57f4c51030356492cc123ba",
          "sha1": "bc7494f6e648c6fd39578ede5903b790da3d5e4c",
          "md5": "7d1bbeacceccfe9f332cdf924895d6b9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.2.0-alpha03.aar",
          "url": "datastore-preferences-rxjava2-1.2.0-alpha03.aar",
          "size": 17094,
          "sha512": "23f3c626228178d6e35ddb150d1a1b8d00ace9227b5215b5d457955fe1cdadd3a4ec25211036faaa76e81135af3bd1129e33487f35789b57afe0cbbd2a29efc4",
          "sha256": "5dd50d1b51f5c4234506a2d5d642c7bd19a89ee8d57f4c51030356492cc123ba",
          "sha1": "bc7494f6e648c6fd39578ede5903b790da3d5e4c",
          "md5": "7d1bbeacceccfe9f332cdf924895d6b9"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-preferences-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-preferences-rxjava2-1.2.0-alpha03-versionMetadata.json",
          "url": "datastore-preferences-rxjava2-1.2.0-alpha03-versionMetadata.json",
          "size": 1400,
          "sha512": "a2f60bf4afa8dbfccc3567e35ca5878f63a8c7893e17d620e4b3b25cb43c52bcc2ea0b4cc4335eeabc474f26f8cf47ef08773ce3d5ccf54062edba8e0200769e",
          "sha256": "a305542cec217c23926eca87386e523d0b8160f39649f1bdef41cda57490aeae",
          "sha1": "43ad19b79d58d73a4c9f481b2d39e4e2177e1fdc",
          "md5": "f573598310b8501c653b472b9e6b448f"
        }
      ]
    }
  ]
}