version: "1.8.0-alpha04"
dependency_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-android"
    version: "1.8.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-jvmstubs"
    version: "1.8.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-linuxx64stubs"
    version: "1.8.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.8.0-alpha04"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.foundation"
group_id: "androidx.compose.foundation"
artifact_id: "foundation-layout"
path: "/compose/foundation/foundation-layout"
sha: "56f6328371e86b1303ce6c228a00c2351ae3b412"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.foundation-foundation-layout-all-12482706-1.8.0-alpha04.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation"
    version: "1.8.0-alpha04"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
kmp_children: "jvmStubs"
kmp_children: "linuxx64Stubs"
