version: "1.3.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.room"
    artifact_id: "room-compiler-processing"
    version: "2.6.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "13552626"
group_id: "androidx.hilt"
artifact_id: "hilt-compiler"
path: "/hilt/hilt-compiler"
sha: "de219c8c3eeeab06b16a4a2be76a7ceaa65b44b8"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.hilt-hilt-compiler-all-13552626-1.3.0-alpha01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: false
is_kmp: false
target: "androidx"
test_module_names: ":hilt:hilt-compiler:test"
