{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material-core",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha01.aar",
          "url": "compose-material-core-1.4.0-alpha01.aar",
          "size": 153304,
          "sha512": "b62781df4bcadaccd79b4043314fc58e856129e5c87aa9bb092a8841e7ac20311e90cb253de54a058095242446a9644e082326c1ef2c5ea43ac5be3d055c1dca",
          "sha256": "1ac45cf51ff64324f308a49b8123d440b4e2a236fa09e2ad9a1fcbf366a09053",
          "sha1": "db27cd0f18259f7af45ae398d3df89d3d9defbc8",
          "md5": "3ff86de4c66bf1d6080b5345be392cba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0-alpha02"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha01.aar",
          "url": "compose-material-core-1.4.0-alpha01.aar",
          "size": 153304,
          "sha512": "b62781df4bcadaccd79b4043314fc58e856129e5c87aa9bb092a8841e7ac20311e90cb253de54a058095242446a9644e082326c1ef2c5ea43ac5be3d055c1dca",
          "sha256": "1ac45cf51ff64324f308a49b8123d440b4e2a236fa09e2ad9a1fcbf366a09053",
          "sha1": "db27cd0f18259f7af45ae398d3df89d3d9defbc8",
          "md5": "3ff86de4c66bf1d6080b5345be392cba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha01-sources.jar",
          "url": "compose-material-core-1.4.0-alpha01-sources.jar",
          "size": 29657,
          "sha512": "23b9717e02bcda9a2ca162cd5dd37ca2800d9a1f69ab74a0f8e1a1b860681ba6e377998ab4c700a452f55ed5dba64be0e996fb30882751482dc5fe3ec0cde219",
          "sha256": "32fb37582c0a534c4455fe96708d917d352bd8cb0e6a68fab95a5c7a8e95a9d2",
          "sha1": "7e86a64a6b4b1a3824d8693675e659d988c31c43",
          "md5": "d432e4ab6f6426e6f2e669c68739b5cf"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.4.0-alpha01"
          },
          "reason": "compose-material-core is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-core-1.4.0-alpha01-versionMetadata.json",
          "url": "compose-material-core-1.4.0-alpha01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}