{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.5.0-alpha04",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha04"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha04-sources.jar",
          "url": "credentials-1.5.0-alpha04-sources.jar",
          "size": 225805,
          "sha512": "28046b703d3f841258415d11979b858349bf4a2a0cf21548edbc5f42454bdf2f3b2e67049cfe6b52b883cc253af8f5cea0e58e86280c390bcd8a6b99df73667b",
          "sha256": "e0a5fb3b09f9c63cd9f4a24f7e4bc0035494c7c86f56a07495f70c00e4b13d9a",
          "sha1": "e4b0ccc441c6666590a1aa822248838c6a38fb77",
          "md5": "ade7c64f5d53abf0c57b2f7c679fdbbb"
        },
        {
          "name": "credentials-1.5.0-alpha04-samples-sources.jar",
          "url": "credentials-1.5.0-alpha04-samples-sources.jar",
          "size": 7243,
          "sha512": "4802d83b3197e0faf36b8968e23723ad598d1954bdc5353bbe7193cd28f00fb0d41e98b28df9cae41584153608b7e52215c29dc8089d8785b2a4b83f34e4a003",
          "sha256": "fe1e7e44cf21e3cfd6858d14fba9da11aff6a3dc9d25b2bb634afb5a7dae73ae",
          "sha1": "1c39e28debbbbfaf621ec1643048b3ae9e7c745e",
          "md5": "44b66a46acc1d1332daf97f2211fe1a5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha04"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha04.aar",
          "url": "credentials-1.5.0-alpha04.aar",
          "size": 518905,
          "sha512": "4d0a2e4d1af70fdf65cc6d49abd0d0a912c348d35f65a5dd3a795aced7c973fbc6eb3eb160fa61cc9f0abdb71af59d476783fef82c6de761af150a7502eff0f9",
          "sha256": "050b3b6812b7ca884100f8b71e154ed7e0b39aad40f7cf4c51e94ebd4f4f13d9",
          "sha1": "7dced859e82e75a7dbe81f18c02c2fb79cfc2617",
          "md5": "ad3bb6d34bb095df9a4826f7e71785dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric-ktx",
          "version": {
            "requires": "1.4.0-alpha02"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha04"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha04.aar",
          "url": "credentials-1.5.0-alpha04.aar",
          "size": 518905,
          "sha512": "4d0a2e4d1af70fdf65cc6d49abd0d0a912c348d35f65a5dd3a795aced7c973fbc6eb3eb160fa61cc9f0abdb71af59d476783fef82c6de761af150a7502eff0f9",
          "sha256": "050b3b6812b7ca884100f8b71e154ed7e0b39aad40f7cf4c51e94ebd4f4f13d9",
          "sha1": "7dced859e82e75a7dbe81f18c02c2fb79cfc2617",
          "md5": "ad3bb6d34bb095df9a4826f7e71785dd"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.5.0-alpha04"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.5.0-alpha04-versionMetadata.json",
          "url": "credentials-1.5.0-alpha04-versionMetadata.json",
          "size": 63910,
          "sha512": "46c526e9ad2c52c64188f58650a1fbb5a3833d70e9085bd2adfd1327c9719eb8f2a9805a5789d10f1ce412531ac902c298bf26d3191446ec0b85ec70056e6f96",
          "sha256": "d36181349f791b0df0fefbff3832a3145eb9d218214591549b087705de817972",
          "sha1": "950f6c8e5b870cec0cfaa54655c94035ebe37025",
          "md5": "efc3e2fca3dac0679c74c50179bdc9b2"
        }
      ]
    }
  ]
}