{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.glance",
    "module": "glance",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13718522"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.2.0-alpha01-sources.jar",
          "url": "glance-1.2.0-alpha01-sources.jar",
          "size": 72470,
          "sha512": "f522b0f8576095c54da7eaefd744cb363b120dc6a84afe12185ac1b587bd096275f5e0a7edc0feb519e960c923069b3dd20ab40d81f0466fd018a89d41d0a0ba",
          "sha256": "290bcd2bdd193648d2e8b9eeb8a84ff7cc3bdda9038d8c50ad1b5ba0de2b4d2a",
          "sha1": "8ba62c70d5959e9afdf6717527944fafd3cbad8c",
          "md5": "1598df7ec1ccd4ce9e8b035228117900"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.2.0-alpha01.aar",
          "url": "glance-1.2.0-alpha01.aar",
          "size": 338384,
          "sha512": "5d0bffdb1e4098ac29290e9a4d68444936ef6f8193ebbe31c85be410067c59188c19f625ba1507ee9b3e652ad94d322af12fdd00af11735ea3f24e36067526a0",
          "sha256": "8d654c06470d17a1030d9a6b247a149380677e263f59cee1a0e31b2b72e62342",
          "sha1": "653751c5dc4c5354638db72381ec3c755776503e",
          "md5": "ebbdaf4abc48e219abf79a70993bf2e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.6.8"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "glance-1.2.0-alpha01.aar",
          "url": "glance-1.2.0-alpha01.aar",
          "size": 338384,
          "sha512": "5d0bffdb1e4098ac29290e9a4d68444936ef6f8193ebbe31c85be410067c59188c19f625ba1507ee9b3e652ad94d322af12fdd00af11735ea3f24e36067526a0",
          "sha256": "8d654c06470d17a1030d9a6b247a149380677e263f59cee1a0e31b2b72e62342",
          "sha1": "653751c5dc4c5354638db72381ec3c755776503e",
          "md5": "ebbdaf4abc48e219abf79a70993bf2e0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.glance",
          "module": "glance-appwidget",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-multiprocess",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-proto",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-appwidget-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-preview",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-material3",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        },
        {
          "group": "androidx.glance",
          "module": "glance-testing",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "glance is in atomic group androidx.glance"
        }
      ],
      "files": [
        {
          "name": "glance-1.2.0-alpha01-versionMetadata.json",
          "url": "glance-1.2.0-alpha01-versionMetadata.json",
          "size": 34086,
          "sha512": "7f4b11cbf632acb0a4048f7b3b7bf13a308e58ae36f1e94d896f8ef9ea2636c812b045986adb2bd723cbc0580c2d8702c4739258dd5799602c217234c33e7eff",
          "sha256": "a9d19ddad234464da899b27b4add22ad38bd4349c059bf441bd5c8c582d504fb",
          "sha1": "255e1731772e213c0693ce8ba86830d61811bb65",
          "md5": "09dc74dce5b27c02fda509919ee4918d"
        }
      ]
    }
  ]
}