version: "1.3.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "13522428"
group_id: "androidx.hilt"
artifact_id: "hilt-common"
path: "/hilt/hilt-common"
sha: "559c0fb65c0320ae66a99b815504409f0ca2fe1e"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.hilt-hilt-common-all-13522428-1.3.0-alpha01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":hilt:hilt-common:test"
