{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.5.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13389430"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha14-sources.jar",
          "url": "compose-material-1.5.0-alpha14-sources.jar",
          "size": 191239,
          "sha512": "b0d697d10fab305cef65cef132e78206af4b236b5207a9089d7f7ef69223695df9c670ca0666e0240beb9c25cdd2a120047f4d40c927ca401f97d64e2eaa21c2",
          "sha256": "dac8b19bacd6ad79b4c7e5416475836b09c1b75eafbeb23fc0b705a0945f15f3",
          "sha1": "28d45cfd894efce0f2f49a7eca36e6680abcf1c8",
          "md5": "fbb99cc72bafa311db1c1c73fbe65499"
        },
        {
          "name": "compose-material-1.5.0-alpha14-samples-sources.jar",
          "url": "compose-material-1.5.0-alpha14-samples-sources.jar",
          "size": 36693,
          "sha512": "382ada7e014a3ce2d4a1ef4502ea3d217873b856df19d1bf0354350b8f375b7f779a89bde32d81f4278877a4a95be372ad9f1e3997bfc816684faede73131a95",
          "sha256": "066db092481f4ae60e1357545c9a51ecdaaae158aafacb7284c024fa9f78b476",
          "sha1": "930ea24820b76eddafdd476383ceb602d8c7eed9",
          "md5": "f6228f59a430d637acf5285ff41d94e5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha14"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha14.aar",
          "url": "compose-material-1.5.0-alpha14.aar",
          "size": 1077512,
          "sha512": "3d3c79064e7ea2dec50a1a91a4c53ccc219ce66056b93cba7b061bcbe709c0b42af3a4de9cb85641d17744b17518370eb33c360164ad462372bed350da7c46ca",
          "sha256": "d3b3a6d4ea3ef7e53e3ac631184caf65bd5c86c6f18e1adca532031a3e92a74f",
          "sha1": "26e692852afa80c3fac870072156ca73fdd97cf0",
          "md5": "b249c135e92d47ef8003c6c30f17eb20"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.7"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.0-rc02"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha14"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha14"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha14.aar",
          "url": "compose-material-1.5.0-alpha14.aar",
          "size": 1077512,
          "sha512": "3d3c79064e7ea2dec50a1a91a4c53ccc219ce66056b93cba7b061bcbe709c0b42af3a4de9cb85641d17744b17518370eb33c360164ad462372bed350da7c46ca",
          "sha256": "d3b3a6d4ea3ef7e53e3ac631184caf65bd5c86c6f18e1adca532031a3e92a74f",
          "sha1": "26e692852afa80c3fac870072156ca73fdd97cf0",
          "md5": "b249c135e92d47ef8003c6c30f17eb20"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha14"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha14-versionMetadata.json",
          "url": "compose-material-1.5.0-alpha14-versionMetadata.json",
          "size": 86417,
          "sha512": "253490ed453740d2039bb97fc69be3f94c55183f9207ed667017343cacefab62cf4634dfb736016c6f1a76ebf827938a2e746a5b03bc612b4c8c28c6e76f4225",
          "sha256": "82de44019f952e1b77bc1d2416be82a699a6e275da55781c95d2665d7c3d855f",
          "sha1": "e02839962cec1c6900f92b0710e89cf3efff520c",
          "md5": "f74d247bb70e95430e2ed1614e4ca4a4"
        }
      ]
    }
  ]
}