{
  "formatVersion": "1.1",
  "component": {
    "url": "../../material3-window-size-class/1.4.0-alpha14/material3-window-size-class-1.4.0-alpha14.module",
    "group": "androidx.compose.material3",
    "module": "material3-window-size-class",
    "version": "1.4.0-alpha14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13433013"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class.aar",
          "url": "material3-window-size-class-android-1.4.0-alpha14.aar",
          "size": 21622,
          "sha512": "66bde1f6cf9e614859ab095cb84aa2c68e4ce8c056678df1769cc7e79f366c1f92a846cff4230cfa9afe697ce8d6a42f8ba78c02a5ec9f2fb64910615435ea86",
          "sha256": "286f988c71bc1e636b2a811ba4d1954368f6f56274cd774dcf271b56fef0604a",
          "sha1": "4d4678dfd3cb0017460e7c94b635f71ec66c721d",
          "md5": "a42a7fd2ecc16d58b640f071c9a78aec"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class.aar",
          "url": "material3-window-size-class-android-1.4.0-alpha14.aar",
          "size": 21622,
          "sha512": "66bde1f6cf9e614859ab095cb84aa2c68e4ce8c056678df1769cc7e79f366c1f92a846cff4230cfa9afe697ce8d6a42f8ba78c02a5ec9f2fb64910615435ea86",
          "sha256": "286f988c71bc1e636b2a811ba4d1954368f6f56274cd774dcf271b56fef0604a",
          "sha1": "4d4678dfd3cb0017460e7c94b635f71ec66c721d",
          "md5": "a42a7fd2ecc16d58b640f071c9a78aec"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-adaptive-navigation-suite",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-lint",
          "version": {
            "requires": "1.4.0-alpha14"
          },
          "reason": "material3-window-size-class is in atomic group androidx.compose.material3"
        }
      ],
      "files": [
        {
          "name": "material3-window-size-class-android-1.4.0-alpha14-sources.jar",
          "url": "material3-window-size-class-android-1.4.0-alpha14-sources.jar",
          "size": 12864,
          "sha512": "a9c21a7b1968ad179a95750c0ce7b96c82eceafaca6c10422d7189413e6b41ff9fddb8add3df2b1823c95086fbd1aaa072f3f0e0cf2bd44479d419a1577aaa14",
          "sha256": "67cc34ca6db9319e18be823161ff75acd112bec25ecea879ffafe0420134d98b",
          "sha1": "26ab6d9b1a356ad6db1b05d6efce1245afa8e172",
          "md5": "79f5cb1e99e9a189ac96ff3b2c142d55"
        },
        {
          "name": "material3-window-size-class-1.4.0-alpha14-samples-sources.jar",
          "url": "material3-window-size-class-android-1.4.0-alpha14-samples-sources.jar",
          "size": 6513,
          "sha512": "69547dd36fa8f2bcca298c97383d4b3f488404fd3579fbabec0d68f4af515d39d83ac8a2282874de93e2c1e0b7ab64e845b7e1d906b3c6f4b1d9047fdcdc1884",
          "sha256": "b319045da15bf9ed8003d4636702cf83fd322e1ee164955d28b2cffb3a591818",
          "sha1": "0eda4b3d6cc1b0383cc1379a157d7c19eb462c20",
          "md5": "aa6a2af64c7d4a06d0cea72d570dcd0c"
        }
      ]
    }
  ]
}