{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.ads",
    "module": "ads-adservices-java",
    "version": "1.1.0-beta09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta09"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta09-sources.jar",
          "url": "ads-adservices-java-1.1.0-beta09-sources.jar",
          "size": 22958,
          "sha512": "a2dcea977f56f468fee9192a9aba6b5dd0c6203c36c98bad5fd95dcd814d6981f7105442d069dc3bffda40ac243a0e4bb2849abb2c529ddcc45c5ca05020b9f2",
          "sha256": "124bfd1e7ddc4237992d1ffa26382472df43fbf4a5a9ac08052c78a5595ecea8",
          "sha1": "a8b4b4e83aec1a938401f49f98bb3631ea37499a",
          "md5": "2202a7f68fcddd6afe2d6635d6afa53d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta09"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta09.aar",
          "url": "ads-adservices-java-1.1.0-beta09.aar",
          "size": 70484,
          "sha512": "a78a2009dceb1623337a31b836781a8a5890f0b4a555a5c11c64c09670ed79e0b1b60638184e58a80233bce067c2ba1bccdca6671787f10ca55b90af88896350",
          "sha256": "eb19932a41a12ccc25b3633daab07389ca1dd35325e26f79986ab47d11185acd",
          "sha1": "ad156f6d51e09fc1550573c7bc832671a31f961a",
          "md5": "dc674d5677da54c87cbc9ea33131057c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta09"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta09"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta09.aar",
          "url": "ads-adservices-java-1.1.0-beta09.aar",
          "size": 70484,
          "sha512": "a78a2009dceb1623337a31b836781a8a5890f0b4a555a5c11c64c09670ed79e0b1b60638184e58a80233bce067c2ba1bccdca6671787f10ca55b90af88896350",
          "sha256": "eb19932a41a12ccc25b3633daab07389ca1dd35325e26f79986ab47d11185acd",
          "sha1": "ad156f6d51e09fc1550573c7bc832671a31f961a",
          "md5": "dc674d5677da54c87cbc9ea33131057c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.ads",
          "module": "ads-adservices",
          "version": {
            "requires": "1.1.0-beta09"
          },
          "reason": "ads-adservices-java is in atomic group androidx.privacysandbox.ads"
        }
      ],
      "files": [
        {
          "name": "ads-adservices-java-1.1.0-beta09-versionMetadata.json",
          "url": "ads-adservices-java-1.1.0-beta09-versionMetadata.json",
          "size": 5561,
          "sha512": "553d94aaa3fb145bdbcc7b66e49254d7b3926cc56186d57775392a714fd75c8e16dacc5e2a5cb7c5439d681b6a4862fca077649321f8c3bea4da137ee3f9c5e0",
          "sha256": "a0c449960bd3c34fc5311b04c0ca1dc73e42e084e6e678056ba04a7f8f0e769c",
          "sha1": "d273fcb90dd8650e9745d220423a691b64438085",
          "md5": "4e7541620bd2b7c271b1a2c72756d998"
        }
      ]
    }
  ]
}