version: "1.1.0-beta09"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.2.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.concurrent"
    artifact_id: "concurrent-futures"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.8.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices"
    version: "1.1.0-beta09"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.privacysandbox.ads"
group_id: "androidx.privacysandbox.ads"
artifact_id: "ads-adservices-java"
path: "/privacysandbox/ads/ads-adservices-java"
sha: "6c54b466d017f3de29d5aefada28c93e44db546d"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.ads-ads-adservices-java-all-12121212-1.1.0-beta09.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.ads"
    artifact_id: "ads-adservices"
    version: "1.1.0-beta09"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
