{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.3.0-alpha01.aar",
          "url": "tracing-1.3.0-alpha01.aar",
          "size": 6069,
          "sha512": "7f0d2aab31d53094af5f91b131b571550dca627ef4c9d0c9cdbe452ebb6323cecebccda67c39a4bb3ad1ad078df103d00c1f49fd62a2167ced148c37fbb521ba",
          "sha256": "3176519b02bc93525eef8b6a68f39c2d212d84cfc9db2ef049303c89f27c7483",
          "sha1": "1f92fe3f7bb4f838bfb4a1c6f8a8290c09d5a35a",
          "md5": "422ab7fe90a51b435e8cfe938d9c60f5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.3.0-alpha01.aar",
          "url": "tracing-1.3.0-alpha01.aar",
          "size": 6069,
          "sha512": "7f0d2aab31d53094af5f91b131b571550dca627ef4c9d0c9cdbe452ebb6323cecebccda67c39a4bb3ad1ad078df103d00c1f49fd62a2167ced148c37fbb521ba",
          "sha256": "3176519b02bc93525eef8b6a68f39c2d212d84cfc9db2ef049303c89f27c7483",
          "sha1": "1f92fe3f7bb4f838bfb4a1c6f8a8290c09d5a35a",
          "md5": "422ab7fe90a51b435e8cfe938d9c60f5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-ktx",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-1.3.0-alpha01-sources.jar",
          "url": "tracing-1.3.0-alpha01-sources.jar",
          "size": 6669,
          "sha512": "3636b4b1c41d48c446119695ec8790044e74d8798df26705810a469287a0e291b4fd9543e2811d5c244b754361ebcaa70f0537d666bdd6785222d5f6873dda47",
          "sha256": "3daf3a210e213f1675e6ea9ae2a9c0b9c837b42805835b65d999eca58fbddc90",
          "sha1": "7a8da514613e34b2f3cc6f1d9dc805295d9838a7",
          "md5": "b5ef389b90cc8492cd70bd525ace30b7"
        }
      ]
    }
  ]
}