{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.privacysandbox.sdkruntime",
    "module": "sdkruntime-core",
    "version": "1.0.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha09.aar",
          "url": "sdkruntime-core-1.0.0-alpha09.aar",
          "size": 52350,
          "sha512": "20287165f2a59e0e7b6498bad131ac0134416476243da6405c5336cde5ee2ace5c41774fe0f837f40581421560765d4decfbf8c049f2b8ad7df38093307a7018",
          "sha256": "05a196b339ed4495baed5ab3a8983550debac972986e2969f16a247259dc1718",
          "sha1": "b086fb9da3b28b4db1496cae64e1de781bad5607",
          "md5": "7600d7cec753c4342c096f1ed8a4c4fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.8.0-alpha06"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.12.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha09.aar",
          "url": "sdkruntime-core-1.0.0-alpha09.aar",
          "size": 52350,
          "sha512": "20287165f2a59e0e7b6498bad131ac0134416476243da6405c5336cde5ee2ace5c41774fe0f837f40581421560765d4decfbf8c049f2b8ad7df38093307a7018",
          "sha256": "05a196b339ed4495baed5ab3a8983550debac972986e2969f16a247259dc1718",
          "sha1": "b086fb9da3b28b4db1496cae64e1de781bad5607",
          "md5": "7600d7cec753c4342c096f1ed8a4c4fd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha09-sources.jar",
          "url": "sdkruntime-core-1.0.0-alpha09-sources.jar",
          "size": 24955,
          "sha512": "111f3a28200b37aabbf0906917b9932f75d62947587488404cccb5ae0e9dea229020b75f7a0a54d79e2758629f5e7c74b0344f6dd7a975c803e5246ec758ee7c",
          "sha256": "a56aee785d8daf83d09a6260a549e6030df58c30d1d8e2a26e26f001d68a6cad",
          "sha1": "56e0f5a8c52870b246c33526ca82e3da87faf6f7",
          "md5": "92bfe5fa61d2081239abf6fa25dfeb13"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-client",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        },
        {
          "group": "androidx.privacysandbox.sdkruntime",
          "module": "sdkruntime-provider",
          "version": {
            "requires": "1.0.0-alpha09"
          },
          "reason": "sdkruntime-core is in atomic group androidx.privacysandbox.sdkruntime"
        }
      ],
      "files": [
        {
          "name": "sdkruntime-core-1.0.0-alpha09-versionMetadata.json",
          "url": "sdkruntime-core-1.0.0-alpha09-versionMetadata.json",
          "size": 4599,
          "sha512": "7cde2622b3b74ac9b0f10bf15d551e2b1edb2f1ce93b9284e146e7ae3c78c591e1945ac393d3a1a00224105a5938c7f62e8c6c2110596987aaf5f72b480d162f",
          "sha256": "c2393adb73e385f7113e1c6ece78c25e7400deaeab5fcda5f810b97a0eff3ede",
          "sha1": "18760265ac4f04cf7bf701ea25ab380a134cf57a",
          "md5": "b2de847a93dc834ff740d242b9b65678"
        }
      ]
    }
  ]
}