version: "1.7.0-alpha09"
dependency_list {
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.13.0-alpha04"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.7.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing-manifest"
    version: "1.7.0-alpha09"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.fragment"
group_id: "androidx.fragment"
artifact_id: "fragment-testing"
path: "/fragment/fragment-testing"
sha: "3abba2d2e4a810f1cf9909ba77546cae2258919d"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-fragment-11334678.zip"
project_zip_path: "per-project-zips/androidx.fragment-fragment-testing-all-11334678-1.7.0-alpha09.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment"
    version: "1.7.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-compose"
    version: "1.7.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-ktx"
    version: "1.7.0-alpha09"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.fragment"
    artifact_id: "fragment-testing-manifest"
    version: "1.7.0-alpha09"
    is_tip_of_tree: true
  }
}
