version: "1.0.0-alpha13"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.3.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "13291458"
group_id: "androidx.privacysandbox.tools"
artifact_id: "tools"
path: "/privacysandbox/tools/tools"
sha: "f7310b9889c3082fc00034dbf282c09da8a6d1c5"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.privacysandbox.tools-tools-all-13291458-1.0.0-alpha13.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apicompiler"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apigenerator"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-apipackager"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.privacysandbox.tools"
    artifact_id: "tools-core-external-protobuf"
    version: "1.0.0-alpha13"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: ":privacysandbox:tools:tools:test"
