version: "1.7.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-android"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation-layout-desktop"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.foundation"
group_id: "androidx.compose.foundation"
artifact_id: "foundation-layout"
path: "/compose/foundation/foundation-layout"
sha: "50b8e540969e849ab920012a394051f7f5514d0d"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-foundation-11420469.zip"
project_zip_path: "per-project-zips/androidx.compose.foundation-foundation-layout-all-11420469-1.7.0-alpha02.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.foundation"
    artifact_id: "foundation"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
}
