{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material",
    "version": "1.5.0-alpha05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha05-sources.jar",
          "url": "compose-material-1.5.0-alpha05-sources.jar",
          "size": 183577,
          "sha512": "34e8369af509e56c3255638bafc2172d49843ebf951ff7c679a7bd15c76152402686f81e53055c5167340c989d8603a6311d4eb96d868a619df6b4938ade1db2",
          "sha256": "ac9e9787409ce5f2e45fb9d6dc1774bae8be7c18c9287fb0082abc37da287d9e",
          "sha1": "db8e6776bc48412500d8e64dab7ef627a8430dd6",
          "md5": "2bac5e2be51f37d5eae8661eb2e80c09"
        },
        {
          "name": "compose-material-1.5.0-alpha05-samples-sources.jar",
          "url": "compose-material-1.5.0-alpha05-samples-sources.jar",
          "size": 36724,
          "sha512": "ba5d8df79298d9dc20589e93e9be034533faf53ab64e1b9e90757ebe544e3c155d8f55c66ca7c235eb1dd7801c0b2e36dfb711d1146aef1cc035f0d0b144c6df",
          "sha256": "bc71700c8350e291e2d7f09bdff5327d1a569cb3d30e368ce3949c97935825d8",
          "sha1": "bf2c202837ff7dd9a57d5b456630f07c7565969f",
          "md5": "aeebf129c8414ff21ea5ce0025123c6a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha05.aar",
          "url": "compose-material-1.5.0-alpha05.aar",
          "size": 1273695,
          "sha512": "7a0618f53403944057337b49f1ea3764b1a43cd202241c307261f290f7cc614af9a665a45402f253d0c3c0d77d57c150d00ef9e7c14c9c81cfa103271a810f72",
          "sha256": "12a9b5fcc1a76feb54397f812a59277cc7e489faf0edcc4982788686be85fcf6",
          "sha1": "b293e7f6915c168b218315876327268c006ff848",
          "md5": "06f3090795ddfb67a130eb06af4f13dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha05"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha05.aar",
          "url": "compose-material-1.5.0-alpha05.aar",
          "size": 1273695,
          "sha512": "7a0618f53403944057337b49f1ea3764b1a43cd202241c307261f290f7cc614af9a665a45402f253d0c3c0d77d57c150d00ef9e7c14c9c81cfa103271a810f72",
          "sha256": "12a9b5fcc1a76feb54397f812a59277cc7e489faf0edcc4982788686be85fcf6",
          "sha1": "b293e7f6915c168b218315876327268c006ff848",
          "md5": "06f3090795ddfb67a130eb06af4f13dc"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-navigation",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-ui-tooling",
          "version": {
            "requires": "1.5.0-alpha05"
          },
          "reason": "compose-material is in atomic group androidx.wear.compose"
        }
      ],
      "files": [
        {
          "name": "compose-material-1.5.0-alpha05-versionMetadata.json",
          "url": "compose-material-1.5.0-alpha05-versionMetadata.json",
          "size": 81701,
          "sha512": "e5400c0229cc78906f7de42dd15c8adb0094a9c22e130804fed8e0490f97317aea4e32e731a95ae86b4eb5ac76c0f13ad834a7ecc0043e79cb86a48a8c24d8cc",
          "sha256": "be79609a5cd920a9149949c4e3d414e1e8f8b75fd0e596b6f4e2e78cdd223a65",
          "sha1": "be3cf87324dd75128c8a722612fadddbe5eb569c",
          "md5": "180a9fac21c17ef2d6cb7fa076e3c2fd"
        }
      ]
    }
  ]
}