{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.foundation",
    "module": "foundation",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.4.0-alpha01.aar",
          "url": "foundation-1.4.0-alpha01.aar",
          "size": 3085440,
          "sha512": "045b924b983a937aecad09b0ee694021037adc8b6cb850a0990b7e3b03255a2990795db82475511529867ee996df2c46e0f0090e37791df2e6fe813b4af2cd6b",
          "sha256": "9ef72e74c4b159b33b328914ca45e4e3fc3b5dfb7837160ec0f5b3880c50d02d",
          "sha1": "6d9c7a922ba06b4cb3d1e69339ccfc9eb9bfb07e",
          "md5": "2001509bd0ed82be7d0a8469e0d4fbd0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.3.0-rc01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "foundation-1.4.0-alpha01.aar",
          "url": "foundation-1.4.0-alpha01.aar",
          "size": 3085440,
          "sha512": "045b924b983a937aecad09b0ee694021037adc8b6cb850a0990b7e3b03255a2990795db82475511529867ee996df2c46e0f0090e37791df2e6fe813b4af2cd6b",
          "sha256": "9ef72e74c4b159b33b328914ca45e4e3fc3b5dfb7837160ec0f5b3880c50d02d",
          "sha1": "6d9c7a922ba06b4cb3d1e69339ccfc9eb9bfb07e",
          "md5": "2001509bd0ed82be7d0a8469e0d4fbd0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "foundation-1.4.0-alpha01-sources.jar",
          "url": "foundation-1.4.0-alpha01-sources.jar",
          "size": 423790,
          "sha512": "7e38f6d78379c3b74d6f71252e704dba0f515e2a57ce15c79371d2dbb5c479b2570d9e2f31e4fc75164a96e6f81cebe1555d2ec5bb5dd7f2748ea8f11703a2b1",
          "sha256": "90b664292f9710c1713385e41e346dc1f68adf9f4479305612e8f4c44195a718",
          "sha1": "c2c4df40c0b6d5dd48b7a6aeabeb361e8974170f",
          "md5": "64a5bf44da71c3bf4fdf4d4f6da60891"
        }
      ]
    }
  ]
}