{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.6.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13679201"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha03-sources.jar",
          "url": "credentials-1.6.0-alpha03-sources.jar",
          "size": 263747,
          "sha512": "0016c12074e1b7e86d1c2dcd3008b58e47ff143df5c166214f24bf2ab0ec63cf8db72ea9456f13ce93bbe111567a21c010f6d955ee809731b6409c7e4874eb40",
          "sha256": "242a0916a2a66626c8e6649c342abcff48cf737d30be1b813de23990b9a6dd5a",
          "sha1": "82645430e1457ec4dd7389bb977e77923733bd30",
          "md5": "5a023b81cdf35143a4e8f4a18cc46ec8"
        },
        {
          "name": "credentials-1.6.0-alpha03-samples-sources.jar",
          "url": "credentials-1.6.0-alpha03-samples-sources.jar",
          "size": 7239,
          "sha512": "1ee633d1013b2183cef418dffdb9500b3a44d99e3c99793423a362924671ee4de542342eee40de11f1a2df2b629127d11c52848cedb23b23d0c70a012e95f920",
          "sha256": "96cd83931877cd1a45ca054fb691d132a2bea0e396cdacdf8662c6f48a88b458",
          "sha1": "a0b5f12eb38243c4331f41ab2fede931b1d6e4ad",
          "md5": "5eb1bb8e4567872e48582c79164f4b22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha03.aar",
          "url": "credentials-1.6.0-alpha03.aar",
          "size": 626972,
          "sha512": "09a5d0349df5e168bb6ec6ff7d2c04f4fd86eb8a210153b17a8ce51c72ead9ce15f16d74db1337489e4db265be7a99e894a2bbb1fcb43f25bd14f1261eeceb0c",
          "sha256": "7ca9bf67dd17c5fbc7487bc6939d89d779d0a896a2ef298e7ae0cfe17d607969",
          "sha1": "23be9176204e6ee708c6113c97434e6f310fa74d",
          "md5": "2b47bd679024d7bc831a815a65a3a3b7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.20"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha03.aar",
          "url": "credentials-1.6.0-alpha03.aar",
          "size": 626972,
          "sha512": "09a5d0349df5e168bb6ec6ff7d2c04f4fd86eb8a210153b17a8ce51c72ead9ce15f16d74db1337489e4db265be7a99e894a2bbb1fcb43f25bd14f1261eeceb0c",
          "sha256": "7ca9bf67dd17c5fbc7487bc6939d89d779d0a896a2ef298e7ae0cfe17d607969",
          "sha1": "23be9176204e6ee708c6113c97434e6f310fa74d",
          "md5": "2b47bd679024d7bc831a815a65a3a3b7"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha03"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha03-versionMetadata.json",
          "url": "credentials-1.6.0-alpha03-versionMetadata.json",
          "size": 70734,
          "sha512": "3cf59fdc9d3372a35885abf84a93346b9ea6b295d1f732939fd22c6cefc950749bd7d5fc13ae7b470980cc21b9b4e028c19c4b70ac7efb4bc8de2a3ac23c86a6",
          "sha256": "51f4186604a43390aa57bdffed964c97cc1ea734275f40068d5bf18dbacc1aec",
          "sha1": "fded54a9b713c73d9a8ffe502e0da38adfeb733f",
          "md5": "10582b02ca6a30db7d8e7018965ef13c"
        }
      ]
    }
  ]
}