{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.car.app",
    "module": "app",
    "version": "1.8.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13621151"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha02-sources.jar",
          "url": "app-1.8.0-alpha02-sources.jar",
          "size": 474217,
          "sha512": "b285b466e724b5134a0a5d27f10a4bc778e93e938f1e6a94f8de37cd2376eb0b12c2767df126c0744c6b74d41c77830a5e553c8dae697681f6a26a265db5bf6a",
          "sha256": "c02fbb2d6de6eaf90619ec2683fb2c284aa1039cb1ebf42834864d172a0f2f22",
          "sha1": "999cc7af5242b7b1363f851f3acad49bc4d78642",
          "md5": "3a0147f4716501be02f736c09a325577"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha02.aar",
          "url": "app-1.8.0-alpha02.aar",
          "size": 639746,
          "sha512": "d6fefa2c1cacea830a4ade6b5757b4163fa512b8d3defa6ca09b34697dec20cfc2dcc4864b30a485a7bda97b61bb18492b0039885a2508c05464aef48874c7bf",
          "sha256": "90efdcdcc32be32e7ff9ede0c2c1561496a64935031534079bce3e08c43b6ded",
          "sha1": "50f39c6ad65edfea2ed7ba1c07ca6205ae78c5e3",
          "md5": "6aa2fdaf71dad54b9e293f57f4bf0c19"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha02.aar",
          "url": "app-1.8.0-alpha02.aar",
          "size": 639746,
          "sha512": "d6fefa2c1cacea830a4ade6b5757b4163fa512b8d3defa6ca09b34697dec20cfc2dcc4864b30a485a7bda97b61bb18492b0039885a2508c05464aef48874c7bf",
          "sha256": "90efdcdcc32be32e7ff9ede0c2c1561496a64935031534079bce3e08c43b6ded",
          "sha1": "50f39c6ad65edfea2ed7ba1c07ca6205ae78c5e3",
          "md5": "6aa2fdaf71dad54b9e293f57f4bf0c19"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.car.app",
          "module": "app-automotive",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-projected",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        },
        {
          "group": "androidx.car.app",
          "module": "app-testing",
          "version": {
            "requires": "1.8.0-alpha02"
          },
          "reason": "app is in atomic group androidx.car.app"
        }
      ],
      "files": [
        {
          "name": "app-1.8.0-alpha02-versionMetadata.json",
          "url": "app-1.8.0-alpha02-versionMetadata.json",
          "size": 127080,
          "sha512": "50630e32cc3b78958848d85ac0f6edf2123257b6f67461b0b26a1170efb46e11c3bce2a3fba5fa8ac7576422b8b0a420c146879135b66f3383bc19fde74809d7",
          "sha256": "43123109fa2dd3e5716fdc36e516464ad188afa9858e2379deddb554f900d872",
          "sha1": "43a2b9502769bae7884f804f44ccf997310e4e7b",
          "md5": "d76e14b5b88e3bf3f775b435331f3095"
        }
      ]
    }
  ]
}