{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.activity",
    "module": "activity-compose",
    "version": "1.10.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01-sources.jar",
          "url": "activity-compose-1.10.0-alpha01-sources.jar",
          "size": 10901,
          "sha512": "ad4e4c015ecb44fedade74af9f4cfe9cd09cc37ab549a09d21536083c151134a1a7eabf8d9565e2eee89205341f41b68a03dd75a274a8b254229334048a38aaf",
          "sha256": "88a0a4ffda99d707b83f71e75c6ba3c5eddfdd95457e2338564e4d3e164d3e21",
          "sha1": "63b8e57937918d0f49e5f5eb7d35e78fd5e7c25e",
          "md5": "85d42e1cc3c72ac04e4704bc29066cc9"
        },
        {
          "name": "activity-compose-1.10.0-alpha01-samples-sources.jar",
          "url": "activity-compose-1.10.0-alpha01-samples-sources.jar",
          "size": 3661,
          "sha512": "904e640aac5f92462f97083d2ecf8fafd57d41fe79a56cd17200290c770da45b8e68f93e2e47c14b6d7dd9e6c6768f87054cf16b7715144f8afdf0faf5265e14",
          "sha256": "eb6faec8713cd98e209e12aa8298aabc93df60ca81c9f5c3e4c89b6dbc8a4292",
          "sha1": "70d9d99b84f92f4760a59f9c7a63575f2c46c297",
          "md5": "ff77727e192cb5918e4f2116fb9b9755"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01.aar",
          "url": "activity-compose-1.10.0-alpha01.aar",
          "size": 1148473,
          "sha512": "3ec4b73b5aaaaaca032dd4dd9d93d1606922ed728dbe642ea89eea9f82c5b9bf6a1f97ffdedf689f2db61e95f8de72cd512d5c0020f2cadc1b4e072c958adb74",
          "sha256": "dcbf21a2ab299ab2240b1cde9bcbbc63e5c74b21cb725e96d043d1467620b9cd",
          "sha1": "7e3684e7a919209b09023e9bf3aed2ba8b2a288e",
          "md5": "df2937a27409b6873d0ce9a2467c37c2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-saveable",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01.aar",
          "url": "activity-compose-1.10.0-alpha01.aar",
          "size": 1148473,
          "sha512": "3ec4b73b5aaaaaca032dd4dd9d93d1606922ed728dbe642ea89eea9f82c5b9bf6a1f97ffdedf689f2db61e95f8de72cd512d5c0020f2cadc1b4e072c958adb74",
          "sha256": "dcbf21a2ab299ab2240b1cde9bcbbc63e5c74b21cb725e96d043d1467620b9cd",
          "sha1": "7e3684e7a919209b09023e9bf3aed2ba8b2a288e",
          "md5": "df2937a27409b6873d0ce9a2467c37c2"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.10.0-alpha01"
          },
          "reason": "activity-compose is in atomic group androidx.activity"
        }
      ],
      "files": [
        {
          "name": "activity-compose-1.10.0-alpha01-versionMetadata.json",
          "url": "activity-compose-1.10.0-alpha01-versionMetadata.json",
          "size": 2701,
          "sha512": "38e96fef550bc65a3cf2ef95fe4db98d47cef44c3db84ce19558c46543fce2b7f45b4dcad6c014993537706d3efd7d5d0b5b252b46c69d16a1e4b56fab8dee3f",
          "sha256": "edf2427da6f69559a4988536153f0826f46d319a7b2b80ef23c57fa83d23c7f3",
          "sha1": "3ce35c3833c670be76e757d0e68e8a9b4d0f6f15",
          "md5": "0866fd37c1abd4c3104bbf8b74e478d9"
        }
      ]
    }
  ]
}