{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13621151"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-1.2.0-alpha01-sources.jar",
          "url": "appsearch-1.2.0-alpha01-sources.jar",
          "size": 298523,
          "sha512": "13ed0a19f30634251e515d6c0a1162570921148b05abbdbc2328fe5d380abb3621a0c6144e560a4114ed1e01a0cd32d1920ba27e0602608e9c393e523044971a",
          "sha256": "e4bc13788e7ee5adc02c6d631e01591acca0ef93ef82942d87b6f6e2befe8461",
          "sha1": "853cc505b8812a2b43bcdaf7740e506aaa01709e",
          "md5": "8aafdda7259794aa6e831f292b81cad0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-1.2.0-alpha01.aar",
          "url": "appsearch-1.2.0-alpha01.aar",
          "size": 365624,
          "sha512": "b4b6925e68ecfec178e948329acbd8bcc77458e5495a4bd2fd6935a826b01a0c2edab263c127a1d4c7f8e452d40619c036d34809f6d9cf11cd0d7af94bd2c973",
          "sha256": "2482689051a1b3fa92f82993bdfa8e70f0f588576297f29f8d043376abe4ce05",
          "sha1": "713eb74e20ca585b64f182f1d86d7b5e67cd47f8",
          "md5": "2aa6a8efe27fb730c1b720d5efa9c798"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.auto.service",
          "module": "auto-service-annotations",
          "version": {
            "requires": "1.0-rc6"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "31.1-android"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-1.2.0-alpha01.aar",
          "url": "appsearch-1.2.0-alpha01.aar",
          "size": 365624,
          "sha512": "b4b6925e68ecfec178e948329acbd8bcc77458e5495a4bd2fd6935a826b01a0c2edab263c127a1d4c7f8e452d40619c036d34809f6d9cf11cd0d7af94bd2c973",
          "sha256": "2482689051a1b3fa92f82993bdfa8e70f0f588576297f29f8d043376abe4ce05",
          "sha1": "713eb74e20ca585b64f182f1d86d7b5e67cd47f8",
          "md5": "2aa6a8efe27fb730c1b720d5efa9c798"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-platform-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-1.2.0-alpha01-versionMetadata.json",
          "url": "appsearch-1.2.0-alpha01-versionMetadata.json",
          "size": 70021,
          "sha512": "4728e4206342ee13cd5c7561dbdcb0a7f67ef76f1e4c3880184983491fa4e8267fcb7b1bac2778ca25acedbecad417602a87afd6674f7380e2c6c083ffb132b3",
          "sha256": "faf75582d7fa5251abc9ff387da947c360c06217fde5571c4a1205ec63e27474",
          "sha1": "c5a9b8ba8196358535d989f01707622f226a75cb",
          "md5": "be12dfbae04f91b8cd294c1a76762fdb"
        }
      ]
    }
  ]
}