version: "1.5.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "13463947"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "357d9054e65f62780e2ddb373ac238d3b22f23f1"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-13463947-1.5.0-rc01.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "annotation-annotation-experimentalreleaseAndroidTest.xml"
test_module_names: ":annotation:annotation-experimental:testReleaseUnitTest"
