version: "1.5.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "13457307"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "6145f7b86ab4f341c688f916b8151d6c0c244ec0"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-13457307-1.5.0-rc01.zip"
kotlin_version: "2.1.20"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "annotation-annotation-experimentalreleaseAndroidTest.xml"
test_module_names: ":annotation:annotation-experimental:testReleaseUnitTest"
