version: "1.5.0-rc01"
dependency_list {
}
release_checklist {
}
build_id: "13522428"
group_id: "androidx.annotation"
artifact_id: "annotation-experimental"
path: "/annotation/annotation-experimental"
sha: "559c0fb65c0320ae66a99b815504409f0ca2fe1e"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-experimental-all-13522428-1.5.0-rc01.zip"
kotlin_version: "2.1.21"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "annotation-annotation-experimentalreleaseAndroidTest.xml"
test_module_names: ":annotation:annotation-experimental:testReleaseUnitTest"
