{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.viewpager2",
    "module": "viewpager2",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewpager2-1.2.0-alpha01.aar",
          "url": "viewpager2-1.2.0-alpha01.aar",
          "size": 67078,
          "sha512": "45c935f28ee3b9671d266d92b20ea7b8dfd7af310338f857d97adb9ef84595fa8d692c35db76fd9b548f8507813c0913a1c65d142bd9ff5338edec05f50d53ba",
          "sha256": "8ab449ef284cad9b0503d896a0c9e326892926534859d688f6ea88819c72f996",
          "sha1": "f1dfb15e955362f0b81cc189f1555c82aff1c1a9",
          "md5": "8e064d42cefb96f361117ef1296f142f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewpager2-1.2.0-alpha01.aar",
          "url": "viewpager2-1.2.0-alpha01.aar",
          "size": 67078,
          "sha512": "45c935f28ee3b9671d266d92b20ea7b8dfd7af310338f857d97adb9ef84595fa8d692c35db76fd9b548f8507813c0913a1c65d142bd9ff5338edec05f50d53ba",
          "sha256": "8ab449ef284cad9b0503d896a0c9e326892926534859d688f6ea88819c72f996",
          "sha1": "f1dfb15e955362f0b81cc189f1555c82aff1c1a9",
          "md5": "8e064d42cefb96f361117ef1296f142f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "viewpager2-1.2.0-alpha01-sources.jar",
          "url": "viewpager2-1.2.0-alpha01-sources.jar",
          "size": 41932,
          "sha512": "38fa71fec1f8e2aa954d2b735281a493f6a923768aeeac5da511b500ce062313018561fd225a596087d41851735527699fe8d685b3b236a704f31e14c2d49c99",
          "sha256": "b87b011e2d318dafbb3a6914a5065fe40c8f691c108da8231ab565e54d045b51",
          "sha1": "e52b1e626b077665eff78bc5326eebd0813559d2",
          "md5": "e2abf6057104dd8221426478d718780b"
        }
      ]
    }
  ]
}