version: "1.0.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.graphics"
    artifact_id: "graphics-shapes-android"
    version: "1.0.0-rc01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.graphics"
    artifact_id: "graphics-shapes-desktop"
    version: "1.0.0-rc01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.graphics"
group_id: "androidx.graphics"
artifact_id: "graphics-shapes"
path: "/graphics/graphics-shapes"
sha: "ce52455279aa9ebdc982f68d22113879ff17c9d2"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.graphics-graphics-shapes-all-12023614-1.0.0-rc01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: true
