version: "1.5.10"
dependency_list {
}
release_checklist {
}
build_id: "androidx.compose.compiler"
group_id: "androidx.compose.compiler"
artifact_id: "compiler"
path: "/compose/compiler/compiler"
sha: "251347cb268ddfa1d319156f5fe5d483dffe0dbb"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.compiler-compiler-all-11525184-1.5.10.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.compiler"
    artifact_id: "compiler-hosted"
    version: "1.5.10"
    is_tip_of_tree: true
  }
}
should_publish_docs: false
