{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.datastore",
    "module": "datastore-rxjava2",
    "version": "1.2.0-alpha03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13882970"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha03-sources.jar",
          "url": "datastore-rxjava2-1.2.0-alpha03-sources.jar",
          "size": 14165,
          "sha512": "92cc2c6290bb885e02227d04aa2be9db4a983c12d358e4ee0ea2eabe59a0fd9ebd7b8ff640ab432823c7e575ce7887b0b6e22c41d8e04f6fe5f64b8ebd936053",
          "sha256": "5fb94bda9ba28a50a2d704d0b4b0dd4231cdb2a0f8013fd48f79a0e8561b0d1a",
          "sha1": "8b8981466b1a49e7bcfd6d018aeda6e76be5cb59",
          "md5": "e72c5accc375707623aef2262eb47a9a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha03.aar",
          "url": "datastore-rxjava2-1.2.0-alpha03.aar",
          "size": 33481,
          "sha512": "426378ea31c43609cbe811c791b11013e42dc28cbc1f924c3789be87473c6ae226cb16cf459c6bc077f4976f651c0f062385971c92cb2da6c59f1374d7700d31",
          "sha256": "6a00c6de2fe3d6067dec9946ced30d62133d23670fc126d158a4757760c81f89",
          "sha1": "652b4cbc5655aec416d1463a42fb4cf973aac0ca",
          "md5": "52d837950c9e69112f48bc97f09accce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-rx2",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha03.aar",
          "url": "datastore-rxjava2-1.2.0-alpha03.aar",
          "size": 33481,
          "sha512": "426378ea31c43609cbe811c791b11013e42dc28cbc1f924c3789be87473c6ae226cb16cf459c6bc077f4976f651c0f062385971c92cb2da6c59f1374d7700d31",
          "sha256": "6a00c6de2fe3d6067dec9946ced30d62133d23670fc126d158a4757760c81f89",
          "sha1": "652b4cbc5655aec416d1463a42fb4cf973aac0ca",
          "md5": "52d837950c9e69112f48bc97f09accce"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-core-okio",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-guava",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-core",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-proto",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava2",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-rxjava3",
          "version": {
            "requires": "1.2.0-alpha03"
          },
          "reason": "datastore-rxjava2 is in atomic group androidx.datastore"
        }
      ],
      "files": [
        {
          "name": "datastore-rxjava2-1.2.0-alpha03-versionMetadata.json",
          "url": "datastore-rxjava2-1.2.0-alpha03-versionMetadata.json",
          "size": 2600,
          "sha512": "6638f7a40dd641154935a7eb8e61106963cf2693571601b65a6e0b4386bb00c6415ff09c0d39d23f82e43cbde13fbaac752ee965c03ea8e08dfb86d71b201d81",
          "sha256": "c2d80d8ef909bf4c0f584ae74db9af1bf99f429a3fe010b25f929cfad6ed896d",
          "sha1": "9e291ab6d9b04e9a70201be42edad57644193117",
          "md5": "f91170272f39dad17450e6da9465315e"
        }
      ]
    }
  ]
}