{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-ktx",
    "version": "2.7.0-alpha12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1",
      "buildId:": "12691003"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha12-sources.jar",
          "url": "room-ktx-2.7.0-alpha12-sources.jar",
          "size": 4366,
          "sha512": "c5c333da49731c2ce6073d50bcc132c46bc01682e80631704fc281598900eb726cb33a110354cdf40b01a90a2ef706093d4f4a345d381e3a40c5c3c37ec48fd7",
          "sha256": "8899d9cfe91cf4ba3bfb82dd7510447bc47f01cde9b63cee66429e85ff97ce8f",
          "sha1": "2318489c4bd45a5215cbf75ec592ef2aaf366b3b",
          "md5": "8afb2dd22f7867ad0feed63226a06340"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha12"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha12.aar",
          "url": "room-ktx-2.7.0-alpha12.aar",
          "size": 5892,
          "sha512": "8fdcb16d307a9457c988344870e805dc09f93112811d5a05ad7d44c5687ae2866500b759683b53d22b8d97ab20f4e6846211c7e8a1d5f3f086ff74f67b792237",
          "sha256": "251ec3926ddef7b2728a0300acd59f46354bd7bd98e48055dd2cb0faded40e51",
          "sha1": "6cc5b54532a40233b0fcf788e9c5ce4ba50b2b76",
          "md5": "bbbdac9e3714ec7152f56d36b2515907"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha12"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha12.aar",
          "url": "room-ktx-2.7.0-alpha12.aar",
          "size": 5892,
          "sha512": "8fdcb16d307a9457c988344870e805dc09f93112811d5a05ad7d44c5687ae2866500b759683b53d22b8d97ab20f4e6846211c7e8a1d5f3f086ff74f67b792237",
          "sha256": "251ec3926ddef7b2728a0300acd59f46354bd7bd98e48055dd2cb0faded40e51",
          "sha1": "6cc5b54532a40233b0fcf788e9c5ce4ba50b2b76",
          "md5": "bbbdac9e3714ec7152f56d36b2515907"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.room",
          "module": "room-common",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-compiler-processing-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-external-antlr",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-gradle-plugin",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-migration",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-guava",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-paging-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava2",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-rxjava3",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        },
        {
          "group": "androidx.room",
          "module": "room-testing",
          "version": {
            "requires": "2.7.0-alpha12"
          },
          "reason": "room-ktx is in atomic group androidx.room"
        }
      ],
      "files": [
        {
          "name": "room-ktx-2.7.0-alpha12-versionMetadata.json",
          "url": "room-ktx-2.7.0-alpha12-versionMetadata.json",
          "size": 814,
          "sha512": "1c94a33cd9b1fbf050412e6cb6ea9da9a8502b88a79f92a5c3e34a48abab58b8b2cb7629609339e4f6507d21f82adcc68e78db6069c605f931f9d289b2e38405",
          "sha256": "354f00f9f639395f1b3b7b67f1b347930877a53d5478ee774a0fe2d0bff0e4a5",
          "sha1": "f30bf3b8e6bbd1c7e2f14f55088451a93592b71b",
          "md5": "6c27c68f0c9e5a610e3f76c99bb34c56"
        }
      ]
    }
  ]
}