{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.protolayout",
    "module": "protolayout-expression-pipeline",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha01-sources.jar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha01-sources.jar",
          "size": 74866,
          "sha512": "432f9aec8dff8c93ba211ac409f8fe73b440ddf13ef314c05351341ce393631d4860c409268798e2003508fb13c0236dcd2c5953b581c51824153370c03f192f",
          "sha256": "56569dbc347f640424f9ddf750bf92fd8b58e3efc5c7bd10055b42f2882a444a",
          "sha1": "fdd11a0c6cb19f5f608df7e7129fcca00ea32517",
          "md5": "9a7d57870b69eebbeea257a8904183dd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha01.aar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha01.aar",
          "size": 152663,
          "sha512": "5023404ff73e021e09ed4d51d2c7dc99877e88c00db7bb2a27a9464b2daf3108215244d034fb1daeeeea779003c4f87c6a124e2ab4034002a5ad908c01301c22",
          "sha256": "397f8ba27b838db81ceb73f766282538dab7ad86da6b02b5678f159ead8fc5ab",
          "sha1": "0aaa613b80ed9a76fde8edf11631a2a601fe6df0",
          "md5": "061866a6eb9274ec99d816764dd7b677"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha01.aar",
          "url": "protolayout-expression-pipeline-1.3.0-alpha01.aar",
          "size": 152663,
          "sha512": "5023404ff73e021e09ed4d51d2c7dc99877e88c00db7bb2a27a9464b2daf3108215244d034fb1daeeeea779003c4f87c6a124e2ab4034002a5ad908c01301c22",
          "sha256": "397f8ba27b838db81ceb73f766282538dab7ad86da6b02b5678f159ead8fc5ab",
          "sha1": "0aaa613b80ed9a76fde8edf11631a2a601fe6df0",
          "md5": "061866a6eb9274ec99d816764dd7b677"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-expression",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-external-protobuf",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-material-core",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-proto",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        },
        {
          "group": "androidx.wear.protolayout",
          "module": "protolayout-renderer",
          "version": {
            "requires": "1.3.0-alpha01"
          },
          "reason": "protolayout-expression-pipeline is in atomic group androidx.wear.protolayout"
        }
      ],
      "files": [
        {
          "name": "protolayout-expression-pipeline-1.3.0-alpha01-versionMetadata.json",
          "url": "protolayout-expression-pipeline-1.3.0-alpha01-versionMetadata.json",
          "size": 5880,
          "sha512": "df667da0f4f4a20ef6b0e37c5b451e643df20db9758e9367d48c97860240391032d861a79d2e04b66fe74d0fb434c4685b497e88ed4a1eaf594f392076ea88f3",
          "sha256": "cf451ddbde3d3cfc6be15431fba32dcbe514791fe8f6bdb79e6d35b65eb870d5",
          "sha1": "994f9f70fb804c19386d7fc7724e0cf1a70e9886",
          "md5": "796c75c8c38591dae19cd077d6067b5a"
        }
      ]
    }
  ]
}