{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.watchface",
    "module": "watchface-editor",
    "version": "1.3.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-1.3.0-alpha02.aar",
          "url": "watchface-editor-1.3.0-alpha02.aar",
          "size": 89824,
          "sha512": "57114985ae01d52fee51b1ec26cd6fd404fe4018643699f2650520798c6d7df61038368e7616890506ddb3cbc35399a6d41ece56d2ce686faf7cbe8ba4333c58",
          "sha256": "ee0e03169bd8b9d9950d91fbcd8a40e60888221ef193bc1e6bff9a44ca70cef4",
          "sha1": "c9432ed8a725c751bbda2409e52075b55bbc6c9d",
          "md5": "1f7add306867e724a5e3815d66698f2c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-1.3.0-alpha02.aar",
          "url": "watchface-editor-1.3.0-alpha02.aar",
          "size": 89824,
          "sha512": "57114985ae01d52fee51b1ec26cd6fd404fe4018643699f2650520798c6d7df61038368e7616890506ddb3cbc35399a6d41ece56d2ce686faf7cbe8ba4333c58",
          "sha256": "ee0e03169bd8b9d9950d91fbcd8a40e60888221ef193bc1e6bff9a44ca70cef4",
          "sha1": "c9432ed8a725c751bbda2409e52075b55bbc6c9d",
          "md5": "1f7add306867e724a5e3815d66698f2c"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.wear.watchface",
          "module": "watchface",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-data-source-ktx",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-complications-rendering",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-client-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-data",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-editor-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-guava",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        },
        {
          "group": "androidx.wear.watchface",
          "module": "watchface-style",
          "version": {
            "requires": "1.3.0-alpha02"
          },
          "reason": "watchface-editor is in atomic group androidx.wear.watchface"
        }
      ],
      "files": [
        {
          "name": "watchface-editor-1.3.0-alpha02-versionMetadata.json",
          "url": "watchface-editor-1.3.0-alpha02-versionMetadata.json",
          "size": 4811,
          "sha512": "9d121e4a92cb050f9881fcdc9f0020bba6f4c43b15f5c4e9df193f76a39af40a4cf1639da8fb6e2b0880951a2b0227f3e4854feb59fe58407e31981cb38bc3e6",
          "sha256": "d69f91cebfc2dbea7c39b5157eb67f3c22c2b8142c053807ec77131ad66bd8ec",
          "sha1": "94d191b0458ea0f41da64df615f913b917b1f6ff",
          "md5": "e07bc1567c7e549be322e167090d3e71"
        }
      ]
    }
  ]
}