{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.6.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.6.0-alpha01-sources.jar",
          "url": "window-1.6.0-alpha01-sources.jar",
          "size": 212320,
          "sha512": "704527b252ca9cf3b20226acc1abb516b85f990d083126ccb40cb09f722f543666cedb88c3fd63fd09b5de539d61ae3f005216cc3a09054224614546bcf5f13d",
          "sha256": "4a2e47f22d4ed075174ba06cea102186b3a0ed90da7f85a7dc373de08a0a0457",
          "sha1": "bb5385fb34485ae05590ec4ceec25ea1e06349c4",
          "md5": "b0a2ebe179231908ab38f0337abee6d5"
        },
        {
          "name": "window-1.6.0-alpha01-samples-sources.jar",
          "url": "window-1.6.0-alpha01-samples-sources.jar",
          "size": 11042,
          "sha512": "e20b7c4a6508402931ec691938773d00df7b3e372b05c5b8e60932afe27765fd1522e0f4464dfe135002cf22c86c0b95259b4e976f85f07db40ef5e804340724",
          "sha256": "d74f224365c2c36b6d927cb925c72a68b384387ae48778fc70b5f47611113195",
          "sha1": "11627cb0af8769741cc05bb52c7d00f46155ef32",
          "md5": "4cf461f98ab5180edb757d941c815361"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.6.0-alpha01.aar",
          "url": "window-1.6.0-alpha01.aar",
          "size": 591716,
          "sha512": "165cf4f92c0f6179b4db836630e52bb16dbdafdaabe4d7808d112598d10eb3c383619dd4a8765f8439922a6945f71d22d11260601733de9333a75204bb148b85",
          "sha256": "4b742fb0831c330542c5a19d6869cec5154026180582e906b5063f689e78365f",
          "sha1": "0f12e37ee717e6fb097ccf1f4145a167a489e149",
          "md5": "851c3b9832182e276a326e47ddb7294b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.6.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.6.0-alpha01.aar",
          "url": "window-1.6.0-alpha01.aar",
          "size": 591716,
          "sha512": "165cf4f92c0f6179b4db836630e52bb16dbdafdaabe4d7808d112598d10eb3c383619dd4a8765f8439922a6945f71d22d11260601733de9333a75204bb148b85",
          "sha256": "4b742fb0831c330542c5a19d6869cec5154026180582e906b5063f689e78365f",
          "sha1": "0f12e37ee717e6fb097ccf1f4145a167a489e149",
          "md5": "851c3b9832182e276a326e47ddb7294b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.window",
          "module": "window-java",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-core",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava2",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-rxjava3",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        },
        {
          "group": "androidx.window",
          "module": "window-testing",
          "version": {
            "requires": "1.6.0-alpha01"
          },
          "reason": "window is in atomic group androidx.window"
        }
      ],
      "files": [
        {
          "name": "window-1.6.0-alpha01-versionMetadata.json",
          "url": "window-1.6.0-alpha01-versionMetadata.json",
          "size": 32805,
          "sha512": "5d9cf0f20c445b331d6d01d20247c59b5980e1f431c2b705c10100fec5b961cd9a190632835a16ce9cb70f86377aef25d5156a12183bdaba350807e05f032968",
          "sha256": "1ace070f549d634f3b47829dfb9840e54ac44fc64e1363f0cddb98821a71f07b",
          "sha1": "ffebb9f5c16f94bc7cb9bd95eb6104ae28871876",
          "md5": "7128546b78d9af36fca01f193e1b70c5"
        }
      ]
    }
  ]
}