{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.14.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01-sources.jar",
          "url": "core-ktx-1.14.0-alpha01-sources.jar",
          "size": 74126,
          "sha512": "42f6e3a6b511952221422162cbb12e32c2721e351de35207fa314e393b2798654600a05d73214b14e169432558fc7c6c2074c12e5161b3b642ae87d6ec0eec4b",
          "sha256": "0983bac2e1f34962cca84522748e4329be4a26c9880d8916fbf0ffee06a67e42",
          "sha1": "e5d4514f26f7589ef3b5ba8469f252484b368a89",
          "md5": "289af9ade3cdf17162d996fc7a2686f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01.aar",
          "url": "core-ktx-1.14.0-alpha01.aar",
          "size": 174911,
          "sha512": "7d584a9de63e6d34e2282e550538a255ec7131dded5a594dc97129e7dd35aa023bb81d3d8e4e94c20c49f3701ecdda010860a371dc9df5f23039b2336e66d5dd",
          "sha256": "ec6b9f03c8099fd46ab6d388a0c0d4cdfba72044031f0197533003479ab84bc2",
          "sha1": "28dc02fc58347ba818a981a36aea71187150c65f",
          "md5": "4b074924a6f0d7230e373ff89b88272b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.14.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01.aar",
          "url": "core-ktx-1.14.0-alpha01.aar",
          "size": 174911,
          "sha512": "7d584a9de63e6d34e2282e550538a255ec7131dded5a594dc97129e7dd35aa023bb81d3d8e4e94c20c49f3701ecdda010860a371dc9df5f23039b2336e66d5dd",
          "sha256": "ec6b9f03c8099fd46ab6d388a0c0d4cdfba72044031f0197533003479ab84bc2",
          "sha1": "28dc02fc58347ba818a981a36aea71187150c65f",
          "md5": "4b074924a6f0d7230e373ff89b88272b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-ktx-1.14.0-alpha01-versionMetadata.json",
          "url": "core-ktx-1.14.0-alpha01-versionMetadata.json",
          "size": 42717,
          "sha512": "d94e7af20884072ba66f3e89dbd1b4e1823156d64bae821674229d47b5a48aa8d552ab42628b5a4d51286814390f8bf4a848006c3653a783e1d324ac6e643eea",
          "sha256": "261dcd3c8616cae91271d5163997c45b8b509af204786420649a0b7e0f245281",
          "sha1": "9ccd1b46b95778109472c0a16ddd08e4bef021f0",
          "md5": "e320a403a93dad70e1c5d328f07a9e93"
        }
      ]
    }
  ]
}