version: "1.0.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "androidx.core"
group_id: "androidx.core"
artifact_id: "core-viewtree"
path: "/core/core-viewtree"
sha: "9b5edca8440f3f8ff25d47418d53380e1799d0d0"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-viewtree-all-12787570-1.0.0-alpha01.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
