version: "1.0.0-alpha01"
dependency_list {
}
release_checklist {
}
build_id: "12958663"
group_id: "androidx.core"
artifact_id: "core-viewtree"
path: "/core/core-viewtree"
sha: "7b9c01964c34698a8fdf83210a5ffd2765512f1a"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-viewtree-all-12958663-1.0.0-alpha01.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-viewtreereleaseAndroidTest.xml"
test_module_names: ":core:core-viewtree:testReleaseUnitTest"
