{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-ktx",
    "version": "1.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.4",
      "buildId:": "6495117"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.4.0-alpha01.aar",
          "url": "core-ktx-1.4.0-alpha01.aar",
          "size": 164709,
          "sha512": "5d493c5304f98af65e4069d2ae24e1b031cf81c3f2cd69041b525c206a25109b49d59b474a3adc9e6653c1016a45c63d196c4696753d26542c235974695580b8",
          "sha256": "ee64cbe5388167710f3cf36f44c36147982586353ab2fad371a664b6590577c4",
          "sha1": "1b0947835615cb3fd3a590b2d95d2f794972bc43",
          "md5": "bc59597219cc0380e8622eb24d7b27cb"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.71"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "core-ktx-1.4.0-alpha01.aar",
          "url": "core-ktx-1.4.0-alpha01.aar",
          "size": 164709,
          "sha512": "5d493c5304f98af65e4069d2ae24e1b031cf81c3f2cd69041b525c206a25109b49d59b474a3adc9e6653c1016a45c63d196c4696753d26542c235974695580b8",
          "sha256": "ee64cbe5388167710f3cf36f44c36147982586353ab2fad371a664b6590577c4",
          "sha1": "1b0947835615cb3fd3a590b2d95d2f794972bc43",
          "md5": "bc59597219cc0380e8622eb24d7b27cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-ktx-1.4.0-alpha01-sources.jar",
          "url": "core-ktx-1.4.0-alpha01-sources.jar",
          "size": 61361,
          "sha512": "fb58ba49df4537ba6cf403502babaa93a29264c6f3523da8ba1bac3e8d8f4c35ffa38c2c42a93a5c5794ef10b35996db3bfd1474b651d07498424f49777cb1dc",
          "sha256": "f594a4186e444e3bbb5bd1782e21b41500b31a5e6c940f49bffaa47166a46144",
          "sha1": "25db0896630c2c51f25cb54dd4f74264fe48336f",
          "md5": "479bdf857b5a82b2f7b79b50cf7c3212"
        }
      ]
    }
  ]
}
