version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.2.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.exifinterface"
group_id: "androidx.exifinterface"
artifact_id: "exifinterface"
path: "/exifinterface/exifinterface"
sha: "edd19514b50734044a2a42cd9be3930fdf188b0f"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.exifinterface-exifinterface-all-12133442-1.4.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
