{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.hilt",
    "module": "hilt-navigation-compose",
    "version": "1.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13842168"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.3.0-beta01-sources.jar",
          "url": "hilt-navigation-compose-1.3.0-beta01-sources.jar",
          "size": 6266,
          "sha512": "9ed7b4422c658d0f7978eeeab21ee9e8da6b34dfbbad833bb90dfa6965fc32564cf53fafd44337251abea0058631eb5b493cdd5c73e36f91b6fd5c227f098027",
          "sha256": "dc31f429b3be0508aae0493770ffb216ad99c9506f457d5904ce110793757403",
          "sha1": "7e5b888341f66ab6db9fc46df6e91a54c5f5bcd9",
          "md5": "7ff697ae81e9a133dd9b70f65c528bf7"
        },
        {
          "name": "hilt-navigation-compose-1.3.0-beta01-samples-sources.jar",
          "url": "hilt-navigation-compose-1.3.0-beta01-samples-sources.jar",
          "size": 6129,
          "sha512": "04cfda5edfb46efa8085e46a4df0eef0dcb689f877bb5be310645f5afa30f5bdaf864870965d9e8779cd48ac39eba5f33f4494ba3da981eb617690f923c69047",
          "sha256": "095f4f3e2101483c5cb195df180cdf1909bd029d814e9cb053034f3e9c951538",
          "sha1": "0fef43778446f39962a23eda145f8b249c51e14e",
          "md5": "5bcd2482124ab846f73b7102dcf89616"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.3.0-beta01.aar",
          "url": "hilt-navigation-compose-1.3.0-beta01.aar",
          "size": 9996,
          "sha512": "69cd692951934171d59d44d7e3a222cd9f906f544eb0377d8fdc11034ee0e5ee0a24424a099cff033588486faf2bd91f7904ed860ba17d876dfda06236f8f7af",
          "sha256": "26f889118796abf4ac84beec1c1902b5f88f7b664752a39f1fa139f3fdf3ddcc",
          "sha1": "ee5707ef1244aa53eb45de6f55dc03d0a0a8788c",
          "md5": "f264476575ea0470c8a3665a8fec5e08"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "androidx.hilt",
          "module": "hilt-lifecycle-viewmodel-compose",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "hilt-navigation-compose-1.3.0-beta01.aar",
          "url": "hilt-navigation-compose-1.3.0-beta01.aar",
          "size": 9996,
          "sha512": "69cd692951934171d59d44d7e3a222cd9f906f544eb0377d8fdc11034ee0e5ee0a24424a099cff033588486faf2bd91f7904ed860ba17d876dfda06236f8f7af",
          "sha256": "26f889118796abf4ac84beec1c1902b5f88f7b664752a39f1fa139f3fdf3ddcc",
          "sha1": "ee5707ef1244aa53eb45de6f55dc03d0a0a8788c",
          "md5": "f264476575ea0470c8a3665a8fec5e08"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "hilt-navigation-compose-1.3.0-beta01-versionMetadata.json",
          "url": "hilt-navigation-compose-1.3.0-beta01-versionMetadata.json",
          "size": 880,
          "sha512": "2e247f1c65df40128a4c4d9c46e47ceeff40c75a903f3cb7f86ca4e3f732136ed71b1dcb295e7cd71b439a485c6448dd990734d3d28425a41eca2764ffdaa2f0",
          "sha256": "a2a6622b51b8a7902268b4fd9a1c6d6aebb5cf0cf3b321c417192193cd6ec216",
          "sha1": "248c4a828b5c7c7ade345c46af4431934d133146",
          "md5": "87658a70ee85bd60a333fae2f791d6df"
        }
      ]
    }
  ]
}