{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-runtime-ktx",
    "version": "2.11.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13552626"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.11.0-alpha01-sources.jar",
          "url": "work-runtime-ktx-2.11.0-alpha01-sources.jar",
          "size": 4398,
          "sha512": "eaaa9f9f26a7c979c48aa131e1a39b091f73c3d63b4ec209f4cf8c848bd4c22354e8c2cdba41e68e72c69793624ba72f60f8e7a705ef2213ec7683217b5b8f28",
          "sha256": "4a5f293a931444d1cb766fb365bfcc2c286cd8ae43fdedad0cdfa2a69362ed15",
          "sha1": "66ac1feafafc2d29b82f59287681b0f806a662b7",
          "md5": "0bcab478160980290b15a4759d9b600c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.11.0-alpha01.aar",
          "url": "work-runtime-ktx-2.11.0-alpha01.aar",
          "size": 6110,
          "sha512": "8a3ecf84b058468acbd42b06bd99f99609f2976b81a92c4c001803decddc97191cf1edd1d9eb9f85adf636d19ab71163ce52929281763adebb0a1abfbbf24693",
          "sha256": "c9f170b36cd25bb0bd8201aadc433dfeb54f70950f15c5bbb73c11e908c95951",
          "sha1": "72edb45af3899777dacd0bfe7c723fa6271ae2b3",
          "md5": "914b1819966c3ebd8c6eb71349f571a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.11.0-alpha01.aar",
          "url": "work-runtime-ktx-2.11.0-alpha01.aar",
          "size": 6110,
          "sha512": "8a3ecf84b058468acbd42b06bd99f99609f2976b81a92c4c001803decddc97191cf1edd1d9eb9f85adf636d19ab71163ce52929281763adebb0a1abfbbf24693",
          "sha256": "c9f170b36cd25bb0bd8201aadc433dfeb54f70950f15c5bbb73c11e908c95951",
          "sha1": "72edb45af3899777dacd0bfe7c723fa6271ae2b3",
          "md5": "914b1819966c3ebd8c6eb71349f571a0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.work",
          "module": "work-gcm",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-multiprocess",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-runtime",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava2",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-rxjava3",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        },
        {
          "group": "androidx.work",
          "module": "work-testing",
          "version": {
            "requires": "2.11.0-alpha01"
          },
          "reason": "work-runtime-ktx is in atomic group androidx.work"
        }
      ],
      "files": [
        {
          "name": "work-runtime-ktx-2.11.0-alpha01-versionMetadata.json",
          "url": "work-runtime-ktx-2.11.0-alpha01-versionMetadata.json",
          "size": 3007,
          "sha512": "f51a4cdd45cd0c2f6785929ca3a9c0e974326f24b887e2679b037387053c43d25c40ae443e4266a8d2dcea343656b079a826d7ab0265e4a656e7d5ec528f477e",
          "sha256": "4c2d110c235bea2bdac1bcd3ab0f64571a98df7ec47f46c2ea5839fd5234f68a",
          "sha1": "437305f19ab1ce143709e68655edcd4dad040fea",
          "md5": "ab4748cfa6fb9d54ef83452abdd4248a"
        }
      ]
    }
  ]
}