version: "1.2.0-beta01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.appcompat"
    artifact_id: "appcompat"
    version: "1.0.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection"
    version: "1.4.2"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.leanback"
    artifact_id: "leanback"
    version: "1.2.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.preference"
    artifact_id: "preference"
    version: "1.1.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.recyclerview"
    artifact_id: "recyclerview"
    version: "1.3.2"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.leanback"
group_id: "androidx.leanback"
artifact_id: "leanback-preference"
path: "/leanback/leanback-preference"
sha: "38265f9164ad74444462fd5e1df31c9799a08d0d"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.leanback-leanback-preference-all-12193771-1.2.0-beta01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
