{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.leanback",
    "module": "leanback-preference",
    "version": "1.2.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "leanback-preference-1.2.0-beta01-sources.jar",
          "url": "leanback-preference-1.2.0-beta01-sources.jar",
          "size": 29936,
          "sha512": "706e15097b97b5d392e6311cddac226721e42d0b789d799d7a5be206eaa4f5734633267f8a7dd2d6a723ece97717fa83fd8f628c13ab8065687b73056e99d247",
          "sha256": "24cfaad2d678002a0ff1c4991752c3361ca41559035b1ee3f429b377ef8b659a",
          "sha1": "b7459eec11f9ca80c7b6cef13889b53408fbbe2b",
          "md5": "03453c382c133a249385d2a9c1c863c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "leanback-preference-1.2.0-beta01.aar",
          "url": "leanback-preference-1.2.0-beta01.aar",
          "size": 67912,
          "sha512": "6dff4fc1a0347edf4047e466e335855d6a1d024d9032ffd2a94f7c8a18ae9eb313971ec2f9f5f1846d8918d4032d58c9e0ca04271980b510d7c04b9befd639d5",
          "sha256": "d303ade540c920f5b42cfde7fb84d02e6794dffc9c88ed8151924a32c0c2c197",
          "sha1": "087d3fd44857a15b24b3504f99d0bbef31a17834",
          "md5": "2466092df22b10a8864cb0d8a4b88d4b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.leanback",
          "module": "leanback",
          "version": {
            "requires": "1.2.0-beta01"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "leanback-preference-1.2.0-beta01.aar",
          "url": "leanback-preference-1.2.0-beta01.aar",
          "size": 67912,
          "sha512": "6dff4fc1a0347edf4047e466e335855d6a1d024d9032ffd2a94f7c8a18ae9eb313971ec2f9f5f1846d8918d4032d58c9e0ca04271980b510d7c04b9befd639d5",
          "sha256": "d303ade540c920f5b42cfde7fb84d02e6794dffc9c88ed8151924a32c0c2c197",
          "sha1": "087d3fd44857a15b24b3504f99d0bbef31a17834",
          "md5": "2466092df22b10a8864cb0d8a4b88d4b"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "leanback-preference-1.2.0-beta01-versionMetadata.json",
          "url": "leanback-preference-1.2.0-beta01-versionMetadata.json",
          "size": 7656,
          "sha512": "f0f8edea1cb1ce5acb42b3baaa92d3d35562d56d7ea58119b1989d1c03d6b1d86db4bafa335a9d629a3de98503d82214f11a0ecbec3be3e7eeb35f2742fd386d",
          "sha256": "c24e8b5b5a6f0bf088aa274e7545694fdb72355307121721c39d8a2e56d3cfbd",
          "sha1": "f21709cfa6aa6b11dbf66eb59ed0cea393c9e788",
          "md5": "6b2a075d279823bd0969a9341f7b86fc"
        }
      ]
    }
  ]
}