version: "1.8.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativearm32"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativearm64"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativex64"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-androidnativex86"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-jvm"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation-linuxx64"
    version: "1.8.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.annotation"
group_id: "androidx.annotation"
artifact_id: "annotation"
path: "/annotation/annotation"
sha: "bea3f6a46a9e383fcb8977cd8cdf95289d766806"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.annotation-annotation-all-11558776-1.8.0-alpha02.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
}
should_publish_docs: true
