version: "1.4.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3-window-size-class-android"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3-window-size-class-jvmstubs"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3-window-size-class-linuxx64stubs"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.runtime"
    artifact_id: "runtime"
    version: "1.8.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.8.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.8.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.material3"
group_id: "androidx.compose.material3"
artifact_id: "material3-window-size-class"
path: "/compose/material3/material3-window-size-class"
sha: "aea5f0af9ec0ecea3f971d0e525e95611f418be1"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.material3-material3-window-size-class-all-12159406-1.4.0-alpha01.zip"
kotlin_version: "1.9.24"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.material3"
    artifact_id: "material3-adaptive-navigation-suite"
    version: "1.4.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
