{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.tracing",
    "module": "tracing-perfetto",
    "version": "1.0.0-beta03",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4-rc-2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03.aar",
          "url": "tracing-perfetto-1.0.0-beta03.aar",
          "size": 36781,
          "sha512": "503413f710edb5994f254ab9a5b66fb79f6b8e3a83e36d20345caa47e04286b15d12ac37b53ba2ad5a6d24f47be2f823c949613686969610b56988116118435a",
          "sha256": "810b3c40ca930fc9547eeb5f1ee7d95715e3fc9b079b6128c7a69b18368679d2",
          "sha1": "8393ab0e8b8ef41de449a66c6401c0941e895baa",
          "md5": "fee5df549187ccdbc11a93bde75aa3f4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.startup",
          "module": "startup-runtime",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03.aar",
          "url": "tracing-perfetto-1.0.0-beta03.aar",
          "size": 36781,
          "sha512": "503413f710edb5994f254ab9a5b66fb79f6b8e3a83e36d20345caa47e04286b15d12ac37b53ba2ad5a6d24f47be2f823c949613686969610b56988116118435a",
          "sha256": "810b3c40ca930fc9547eeb5f1ee7d95715e3fc9b079b6128c7a69b18368679d2",
          "sha1": "8393ab0e8b8ef41de449a66c6401c0941e895baa",
          "md5": "fee5df549187ccdbc11a93bde75aa3f4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03-sources.jar",
          "url": "tracing-perfetto-1.0.0-beta03-sources.jar",
          "size": 18677,
          "sha512": "841ecdc5fd072f822a26cd45bdbc9116dfe0b454c0a2fbc35bf7eaedaa31d7e67f03411d2f064c777a7cdc53ba84de972868e30555b7f85e1fee4738f79120c3",
          "sha256": "aa89324135d37055718c776045d36922318615310f17edafe474a9b39031b9e6",
          "sha1": "22889f5796f1a9f9a7a963081118c7674ad604a8",
          "md5": "8870c5a40dfbfd018f45fdad56ccf007"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-binary",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-perfetto-handshake",
          "version": {
            "requires": "1.0.0-beta03"
          },
          "reason": "tracing-perfetto is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-perfetto-1.0.0-beta03-versionMetadata.json",
          "url": "tracing-perfetto-1.0.0-beta03-versionMetadata.json",
          "size": 622,
          "sha512": "35791e37098bd7fc6938013931ce30ef3846b4426275a78cb9f54aada18f4dd110ce03f16566db840b9a60c84eb7d1aafccc1e5ee528eb3e7f2becfb27a18578",
          "sha256": "53aaf80a83d2fc12f26079f5f3d6fd44e5d171e4299787b2fcd81a5233c15bd5",
          "sha1": "8681633d0f8dfac5dd5a5995b5df7e2bd1b98619",
          "md5": "985ba6d2dbf69d0c878093dbc2601590"
        }
      ]
    }
  ]
}