{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.camera.viewfinder",
    "module": "viewfinder-compose",
    "version": "1.5.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3",
      "buildId:": "13882970"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        },
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-view",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        }
      ],
      "files": [
        {
          "name": "viewfinder-compose-1.5.0-rc01-sources.jar",
          "url": "viewfinder-compose-1.5.0-rc01-sources.jar",
          "size": 20140,
          "sha512": "96b0997885c2f01c4ff8a7fd79deb5a8e1be26efcd67b71350f1fa04471657412a952e29ec6ac8bcd33006f038ab690fac809376a6835ca1d2c951f724f4024b",
          "sha256": "fcd9b5e1e3c2ba1a4772bcfc410d34789fa56b42d04dd71b15dcf0f2e236ea48",
          "sha1": "d85a66a659bfb13128baa9e378b54ffa1b9ce3b4",
          "md5": "9aea391b57e87158e3e8cffaad79f170"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-core",
          "version": {
            "requires": "1.5.0-rc01"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        },
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-view",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        }
      ],
      "files": [
        {
          "name": "viewfinder-compose-1.5.0-rc01.aar",
          "url": "viewfinder-compose-1.5.0-rc01.aar",
          "size": 66491,
          "sha512": "863f47e1d6993f48e94d360275424b6a7a5470d3cc6c67556e4fa8d3640a39b4162768754c0f7cd06b7a8ce60d1c132c7394e49b24fb8abdb46d4ae5eeb1f370",
          "sha256": "7a321a052a63be76223842dd70f77d367b7524bbf3c5f30b3f2376982929412b",
          "sha1": "2c3508ed7120ef7a39731b973d5d9d08eb589aa5",
          "md5": "314db2700d753087c5ae0e8c94bba1bf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-core",
          "version": {
            "requires": "1.5.0-rc01"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-geometry",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-graphics",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-unit",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        },
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-view",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "viewfinder-compose-1.5.0-rc01.aar",
          "url": "viewfinder-compose-1.5.0-rc01.aar",
          "size": 66491,
          "sha512": "863f47e1d6993f48e94d360275424b6a7a5470d3cc6c67556e4fa8d3640a39b4162768754c0f7cd06b7a8ce60d1c132c7394e49b24fb8abdb46d4ae5eeb1f370",
          "sha256": "7a321a052a63be76223842dd70f77d367b7524bbf3c5f30b3f2376982929412b",
          "sha1": "2c3508ed7120ef7a39731b973d5d9d08eb589aa5",
          "md5": "314db2700d753087c5ae0e8c94bba1bf"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-core",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        },
        {
          "group": "androidx.camera.viewfinder",
          "module": "viewfinder-view",
          "version": {
            "requires": "1.5.0-rc01"
          },
          "reason": "viewfinder-compose is in atomic group androidx.camera.viewfinder"
        }
      ],
      "files": [
        {
          "name": "viewfinder-compose-1.5.0-rc01-versionMetadata.json",
          "url": "viewfinder-compose-1.5.0-rc01-versionMetadata.json",
          "size": 2264,
          "sha512": "3ec7851f4f74f14d9bbef2608f5e202905ac7ec18bb6a82cba47e17bd2db5fa4096ebdf043bc1b99ab52fb6cbc80656927421d754acca5975ba79e608b5d0137",
          "sha256": "c31590daba5b03a5eb86df135ca11ba05890f02b6a0e2fcaaac8a444df1a6163",
          "sha1": "518f610e51656a4c01996237213b3ba66d662c2b",
          "md5": "f339e78a3676d2ff7afe2a4c39c1db91"
        }
      ]
    }
  ]
}