{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.appsearch",
    "module": "appsearch-platform-storage",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13679201"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.2.0-alpha01-sources.jar",
          "url": "appsearch-platform-storage-1.2.0-alpha01-sources.jar",
          "size": 57066,
          "sha512": "aaba90712d7730fec5d7dd0f07e5575c1d88e7bc5800a41cbbea980b061e610f1f9f08718e10f8ea7f1a281a4415fd99e4e35a93df87091c8b98cbb283d18b79",
          "sha256": "6cfc69dc7d0676c64b297874e9d36499cca56cfcfb1b0119f84f8120503890de",
          "sha1": "785a3aa804903f33e6a0d46457cdaa679acab0a9",
          "md5": "d9b090cf3fa3224e09d6efa504844ac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.2.0-alpha01.aar",
          "url": "appsearch-platform-storage-1.2.0-alpha01.aar",
          "size": 97127,
          "sha512": "d52e618f079fb7c3f828b07c3b2b5a43b6a36751d91572cf68e63cea795456e5649f7e34d1aa1e1971b6c0f98ff683fa4e9057bd8eb96e1e56d19bbe0c448b46",
          "sha256": "77fb3eac2d983c7304b9413a4acd1354480bd493e8cd7fd5f7cb47906667051f",
          "sha1": "5fc8ce67a8184c9ecba14917867fb8c4dddc58c8",
          "md5": "a4d13dd8fcc371f7bfa1c46896e02ede"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.2.0-alpha01"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.2.0-alpha01.aar",
          "url": "appsearch-platform-storage-1.2.0-alpha01.aar",
          "size": 97127,
          "sha512": "d52e618f079fb7c3f828b07c3b2b5a43b6a36751d91572cf68e63cea795456e5649f7e34d1aa1e1971b6c0f98ff683fa4e9057bd8eb96e1e56d19bbe0c448b46",
          "sha256": "77fb3eac2d983c7304b9413a4acd1354480bd493e8cd7fd5f7cb47906667051f",
          "sha1": "5fc8ce67a8184c9ecba14917867fb8c4dddc58c8",
          "md5": "a4d13dd8fcc371f7bfa1c46896e02ede"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.appsearch",
          "module": "appsearch",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-builtin-types",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-compiler",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-debug-view",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-external-protobuf",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-ktx",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-local-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        },
        {
          "group": "androidx.appsearch",
          "module": "appsearch-play-services-storage",
          "version": {
            "requires": "1.2.0-alpha01"
          },
          "reason": "appsearch-platform-storage is in atomic group androidx.appsearch"
        }
      ],
      "files": [
        {
          "name": "appsearch-platform-storage-1.2.0-alpha01-versionMetadata.json",
          "url": "appsearch-platform-storage-1.2.0-alpha01-versionMetadata.json",
          "size": 1700,
          "sha512": "0b47ec78002b3094ec4c41e05e46c8adf0addbb336beefde70763716953ab1d00ce20edf8774e618566ec6eaa11fc62d1861566020d84aab8fcb04bdf5463d33",
          "sha256": "0685acf4dde397fc766ee20cb9d4025331a847b4df05e4204328f3603f7fb220",
          "sha1": "ec5cb8d384561b325e582c8a869b5e94cd00a721",
          "md5": "b57e4f39c9aa9fbf818a6f10ee63e9c1"
        }
      ]
    }
  ]
}