version: "1.8.0-alpha08"
dependency_list {
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-graphics"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-android"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-jvmstubs"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-linuxx64stubs"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "12944746"
group_id: "androidx.compose.ui"
artifact_id: "ui-text"
path: "/compose/ui/ui-text"
sha: "ddc1fb7522a112c60225c3e4eb1d0f077375fa1c"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.compose.ui-ui-text-all-12944746-1.8.0-alpha08.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-geometry"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-graphics"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-graphics-lint"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-lint"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-junit4"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-manifest"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-manifest-lint"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-google-fonts"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-lint"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-data"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-preview"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-util"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-viewbinding"
    version: "1.8.0-alpha08"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
target: "androidx"
kmp_children: "android"
kmp_children: "jvmStubs"
kmp_children: "linuxx64Stubs"
test_module_names: ":compose:ui:ui-text:jvmStubsTest"
test_module_names: ":compose:ui:ui-text:linuxx64StubsTest"
test_module_names: "compose-ui-ui-textreleaseAndroidTest.xml"
test_module_names: ":compose:ui:ui-text:testReleaseUnitTest"
