{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.16.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12905550"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.16.0-alpha01-sources.jar",
          "url": "core-1.16.0-alpha01-sources.jar",
          "size": 970214,
          "sha512": "6131774397c5a4d4fd7a0d7b5fb8d81b9f756a3f75e05da80e81a6c55ed0b8bcac5647da08d9fdfd8582eb21d4987d01c678560c3b381ce075f21f0807b8b893",
          "sha256": "811d0367fb7215156811a4c825a71503a9ce341ef70805a47e3fe1e75d7e6c39",
          "sha1": "222c27cb6da03acbdc673447998b0ebc41de242c",
          "md5": "777b8d69ada33b6c2464bd611fdb36a2"
        },
        {
          "name": "core-1.16.0-alpha01-samples-sources.jar",
          "url": "core-1.16.0-alpha01-samples-sources.jar",
          "size": 6272,
          "sha512": "924ae5a6b8388f097b80b00a2bb7e094f5c4bcbb08df69cdc15770e97b575e6ec8bc77dd4ac50d927fbad2bd22bf9d73622984b4a761d94ef86839c3e28f2a70",
          "sha256": "7b42513b7a33535365c4606d46e5dd9c0c747ed704bcdc39ae1db665c3d00b8d",
          "sha1": "7a746abb87119c59f68b3274f0692e3a0390a4aa",
          "md5": "96f5c93bc127f664fd6906f5045af6ba"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.16.0-alpha01.aar",
          "url": "core-1.16.0-alpha01.aar",
          "size": 1374773,
          "sha512": "bb881b6b6dc0afadfa0586683db39d150d00deecec93efbbc6796167c59ab20ea518f04f6b2011c3987200ee44a50488b54d1c8dd94d149298fb44c8af41eec6",
          "sha256": "e43c2901067bf359bffeb9ddf43103bc3d0b90bdb4bd1bde8ce83e167fadadf2",
          "sha1": "df4e222d35b0e686171abb4aba341949edb49d1b",
          "md5": "27f1f3c28aa870abb8db47de7dc31af6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-viewtree",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0-alpha01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.16.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.16.0-alpha01.aar",
          "url": "core-1.16.0-alpha01.aar",
          "size": 1374773,
          "sha512": "bb881b6b6dc0afadfa0586683db39d150d00deecec93efbbc6796167c59ab20ea518f04f6b2011c3987200ee44a50488b54d1c8dd94d149298fb44c8af41eec6",
          "sha256": "e43c2901067bf359bffeb9ddf43103bc3d0b90bdb4bd1bde8ce83e167fadadf2",
          "sha1": "df4e222d35b0e686171abb4aba341949edb49d1b",
          "md5": "27f1f3c28aa870abb8db47de7dc31af6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.16.0-alpha01-versionMetadata.json",
          "url": "core-1.16.0-alpha01-versionMetadata.json",
          "size": 267924,
          "sha512": "6d7191eb775e9f59a57ad5cb22b8774e022ca16c6875d0ac942313d549a7ce9483d5d9f1e4b028bb3a62544c74dab9cb0ae0c975b6a60901e71a0b5ad037e649",
          "sha256": "77ed9f171a106ae0fb027b2ae2d7d88fa17091f22afb94bcadade2d496956ffb",
          "sha1": "ccce5adf2c5ba8fcfe3f9d0aca5205d24d19404c",
          "md5": "9f662abc2ca3198e9f9522a510c554ab"
        }
      ]
    }
  ]
}