{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window.extensions",
    "module": "extensions",
    "version": "1.5.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "extensions-1.5.0-alpha01.aar",
          "url": "extensions-1.5.0-alpha01.aar",
          "size": 65038,
          "sha512": "729b09d5add6928cd8136f6c09fb4d7862714e9b32ed0e416bdfb75919f5fb7670f6ba2854a73432141e7f5030db588ca94a249f093bc8cc81c57d355b852741",
          "sha256": "6f24b1094d1012cc997f9a83aaca54af422d6b63006a7c50e75621761a16d23d",
          "sha1": "6b617f08dc3599db0b1387058ecd91255f4d379f",
          "md5": "a98e7f0910714b1a984a29ed71ad20b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.window.extensions.core",
          "module": "core",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "extensions-1.5.0-alpha01.aar",
          "url": "extensions-1.5.0-alpha01.aar",
          "size": 65038,
          "sha512": "729b09d5add6928cd8136f6c09fb4d7862714e9b32ed0e416bdfb75919f5fb7670f6ba2854a73432141e7f5030db588ca94a249f093bc8cc81c57d355b852741",
          "sha256": "6f24b1094d1012cc997f9a83aaca54af422d6b63006a7c50e75621761a16d23d",
          "sha1": "6b617f08dc3599db0b1387058ecd91255f4d379f",
          "md5": "a98e7f0910714b1a984a29ed71ad20b0"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "extensions-1.5.0-alpha01-versionMetadata.json",
          "url": "extensions-1.5.0-alpha01-versionMetadata.json",
          "size": 24085,
          "sha512": "9881966e75a0e4cc83fc59d9acf81b8be86028ea1a25754ba437bc8b024014502616d926d258eeebb1b3c8b347daae1cac43d39651af0b367cb3efb9af02b6e3",
          "sha256": "7b768a2425cf308498ceb24d119fbe39814a74a7b9e537d4e1082af96711b8df",
          "sha1": "bdf0860bb5e52093fef8f509b843d67f6f23ba6b",
          "md5": "fd9a03ff2b4d5f094dd65d678bb18b86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extensions-1.5.0-alpha01-sources.jar",
          "url": "extensions-1.5.0-alpha01-sources.jar",
          "size": 64573,
          "sha512": "c181afa3cc307f7c1066be991cee420c0ecfcbcf7b38e5d32484ec637f23b4fc12301fdde5e70676f8b3009468e7ad9aafaa9d95e1897a3ebb878b357aae9a9a",
          "sha256": "ca3a85bd49de3eafddc4d34fe03e9d726e66fcb8d72a12488deef26d216ae691",
          "sha1": "e0954d104b7ae6825d38b4a2eacc14117c5b58f6",
          "md5": "32ad59f2a27d60eee3ddfadd0dd46d28"
        }
      ]
    }
  ]
}