{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.wear.compose",
    "module": "compose-material3",
    "version": "1.0.0-alpha31",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12",
      "buildId:": "12929033"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha31-sources.jar",
          "url": "compose-material3-1.0.0-alpha31-sources.jar",
          "size": 321897,
          "sha512": "c3fcadde432e9624787e64e761d94dfc3ff3c4f4868c2f007422b273e9c646e4dcd8c1f1d4ab604d0b20496b5db89f4ec7a7a990b91ff49c7ed8faa65e930c99",
          "sha256": "8852ece4e67200aa012720845d2432115e80328705ca441ea067c8c3e19a31af",
          "sha1": "065fd17be361574f7ead7c6f991bdbedebd20913",
          "md5": "b4dac1fe0263c956ce97638323c6c043"
        },
        {
          "name": "compose-material3-1.0.0-alpha31-samples-sources.jar",
          "url": "compose-material3-1.0.0-alpha31-samples-sources.jar",
          "size": 53838,
          "sha512": "cac9c1648257a2045858e776036a069aac9c8ac3b8a4db0e1b0546b1eae409deba1030ef125ca7b6888728c4ddd6be7add4a018f84bf58fdba3f5f3c2ee7db14",
          "sha256": "0d48341cada3c068dbf427b15b582452ad6769ab6d12aaed0f7ad04792731fc3",
          "sha1": "9f5ac649100be1beba0d86195cb2f08699eac799",
          "md5": "b276d371a213bab6937959cb9a8f1c29"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha31.aar",
          "url": "compose-material3-1.0.0-alpha31.aar",
          "size": 2354698,
          "sha512": "cfdc64953309b5babf6941d2a7d594b47884fd6d746f8a8cbd5c8c872f63c0eb65510b895203ec86d89522b6ed2f38a7d84c62715e9d5520ec71f2c44d0417a9",
          "sha256": "dc141fc8ff7953415ae308069e31a1c956a6f4177ca08e3aedd2c490b1e76d7d",
          "sha1": "731f717d5c52daa7b1afd292b3a380645d63cb36",
          "md5": "45b77aad042f9e57deaabb090afbe158"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation-graphics",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-ripple",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.8.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text",
          "version": {
            "requires": "1.8.0-alpha08"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util",
          "version": {
            "requires": "1.7.4"
          }
        },
        {
          "group": "androidx.graphics",
          "module": "graphics-shapes",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-foundation",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        },
        {
          "group": "androidx.wear.compose",
          "module": "compose-material-core",
          "version": {
            "requires": "1.5.0-alpha08"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha31.aar",
          "url": "compose-material3-1.0.0-alpha31.aar",
          "size": 2354698,
          "sha512": "cfdc64953309b5babf6941d2a7d594b47884fd6d746f8a8cbd5c8c872f63c0eb65510b895203ec86d89522b6ed2f38a7d84c62715e9d5520ec71f2c44d0417a9",
          "sha256": "dc141fc8ff7953415ae308069e31a1c956a6f4177ca08e3aedd2c490b1e76d7d",
          "sha1": "731f717d5c52daa7b1afd292b3a380645d63cb36",
          "md5": "45b77aad042f9e57deaabb090afbe158"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "compose-material3-1.0.0-alpha31-versionMetadata.json",
          "url": "compose-material3-1.0.0-alpha31-versionMetadata.json",
          "size": 114749,
          "sha512": "de440e743b5acec05b0d02c9a7dd0a1134f2155984bebca5417e455d09e72b66a76ca8bd2e0e4c2eb0b14e1d6cb0af3ff9cdb2320ec44c25714b72a7b56f0a90",
          "sha256": "20ad43b8b44604e8397c45e7a970a25f72e7996c7ad5895b21d53f2d34a0ad5a",
          "sha1": "d8a1a174c09103cf59ae0bcc561759af1415d80b",
          "md5": "08737e94be3e86c0f76162f95dace1b4"
        }
      ]
    }
  ]
}