{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-testing",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7080078"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "work-testing-2.7.0-alpha01.aar",
          "url": "work-testing-2.7.0-alpha01.aar",
          "size": 21385,
          "sha512": "93ac15dfc085d31df913acd37dac77594121c63a495ce9031f550d21af2de984eaa0e96c394bbc7a925d02a9b220ece786965d58f4932b6e413df7eedaa90df8",
          "sha256": "c39d56b4c081481fd351eea23c44fef2be6a259b21658356085879ee6f820de8",
          "sha1": "5eaab595f4b32cd29524a6ad2913925d54737783",
          "md5": "5e533c2cc24d2a78180d98903d28a731"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "work-testing-2.7.0-alpha01.aar",
          "url": "work-testing-2.7.0-alpha01.aar",
          "size": 21385,
          "sha512": "93ac15dfc085d31df913acd37dac77594121c63a495ce9031f550d21af2de984eaa0e96c394bbc7a925d02a9b220ece786965d58f4932b6e413df7eedaa90df8",
          "sha256": "c39d56b4c081481fd351eea23c44fef2be6a259b21658356085879ee6f820de8",
          "sha1": "5eaab595f4b32cd29524a6ad2913925d54737783",
          "md5": "5e533c2cc24d2a78180d98903d28a731"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-testing-2.7.0-alpha01-sources.jar",
          "url": "work-testing-2.7.0-alpha01-sources.jar",
          "size": 17718,
          "sha512": "c491910a699c4540292e58009c52ea59a22d01fef452d75fd16a6d98e030a1bc7e7085ed12f8d57086c18b0e6c51a31c2e4bf9e4960543f96882909fa13ae96f",
          "sha256": "4473b54b09dea7ebc5946307fa8ef97c39092a6d0282d03209dfb38856ee70f1",
          "sha1": "e36bd27fc486e150bc67b53c24f870bac9877254",
          "md5": "1677aa33fb1dd3102332c0f6a987438b"
        }
      ]
    }
  ]
}
