{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.work",
    "module": "work-testing",
    "version": "2.7.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7139798"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "work-testing-2.7.0-alpha01.aar",
          "url": "work-testing-2.7.0-alpha01.aar",
          "size": 21938,
          "sha512": "0ac0f39158678d955bff9525d4a4435759b104f44584919fda7bc4b26a7cd7324992f9f89c7e855a28e3440aec45e5e1ee7bd2210adb5baa41b0b6fe0257a808",
          "sha256": "7ff7b063de86c1738fb5e12669692409bb70742413062092bd8112468ba3933f",
          "sha1": "4f89e6906d40aab197157174dc5e0226076f3abf",
          "md5": "c48352e30269f92565ae9248b4f9b65d"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.7.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "work-testing-2.7.0-alpha01.aar",
          "url": "work-testing-2.7.0-alpha01.aar",
          "size": 21938,
          "sha512": "0ac0f39158678d955bff9525d4a4435759b104f44584919fda7bc4b26a7cd7324992f9f89c7e855a28e3440aec45e5e1ee7bd2210adb5baa41b0b6fe0257a808",
          "sha256": "7ff7b063de86c1738fb5e12669692409bb70742413062092bd8112468ba3933f",
          "sha1": "4f89e6906d40aab197157174dc5e0226076f3abf",
          "md5": "c48352e30269f92565ae9248b4f9b65d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "work-testing-2.7.0-alpha01-sources.jar",
          "url": "work-testing-2.7.0-alpha01-sources.jar",
          "size": 17718,
          "sha512": "c491910a699c4540292e58009c52ea59a22d01fef452d75fd16a6d98e030a1bc7e7085ed12f8d57086c18b0e6c51a31c2e4bf9e4960543f96882909fa13ae96f",
          "sha256": "4473b54b09dea7ebc5946307fa8ef97c39092a6d0282d03209dfb38856ee70f1",
          "sha1": "e36bd27fc486e150bc67b53c24f870bac9877254",
          "md5": "1677aa33fb1dd3102332c0f6a987438b"
        }
      ]
    }
  ]
}
