{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials",
    "version": "1.6.0-alpha02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14",
      "buildId:": "13588622"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha02-sources.jar",
          "url": "credentials-1.6.0-alpha02-sources.jar",
          "size": 254648,
          "sha512": "82726fab5f0de562fc7150d945ed2b3c1e26b2329261c57fec7766ec98895799e28ac3db48cd901fe568f761d15e85edb0f3ee9d5db4adb5da925946220ce31e",
          "sha256": "f07e60466953081c65831daef690bfa32fdd3dfdd575d269cab8d51a41bdd918",
          "sha1": "0072387d6ff0ffd91efad6310daecaf2271f658e",
          "md5": "dd3c330a4e6b2c70f431b96ba0d7a01e"
        },
        {
          "name": "credentials-1.6.0-alpha02-samples-sources.jar",
          "url": "credentials-1.6.0-alpha02-samples-sources.jar",
          "size": 7239,
          "sha512": "1ee633d1013b2183cef418dffdb9500b3a44d99e3c99793423a362924671ee4de542342eee40de11f1a2df2b629127d11c52848cedb23b23d0c70a012e95f920",
          "sha256": "96cd83931877cd1a45ca054fb691d132a2bea0e396cdacdf8662c6f48a88b458",
          "sha1": "a0b5f12eb38243c4331f41ab2fede931b1d6e4ad",
          "md5": "5eb1bb8e4567872e48582c79164f4b22"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha02.aar",
          "url": "credentials-1.6.0-alpha02.aar",
          "size": 608978,
          "sha512": "b7670f932a5a39d1d8c38d56f5638cb1a7093255547e1d04b92f140a1a5febee9b3c471dcecf084c5330dc631888cfe041c482c9ae4cded5afa9d885260bed75",
          "sha256": "2d2a51eef2919cfdbbd2370a4d8b608b998bdf8c481788efa6b3694a5c51f20a",
          "sha1": "18b064eccea9b075fd5c74316f4a14603af57198",
          "md5": "d445cd46f946b1321bb59595c1030146"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.biometric",
          "module": "biometric",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jspecify",
          "module": "jspecify",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha02.aar",
          "url": "credentials-1.6.0-alpha02.aar",
          "size": 608978,
          "sha512": "b7670f932a5a39d1d8c38d56f5638cb1a7093255547e1d04b92f140a1a5febee9b3c471dcecf084c5330dc631888cfe041c482c9ae4cded5afa9d885260bed75",
          "sha256": "2d2a51eef2919cfdbbd2370a4d8b608b998bdf8c481788efa6b3694a5c51f20a",
          "sha1": "18b064eccea9b075fd5c74316f4a14603af57198",
          "md5": "d445cd46f946b1321bb59595c1030146"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.6.0-alpha02"
          },
          "reason": "credentials is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-1.6.0-alpha02-versionMetadata.json",
          "url": "credentials-1.6.0-alpha02-versionMetadata.json",
          "size": 70734,
          "sha512": "9e3df74b5de425609681fb92be1fcc5e2f836e15560c0b05268c4af6e453216470e52d96b66a71a1ad8499354603907d4ba8c88cbfe706599ef037fce7e83743",
          "sha256": "c7fd6662cfdb01bb09252baf2609f81525a5cca5c3c497b5cc514558e792331a",
          "sha1": "df3e5fa092fa3c586685940bd130c25545f9f789",
          "md5": "5f3f974004e135aebc093c930ca9eacd"
        }
      ]
    }
  ]
}