version: "1.7.0-alpha02"
dependency_list {
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-geometry-android"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-geometry-desktop"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.compose.ui"
group_id: "androidx.compose.ui"
artifact_id: "ui-geometry"
path: "/compose/ui/ui-geometry"
sha: "809fd67be047474da72598cb02e0d08d2943c712"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-compose-ui-11372091.zip"
project_zip_path: "per-project-zips/androidx.compose.ui-ui-geometry-all-11372091-1.7.0-alpha02.zip"
kotlin_version: "1.9.22"
dependency_constraint_list {
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-graphics"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-junit4"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-test-manifest"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-text-google-fonts"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-data"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-tooling-preview"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-unit"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-util"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.compose.ui"
    artifact_id: "ui-viewbinding"
    version: "1.7.0-alpha02"
    is_tip_of_tree: true
  }
}
