version: "1.9.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core-ktx"
    version: "1.9.0"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-runtime-ktx"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.lifecycle"
    artifact_id: "lifecycle-viewmodel-ktx"
    version: "2.6.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.savedstate"
    artifact_id: "savedstate-ktx"
    version: "1.2.1"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "androidx.activity"
group_id: "androidx.activity"
artifact_id: "activity-ktx"
path: "/activity/activity-ktx"
sha: "4efe88e0501fbbb5b76d2f58539cf268be0d71a0"
require_same_version_group_build: true
group_zip_path: "per-group-zips/gmaven-androidx-activity-11104036.zip"
project_zip_path: "per-project-zips/androidx.activity-activity-ktx-all-11104036-1.9.0-alpha01.zip"
kotlin_version: "1.9.20"
dependency_constraint_list {
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.activity"
    artifact_id: "activity-compose"
    version: "1.9.0-alpha01"
    is_tip_of_tree: true
  }
}
