{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-service",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7068945"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha01.aar",
          "url": "lifecycle-service-2.4.0-alpha01.aar",
          "size": 3841,
          "sha512": "d367e38c91ff79409689cf0de7b82448d8c0fd75cbfac68b26330794f975c32f05f967a572e28eeed65c6d9ae5c83726bb552fa75ea435d384d58f42bfeea7f1",
          "sha256": "80327822732b5f7d45b65b9a6341d24b6f1b2574c4aeae221f89b0c4e1141dcc",
          "sha1": "8ee574b2f24213a3a3d9300d0597423a9fdc9b56",
          "md5": "15675c135a271198b8609481bee17d1b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha01.aar",
          "url": "lifecycle-service-2.4.0-alpha01.aar",
          "size": 3841,
          "sha512": "d367e38c91ff79409689cf0de7b82448d8c0fd75cbfac68b26330794f975c32f05f967a572e28eeed65c6d9ae5c83726bb552fa75ea435d384d58f42bfeea7f1",
          "sha256": "80327822732b5f7d45b65b9a6341d24b6f1b2574c4aeae221f89b0c4e1141dcc",
          "sha1": "8ee574b2f24213a3a3d9300d0597423a9fdc9b56",
          "md5": "15675c135a271198b8609481bee17d1b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-service-2.4.0-alpha01-sources.jar",
          "url": "lifecycle-service-2.4.0-alpha01-sources.jar",
          "size": 2853,
          "sha512": "979627cb3b88a14fccae7c6dbdf0124ac7fb6590840bf48dd965811eeb6129cabe12b9200083115a2b5d99c6172716bcb11243edcb98c7832939cbb649039cdf",
          "sha256": "821d7ef6cfa5d768f9f73327ab92b400dc2edb05343b99ce78ba1b9a8866cd1a",
          "sha1": "1be95a2b00fd4a7f88c01acae9f6635504f6a5ef",
          "md5": "da94b954e7856cab464491de573095e8"
        }
      ]
    }
  ]
}
