version: "2.5.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.0-beta01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite"
    version: "2.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-android"
    version: "2.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-framework-linuxx64"
    version: "2.5.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.sqlite"
group_id: "androidx.sqlite"
artifact_id: "sqlite-framework"
path: "/sqlite/sqlite-framework"
sha: "ad6bfd28037d5d5295d6de24cd2754dceb712b74"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.sqlite-sqlite-framework-all-11623079-2.5.0-alpha01.zip"
kotlin_version: "1.9.23"
dependency_constraint_list {
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite"
    version: "2.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-bundled"
    version: "2.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.sqlite"
    artifact_id: "sqlite-ktx"
    version: "2.5.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
