{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.window",
    "module": "window",
    "version": "1.0.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.0-beta01.aar",
          "url": "window-1.0.0-beta01.aar",
          "size": 83477,
          "sha512": "a739d060a6c8c4683a29f4aec418c2e8e0dcc73a94b736b1563f8810bfa98e1b000d26ce6a3ad66aeb98398ba5211c8c2e40f7032ff716f2dd10106d80c8d89f",
          "sha256": "de33addbbe57eec0786654533971b277c0fc6087051b1768f1c6df9a0cd0ba1e",
          "sha1": "a3f4189d1b3e669ad560c4b6e5f452ce17a2e405",
          "md5": "60764128987f728b708a34d7e66b0da1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "window-1.0.0-beta01.aar",
          "url": "window-1.0.0-beta01.aar",
          "size": 83477,
          "sha512": "a739d060a6c8c4683a29f4aec418c2e8e0dcc73a94b736b1563f8810bfa98e1b000d26ce6a3ad66aeb98398ba5211c8c2e40f7032ff716f2dd10106d80c8d89f",
          "sha256": "de33addbbe57eec0786654533971b277c0fc6087051b1768f1c6df9a0cd0ba1e",
          "sha1": "a3f4189d1b3e669ad560c4b6e5f452ce17a2e405",
          "md5": "60764128987f728b708a34d7e66b0da1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "window-1.0.0-beta01-sources.jar",
          "url": "window-1.0.0-beta01-sources.jar",
          "size": 33618,
          "sha512": "b385c581e565b61c1a02d088847d70acf30d15bebec1a8a03e4672e103c2de11df431bd94605198c7439b132dea112a6241bc8a72ac96d47ee15b79ce376117f",
          "sha256": "4082e30cb2ac11ab570e028b0461b9d4f8ffdbea7a27e888d8ef2ba6ef128e04",
          "sha1": "e4eb764212714d6f9c4bb9601f50bb0915c97927",
          "md5": "f8dcd63fdd9440c89d32a5671ece34ee"
        }
      ]
    }
  ]
}
