{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.vectordrawable",
    "module": "vectordrawable-animated",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-alpha01.aar",
          "url": "vectordrawable-animated-1.2.0-alpha01.aar",
          "size": 32805,
          "sha512": "98e959815dca66ec4cdc5047b194155fa6a37d5ec3952fe75c2510cc5fb786440e72e8b812202a83b2b3f9794592c915141d2e9ea6745e7b45f35405d138c4b6",
          "sha256": "3200189804edea8cba279519487969247dd045e81ca7fc8695fae909e1e32482",
          "sha1": "b5f336da688269d41e0fb8c1ca75d325e4fc9226",
          "md5": "74dce0ebbe1f5f93d7b266b8948e4b3d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-alpha01.aar",
          "url": "vectordrawable-animated-1.2.0-alpha01.aar",
          "size": 32805,
          "sha512": "98e959815dca66ec4cdc5047b194155fa6a37d5ec3952fe75c2510cc5fb786440e72e8b812202a83b2b3f9794592c915141d2e9ea6745e7b45f35405d138c4b6",
          "sha256": "3200189804edea8cba279519487969247dd045e81ca7fc8695fae909e1e32482",
          "sha1": "b5f336da688269d41e0fb8c1ca75d325e4fc9226",
          "md5": "74dce0ebbe1f5f93d7b266b8948e4b3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-alpha01-sources.jar",
          "url": "vectordrawable-animated-1.2.0-alpha01-sources.jar",
          "size": 23793,
          "sha512": "069bc296257bf5aecd3ff771e3f6c4f64e91f3e849d22bf62e6af3f0e0166b35ca6e6e29164f630bdf064fc1c3eea510e9b3c64cac0954216267d7861cfb86cc",
          "sha256": "87906b7f03ceb33da1b5e537f00908edbc6878d9fa8e1aa9df61ac06f0aa0dc8",
          "sha1": "6bb0104cec345c06af70734e572acf50f9a4396f",
          "md5": "0028fbdf56afea1bd251d46ad5ae4c74"
        }
      ]
    }
  ]
}
