{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.vectordrawable",
    "module": "vectordrawable-animated",
    "version": "1.2.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7080078"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-alpha01.aar",
          "url": "vectordrawable-animated-1.2.0-alpha01.aar",
          "size": 33546,
          "sha512": "f8f2008eb976dfcab25021e68a1fa4ac4e9886f887e50d73e69b51601d3d85c120bf3486fcfb507f47f88ef2a1d579672e3570c0063d60153c96c8cf1879055e",
          "sha256": "5f3fd8f5b66e44ed2f1b5700a8a7d6a0790cc3aad666c0b38b36a99da992c3b1",
          "sha1": "06cc64ce8fab4ab71e2df0dc40a92e07b551d44d",
          "md5": "aa6b1b5a90872c240f71fb00e05003a2"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.vectordrawable",
          "module": "vectordrawable",
          "version": {
            "requires": "1.2.0-alpha03"
          }
        }
      ],
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-alpha01.aar",
          "url": "vectordrawable-animated-1.2.0-alpha01.aar",
          "size": 33546,
          "sha512": "f8f2008eb976dfcab25021e68a1fa4ac4e9886f887e50d73e69b51601d3d85c120bf3486fcfb507f47f88ef2a1d579672e3570c0063d60153c96c8cf1879055e",
          "sha256": "5f3fd8f5b66e44ed2f1b5700a8a7d6a0790cc3aad666c0b38b36a99da992c3b1",
          "sha1": "06cc64ce8fab4ab71e2df0dc40a92e07b551d44d",
          "md5": "aa6b1b5a90872c240f71fb00e05003a2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "vectordrawable-animated-1.2.0-alpha01-sources.jar",
          "url": "vectordrawable-animated-1.2.0-alpha01-sources.jar",
          "size": 23793,
          "sha512": "069bc296257bf5aecd3ff771e3f6c4f64e91f3e849d22bf62e6af3f0e0166b35ca6e6e29164f630bdf064fc1c3eea510e9b3c64cac0954216267d7861cfb86cc",
          "sha256": "87906b7f03ceb33da1b5e537f00908edbc6878d9fa8e1aa9df61ac06f0aa0dc8",
          "sha1": "6bb0104cec345c06af70734e572acf50f9a4396f",
          "md5": "0028fbdf56afea1bd251d46ad5ae4c74"
        }
      ]
    }
  ]
}
