{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-livedata-ktx",
    "version": "2.4.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId:": "7080078"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.4.0-alpha01.aar",
          "url": "lifecycle-livedata-ktx-2.4.0-alpha01.aar",
          "size": 39859,
          "sha512": "4926a7345aedbd19db28f0bc18e99458047cbc5eb8d55552328e898a55cef07d06fa7bcb3384cfc00c3c8b309b8f886e8b513c83b9aff5103fbce2df1e30613c",
          "sha256": "197eb1dc92392f86835f609300137d1bb8832448d1061f49454476603f7b633b",
          "sha1": "c500d63c448141df97b91f6e2c491a99a878e7a5",
          "md5": "b82a8e0891950f37a517188d7de72331"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-core-ktx",
          "version": {
            "requires": "2.4.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.4.0-alpha01.aar",
          "url": "lifecycle-livedata-ktx-2.4.0-alpha01.aar",
          "size": 39859,
          "sha512": "4926a7345aedbd19db28f0bc18e99458047cbc5eb8d55552328e898a55cef07d06fa7bcb3384cfc00c3c8b309b8f886e8b513c83b9aff5103fbce2df1e30613c",
          "sha256": "197eb1dc92392f86835f609300137d1bb8832448d1061f49454476603f7b633b",
          "sha1": "c500d63c448141df97b91f6e2c491a99a878e7a5",
          "md5": "b82a8e0891950f37a517188d7de72331"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-livedata-ktx-2.4.0-alpha01-sources.jar",
          "url": "lifecycle-livedata-ktx-2.4.0-alpha01-sources.jar",
          "size": 8580,
          "sha512": "8199d2f1df3ba53fd8c90e2f2b92288803d7bfc289fbce7014cd899d253d567ef2af6c19667814f711aafffcce72a911c45fca413e287a70c6700b83a8fe75ff",
          "sha256": "108c76911f2f7614234456e011a65b8e20d3635a9b3a3a6b896c3fbebdfaed46",
          "sha1": "086ef44d2dab57d278e18eaff5ce09c816685cd1",
          "md5": "9a22cbca7503671ff17c6ec980f0f770"
        }
      ]
    }
  ]
}
