{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.browser",
    "module": "browser",
    "version": "1.3.0-alpha06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId:": "6836159"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.3.0-alpha06.aar",
          "url": "browser-1.3.0-alpha06.aar",
          "size": 204123,
          "sha512": "ef62dc69a39a80010947d601729e2c4bd7aa767707c429d58a7ad21aa25bdf4410ab76f76ad03f0921587d590bb4cb498a3cc78fbf6f0976c2d2f0639503b0ce",
          "sha256": "38e890bea892fc54599f00d606a8aa9bb78b134ceed821d3ee594c798cef13bc",
          "sha1": "b6502b384845034e63687369034c435161931257",
          "md5": "54128d02eec09d0a555a43dc900fc689"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "listenablefuture",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "browser-1.3.0-alpha06.aar",
          "url": "browser-1.3.0-alpha06.aar",
          "size": 204123,
          "sha512": "ef62dc69a39a80010947d601729e2c4bd7aa767707c429d58a7ad21aa25bdf4410ab76f76ad03f0921587d590bb4cb498a3cc78fbf6f0976c2d2f0639503b0ce",
          "sha256": "38e890bea892fc54599f00d606a8aa9bb78b134ceed821d3ee594c798cef13bc",
          "sha1": "b6502b384845034e63687369034c435161931257",
          "md5": "54128d02eec09d0a555a43dc900fc689"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "browser-1.3.0-alpha06-sources.jar",
          "url": "browser-1.3.0-alpha06-sources.jar",
          "size": 96463,
          "sha512": "4d896e8dcd54784ba45f5024976e0daf7cfe724b4cfd761a617fba39b8d1097c63bbee2d02bf2ae5a1688092f0767e4260a1e9b3c5f898c6cb047414d590de5e",
          "sha256": "297a7ae31587ddf32eb5850d1152c53ba68dd68f486b6a44a0544cdc32e75bc5",
          "sha1": "ec05351b5d5f7cfe608868fa2cc1717a042a1d89",
          "md5": "1d4d2ae8c5e0b217b4adc8931777b4bf"
        }
      ]
    }
  ]
}
