{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.room",
    "module": "room-compiler-processing",
    "version": "2.3.0-beta01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId:": "7116071"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta01.jar",
          "url": "room-compiler-processing-2.3.0-beta01.jar",
          "size": 583574,
          "sha512": "6a1119009a5d49e85596dede313b1a0457aa8941207becec833723cddafe2c34da643dc3f197f5958726a54b13a5c58eeff8341ef71fd2f042747c42c0fdd29a",
          "sha256": "c7b9757af1b0c21423a7be949b4577726caf4367e204ffe09281b9188efdf5d5",
          "sha1": "78fd2075bc4790f18c0dabceffe0e65338f3495a",
          "md5": "c105d6c0f78f92762cd6413c6632fa6c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "29.0-jre"
          }
        },
        {
          "group": "com.google.auto",
          "module": "auto-common",
          "version": {
            "requires": "0.10"
          }
        },
        {
          "group": "com.google.auto.value",
          "module": "auto-value-annotations",
          "version": {
            "requires": "1.6.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-metadata-jvm",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "com.intellij",
          "module": "annotations",
          "version": {
            "requires": "12.0"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.4.20-dev-experimental-20210111"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta01.jar",
          "url": "room-compiler-processing-2.3.0-beta01.jar",
          "size": 583574,
          "sha512": "6a1119009a5d49e85596dede313b1a0457aa8941207becec833723cddafe2c34da643dc3f197f5958726a54b13a5c58eeff8341ef71fd2f042747c42c0fdd29a",
          "sha256": "c7b9757af1b0c21423a7be949b4577726caf4367e204ffe09281b9188efdf5d5",
          "sha1": "78fd2075bc4790f18c0dabceffe0e65338f3495a",
          "md5": "c105d6c0f78f92762cd6413c6632fa6c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "room-compiler-processing-2.3.0-beta01-sources.jar",
          "url": "room-compiler-processing-2.3.0-beta01-sources.jar",
          "size": 124898,
          "sha512": "7c229faa05dfc704afdc1394d31b8ce8523b8c1172045bd7bd712bba94a14c243b4031ed131df3885bfb0be36aa831c78c7c969349dbc94320d702bab58e1e91",
          "sha256": "361a41c2355f653f302115899c51aa9502c9705d5202741ab7803f5e73bf6e05",
          "sha1": "037ae2f55a0a80e57d0be668e23e09048c318624",
          "md5": "a3b0798a50354649691125db5fb0f09c"
        }
      ]
    }
  ]
}
