{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-runtime-ktx",
    "version": "2.9.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13",
      "buildId:": "13259688"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.9.0-alpha09-sources.jar",
          "url": "navigation-runtime-ktx-2.9.0-alpha09-sources.jar",
          "size": 4458,
          "sha512": "f30643b2bb81343a879bc4e88c7457e722725afba3136c589d85e6fca1825da6964cc54525e97a03084f5bd6a1c922dded6556dc02081891b6052c2e4ddb47a5",
          "sha256": "a012de5a17cdfafc06ab48be56b442fbcfa64e8459beb5017459d6f9030ede72",
          "sha1": "79cb4cd4f96c6a64a1fc953a9e7111e56c394297",
          "md5": "38d54d2f5f3f2a6d3be9359af681b8e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.9.0-alpha09.aar",
          "url": "navigation-runtime-ktx-2.9.0-alpha09.aar",
          "size": 5811,
          "sha512": "cf81a86e1f719d74a077577a2145001962c0732cf23687bbaeeccddd7a6c472123d436843bfd5508fcc1a1e78af4e9d7a06d282d20949410d1dee30cf1a69040",
          "sha256": "9bd3ddb10e16ca5892564d7140f3742c65a645b5e35217552593cf1e2819b513",
          "sha1": "93265122150324924a244b708a4bf4549cb2fa43",
          "md5": "d0564c4783db8f90ab096b6d84c24ba3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.9.0-alpha09.aar",
          "url": "navigation-runtime-ktx-2.9.0-alpha09.aar",
          "size": 5811,
          "sha512": "cf81a86e1f719d74a077577a2145001962c0732cf23687bbaeeccddd7a6c472123d436843bfd5508fcc1a1e78af4e9d7a06d282d20949410d1dee30cf1a69040",
          "sha256": "9bd3ddb10e16ca5892564d7140f3742c65a645b5e35217552593cf1e2819b513",
          "sha1": "93265122150324924a244b708a4bf4549cb2fa43",
          "md5": "d0564c4783db8f90ab096b6d84c24ba3"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.navigation",
          "module": "navigation-common",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-common-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-dynamic-features-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-compose",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-generator",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-safe-args-gradle-plugin",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-testing",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-ui-ktx",
          "version": {
            "requires": "2.9.0-alpha09"
          },
          "reason": "navigation-runtime-ktx is in atomic group androidx.navigation"
        }
      ],
      "files": [
        {
          "name": "navigation-runtime-ktx-2.9.0-alpha09-versionMetadata.json",
          "url": "navigation-runtime-ktx-2.9.0-alpha09-versionMetadata.json",
          "size": 2839,
          "sha512": "79a3d84c0bd6c1176a8ab7dff86a98f4858628eb68915a8b5d0f4d1065eb77c14dc162094a01f326ba0c50b0c69360e53860d97ed4ee5c4285c8ba0e7d1e72ea",
          "sha256": "cbe25d1a11ef681ec6a0c20359ceffa944cc62298e85662dcadafd29efd98eea",
          "sha1": "6353e85fa556caeab1d75faadcc0a80a84c69bde",
          "md5": "5d33fbb450a5d35066a9a8eec7b8ce6b"
        }
      ]
    }
  ]
}