{
  "formatVersion": "1.1",
  "component": {
    "url": "../../tracing-driver-wire/1.0.0-alpha01/tracing-driver-wire-1.0.0-alpha01.module",
    "group": "androidx.tracing",
    "module": "tracing-driver-wire",
    "version": "1.0.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0",
      "buildId:": "13986476"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-driver",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-driver",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "tracing-driver-wire is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-driver-wire.aar",
          "url": "tracing-driver-wire-android-1.0.0-alpha01.aar",
          "size": 129351,
          "sha512": "5cee53a874e53384c8d1fa5954f2d975e5845a7828d8580127dddb3406a3acf24a99e97500b353dc85d425e19a888c81b8373f16d099a2888500142d2b946e9a",
          "sha256": "bfa5809e05a0290b21a0ddee8a483b7a8afe8669df09fd3f65fad486861a0027",
          "sha1": "275c25e762759529083f938e6a0ea9eaf605ff38",
          "md5": "2946802444fa7b79c892b7ed550fe3f2"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing-driver",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.9.1"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.3.11"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-driver",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "tracing-driver-wire is in atomic group androidx.tracing"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "tracing-driver-wire.aar",
          "url": "tracing-driver-wire-android-1.0.0-alpha01.aar",
          "size": 129351,
          "sha512": "5cee53a874e53384c8d1fa5954f2d975e5845a7828d8580127dddb3406a3acf24a99e97500b353dc85d425e19a888c81b8373f16d099a2888500142d2b946e9a",
          "sha256": "bfa5809e05a0290b21a0ddee8a483b7a8afe8669df09fd3f65fad486861a0027",
          "sha1": "275c25e762759529083f938e6a0ea9eaf605ff38",
          "md5": "2946802444fa7b79c892b7ed550fe3f2"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.tracing",
          "module": "tracing-driver",
          "version": {
            "requires": "1.0.0-alpha01"
          },
          "reason": "tracing-driver-wire is in atomic group androidx.tracing"
        }
      ],
      "files": [
        {
          "name": "tracing-driver-wire-android-1.0.0-alpha01-sources.jar",
          "url": "tracing-driver-wire-android-1.0.0-alpha01-sources.jar",
          "size": 40866,
          "sha512": "573505bce48293a00a7b1d50230d54248f4803b75b77edc628c12e4b8d1e735723a1a6011c7bc5d49cfcdfc2dea25d88a26a0866511e9cfcfa0a48ebb8b74ff2",
          "sha256": "aa8e22edaff6a16d4b1e3e1dfc925091b54b486dff442c414f08cc36afa4d62f",
          "sha1": "4a53ca6600fd6868c1ec34b913d14b56974e8650",
          "md5": "fa289ebee666d683c302d2bcfc18c532"
        }
      ]
    }
  ]
}