version: "1.1.0-rc01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.8.1"
    is_tip_of_tree: false
  }
  dependency {
    group_id: "androidx.core"
    artifact_id: "core"
    version: "1.8.0"
    is_tip_of_tree: false
  }
}
release_checklist {
}
build_id: "12919290"
group_id: "androidx.core"
artifact_id: "core-remoteviews"
path: "/core/core-remoteviews"
sha: "4a4e5408e27bc3efcc5383b014916f83edd6f0fc"
require_same_version_group_build: false
project_zip_path: "per-project-zips/androidx.core-core-remoteviews-all-12919290-1.1.0-rc01.zip"
kotlin_version: "2.1.0"
dependency_constraint_list {
}
should_publish_docs: true
is_kmp: false
target: "androidx"
test_module_names: "core-core-remoteviewsreleaseAndroidTest.xml"
test_module_names: ":core:core-remoteviews:testReleaseUnitTest"
