{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core-remoteviews",
    "version": "1.1.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-remoteviews-1.1.0-rc01-sources.jar",
          "url": "core-remoteviews-1.1.0-rc01-sources.jar",
          "size": 24654,
          "sha512": "01333fb2c18d4cc0483a15669222a1a2fb8e7cada565af3129cc2b3002fc3b5a3ff33ae32d5fe4217ea534e7f349ec958b0e6095f802c69cc786bc54a1b9fa6d",
          "sha256": "12350912d74882ae74d19fe23c592cdbb64ef984a2135d94d6563a67d2a4682b",
          "sha1": "466c48b3fdf7ac7a0460b5a986255161df6a5c50",
          "md5": "018c77fed4272553268e88871d98330b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.1.0-rc01.aar",
          "url": "core-remoteviews-1.1.0-rc01.aar",
          "size": 58641,
          "sha512": "97ed13ac54f87339f1b019b09d92263cf18d2ae8f8da148d2b57933816cfe45d0fb9bdbeaeac590bda91a6b9ca1be445556908a38ef4aead524cc0b8a8c3c052",
          "sha256": "0254af191ef67a1ff6e9c6bcd8a104d3461ce51b3afa6aae44728bde55e16667",
          "sha1": "008603d7aed81344625c2d74de05adefa3f588db",
          "md5": "6cd7ea100b5fca5a2b378a369a12d69e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "core-remoteviews-1.1.0-rc01.aar",
          "url": "core-remoteviews-1.1.0-rc01.aar",
          "size": 58641,
          "sha512": "97ed13ac54f87339f1b019b09d92263cf18d2ae8f8da148d2b57933816cfe45d0fb9bdbeaeac590bda91a6b9ca1be445556908a38ef4aead524cc0b8a8c3c052",
          "sha256": "0254af191ef67a1ff6e9c6bcd8a104d3461ce51b3afa6aae44728bde55e16667",
          "sha1": "008603d7aed81344625c2d74de05adefa3f588db",
          "md5": "6cd7ea100b5fca5a2b378a369a12d69e"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-remoteviews-1.1.0-rc01-versionMetadata.json",
          "url": "core-remoteviews-1.1.0-rc01-versionMetadata.json",
          "size": 28056,
          "sha512": "c138f2a0531b0b003e6faed04a49a913cbdfd7b85307509a3cddcc313b1b980261f3421475f461528ee90fdd1625b51964497f26d5cf0c96f64d418be9407947",
          "sha256": "268dfc74cd1e65c1d11e2d395243301d8cbf87a42d06526072db9f62d6211fa9",
          "sha1": "4f9db05b8075b71e329d7058c2c66fb324eceeef",
          "md5": "004664c9215f108e5cf22c172bf87ec5"
        }
      ]
    }
  ]
}