{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.fragment",
    "module": "fragment-testing-manifest",
    "version": "1.7.0-alpha09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.7.0-alpha09.aar",
          "url": "fragment-testing-manifest-1.7.0-alpha09.aar",
          "size": 18283,
          "sha512": "efb3d030facb4360f50c6ac2cad6eeb9474d383147bb6a751eb6eaf4eaeccbc2895fc2d84db2bc9f1e38c76af90ad51ec0c6d3a683c7dba220d47acf1badd5d3",
          "sha256": "147afa59ef724116bf9f05992361be690e2a7ec78628b838d7374493065fe2d9",
          "sha1": "44f5521fbb13d4af9a716dbbf367c4c527d17499",
          "md5": "5a6842d867aa9153428b01ce1b63922d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-alpha09"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.7.0-alpha09.aar",
          "url": "fragment-testing-manifest-1.7.0-alpha09.aar",
          "size": 18283,
          "sha512": "efb3d030facb4360f50c6ac2cad6eeb9474d383147bb6a751eb6eaf4eaeccbc2895fc2d84db2bc9f1e38c76af90ad51ec0c6d3a683c7dba220d47acf1badd5d3",
          "sha256": "147afa59ef724116bf9f05992361be690e2a7ec78628b838d7374493065fe2d9",
          "sha1": "44f5521fbb13d4af9a716dbbf367c4c527d17499",
          "md5": "5a6842d867aa9153428b01ce1b63922d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.7.0-alpha09-sources.jar",
          "url": "fragment-testing-manifest-1.7.0-alpha09-sources.jar",
          "size": 2871,
          "sha512": "96b2a8f1d29a37f107bf2e96bce963329724ebf7da35fd5bf04db7ba476ed19122cc66423d7e6d782ae60bd7097acacd2361235d1011da5476bbcc0de70d45c3",
          "sha256": "e9edf7dcb47306fdffb99e2a621d110358d488d1849c1f7dd605ecdffcf04041",
          "sha1": "75307a1e58dea2bb40d93b42229c7da4ee315a09",
          "md5": "14357407515ad513110c94e11e472ba6"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-compose",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-testing",
          "version": {
            "requires": "1.7.0-alpha09"
          },
          "reason": "fragment-testing-manifest is in atomic group androidx.fragment"
        }
      ],
      "files": [
        {
          "name": "fragment-testing-manifest-1.7.0-alpha09-versionMetadata.json",
          "url": "fragment-testing-manifest-1.7.0-alpha09-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}