{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media2",
    "module": "media2-widget",
    "version": "1.3.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media2",
          "module": "media2-session",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "media2-widget-1.3.0-alpha01.aar",
          "url": "media2-widget-1.3.0-alpha01.aar",
          "size": 441388,
          "sha512": "ad31bdaf52ea9b65d01c8dba1ed35acec34a023b6db2c57485e74cbd1ae91aaa0f536d9f27589c2c45c8a2b4616b94fc0f27602d4272998469c50e2ea6f0d036",
          "sha256": "6273de120a60035376efcfe923b387a2d038cff14ab95c7a26b23574b497308a",
          "sha1": "c57c125a4c3ac5e714e793ff3d4b1638ffab93ee",
          "md5": "3f2f425057769155ec85220f4701a19d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.media2",
          "module": "media2-session",
          "version": {
            "requires": "1.3.0-alpha01"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "media2-widget-1.3.0-alpha01.aar",
          "url": "media2-widget-1.3.0-alpha01.aar",
          "size": 441388,
          "sha512": "ad31bdaf52ea9b65d01c8dba1ed35acec34a023b6db2c57485e74cbd1ae91aaa0f536d9f27589c2c45c8a2b4616b94fc0f27602d4272998469c50e2ea6f0d036",
          "sha256": "6273de120a60035376efcfe923b387a2d038cff14ab95c7a26b23574b497308a",
          "sha1": "c57c125a4c3ac5e714e793ff3d4b1638ffab93ee",
          "md5": "3f2f425057769155ec85220f4701a19d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media2-widget-1.3.0-alpha01-sources.jar",
          "url": "media2-widget-1.3.0-alpha01-sources.jar",
          "size": 91466,
          "sha512": "01e300cdc268efa74eee6b3c1540599c670152cbfb15792f0323e31f20415b013a5bd1e7df2fd242f472ca8adceece9ca10a4a56414992d84a69a9723d367d7b",
          "sha256": "5e64740e52832db083a2937ea605e192ba2d50873b83cc2b80b60a2ae6af5413",
          "sha1": "09f4b3d5c5a7312f127a6d749ba90af3d94f67f6",
          "md5": "86ed0d5f12b24324a65001ee7a9536a7"
        }
      ]
    }
  ]
}