{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.core",
    "module": "core",
    "version": "1.12.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.12.0-rc01.aar",
          "url": "core-1.12.0-rc01.aar",
          "size": 1322966,
          "sha512": "3403022ac4a361fe50872ad727faac36b3f80ebae5e9db55d813778725abed881c262bd0bdd7cf2d34cb6fe8441472cc8b2e63b2c60ff0440838a0e437afac83",
          "sha256": "7336c60c0d91f67cdb430a99b919502cd32306c8631dfe2d2720335138458416",
          "sha1": "d779cf2706f0186d641c36bf412e65e3c5267c5f",
          "md5": "89cf65bdc981eb913630b36451f623fb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.collection",
          "module": "collection",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.interpolator",
          "module": "interpolator",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "androidx.versionedparcelable",
          "module": "versionedparcelable",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0-rc01"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-testing",
          "version": {
            "requires": "1.12.0-rc01"
          }
        }
      ],
      "files": [
        {
          "name": "core-1.12.0-rc01.aar",
          "url": "core-1.12.0-rc01.aar",
          "size": 1322966,
          "sha512": "3403022ac4a361fe50872ad727faac36b3f80ebae5e9db55d813778725abed881c262bd0bdd7cf2d34cb6fe8441472cc8b2e63b2c60ff0440838a0e437afac83",
          "sha256": "7336c60c0d91f67cdb430a99b919502cd32306c8631dfe2d2720335138458416",
          "sha1": "d779cf2706f0186d641c36bf412e65e3c5267c5f",
          "md5": "89cf65bdc981eb913630b36451f623fb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-1.12.0-rc01-sources.jar",
          "url": "core-1.12.0-rc01-sources.jar",
          "size": 934229,
          "sha512": "aa5e18fb29a5d58c271cf90a17c1ce1e2849e3f8177cbec6eb77b6a326b82d9af42514fa4e1cc11b8ab7106850287ad8ee082269568ad6979b3ba6725940c252",
          "sha256": "9c9799fd4f8b6b35d7b27199706cbaa73af74b5063ced4cb1be4be12b3baa3eb",
          "sha1": "0696658fc9147f9bb2e04c64f77fa0c8a603583d",
          "md5": "938496ff3820445b65f4589394f62459"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "files": [
        {
          "name": "core-1.12.0-rc01-versionMetadata.json",
          "url": "core-1.12.0-rc01-versionMetadata.json",
          "size": 262559,
          "sha512": "6f1110b4bb8b8fd7cf10925e61956cfda948b4ab87e208c41447f2a106bd32aa003bddb634c511235c786c353285ea2bed8c5c981e398bed7675e02e3b945154",
          "sha256": "7fe54c19220ed7af72e7e7dcff5eb67d69a7c052bc7da900b655c9cf0a728d23",
          "sha1": "d1d9ec86bec69ed0e6eb478c47c57c24c587f0cb",
          "md5": "134c6d322c6d5d1f24b05b2c1218f46e"
        }
      ]
    }
  ]
}