version: "1.5.0-alpha01"
dependency_list {
  dependency {
    group_id: "androidx.annotation"
    artifact_id: "annotation"
    version: "1.9.0-alpha03"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-iosarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-iossimulatorarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-iosx64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-jvm"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-linuxarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-linuxx64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-macosarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-macosx64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-mingwx64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-tvosarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-tvossimulatorarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-tvosx64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-watchosarm32"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-watchosarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-watchossimulatorarm64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-watchosx64"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
}
release_checklist {
}
build_id: "androidx.collection"
group_id: "androidx.collection"
artifact_id: "collection"
path: "/collection/collection"
sha: "dd22e5d13aa5f480943f380227489ee927a853dd"
require_same_version_group_build: true
project_zip_path: "per-project-zips/androidx.collection-collection-all-12314249-1.5.0-alpha01.zip"
kotlin_version: "2.0.10"
dependency_constraint_list {
  dependency {
    group_id: "androidx.collection"
    artifact_id: "collection-ktx"
    version: "1.5.0-alpha01"
    is_tip_of_tree: true
  }
}
should_publish_docs: true
is_kmp: true
